// PvZ2/zombies/PumpkinScarecrowBird/ZombiePumpkinScarecrowBird.cpp
//
// 48 function(s), 8648 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombiePumpkinScarecrowBird
//
// TODO   1624 B  ZombiePumpkinScarecrowBird::StaticClassInit          _ZN26ZombiePumpkinScarecrowBird15StaticClassInitEv
// TODO    580 B  ZombiePumpkinScarecrowBird::updateState_AttachedToPlant _ZN26ZombiePumpkinScarecrowBird27updateState_AttachedToPlantEv
// TODO    504 B  ZombiePumpkinScarecrowBird::moveToDestination        _ZN26ZombiePumpkinScarecrowBird17moveToDestinationEff
// TODO    400 B  ZombiePumpkinScarecrowBird::findNewTargetAndFlyTo    _ZN26ZombiePumpkinScarecrowBird21findNewTargetAndFlyToEv
// TODO    388 B  ZombiePumpkinScarecrowBird::onDestroy                _ZN26ZombiePumpkinScarecrowBird9onDestroyEv
// TODO    340 B  ZombiePumpkinScarecrowBird::onApplyCondition         _ZN26ZombiePumpkinScarecrowBird16onApplyConditionE16ZombieConditions
// TODO    340 B  ZombiePumpkinScarecrowBird::updateState_PickingUpPlant _ZN26ZombiePumpkinScarecrowBird26updateState_PickingUpPlantEv
// TODO    320 B  ZombiePumpkinScarecrowBird::moveToDestination        _ZN26ZombiePumpkinScarecrowBird17moveToDestinationEN4Sexy11SexyVector3E
// TODO    296 B  ZombiePumpkinScarecrowBird::findPlantTarget          _ZN26ZombiePumpkinScarecrowBird15findPlantTargetEv
// TODO    272 B  ZombiePumpkinScarecrowBird::onEnterState_FlyToTarget _ZN26ZombiePumpkinScarecrowBird24onEnterState_FlyToTargetE11ZombieState
// TODO    264 B  ZombiePumpkinScarecrowBird::onEnterState_DestroyingPlant _ZN26ZombiePumpkinScarecrowBird28onEnterState_DestroyingPlantE11ZombieState
// TODO    260 B  ZombiePumpkinScarecrowBird::onEnterState_Returning   _ZN26ZombiePumpkinScarecrowBird22onEnterState_ReturningE11ZombieState
// TODO    228 B  ZombiePumpkinScarecrowBird::onEnterState_AttachedToPlant _ZN26ZombiePumpkinScarecrowBird28onEnterState_AttachedToPlantE11ZombieState
// TODO    228 B  ZombiePumpkinScarecrowBird::updateState_DestroyingPlant _ZN26ZombiePumpkinScarecrowBird27updateState_DestroyingPlantEv
// TODO    224 B  ZombiePumpkinScarecrowBird::onEnterState_FlyingAway  _ZN26ZombiePumpkinScarecrowBird23onEnterState_FlyingAwayE11ZombieState
// TODO    224 B  ZombiePumpkinScarecrowBird::onEnterState_FlyToScarecrow _ZN26ZombiePumpkinScarecrowBird27onEnterState_FlyToScarecrowE11ZombieState
// TODO    212 B  ZombiePumpkinScarecrowBird::updateState_Returning    _ZN26ZombiePumpkinScarecrowBird21updateState_ReturningEv
// TODO    200 B  ZombiePumpkinScarecrowBird::updateState_FlyingAway   _ZN26ZombiePumpkinScarecrowBird22updateState_FlyingAwayEv
// TODO    196 B  ZombiePumpkinScarecrowBird::onUpdate                 _ZN26ZombiePumpkinScarecrowBird8onUpdateEv
// TODO    176 B  ZombiePumpkinScarecrowBird::pickTarget               _ZN26ZombiePumpkinScarecrowBird10pickTargetERN4Sexy5PointE
// TODO    148 B  ZombiePumpkinScarecrowBird::OnCaptainDied            _ZN26ZombiePumpkinScarecrowBird13OnCaptainDiedEv
// TODO    136 B  ZombiePumpkinScarecrowBird::onTakeFatalDamage        _ZN26ZombiePumpkinScarecrowBird17onTakeFatalDamageERK10DamageInfo
// TODO    124 B  ZombiePumpkinScarecrowBird::StaticGetClass           _ZN26ZombiePumpkinScarecrowBird14StaticGetClassEv
// TODO    116 B  ZombiePumpkinScarecrowBird::ZombiePumpkinScarecrowBird _ZN26ZombiePumpkinScarecrowBirdC2Ev
// TODO    116 B  ZombiePumpkinScarecrowBird::ZombiePumpkinScarecrowBird _ZN26ZombiePumpkinScarecrowBirdC1Ev
// TODO    116 B  ZombiePumpkinScarecrowBird::onPlaceOnBoard           _ZN26ZombiePumpkinScarecrowBird14onPlaceOnBoardEv
// TODO    104 B  ZombiePumpkinScarecrowBird::flyToScarecrow           _ZN26ZombiePumpkinScarecrowBird14flyToScarecrowEN4Sexy11SexyVector3E
// TODO     72 B  ZombiePumpkinScarecrowBird::~ZombiePumpkinScarecrowBird _ZN26ZombiePumpkinScarecrowBirdD2Ev
// TODO     72 B  ZombiePumpkinScarecrowBird::~ZombiePumpkinScarecrowBird _ZN26ZombiePumpkinScarecrowBirdD1Ev
// TODO     72 B  ZombiePumpkinScarecrowBird::onElectrocuted           _ZN26ZombiePumpkinScarecrowBird14onElectrocutedEv
// TODO     60 B  ZombiePumpkinScarecrowBird::updateState_FlyToTarget  _ZN26ZombiePumpkinScarecrowBird23updateState_FlyToTargetEv
// TODO     56 B  ZombiePumpkinScarecrowBird::onZombieInitialize       _ZN26ZombiePumpkinScarecrowBird18onZombieInitializeEv
// TODO     44 B  ZombiePumpkinScarecrowBird::StaticNew                _ZN26ZombiePumpkinScarecrowBird9StaticNewEv
// TODO     36 B  ZombiePumpkinScarecrowBird::~ZombiePumpkinScarecrowBird _ZN26ZombiePumpkinScarecrowBirdD0Ev
// TODO     16 B  ZombiePumpkinScarecrowBird::updateState_FlyToScarecrow _ZN26ZombiePumpkinScarecrowBird26updateState_FlyToScarecrowEv
// TODO     12 B  ZombiePumpkinScarecrowBird::flyAway                  _ZN26ZombiePumpkinScarecrowBird7flyAwayEv
// TODO     12 B  ZombiePumpkinScarecrowBird::SetTargetColAndRow       _ZN26ZombiePumpkinScarecrowBird18SetTargetColAndRowEii
// TODO     12 B  ZombiePumpkinScarecrowBird::onEnterState_PickingUpPlant _ZN26ZombiePumpkinScarecrowBird27onEnterState_PickingUpPlantE11ZombieState
// TODO      8 B  ZombiePumpkinScarecrowBird::willDieToShrinking       _ZN26ZombiePumpkinScarecrowBird18willDieToShrinkingEv
// TODO      8 B  ZombiePumpkinScarecrowBird::SetCaptain               _ZN26ZombiePumpkinScarecrowBird10SetCaptainEN4Sexy9RtWeakPtrI6ZombieEE
// TODO      4 B  ZombiePumpkinScarecrowBird::onTurnedToAsh            _ZN26ZombiePumpkinScarecrowBird13onTurnedToAshEv
// TODO      4 B  ZombiePumpkinScarecrowBird::onExitState_FlyToTarget  _ZN26ZombiePumpkinScarecrowBird23onExitState_FlyToTargetE11ZombieState
// TODO      4 B  ZombiePumpkinScarecrowBird::onExitState_AttachedToPlant _ZN26ZombiePumpkinScarecrowBird27onExitState_AttachedToPlantE11ZombieState
// TODO      4 B  ZombiePumpkinScarecrowBird::onExitState_PickingUpPlant _ZN26ZombiePumpkinScarecrowBird26onExitState_PickingUpPlantE11ZombieState
// TODO      4 B  ZombiePumpkinScarecrowBird::onExitState_DestroyingPlant _ZN26ZombiePumpkinScarecrowBird27onExitState_DestroyingPlantE11ZombieState
// TODO      4 B  ZombiePumpkinScarecrowBird::onExitState_Returning    _ZN26ZombiePumpkinScarecrowBird21onExitState_ReturningE11ZombieState
// TODO      4 B  ZombiePumpkinScarecrowBird::onExitState_FlyingAway   _ZN26ZombiePumpkinScarecrowBird22onExitState_FlyingAwayE11ZombieState
// TODO      4 B  ZombiePumpkinScarecrowBird::onExitState_FlyToScarecrow _ZN26ZombiePumpkinScarecrowBird26onExitState_FlyToScarecrowE11ZombieState
