// PvZ2/Tools/UIEditor/UIWidgetType.cpp
//
// 12 function(s), 2296 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: UIWidgetType
//
// TODO    408 B  UIWidgetType::FromWidget                             _ZN12UIWidgetType10FromWidgetEPN4Sexy6WidgetEb
// TODO    256 B  UIWidgetType::UIWidgetType                           _ZN12UIWidgetTypeC2ERKS_
// TODO    256 B  UIWidgetType::UIWidgetType                           _ZN12UIWidgetTypeC1ERKS_
// TODO    208 B  UIWidgetType::UIWidgetType                           _ZN12UIWidgetTypeC1Ev
// TODO    208 B  UIWidgetType::ToWidget                               _ZN12UIWidgetType8ToWidgetEPN4Sexy6WidgetE
// TODO    208 B  UIWidgetType::UIWidgetType                           _ZN12UIWidgetTypeC2Ev
// TODO    184 B  UIWidgetType::HasProperty                            _ZN12UIWidgetType11HasPropertyERKSs
// TODO    184 B  UIWidgetType::IsPropertyNeedWrite                    _ZN12UIWidgetType19IsPropertyNeedWriteERKSs
// TODO    148 B  UIWidgetType::InitWidget                             _ZN12UIWidgetType10InitWidgetEPN4Sexy6WidgetE
// TODO     88 B  UIWidgetType::~UIWidgetType                          _ZN12UIWidgetTypeD1Ev
// TODO     88 B  UIWidgetType::~UIWidgetType                          _ZN12UIWidgetTypeD2Ev
// TODO     60 B  UIWidgetType::IsAutoWidget                           _ZN12UIWidgetType12IsAutoWidgetEPN4Sexy6WidgetE
