// PvZ2/plants/LotusShower/PlantAnimRig_LotusShower.cpp
//
// 9 function(s), 760 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_LotusShower
//
// TODO    208 B  PlantAnimRig_LotusShower::getIdleAnimationName       _ZN24PlantAnimRig_LotusShower20getIdleAnimationNameEv
// TODO    180 B  PlantAnimRig_LotusShower::StaticClassInit            _ZN24PlantAnimRig_LotusShower15StaticClassInitEv
// TODO    124 B  PlantAnimRig_LotusShower::StaticGetClass             _ZN24PlantAnimRig_LotusShower14StaticGetClassEv
// TODO     56 B  PlantAnimRig_LotusShower::PlantAnimRig_LotusShower   _ZN24PlantAnimRig_LotusShowerC2Ev
// TODO     56 B  PlantAnimRig_LotusShower::PlantAnimRig_LotusShower   _ZN24PlantAnimRig_LotusShowerC1Ev
// TODO     44 B  PlantAnimRig_LotusShower::StaticNew                  _ZN24PlantAnimRig_LotusShower9StaticNewEv
// TODO     36 B  PlantAnimRig_LotusShower::~PlantAnimRig_LotusShower  _ZN24PlantAnimRig_LotusShowerD0Ev
// TODO     28 B  PlantAnimRig_LotusShower::~PlantAnimRig_LotusShower  _ZN24PlantAnimRig_LotusShowerD2Ev
// TODO     28 B  PlantAnimRig_LotusShower::~PlantAnimRig_LotusShower  _ZN24PlantAnimRig_LotusShowerD1Ev
