// PvZ2/plants/Asparagus/PlantAnimRig_Asparagus.cpp
//
// 14 function(s), 1880 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_Asparagus
//
// TODO    344 B  PlantAnimRig_Asparagus::getPlantFoodMainAnimName     _ZN22PlantAnimRig_Asparagus24getPlantFoodMainAnimNameEv
// TODO    276 B  PlantAnimRig_Asparagus::onAnimStopped                _ZN22PlantAnimRig_Asparagus13onAnimStoppedEv
// TODO    208 B  PlantAnimRig_Asparagus::PlaySleepReady               _ZN22PlantAnimRig_Asparagus14PlaySleepReadyE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    208 B  PlantAnimRig_Asparagus::PlaySleepEnd                 _ZN22PlantAnimRig_Asparagus12PlaySleepEndE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    180 B  PlantAnimRig_Asparagus::StaticClassInit              _ZN22PlantAnimRig_Asparagus15StaticClassInitEv
// TODO    156 B  PlantAnimRig_Asparagus::getAttackAnimationName       _ZN22PlantAnimRig_Asparagus22getAttackAnimationNameEv
// TODO    124 B  PlantAnimRig_Asparagus::StaticGetClass               _ZN22PlantAnimRig_Asparagus14StaticGetClassEv
// TODO    104 B  PlantAnimRig_Asparagus::getPlantFoodOnAnimName       _ZN22PlantAnimRig_Asparagus22getPlantFoodOnAnimNameEv
// TODO     72 B  PlantAnimRig_Asparagus::PlantAnimRig_Asparagus       _ZN22PlantAnimRig_AsparagusC2Ev
// TODO     72 B  PlantAnimRig_Asparagus::PlantAnimRig_Asparagus       _ZN22PlantAnimRig_AsparagusC1Ev
// TODO     44 B  PlantAnimRig_Asparagus::StaticNew                    _ZN22PlantAnimRig_Asparagus9StaticNewEv
// TODO     36 B  PlantAnimRig_Asparagus::~PlantAnimRig_Asparagus      _ZN22PlantAnimRig_AsparagusD0Ev
// TODO     28 B  PlantAnimRig_Asparagus::~PlantAnimRig_Asparagus      _ZN22PlantAnimRig_AsparagusD2Ev
// TODO     28 B  PlantAnimRig_Asparagus::~PlantAnimRig_Asparagus      _ZN22PlantAnimRig_AsparagusD1Ev
