// PvZ2/zombies/ImpPorter/ZombieAnimRig_ImpPorter.cpp
//
// 13 function(s), 1720 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieAnimRig_ImpPorter
//
// TODO    320 B  ZombieAnimRig_ImpPorter::getHeadLayerNames           _ZN23ZombieAnimRig_ImpPorter17getHeadLayerNamesEv
// TODO    320 B  ZombieAnimRig_ImpPorter::getArmLayerNames            _ZN23ZombieAnimRig_ImpPorter16getArmLayerNamesEv
// TODO    320 B  ZombieAnimRig_ImpPorter::getArmReplacementPairNames  _ZN23ZombieAnimRig_ImpPorter26getArmReplacementPairNamesEv
// TODO    200 B  ZombieAnimRig_ImpPorter::PlaySpawnTent               _ZN23ZombieAnimRig_ImpPorter13PlaySpawnTentE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    180 B  ZombieAnimRig_ImpPorter::StaticClassInit             _ZN23ZombieAnimRig_ImpPorter15StaticClassInitEv
// TODO    124 B  ZombieAnimRig_ImpPorter::StaticGetClass              _ZN23ZombieAnimRig_ImpPorter14StaticGetClassEv
// TODO     56 B  ZombieAnimRig_ImpPorter::ZombieAnimRig_ImpPorter     _ZN23ZombieAnimRig_ImpPorterC2Ev
// TODO     56 B  ZombieAnimRig_ImpPorter::ZombieAnimRig_ImpPorter     _ZN23ZombieAnimRig_ImpPorterC1Ev
// TODO     44 B  ZombieAnimRig_ImpPorter::StaticNew                   _ZN23ZombieAnimRig_ImpPorter9StaticNewEv
// TODO     36 B  ZombieAnimRig_ImpPorter::~ZombieAnimRig_ImpPorter    _ZN23ZombieAnimRig_ImpPorterD0Ev
// TODO     28 B  ZombieAnimRig_ImpPorter::~ZombieAnimRig_ImpPorter    _ZN23ZombieAnimRig_ImpPorterD2Ev
// TODO     28 B  ZombieAnimRig_ImpPorter::~ZombieAnimRig_ImpPorter    _ZN23ZombieAnimRig_ImpPorterD1Ev
// TODO      8 B  ZombieAnimRig_ImpPorter::getDieShouldBlend           _ZN23ZombieAnimRig_ImpPorter17getDieShouldBlendEv
