// PvZ2/zombies/HeianNinja/ZombieAnimRig_HeianNinja.cpp
//
// 16 function(s), 1968 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieAnimRig_HeianNinja
//
// TODO    348 B  ZombieAnimRig_HeianNinja::getHeadLayerNames          _ZN24ZombieAnimRig_HeianNinja17getHeadLayerNamesEv
// TODO    200 B  ZombieAnimRig_HeianNinja::PlayThrowSushi             _ZN24ZombieAnimRig_HeianNinja14PlayThrowSushiE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    200 B  ZombieAnimRig_HeianNinja::PlayHangStart              _ZN24ZombieAnimRig_HeianNinja13PlayHangStartE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    200 B  ZombieAnimRig_HeianNinja::PlayHangCut                _ZN24ZombieAnimRig_HeianNinja11PlayHangCutE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    180 B  ZombieAnimRig_HeianNinja::StaticClassInit            _ZN24ZombieAnimRig_HeianNinja15StaticClassInitEv
// TODO    176 B  ZombieAnimRig_HeianNinja::PlayHangIdle               _ZN24ZombieAnimRig_HeianNinja12PlayHangIdleEv
// TODO    176 B  ZombieAnimRig_HeianNinja::PlayHangEat                _ZN24ZombieAnimRig_HeianNinja11PlayHangEatEv
// TODO    124 B  ZombieAnimRig_HeianNinja::StaticGetClass             _ZN24ZombieAnimRig_HeianNinja14StaticGetClassEv
// TODO    104 B  ZombieAnimRig_HeianNinja::getRangedAttackAnimationName _ZN24ZombieAnimRig_HeianNinja28getRangedAttackAnimationNameEv
// TODO     60 B  ZombieAnimRig_HeianNinja::ZombieAnimRig_HeianNinja   _ZN24ZombieAnimRig_HeianNinjaC2Ev
// TODO     60 B  ZombieAnimRig_HeianNinja::ZombieAnimRig_HeianNinja   _ZN24ZombieAnimRig_HeianNinjaC1Ev
// TODO     44 B  ZombieAnimRig_HeianNinja::StaticNew                  _ZN24ZombieAnimRig_HeianNinja9StaticNewEv
// TODO     36 B  ZombieAnimRig_HeianNinja::~ZombieAnimRig_HeianNinja  _ZN24ZombieAnimRig_HeianNinjaD0Ev
// TODO     28 B  ZombieAnimRig_HeianNinja::~ZombieAnimRig_HeianNinja  _ZN24ZombieAnimRig_HeianNinjaD2Ev
// TODO     28 B  ZombieAnimRig_HeianNinja::~ZombieAnimRig_HeianNinja  _ZN24ZombieAnimRig_HeianNinjaD1Ev
// TODO      4 B  ZombieAnimRig_HeianNinja::PlayDie                    _ZN24ZombieAnimRig_HeianNinja7PlayDieEv
