// PvZ2/plants/IcyCurrant/PlantAnimRig_IcyCurrant.cpp
//
// 18 function(s), 1736 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_IcyCurrant
//
// TODO    180 B  PlantAnimRig_IcyCurrant::StaticClassInit             _ZN23PlantAnimRig_IcyCurrant15StaticClassInitEv
// TODO    160 B  PlantAnimRig_IcyCurrant::StartAttack                 _ZN23PlantAnimRig_IcyCurrant11StartAttackE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    152 B  PlantAnimRig_IcyCurrant::StopAttack                  _ZN23PlantAnimRig_IcyCurrant10StopAttackE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    136 B  PlantAnimRig_IcyCurrant::getPlantFoodOffAnimName     _ZN23PlantAnimRig_IcyCurrant23getPlantFoodOffAnimNameEv
// TODO    124 B  PlantAnimRig_IcyCurrant::StaticGetClass              _ZN23PlantAnimRig_IcyCurrant14StaticGetClassEv
// TODO    104 B  PlantAnimRig_IcyCurrant::getPlantFoodOnAnimName      _ZN23PlantAnimRig_IcyCurrant22getPlantFoodOnAnimNameEv
// TODO    104 B  PlantAnimRig_IcyCurrant::getPlantFoodMainAnimName    _ZN23PlantAnimRig_IcyCurrant24getPlantFoodMainAnimNameEv
// TODO    104 B  PlantAnimRig_IcyCurrant::getIdleAnimationName        _ZN23PlantAnimRig_IcyCurrant20getIdleAnimationNameEv
// TODO    104 B  PlantAnimRig_IcyCurrant::getAttackAnimationName      _ZN23PlantAnimRig_IcyCurrant22getAttackAnimationNameEv
// TODO    104 B  PlantAnimRig_IcyCurrant::getWaterAnimName            _ZN23PlantAnimRig_IcyCurrant16getWaterAnimNameEv
// TODO    104 B  PlantAnimRig_IcyCurrant::getAttackLoopAnimationName  _ZN23PlantAnimRig_IcyCurrant26getAttackLoopAnimationNameEv
// TODO    104 B  PlantAnimRig_IcyCurrant::getAttackStopAnimationName  _ZN23PlantAnimRig_IcyCurrant26getAttackStopAnimationNameEv
// TODO     60 B  PlantAnimRig_IcyCurrant::PlantAnimRig_IcyCurrant     _ZN23PlantAnimRig_IcyCurrantC2Ev
// TODO     60 B  PlantAnimRig_IcyCurrant::PlantAnimRig_IcyCurrant     _ZN23PlantAnimRig_IcyCurrantC1Ev
// TODO     44 B  PlantAnimRig_IcyCurrant::StaticNew                   _ZN23PlantAnimRig_IcyCurrant9StaticNewEv
// TODO     36 B  PlantAnimRig_IcyCurrant::~PlantAnimRig_IcyCurrant    _ZN23PlantAnimRig_IcyCurrantD0Ev
// TODO     28 B  PlantAnimRig_IcyCurrant::~PlantAnimRig_IcyCurrant    _ZN23PlantAnimRig_IcyCurrantD2Ev
// TODO     28 B  PlantAnimRig_IcyCurrant::~PlantAnimRig_IcyCurrant    _ZN23PlantAnimRig_IcyCurrantD1Ev
