// PvZ2/plants/SweetPotato/PlantAnimRig_SweetPotato.cpp
//
// 11 function(s), 1120 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_SweetPotato
//
// TODO    456 B  PlantAnimRig_SweetPotato::PlayIdleLooped             _ZN24PlantAnimRig_SweetPotato14PlayIdleLoopedEv
// TODO    180 B  PlantAnimRig_SweetPotato::StaticClassInit            _ZN24PlantAnimRig_SweetPotato15StaticClassInitEv
// TODO    124 B  PlantAnimRig_SweetPotato::StaticGetClass             _ZN24PlantAnimRig_SweetPotato14StaticGetClassEv
// TODO    104 B  PlantAnimRig_SweetPotato::getDamageIdleAnimationName _ZN24PlantAnimRig_SweetPotato26getDamageIdleAnimationNameEv
// TODO     56 B  PlantAnimRig_SweetPotato::PlantAnimRig_SweetPotato   _ZN24PlantAnimRig_SweetPotatoC2Ev
// TODO     56 B  PlantAnimRig_SweetPotato::PlantAnimRig_SweetPotato   _ZN24PlantAnimRig_SweetPotatoC1Ev
// TODO     44 B  PlantAnimRig_SweetPotato::StaticNew                  _ZN24PlantAnimRig_SweetPotato9StaticNewEv
// TODO     36 B  PlantAnimRig_SweetPotato::~PlantAnimRig_SweetPotato  _ZN24PlantAnimRig_SweetPotatoD0Ev
// TODO     28 B  PlantAnimRig_SweetPotato::~PlantAnimRig_SweetPotato  _ZN24PlantAnimRig_SweetPotatoD2Ev
// TODO     28 B  PlantAnimRig_SweetPotato::~PlantAnimRig_SweetPotato  _ZN24PlantAnimRig_SweetPotatoD1Ev
// TODO      8 B  PlantAnimRig_SweetPotato::CalcDamageStateCount       _ZN24PlantAnimRig_SweetPotato20CalcDamageStateCountEv
