// PvZ2/effects/Effect_AirflowUp.cpp
//
// 10 function(s), 868 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: Effect_AirflowUp
//
// TODO    336 B  Effect_AirflowUp::playAirflowUp                      _ZN16Effect_AirflowUp13playAirflowUpEN4Sexy11SexyVector3E
// TODO    180 B  Effect_AirflowUp::StaticClassInit                    _ZN16Effect_AirflowUp15StaticClassInitEv
// TODO    124 B  Effect_AirflowUp::StaticGetClass                     _ZN16Effect_AirflowUp14StaticGetClassEv
// TODO     48 B  Effect_AirflowUp::Effect_AirflowUp                   _ZN16Effect_AirflowUpC2Ev
// TODO     48 B  Effect_AirflowUp::Effect_AirflowUp                   _ZN16Effect_AirflowUpC1Ev
// TODO     44 B  Effect_AirflowUp::StaticNew                          _ZN16Effect_AirflowUp9StaticNewEv
// TODO     36 B  Effect_AirflowUp::~Effect_AirflowUp                  _ZN16Effect_AirflowUpD0Ev
// TODO     20 B  Effect_AirflowUp::~Effect_AirflowUp                  _ZN16Effect_AirflowUpD2Ev
// TODO     20 B  Effect_AirflowUp::~Effect_AirflowUp                  _ZN16Effect_AirflowUpD1Ev
// TODO     12 B  Effect_AirflowUp::startAirflowUp                     _ZN16Effect_AirflowUp14startAirflowUpEN4Sexy11SexyVector3E
