// PvZ2/effects/Effect_SmokePollution.cpp
//
// 12 function(s), 956 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: Effect_SmokePollution
//
// TODO    180 B  Effect_SmokePollution::StaticClassInit               _ZN21Effect_SmokePollution15StaticClassInitEv
// TODO    172 B  Effect_SmokePollution::PlaySmokeIdle                 _ZN21Effect_SmokePollution13PlaySmokeIdleEP20GridItemSmokeManhole
// TODO    132 B  Effect_SmokePollution::onAnimStopped                 _ZN21Effect_SmokePollution13onAnimStoppedERKSs
// TODO    124 B  Effect_SmokePollution::StaticGetClass                _ZN21Effect_SmokePollution14StaticGetClassEv
// TODO     96 B  Effect_SmokePollution::registerForEvents             _ZN21Effect_SmokePollution17registerForEventsEv
// TODO     56 B  Effect_SmokePollution::Effect_SmokePollution         _ZN21Effect_SmokePollutionC2Ev
// TODO     56 B  Effect_SmokePollution::Effect_SmokePollution         _ZN21Effect_SmokePollutionC1Ev
// TODO     44 B  Effect_SmokePollution::StaticNew                     _ZN21Effect_SmokePollution9StaticNewEv
// TODO     36 B  Effect_SmokePollution::~Effect_SmokePollution        _ZN21Effect_SmokePollutionD0Ev
// TODO     20 B  Effect_SmokePollution::unregisterForEvents           _ZN21Effect_SmokePollution19unregisterForEventsEv
// TODO     20 B  Effect_SmokePollution::~Effect_SmokePollution        _ZN21Effect_SmokePollutionD2Ev
// TODO     20 B  Effect_SmokePollution::~Effect_SmokePollution        _ZN21Effect_SmokePollutionD1Ev
