// PvZ2/effects/Effect_BouncingArrow.cpp
//
// 19 function(s), 1272 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: Effect_BouncingArrow
//
// TODO    348 B  Effect_BouncingArrow::onDraw                         _ZN20Effect_BouncingArrow6onDrawEPN4Sexy8GraphicsE
// TODO    180 B  Effect_BouncingArrow::StaticClassInit                _ZN20Effect_BouncingArrow15StaticClassInitEv
// TODO    124 B  Effect_BouncingArrow::StaticGetClass                 _ZN20Effect_BouncingArrow14StaticGetClassEv
// TODO     72 B  Effect_BouncingArrow::onInitialized                  _ZN20Effect_BouncingArrow13onInitializedEv
// TODO     56 B  Effect_BouncingArrow::SetBounceHeightsBoardSpace     _ZN20Effect_BouncingArrow26SetBounceHeightsBoardSpaceEff
// TODO     56 B  Effect_BouncingArrow::Effect_BouncingArrow           _ZN20Effect_BouncingArrowC2Ev
// TODO     56 B  Effect_BouncingArrow::Effect_BouncingArrow           _ZN20Effect_BouncingArrowC1Ev
// TODO     52 B  Effect_BouncingArrow::~Effect_BouncingArrow          _ZN20Effect_BouncingArrowD2Ev
// TODO     52 B  Effect_BouncingArrow::~Effect_BouncingArrow          _ZN20Effect_BouncingArrowD1Ev
// TODO     44 B  Effect_BouncingArrow::StaticNew                      _ZN20Effect_BouncingArrow9StaticNewEv
// TODO     44 B  Effect_BouncingArrow::ResetStartTime                 _ZN20Effect_BouncingArrow14ResetStartTimeEv
// TODO     36 B  Effect_BouncingArrow::~Effect_BouncingArrow          _ZN20Effect_BouncingArrowD0Ev
// TODO     32 B  Effect_BouncingArrow::PointDown                      _ZN20Effect_BouncingArrow9PointDownEv
// TODO     32 B  Effect_BouncingArrow::PointUp                        _ZN20Effect_BouncingArrow7PointUpEv
// TODO     32 B  Effect_BouncingArrow::PointLeft                      _ZN20Effect_BouncingArrow9PointLeftEv
// TODO     32 B  Effect_BouncingArrow::PointRight                     _ZN20Effect_BouncingArrow10PointRightEv
// TODO      8 B  Effect_BouncingArrow::SetRotation                    _ZN20Effect_BouncingArrow11SetRotationEf
// TODO      8 B  Effect_BouncingArrow::SetArrowImage                  _ZN20Effect_BouncingArrow13SetArrowImageEN4Sexy9RtWeakPtrINS0_5ImageEEE
// TODO      8 B  Effect_BouncingArrow::SetTransX                      _ZN20Effect_BouncingArrow9SetTransXEb
