// PvZ2/effects/Effect_PoisonGas.cpp
//
// 10 function(s), 1056 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: Effect_PoisonGas
//
// TODO    340 B  Effect_PoisonGas::PoisonZombie                       _ZN16Effect_PoisonGas12PoisonZombieEP6Zombief
// TODO    180 B  Effect_PoisonGas::StaticClassInit                    _ZN16Effect_PoisonGas15StaticClassInitEv
// TODO    124 B  Effect_PoisonGas::StaticGetClass                     _ZN16Effect_PoisonGas14StaticGetClassEv
// TODO    108 B  Effect_PoisonGas::onUpdate                           _ZN16Effect_PoisonGas8onUpdateEv
// TODO     56 B  Effect_PoisonGas::~Effect_PoisonGas                  _ZN16Effect_PoisonGasD2Ev
// TODO     56 B  Effect_PoisonGas::~Effect_PoisonGas                  _ZN16Effect_PoisonGasD1Ev
// TODO     56 B  Effect_PoisonGas::Effect_PoisonGas                   _ZN16Effect_PoisonGasC2Ev
// TODO     56 B  Effect_PoisonGas::Effect_PoisonGas                   _ZN16Effect_PoisonGasC1Ev
// TODO     44 B  Effect_PoisonGas::StaticNew                          _ZN16Effect_PoisonGas9StaticNewEv
// TODO     36 B  Effect_PoisonGas::~Effect_PoisonGas                  _ZN16Effect_PoisonGasD0Ev
