// PvZ2/ScoreEffect.cpp
//
// 12 function(s), 2148 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ScoreEffect
//
// TODO    496 B  ScoreEffect::onUpdate                                _ZN11ScoreEffect8onUpdateEv
// TODO    484 B  ScoreEffect::InitialiseEffect                        _ZN11ScoreEffect16InitialiseEffectERKSsS1_RKN4Sexy11SexyVector2E
// TODO    444 B  ScoreEffect::onDraw                                  _ZN11ScoreEffect6onDrawEPN4Sexy8GraphicsE
// TODO    180 B  ScoreEffect::StaticClassInit                         _ZN11ScoreEffect15StaticClassInitEv
// TODO    124 B  ScoreEffect::StaticGetClass                          _ZN11ScoreEffect14StaticGetClassEv
// TODO    104 B  ScoreEffect::ScoreEffect                             _ZN11ScoreEffectC2Ev
// TODO    104 B  ScoreEffect::ScoreEffect                             _ZN11ScoreEffectC1Ev
// TODO     64 B  ScoreEffect::~ScoreEffect                            _ZN11ScoreEffectD2Ev
// TODO     64 B  ScoreEffect::~ScoreEffect                            _ZN11ScoreEffectD1Ev
// TODO     44 B  ScoreEffect::StaticNew                               _ZN11ScoreEffect9StaticNewEv
// TODO     36 B  ScoreEffect::~ScoreEffect                            _ZN11ScoreEffectD0Ev
// TODO      4 B  ScoreEffect::onDestroy                               _ZN11ScoreEffect9onDestroyEv
