// PvZ2/griditems/renai/GridItemRenaiStatueHalf.cpp
//
// 14 function(s), 1704 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: GridItemRenaiStatueHalf
//
// TODO    464 B  GridItemRenaiStatueHalf::onDraw                      _ZN23GridItemRenaiStatueHalf6onDrawEPN4Sexy8GraphicsE
// TODO    216 B  GridItemRenaiStatueHalf::onGridItemInitialize        _ZN23GridItemRenaiStatueHalf20onGridItemInitializeEv
// TODO    180 B  GridItemRenaiStatueHalf::StaticClassInit             _ZN23GridItemRenaiStatueHalf15StaticClassInitEv
// TODO    160 B  GridItemRenaiStatueHalf::OnChangeState               _ZN23GridItemRenaiStatueHalf13OnChangeStateE11StatueState
// TODO    124 B  GridItemRenaiStatueHalf::StaticGetClass              _ZN23GridItemRenaiStatueHalf14StaticGetClassEv
// TODO    112 B  GridItemRenaiStatueHalf::~GridItemRenaiStatueHalf    _ZN23GridItemRenaiStatueHalfD2Ev
// TODO    112 B  GridItemRenaiStatueHalf::~GridItemRenaiStatueHalf    _ZN23GridItemRenaiStatueHalfD1Ev
// TODO    112 B  GridItemRenaiStatueHalf::onUpdate                    _ZN23GridItemRenaiStatueHalf8onUpdateEv
// TODO     64 B  GridItemRenaiStatueHalf::GridItemRenaiStatueHalf     _ZN23GridItemRenaiStatueHalfC2Ev
// TODO     64 B  GridItemRenaiStatueHalf::GridItemRenaiStatueHalf     _ZN23GridItemRenaiStatueHalfC1Ev
// TODO     44 B  GridItemRenaiStatueHalf::StaticNew                   _ZN23GridItemRenaiStatueHalf9StaticNewEv
// TODO     36 B  GridItemRenaiStatueHalf::~GridItemRenaiStatueHalf    _ZN23GridItemRenaiStatueHalfD0Ev
// TODO     12 B  GridItemRenaiStatueHalf::CanBeCarved                 _ZN23GridItemRenaiStatueHalf11CanBeCarvedEv
// TODO      4 B  GridItemRenaiStatueHalf::onAnimEnded                 _ZN23GridItemRenaiStatueHalf11onAnimEndedERKSs
