// PvZ2/griditems/renai/GridItemRenaiStatue.cpp
//
// 40 function(s), 5464 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: GridItemRenaiStatue, GridItemRenaiStatueProps
//
// TODO    636 B  GridItemRenaiStatue::CreateMinorEffects              _ZN19GridItemRenaiStatue18CreateMinorEffectsEv
// TODO    572 B  GridItemRenaiStatue::setState                        _ZN19GridItemRenaiStatue8setStateE11StatueState
// TODO    444 B  GridItemRenaiStatue::SpawnZombies                    _ZN19GridItemRenaiStatue12SpawnZombiesEv
// TODO    316 B  GridItemRenaiStatue::onGridItemInitialize            _ZN19GridItemRenaiStatue20onGridItemInitializeEv
// TODO    276 B  GridItemRenaiStatue::onUpdate                        _ZN19GridItemRenaiStatue8onUpdateEv
// TODO    236 B  GridItemRenaiStatue::PlayDustEffect                  _ZN19GridItemRenaiStatue14PlayDustEffectEv
// TODO    232 B  GridItemRenaiStatue::DisableEffects                  _ZN19GridItemRenaiStatue14DisableEffectsEv
// TODO    228 B  GridItemRenaiStatue::onDustEffectDone                _ZN19GridItemRenaiStatue16onDustEffectDoneERKSs
// TODO    204 B  GridItemRenaiStatue::PlayRockEffect                  _ZN19GridItemRenaiStatue14PlayRockEffectEv
// TODO    188 B  GridItemRenaiStatue::onAnimEnded                     _ZN19GridItemRenaiStatue11onAnimEndedERKSs
// TODO    180 B  GridItemRenaiStatue::StaticClassInit                 _ZN19GridItemRenaiStatue15StaticClassInitEv
// TODO    180 B  GridItemRenaiStatueProps::StaticClassInit            _ZN24GridItemRenaiStatueProps15StaticClassInitEv
// TODO    164 B  GridItemRenaiStatue::onPostLoad                      _ZN19GridItemRenaiStatue10onPostLoadEv
// TODO    128 B  GridItemRenaiStatue::onDestroy                       _ZN19GridItemRenaiStatue9onDestroyEv
// TODO    124 B  GridItemRenaiStatue::StaticGetClass                  _ZN19GridItemRenaiStatue14StaticGetClassEv
// TODO    124 B  GridItemRenaiStatueProps::StaticGetClass             _ZN24GridItemRenaiStatueProps14StaticGetClassEv
// TODO    108 B  GridItemRenaiStatue::registerForEvents               _ZN19GridItemRenaiStatue17registerForEventsEv
// TODO    104 B  GridItemRenaiStatue::GetRockEffectName               _ZN19GridItemRenaiStatue17GetRockEffectNameEv
// TODO    100 B  GridItemRenaiStatue::onZombieSpawned                 _ZN19GridItemRenaiStatue15onZombieSpawnedEP6Zombie
// TODO     92 B  GridItemRenaiStatue::GridItemRenaiStatue             _ZN19GridItemRenaiStatueC2Ev
// TODO     92 B  GridItemRenaiStatue::GridItemRenaiStatue             _ZN19GridItemRenaiStatueC1Ev
// TODO     88 B  GridItemRenaiStatueProps::GridItemRenaiStatueProps   _ZN24GridItemRenaiStatuePropsC2Ev
// TODO     88 B  GridItemRenaiStatueProps::GridItemRenaiStatueProps   _ZN24GridItemRenaiStatuePropsC1Ev
// TODO     72 B  GridItemRenaiStatue::~GridItemRenaiStatue            _ZN19GridItemRenaiStatueD2Ev
// TODO     72 B  GridItemRenaiStatue::~GridItemRenaiStatue            _ZN19GridItemRenaiStatueD1Ev
// TODO     68 B  GridItemRenaiStatue::TryRevive                       _ZN19GridItemRenaiStatue9TryReviveEv
// TODO     56 B  GridItemRenaiStatueProps::~GridItemRenaiStatueProps  _ZN24GridItemRenaiStatuePropsD2Ev
// TODO     56 B  GridItemRenaiStatueProps::~GridItemRenaiStatueProps  _ZN24GridItemRenaiStatuePropsD1Ev
// TODO     44 B  GridItemRenaiStatue::StaticNew                       _ZN19GridItemRenaiStatue9StaticNewEv
// TODO     44 B  GridItemRenaiStatueProps::StaticNew                  _ZN24GridItemRenaiStatueProps9StaticNewEv
// TODO     36 B  GridItemRenaiStatue::~GridItemRenaiStatue            _ZN19GridItemRenaiStatueD0Ev
// TODO     36 B  GridItemRenaiStatueProps::~GridItemRenaiStatueProps  _ZN24GridItemRenaiStatuePropsD0Ev
// TODO     24 B  GridItemRenaiStatue::GetCarveTime                    _ZN19GridItemRenaiStatue12GetCarveTimeEv
// TODO     12 B  GridItemRenaiStatue::IsCarving                       _ZN19GridItemRenaiStatue9IsCarvingEv
// TODO      8 B  GridItemRenaiStatue::CanBeCarved                     _ZN19GridItemRenaiStatue11CanBeCarvedEv
// TODO      8 B  GridItemRenaiStatue::HasGravity                      _ZN19GridItemRenaiStatue10HasGravityEv
// TODO      8 B  GridItemRenaiStatue::TryCarve                        _ZN19GridItemRenaiStatue8TryCarveEv
// TODO      8 B  GridItemRenaiStatue::TryRecover                      _ZN19GridItemRenaiStatue10TryRecoverEv
// TODO      4 B  GridItemRenaiStatue::OnChangeState                   _ZN19GridItemRenaiStatue13OnChangeStateE11StatueState
// TODO      4 B  GridItemRenaiStatue::onPopAnimCommand                _ZN19GridItemRenaiStatue16onPopAnimCommandERKSsfS1_S1_
