// PvZ2/level/customlevel/CustomLevelDataCreator.cpp
//
// 23 function(s), 3772 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: CustomLevelDataCreator
//
// TODO    480 B  CustomLevelDataCreator::LoadLevelData                _ZN22CustomLevelDataCreator13LoadLevelDataERKSs
// TODO    448 B  CustomLevelDataCreator::LoadLevelDatas               _ZN22CustomLevelDataCreator14LoadLevelDatasEv
// TODO    308 B  CustomLevelDataCreator::DeleteLevelData              _ZN22CustomLevelDataCreator15DeleteLevelDataERKSs
// TODO    264 B  CustomLevelDataCreator::SaveLevelData                _ZN22CustomLevelDataCreator13SaveLevelDataERK22CustomLevelWorldParams
// TODO    248 B  CustomLevelDataCreator::CreateLevelID                _ZN22CustomLevelDataCreator13CreateLevelIDEv
// TODO    240 B  CustomLevelDataCreator::Save                         _ZN22CustomLevelDataCreator4SaveE22CustomLevelWorldParams
// TODO    240 B  CustomLevelDataCreator::RemoveLevelData              _ZN22CustomLevelDataCreator15RemoveLevelDataERKSs
// TODO    232 B  CustomLevelDataCreator::GenerateRandomLevelIDSegment _ZN22CustomLevelDataCreator28GenerateRandomLevelIDSegmentEv
// TODO    220 B  CustomLevelDataCreator::ConstructLevelData           _ZN22CustomLevelDataCreator18ConstructLevelDataERK22CustomLevelWorldParams
// TODO    172 B  CustomLevelDataCreator::GetLevelData                 _ZN22CustomLevelDataCreator12GetLevelDataERKSs
// TODO    168 B  CustomLevelDataCreator::GetLevelDataPtr              _ZN22CustomLevelDataCreator15GetLevelDataPtrERKSs
// TODO    152 B  CustomLevelDataCreator::FillLevelData                _ZN22CustomLevelDataCreator13FillLevelDataEN4Sexy9RtWeakPtrI15CustomLevelDataEE
// TODO    136 B  CustomLevelDataCreator::IsLevelDownload              _ZN22CustomLevelDataCreator15IsLevelDownloadERKSs
// TODO    104 B  CustomLevelDataCreator::GetLevelData                 _ZN22CustomLevelDataCreator12GetLevelDataEi
// TODO    104 B  CustomLevelDataCreator::GetLevelDataPtr              _ZN22CustomLevelDataCreator15GetLevelDataPtrEi
// TODO     64 B  CustomLevelDataCreator::SortLevelDatas               _ZN22CustomLevelDataCreator14SortLevelDatasEv
// TODO     48 B  CustomLevelDataCreator::CustomLevelDataCreator       _ZN22CustomLevelDataCreatorC1Ev
// TODO     48 B  CustomLevelDataCreator::CustomLevelDataCreator       _ZN22CustomLevelDataCreatorC2Ev
// TODO     40 B  CustomLevelDataCreator::~CustomLevelDataCreator      _ZN22CustomLevelDataCreatorD2Ev
// TODO     40 B  CustomLevelDataCreator::~CustomLevelDataCreator      _ZN22CustomLevelDataCreatorD1Ev
// TODO      8 B  CustomLevelDataCreator::DeleteLevelData              _ZN22CustomLevelDataCreator15DeleteLevelDataERK22CustomLevelWorldParams
// TODO      4 B  CustomLevelDataCreator::GetLevelDatas                _ZN22CustomLevelDataCreator13GetLevelDatasEv
// TODO      4 B  CustomLevelDataCreator::Load                         _ZN22CustomLevelDataCreator4LoadEv
