// PvZ2/data/DaveTaskConfig.cpp
//
// 8 function(s), 592 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: DaveTaskConfig
//
// TODO    180 B  DaveTaskConfig::StaticClassInit                      _ZN14DaveTaskConfig15StaticClassInitEv
// TODO    124 B  DaveTaskConfig::StaticGetClass                       _ZN14DaveTaskConfig14StaticGetClassEv
// TODO     52 B  DaveTaskConfig::DaveTaskConfig                       _ZN14DaveTaskConfigC2Ev
// TODO     52 B  DaveTaskConfig::DaveTaskConfig                       _ZN14DaveTaskConfigC1Ev
// TODO     52 B  DaveTaskConfig::~DaveTaskConfig                      _ZN14DaveTaskConfigD2Ev
// TODO     52 B  DaveTaskConfig::~DaveTaskConfig                      _ZN14DaveTaskConfigD1Ev
// TODO     44 B  DaveTaskConfig::StaticNew                            _ZN14DaveTaskConfig9StaticNewEv
// TODO     36 B  DaveTaskConfig::~DaveTaskConfig                      _ZN14DaveTaskConfigD0Ev
