// PvZ2/zombies/FutureJetpack/ZombieAnimRig_FutureJetpack.cpp
//
// 19 function(s), 3424 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieAnimRig_FutureJetpack
//
// TODO    740 B  ZombieAnimRig_FutureJetpack::getDiscoLayerNames      _ZN27ZombieAnimRig_FutureJetpack18getDiscoLayerNamesEv
// TODO    404 B  ZombieAnimRig_FutureJetpack::getHeadLayerNames       _ZN27ZombieAnimRig_FutureJetpack17getHeadLayerNamesEv
// TODO    348 B  ZombieAnimRig_FutureJetpack::getArmLayerNames        _ZN27ZombieAnimRig_FutureJetpack16getArmLayerNamesEv
// TODO    320 B  ZombieAnimRig_FutureJetpack::getArmReplacementPairNames _ZN27ZombieAnimRig_FutureJetpack26getArmReplacementPairNamesEv
// TODO    188 B  ZombieAnimRig_FutureJetpack::PlayDropIn              _ZN27ZombieAnimRig_FutureJetpack10PlayDropInE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    188 B  ZombieAnimRig_FutureJetpack::PlayFlyUp               _ZN27ZombieAnimRig_FutureJetpack9PlayFlyUpE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    188 B  ZombieAnimRig_FutureJetpack::PlayFlyDown             _ZN27ZombieAnimRig_FutureJetpack11PlayFlyDownE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    188 B  ZombieAnimRig_FutureJetpack::SetDiscoMode            _ZN27ZombieAnimRig_FutureJetpack12SetDiscoModeEb
// TODO    180 B  ZombieAnimRig_FutureJetpack::StaticClassInit         _ZN27ZombieAnimRig_FutureJetpack15StaticClassInitEv
// TODO    164 B  ZombieAnimRig_FutureJetpack::PlayFlyIdle             _ZN27ZombieAnimRig_FutureJetpack11PlayFlyIdleEv
// TODO    128 B  ZombieAnimRig_FutureJetpack::GetHeadParticleName     _ZN27ZombieAnimRig_FutureJetpack19GetHeadParticleNameEv
// TODO    124 B  ZombieAnimRig_FutureJetpack::StaticGetClass          _ZN27ZombieAnimRig_FutureJetpack14StaticGetClassEv
// TODO     60 B  ZombieAnimRig_FutureJetpack::ZombieAnimRig_FutureJetpack _ZN27ZombieAnimRig_FutureJetpackC2Ev
// TODO     60 B  ZombieAnimRig_FutureJetpack::ZombieAnimRig_FutureJetpack _ZN27ZombieAnimRig_FutureJetpackC1Ev
// TODO     44 B  ZombieAnimRig_FutureJetpack::StaticNew               _ZN27ZombieAnimRig_FutureJetpack9StaticNewEv
// TODO     36 B  ZombieAnimRig_FutureJetpack::~ZombieAnimRig_FutureJetpack _ZN27ZombieAnimRig_FutureJetpackD0Ev
// TODO     28 B  ZombieAnimRig_FutureJetpack::~ZombieAnimRig_FutureJetpack _ZN27ZombieAnimRig_FutureJetpackD2Ev
// TODO     28 B  ZombieAnimRig_FutureJetpack::~ZombieAnimRig_FutureJetpack _ZN27ZombieAnimRig_FutureJetpackD1Ev
// TODO      8 B  ZombieAnimRig_FutureJetpack::onPopAnimInitialized    _ZN27ZombieAnimRig_FutureJetpack20onPopAnimInitializedEv
