// PvZ2/zombies/ChildrensdayGargantuar/ZombieAnimRig_ChildrensdayGargantuar.cpp
//
// 9 function(s), 872 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieAnimRig_ChildrensdayGargantuar
//
// TODO    320 B  ZombieAnimRig_ChildrensdayGargantuar::getHeadLayerNames _ZN36ZombieAnimRig_ChildrensdayGargantuar17getHeadLayerNamesEv
// TODO    180 B  ZombieAnimRig_ChildrensdayGargantuar::StaticClassInit _ZN36ZombieAnimRig_ChildrensdayGargantuar15StaticClassInitEv
// TODO    124 B  ZombieAnimRig_ChildrensdayGargantuar::StaticGetClass _ZN36ZombieAnimRig_ChildrensdayGargantuar14StaticGetClassEv
// TODO     56 B  ZombieAnimRig_ChildrensdayGargantuar::ZombieAnimRig_ChildrensdayGargantuar _ZN36ZombieAnimRig_ChildrensdayGargantuarC2Ev
// TODO     56 B  ZombieAnimRig_ChildrensdayGargantuar::ZombieAnimRig_ChildrensdayGargantuar _ZN36ZombieAnimRig_ChildrensdayGargantuarC1Ev
// TODO     44 B  ZombieAnimRig_ChildrensdayGargantuar::StaticNew      _ZN36ZombieAnimRig_ChildrensdayGargantuar9StaticNewEv
// TODO     36 B  ZombieAnimRig_ChildrensdayGargantuar::~ZombieAnimRig_ChildrensdayGargantuar _ZN36ZombieAnimRig_ChildrensdayGargantuarD0Ev
// TODO     28 B  ZombieAnimRig_ChildrensdayGargantuar::~ZombieAnimRig_ChildrensdayGargantuar _ZN36ZombieAnimRig_ChildrensdayGargantuarD2Ev
// TODO     28 B  ZombieAnimRig_ChildrensdayGargantuar::~ZombieAnimRig_ChildrensdayGargantuar _ZN36ZombieAnimRig_ChildrensdayGargantuarD1Ev
