// PvZ2/zombies/WolfBoss/ZombieAnimRig_WolfBoss.cpp
//
// 14 function(s), 2100 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieAnimRig_WolfBoss
//
// TODO    320 B  ZombieAnimRig_WolfBoss::getHeadLayerNames            _ZN22ZombieAnimRig_WolfBoss17getHeadLayerNamesEv
// TODO    320 B  ZombieAnimRig_WolfBoss::getArmLayerNames             _ZN22ZombieAnimRig_WolfBoss16getArmLayerNamesEv
// TODO    320 B  ZombieAnimRig_WolfBoss::getArmReplacementPairNames   _ZN22ZombieAnimRig_WolfBoss26getArmReplacementPairNamesEv
// TODO    196 B  ZombieAnimRig_WolfBoss::PlayIntro                    _ZN22ZombieAnimRig_WolfBoss9PlayIntroE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    196 B  ZombieAnimRig_WolfBoss::PlayFire                     _ZN22ZombieAnimRig_WolfBoss8PlayFireE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    196 B  ZombieAnimRig_WolfBoss::PlayBlow                     _ZN22ZombieAnimRig_WolfBoss8PlayBlowE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    180 B  ZombieAnimRig_WolfBoss::StaticClassInit              _ZN22ZombieAnimRig_WolfBoss15StaticClassInitEv
// TODO    124 B  ZombieAnimRig_WolfBoss::StaticGetClass               _ZN22ZombieAnimRig_WolfBoss14StaticGetClassEv
// TODO     56 B  ZombieAnimRig_WolfBoss::ZombieAnimRig_WolfBoss       _ZN22ZombieAnimRig_WolfBossC2Ev
// TODO     56 B  ZombieAnimRig_WolfBoss::ZombieAnimRig_WolfBoss       _ZN22ZombieAnimRig_WolfBossC1Ev
// TODO     44 B  ZombieAnimRig_WolfBoss::StaticNew                    _ZN22ZombieAnimRig_WolfBoss9StaticNewEv
// TODO     36 B  ZombieAnimRig_WolfBoss::~ZombieAnimRig_WolfBoss      _ZN22ZombieAnimRig_WolfBossD0Ev
// TODO     28 B  ZombieAnimRig_WolfBoss::~ZombieAnimRig_WolfBoss      _ZN22ZombieAnimRig_WolfBossD2Ev
// TODO     28 B  ZombieAnimRig_WolfBoss::~ZombieAnimRig_WolfBoss      _ZN22ZombieAnimRig_WolfBossD1Ev
