// PvZ2/plants/JewelRabbit/PlantAnimRig_JewelRabbit.cpp
//
// 14 function(s), 1272 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_JewelRabbit
//
// TODO    180 B  PlantAnimRig_JewelRabbit::StaticClassInit            _ZN24PlantAnimRig_JewelRabbit15StaticClassInitEv
// TODO    156 B  PlantAnimRig_JewelRabbit::playSingleAnimation        _ZN24PlantAnimRig_JewelRabbit19playSingleAnimationESs20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    148 B  PlantAnimRig_JewelRabbit::playLoopAnimation          _ZN24PlantAnimRig_JewelRabbit17playLoopAnimationESs
// TODO    124 B  PlantAnimRig_JewelRabbit::StaticGetClass             _ZN24PlantAnimRig_JewelRabbit14StaticGetClassEv
// TODO    104 B  PlantAnimRig_JewelRabbit::getPlantFoodOnAnimName     _ZN24PlantAnimRig_JewelRabbit22getPlantFoodOnAnimNameEv
// TODO    104 B  PlantAnimRig_JewelRabbit::getIdleAnimationName       _ZN24PlantAnimRig_JewelRabbit20getIdleAnimationNameEv
// TODO    104 B  PlantAnimRig_JewelRabbit::getPlantFoodOffAnimName    _ZN24PlantAnimRig_JewelRabbit23getPlantFoodOffAnimNameEv
// TODO    104 B  PlantAnimRig_JewelRabbit::getPlantFoodMainAnimName   _ZN24PlantAnimRig_JewelRabbit24getPlantFoodMainAnimNameEv
// TODO     56 B  PlantAnimRig_JewelRabbit::PlantAnimRig_JewelRabbit   _ZN24PlantAnimRig_JewelRabbitC2Ev
// TODO     56 B  PlantAnimRig_JewelRabbit::PlantAnimRig_JewelRabbit   _ZN24PlantAnimRig_JewelRabbitC1Ev
// TODO     44 B  PlantAnimRig_JewelRabbit::StaticNew                  _ZN24PlantAnimRig_JewelRabbit9StaticNewEv
// TODO     36 B  PlantAnimRig_JewelRabbit::~PlantAnimRig_JewelRabbit  _ZN24PlantAnimRig_JewelRabbitD0Ev
// TODO     28 B  PlantAnimRig_JewelRabbit::~PlantAnimRig_JewelRabbit  _ZN24PlantAnimRig_JewelRabbitD2Ev
// TODO     28 B  PlantAnimRig_JewelRabbit::~PlantAnimRig_JewelRabbit  _ZN24PlantAnimRig_JewelRabbitD1Ev
