// PvZ2/plants/CarrotMissile/Plant_CarrotMissile.cpp
//
// 17 function(s), 2000 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantCarrotMissile
//
// TODO   1024 B  PlantCarrotMissile::onKilled                         _ZN18PlantCarrotMissile8onKilledEb
// TODO    276 B  PlantCarrotMissile::PlayIdleAnim                     _ZN18PlantCarrotMissile12PlayIdleAnimEb
// TODO    180 B  PlantCarrotMissile::StaticClassInit                  _ZN18PlantCarrotMissile15StaticClassInitEv
// TODO    124 B  PlantCarrotMissile::StaticGetClass                   _ZN18PlantCarrotMissile14StaticGetClassEv
// TODO     72 B  PlantCarrotMissile::UpdateActions                    _ZN18PlantCarrotMissile13UpdateActionsEv
// TODO     52 B  PlantCarrotMissile::PlantCarrotMissile               _ZN18PlantCarrotMissileC2Ev
// TODO     52 B  PlantCarrotMissile::PlantCarrotMissile               _ZN18PlantCarrotMissileC1Ev
// TODO     44 B  PlantCarrotMissile::StaticNew                        _ZN18PlantCarrotMissile9StaticNewEv
// TODO     36 B  PlantCarrotMissile::Initialize                       _ZN18PlantCarrotMissile10InitializeEv
// TODO     36 B  PlantCarrotMissile::~PlantCarrotMissile              _ZN18PlantCarrotMissileD0Ev
// TODO     20 B  PlantCarrotMissile::onBeThrown                       _ZN18PlantCarrotMissile10onBeThrownEv
// TODO     20 B  PlantCarrotMissile::onBePushed                       _ZN18PlantCarrotMissile10onBePushedEv
// TODO     20 B  PlantCarrotMissile::~PlantCarrotMissile              _ZN18PlantCarrotMissileD2Ev
// TODO     20 B  PlantCarrotMissile::~PlantCarrotMissile              _ZN18PlantCarrotMissileD1Ev
// TODO      8 B  PlantCarrotMissile::CanBeShoveled                    _ZN18PlantCarrotMissile13CanBeShoveledEv
// TODO      8 B  PlantCarrotMissile::CanApplyPlantfood                _ZN18PlantCarrotMissile17CanApplyPlantfoodEv
// TODO      8 B  PlantCarrotMissile::HasShadow                        _ZN18PlantCarrotMissile9HasShadowEv
