// PvZ2/griditems/running/GridItemRunningSubwayObjectAnimRig.cpp
//
// 10 function(s), 796 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: GridItemRunningSubwayObjectAnimRig
//
// TODO    180 B  GridItemRunningSubwayObjectAnimRig::StaticClassInit  _ZN34GridItemRunningSubwayObjectAnimRig15StaticClassInitEv
// TODO    140 B  GridItemRunningSubwayObjectAnimRig::PlayIdle         _ZN34GridItemRunningSubwayObjectAnimRig8PlayIdleEv
// TODO    124 B  GridItemRunningSubwayObjectAnimRig::StaticGetClass   _ZN34GridItemRunningSubwayObjectAnimRig14StaticGetClassEv
// TODO    104 B  GridItemRunningSubwayObjectAnimRig::getIdleAnimLabel _ZN34GridItemRunningSubwayObjectAnimRig16getIdleAnimLabelEv
// TODO     56 B  GridItemRunningSubwayObjectAnimRig::GridItemRunningSubwayObjectAnimRig _ZN34GridItemRunningSubwayObjectAnimRigC2Ev
// TODO     56 B  GridItemRunningSubwayObjectAnimRig::GridItemRunningSubwayObjectAnimRig _ZN34GridItemRunningSubwayObjectAnimRigC1Ev
// TODO     44 B  GridItemRunningSubwayObjectAnimRig::StaticNew        _ZN34GridItemRunningSubwayObjectAnimRig9StaticNewEv
// TODO     36 B  GridItemRunningSubwayObjectAnimRig::~GridItemRunningSubwayObjectAnimRig _ZN34GridItemRunningSubwayObjectAnimRigD0Ev
// TODO     28 B  GridItemRunningSubwayObjectAnimRig::~GridItemRunningSubwayObjectAnimRig _ZN34GridItemRunningSubwayObjectAnimRigD2Ev
// TODO     28 B  GridItemRunningSubwayObjectAnimRig::~GridItemRunningSubwayObjectAnimRig _ZN34GridItemRunningSubwayObjectAnimRigD1Ev
