// PvZ2/plants/StickybombRice/Plant_StickybombRice.cpp
//
// 22 function(s), 4104 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantStickybombRice
//
// TODO    600 B  PlantStickybombRice::fireAtTarget                    _ZN19PlantStickybombRice12fireAtTargetEP11BoardEntity11PlantWeapon
// TODO    468 B  PlantStickybombRice::DoSpecial                       _ZN19PlantStickybombRice9DoSpecialEi
// TODO    396 B  PlantStickybombRice::launchSpecialProjectile         _ZN19PlantStickybombRice23launchSpecialProjectileEN4Sexy11SexyVector3ENS0_9RtWeakPtrI11BoardEntityEERKS4_
// TODO    368 B  PlantStickybombRice::isValidTarget                   _ZN19PlantStickybombRice13isValidTargetEP11BoardEntity
// TODO    336 B  PlantStickybombRice::Fire                            _ZN19PlantStickybombRice4FireEN4Sexy9RtWeakPtrI6ZombieEEi11PlantWeapon
// TODO    284 B  PlantStickybombRice::launchLv5ProjectileAt           _ZN19PlantStickybombRice21launchLv5ProjectileAtEP10ProjectileRKN4Sexy11SexyVector3ENS2_9RtWeakPtrI11BoardEntityEEff
// TODO    252 B  PlantStickybombRice::findTargets                     _ZN19PlantStickybombRice11findTargetsERSt6vectorIP11BoardEntitySaIS2_EE11PlantWeapon
// TODO    248 B  PlantStickybombRice::launchProjectileAt              _ZN19PlantStickybombRice18launchProjectileAtEP10ProjectileRKN4Sexy11SexyVector3ENS2_9RtWeakPtrI11BoardEntityEEff
// TODO    208 B  PlantStickybombRice::isZombieFullOfBombs             _ZN19PlantStickybombRice19isZombieFullOfBombsEP6Zombie
// TODO    208 B  PlantStickybombRice::getBestSingleTarget             _ZN19PlantStickybombRice19getBestSingleTargetE11PlantWeapon
// TODO    180 B  PlantStickybombRice::StaticClassInit                 _ZN19PlantStickybombRice15StaticClassInitEv
// TODO    124 B  PlantStickybombRice::StaticGetClass                  _ZN19PlantStickybombRice14StaticGetClassEv
// TODO     96 B  PlantStickybombRice::FindTargetAndFire               _ZN19PlantStickybombRice17FindTargetAndFireE11PlantWeapon
// TODO     72 B  PlantStickybombRice::GetPlantAttackRect              _ZN19PlantStickybombRice18GetPlantAttackRectE11PlantWeapon
// TODO     48 B  PlantStickybombRice::PlantStickybombRice             _ZN19PlantStickybombRiceC2Ev
// TODO     48 B  PlantStickybombRice::PlantStickybombRice             _ZN19PlantStickybombRiceC1Ev
// TODO     44 B  PlantStickybombRice::StaticNew                       _ZN19PlantStickybombRice9StaticNewEv
// TODO     40 B  PlantStickybombRice::playAttackAnimation             _ZN19PlantStickybombRice19playAttackAnimationEb
// TODO     36 B  PlantStickybombRice::~PlantStickybombRice            _ZN19PlantStickybombRiceD0Ev
// TODO     20 B  PlantStickybombRice::~PlantStickybombRice            _ZN19PlantStickybombRiceD2Ev
// TODO     20 B  PlantStickybombRice::~PlantStickybombRice            _ZN19PlantStickybombRiceD1Ev
// TODO      8 B  PlantStickybombRice::CanApplyPlantfood               _ZN19PlantStickybombRice17CanApplyPlantfoodEv
