// PvZ2/ZombiePirateBarrel.cpp
//
// 34 function(s), 4140 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombiePirateBarrel
//
// TODO    636 B  ZombiePirateBarrel::StaticClassInit                  _ZN18ZombiePirateBarrel15StaticClassInitEv
// TODO    500 B  ZombiePirateBarrel::spawnImp                         _ZN18ZombiePirateBarrel8spawnImpEi
// TODO    456 B  ZombiePirateBarrel::tryEating                        _ZN18ZombiePirateBarrel9tryEatingEv
// TODO    348 B  ZombiePirateBarrel::onTakeBodyDamage                 _ZN18ZombiePirateBarrel16onTakeBodyDamageERK10DamageInfo
// TODO    328 B  ZombiePirateBarrel::onTakeFatalDamage                _ZN18ZombiePirateBarrel17onTakeFatalDamageERK10DamageInfo
// TODO    200 B  ZombiePirateBarrel::onApplyCondition                 _ZN18ZombiePirateBarrel16onApplyConditionE16ZombieConditions
// TODO    196 B  ZombiePirateBarrel::CalcProjectileTargetLocation     _ZN18ZombiePirateBarrel28CalcProjectileTargetLocationEf
// TODO    156 B  ZombiePirateBarrel::onDestroy                        _ZN18ZombiePirateBarrel9onDestroyEv
// TODO    124 B  ZombiePirateBarrel::StaticGetClass                   _ZN18ZombiePirateBarrel14StaticGetClassEv
// TODO    116 B  ZombiePirateBarrel::onPlaceOnBoard                   _ZN18ZombiePirateBarrel14onPlaceOnBoardEv
// TODO    108 B  ZombiePirateBarrel::onUpdate                         _ZN18ZombiePirateBarrel8onUpdateEv
// TODO     92 B  ZombiePirateBarrel::updateState_BarrelIdle           _ZN18ZombiePirateBarrel22updateState_BarrelIdleEv
// TODO     92 B  ZombiePirateBarrel::updateState_BarrelRoll           _ZN18ZombiePirateBarrel22updateState_BarrelRollEv
// TODO     92 B  ZombiePirateBarrel::SetPusherZombie                  _ZN18ZombiePirateBarrel15SetPusherZombieEN4Sexy9RtWeakPtrI6ZombieEE
// TODO     88 B  ZombiePirateBarrel::CanForceLaneChange               _ZN18ZombiePirateBarrel18CanForceLaneChangeEv
// TODO     64 B  ZombiePirateBarrel::~ZombiePirateBarrel              _ZN18ZombiePirateBarrelD2Ev
// TODO     64 B  ZombiePirateBarrel::~ZombiePirateBarrel              _ZN18ZombiePirateBarrelD1Ev
// TODO     64 B  ZombiePirateBarrel::ZombiePirateBarrel               _ZN18ZombiePirateBarrelC2Ev
// TODO     64 B  ZombiePirateBarrel::ZombiePirateBarrel               _ZN18ZombiePirateBarrelC1Ev
// TODO     60 B  ZombiePirateBarrel::CanBePushed                      _ZN18ZombiePirateBarrel11CanBePushedEv
// TODO     48 B  ZombiePirateBarrel::onInitialized                    _ZN18ZombiePirateBarrel13onInitializedEv
// TODO     44 B  ZombiePirateBarrel::StaticNew                        _ZN18ZombiePirateBarrel9StaticNewEv
// TODO     40 B  ZombiePirateBarrel::GetPusherZombie                  _ZN18ZombiePirateBarrel15GetPusherZombieEv
// TODO     36 B  ZombiePirateBarrel::~ZombiePirateBarrel              _ZN18ZombiePirateBarrelD0Ev
// TODO     24 B  ZombiePirateBarrel::onEnterState_BarrelIdle          _ZN18ZombiePirateBarrel23onEnterState_BarrelIdleE11ZombieState
// TODO     24 B  ZombiePirateBarrel::onExitState_BarrelIdle           _ZN18ZombiePirateBarrel22onExitState_BarrelIdleE11ZombieState
// TODO     20 B  ZombiePirateBarrel::IsCrushingPlant                  _ZN18ZombiePirateBarrel15IsCrushingPlantEv
// TODO     12 B  ZombiePirateBarrel::onPlaceOnStreet                  _ZN18ZombiePirateBarrel15onPlaceOnStreetEv
// TODO     12 B  ZombiePirateBarrel::chooseDeathState                 _ZN18ZombiePirateBarrel16chooseDeathStateERK10DamageInfo
// TODO      8 B  ZombiePirateBarrel::isImmuneToShrinking              _ZN18ZombiePirateBarrel19isImmuneToShrinkingEv
// TODO      8 B  ZombiePirateBarrel::canTargetEntityHeight            _ZN18ZombiePirateBarrel21canTargetEntityHeightE17BoardEntityHeight
// TODO      8 B  ZombiePirateBarrel::SetBeingPushed                   _ZN18ZombiePirateBarrel14SetBeingPushedEb
// TODO      4 B  ZombiePirateBarrel::onEnterState_BarrelRoll          _ZN18ZombiePirateBarrel23onEnterState_BarrelRollE11ZombieState
// TODO      4 B  ZombiePirateBarrel::onExitState_BarrelRoll           _ZN18ZombiePirateBarrel22onExitState_BarrelRollE11ZombieState
