// PvZ2/plants/WinterRambutan/PlantAnimRig_WinterRambutan.cpp
//
// 10 function(s), 812 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_WinterRambutan
//
// TODO    180 B  PlantAnimRig_WinterRambutan::StaticClassInit         _ZN27PlantAnimRig_WinterRambutan15StaticClassInitEv
// TODO    156 B  PlantAnimRig_WinterRambutan::PlayTapAnimation        _ZN27PlantAnimRig_WinterRambutan16PlayTapAnimationESs20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    124 B  PlantAnimRig_WinterRambutan::StaticGetClass          _ZN27PlantAnimRig_WinterRambutan14StaticGetClassEv
// TODO    104 B  PlantAnimRig_WinterRambutan::getPlantFoodOnAnimName  _ZN27PlantAnimRig_WinterRambutan22getPlantFoodOnAnimNameEv
// TODO     56 B  PlantAnimRig_WinterRambutan::PlantAnimRig_WinterRambutan _ZN27PlantAnimRig_WinterRambutanC2Ev
// TODO     56 B  PlantAnimRig_WinterRambutan::PlantAnimRig_WinterRambutan _ZN27PlantAnimRig_WinterRambutanC1Ev
// TODO     44 B  PlantAnimRig_WinterRambutan::StaticNew               _ZN27PlantAnimRig_WinterRambutan9StaticNewEv
// TODO     36 B  PlantAnimRig_WinterRambutan::~PlantAnimRig_WinterRambutan _ZN27PlantAnimRig_WinterRambutanD0Ev
// TODO     28 B  PlantAnimRig_WinterRambutan::~PlantAnimRig_WinterRambutan _ZN27PlantAnimRig_WinterRambutanD2Ev
// TODO     28 B  PlantAnimRig_WinterRambutan::~PlantAnimRig_WinterRambutan _ZN27PlantAnimRig_WinterRambutanD1Ev
