// PvZ2/zombies/IceAgeHunterElite/ZombieIceAgeHunterElite.cpp
//
// 25 function(s), 3624 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieIceAgeHunterElite, ZombieIceAgeHunterEliteProps
//
// TODO    700 B  ZombieIceAgeHunterElite::FindNearestTargetInRange    _ZN23ZombieIceAgeHunterElite24FindNearestTargetInRangeEi
// TODO    676 B  ZombieIceAgeHunterElite::isNearestTargetInRange      _ZN23ZombieIceAgeHunterElite22isNearestTargetInRangeEv
// TODO    396 B  ZombieIceAgeHunterElite::onPopAnimCommand            _ZN23ZombieIceAgeHunterElite16onPopAnimCommandERKSsfS1_S1_
// TODO    356 B  ZombieIceAgeHunterElite::updateState_Walk            _ZN23ZombieIceAgeHunterElite16updateState_WalkEv
// TODO    200 B  ZombieIceAgeHunterElite::onEnterState_Eat            _ZN23ZombieIceAgeHunterElite16onEnterState_EatE11ZombieState
// TODO    180 B  ZombieIceAgeHunterElite::StaticClassInit             _ZN23ZombieIceAgeHunterElite15StaticClassInitEv
// TODO    180 B  ZombieIceAgeHunterEliteProps::StaticClassInit        _ZN28ZombieIceAgeHunterEliteProps15StaticClassInitEv
// TODO    124 B  ZombieIceAgeHunterElite::StaticGetClass              _ZN23ZombieIceAgeHunterElite14StaticGetClassEv
// TODO    124 B  ZombieIceAgeHunterEliteProps::StaticGetClass         _ZN28ZombieIceAgeHunterEliteProps14StaticGetClassEv
// TODO     72 B  ZombieIceAgeHunterElite::updateState_Eat             _ZN23ZombieIceAgeHunterElite15updateState_EatEv
// TODO     56 B  ZombieIceAgeHunterElite::ZombieIceAgeHunterElite     _ZN23ZombieIceAgeHunterEliteC2Ev
// TODO     56 B  ZombieIceAgeHunterElite::ZombieIceAgeHunterElite     _ZN23ZombieIceAgeHunterEliteC1Ev
// TODO     56 B  ZombieIceAgeHunterEliteProps::ZombieIceAgeHunterEliteProps _ZN28ZombieIceAgeHunterElitePropsC2Ev
// TODO     56 B  ZombieIceAgeHunterEliteProps::ZombieIceAgeHunterEliteProps _ZN28ZombieIceAgeHunterElitePropsC1Ev
// TODO     52 B  ZombieIceAgeHunterElite::IsSpecialSkillTime          _ZN23ZombieIceAgeHunterElite18IsSpecialSkillTimeEv
// TODO     44 B  ZombieIceAgeHunterElite::onPlaceOnBoard              _ZN23ZombieIceAgeHunterElite14onPlaceOnBoardEv
// TODO     44 B  ZombieIceAgeHunterElite::StaticNew                   _ZN23ZombieIceAgeHunterElite9StaticNewEv
// TODO     44 B  ZombieIceAgeHunterEliteProps::StaticNew              _ZN28ZombieIceAgeHunterEliteProps9StaticNewEv
// TODO     40 B  ZombieIceAgeHunterElite::onZombieInitialize          _ZN23ZombieIceAgeHunterElite18onZombieInitializeEv
// TODO     36 B  ZombieIceAgeHunterElite::~ZombieIceAgeHunterElite    _ZN23ZombieIceAgeHunterEliteD0Ev
// TODO     36 B  ZombieIceAgeHunterEliteProps::~ZombieIceAgeHunterEliteProps _ZN28ZombieIceAgeHunterElitePropsD0Ev
// TODO     28 B  ZombieIceAgeHunterElite::~ZombieIceAgeHunterElite    _ZN23ZombieIceAgeHunterEliteD2Ev
// TODO     28 B  ZombieIceAgeHunterElite::~ZombieIceAgeHunterElite    _ZN23ZombieIceAgeHunterEliteD1Ev
// TODO     20 B  ZombieIceAgeHunterEliteProps::~ZombieIceAgeHunterEliteProps _ZN28ZombieIceAgeHunterElitePropsD2Ev
// TODO     20 B  ZombieIceAgeHunterEliteProps::~ZombieIceAgeHunterEliteProps _ZN28ZombieIceAgeHunterElitePropsD1Ev
