// PvZ2/plants/ArmamintPeashooter/Plant_ArmamintPeashooter.cpp
//
// 21 function(s), 4008 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantArmamintPeashooter
//
// TODO    668 B  PlantArmamintPeashooter::launchAtEntity              _ZN23PlantArmamintPeashooter14launchAtEntityEN4Sexy9RtWeakPtrI11BoardEntityEE11PlantWeapon10AttackType
// TODO    460 B  PlantArmamintPeashooter::findAndInsertTargetForRow   _ZN23PlantArmamintPeashooter25findAndInsertTargetForRowERSt6vectorIN4Sexy9RtWeakPtrI11BoardEntityEESaIS4_EES7_ii11PlantWeapon
// TODO    452 B  PlantArmamintPeashooter::launchAtTargetsForNumShots  _ZN23PlantArmamintPeashooter26launchAtTargetsForNumShotsERKSt6vectorIN4Sexy9RtWeakPtrI11BoardEntityEESaIS4_EES8_i11PlantWeapon10AttackType
// TODO    392 B  PlantArmamintPeashooter::Fire                        _ZN23PlantArmamintPeashooter4FireEN4Sexy9RtWeakPtrI6ZombieEEi11PlantWeapon
// TODO    296 B  PlantArmamintPeashooter::getTargetLocationForEntity  _ZN23PlantArmamintPeashooter26getTargetLocationForEntityEN4Sexy9RtWeakPtrI11BoardEntityEE
// TODO    284 B  PlantArmamintPeashooter::PlayAttackAnimation         _ZN23PlantArmamintPeashooter19PlayAttackAnimationEv
// TODO    212 B  PlantArmamintPeashooter::launchProjectileAt          _ZN23PlantArmamintPeashooter18launchProjectileAtEP18ArmamintProjectileRKN4Sexy11SexyVector3Eff
// TODO    200 B  PlantArmamintPeashooter::TriggerAdvancedAttack       _ZN23PlantArmamintPeashooter21TriggerAdvancedAttackEv
// TODO    184 B  PlantArmamintPeashooter::findTargetsSpreadAcrossRows _ZN23PlantArmamintPeashooter27findTargetsSpreadAcrossRowsERSt6vectorIN4Sexy9RtWeakPtrI11BoardEntityEESaIS4_EES7_iii11PlantWeapon
// TODO    180 B  PlantArmamintPeashooter::StaticClassInit             _ZN23PlantArmamintPeashooter15StaticClassInitEv
// TODO    152 B  PlantArmamintPeashooter::TriggerFireAttack           _ZN23PlantArmamintPeashooter17TriggerFireAttackEv
// TODO    132 B  PlantArmamintPeashooter::launchProjectileAt          _ZN23PlantArmamintPeashooter18launchProjectileAtEP10ProjectileRKN4Sexy11SexyVector3Eff
// TODO    124 B  PlantArmamintPeashooter::StaticGetClass              _ZN23PlantArmamintPeashooter14StaticGetClassEv
// TODO     48 B  PlantArmamintPeashooter::Initialize                  _ZN23PlantArmamintPeashooter10InitializeEv
// TODO     48 B  PlantArmamintPeashooter::PlantArmamintPeashooter     _ZN23PlantArmamintPeashooterC2Ev
// TODO     48 B  PlantArmamintPeashooter::PlantArmamintPeashooter     _ZN23PlantArmamintPeashooterC1Ev
// TODO     44 B  PlantArmamintPeashooter::StaticNew                   _ZN23PlantArmamintPeashooter9StaticNewEv
// TODO     36 B  PlantArmamintPeashooter::~PlantArmamintPeashooter    _ZN23PlantArmamintPeashooterD0Ev
// TODO     20 B  PlantArmamintPeashooter::~PlantArmamintPeashooter    _ZN23PlantArmamintPeashooterD2Ev
// TODO     20 B  PlantArmamintPeashooter::~PlantArmamintPeashooter    _ZN23PlantArmamintPeashooterD1Ev
// TODO      8 B  PlantArmamintPeashooter::CanApplyPlantfood           _ZN23PlantArmamintPeashooter17CanApplyPlantfoodEv
