// PvZ2/plants/PassionFlower/Plant_PassionFlower.cpp
//
// 23 function(s), 3600 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantPassionFlower
//
// TODO    584 B  PlantPassionFlower::getFoodTargetPos                 _ZN18PlantPassionFlower16getFoodTargetPosEN4Sexy9RtWeakPtrI6ZombieEE
// TODO    436 B  PlantPassionFlower::foodFire                         _ZN18PlantPassionFlower8foodFireEN4Sexy9RtWeakPtrI6ZombieEEi11PlantWeapon
// TODO    416 B  PlantPassionFlower::FindTargetAndFire                _ZN18PlantPassionFlower17FindTargetAndFireE11PlantWeapon
// TODO    316 B  PlantPassionFlower::normalFire                       _ZN18PlantPassionFlower10normalFireEN4Sexy9RtWeakPtrI6ZombieEEi11PlantWeapon
// TODO    300 B  PlantPassionFlower::getDegree                        _ZN18PlantPassionFlower9getDegreeEN4Sexy9RtWeakPtrI11BoardEntityEE
// TODO    284 B  PlantPassionFlower::Fire                             _ZN18PlantPassionFlower4FireEN4Sexy9RtWeakPtrI6ZombieEEi11PlantWeapon
// TODO    244 B  PlantPassionFlower::PlaySuperAnimation               _ZN18PlantPassionFlower18PlaySuperAnimationEv
// TODO    224 B  PlantPassionFlower::superFire                        _ZN18PlantPassionFlower9superFireEN4Sexy9RtWeakPtrI6ZombieEEi11PlantWeapon
// TODO    180 B  PlantPassionFlower::StaticClassInit                  _ZN18PlantPassionFlower15StaticClassInitEv
// TODO    124 B  PlantPassionFlower::StaticGetClass                   _ZN18PlantPassionFlower14StaticGetClassEv
// TODO    100 B  PlantPassionFlower::getFoodDegree                    _ZN18PlantPassionFlower13getFoodDegreeEN4Sexy9RtWeakPtrI6ZombieEERKNS0_11SexyVector3E
// TODO     64 B  PlantPassionFlower::UpdatePlantfood                  _ZN18PlantPassionFlower15UpdatePlantfoodEv
// TODO     52 B  PlantPassionFlower::PlantPassionFlower               _ZN18PlantPassionFlowerC2Ev
// TODO     52 B  PlantPassionFlower::PlantPassionFlower               _ZN18PlantPassionFlowerC1Ev
// TODO     44 B  PlantPassionFlower::StaticNew                        _ZN18PlantPassionFlower9StaticNewEv
// TODO     36 B  PlantPassionFlower::ApplyPlantfood                   _ZN18PlantPassionFlower14ApplyPlantfoodEv
// TODO     36 B  PlantPassionFlower::CancelPlantfood                  _ZN18PlantPassionFlower15CancelPlantfoodEv
// TODO     36 B  PlantPassionFlower::~PlantPassionFlower              _ZN18PlantPassionFlowerD0Ev
// TODO     20 B  PlantPassionFlower::Initialize                       _ZN18PlantPassionFlower10InitializeEv
// TODO     20 B  PlantPassionFlower::~PlantPassionFlower              _ZN18PlantPassionFlowerD2Ev
// TODO     20 B  PlantPassionFlower::~PlantPassionFlower              _ZN18PlantPassionFlowerD1Ev
// TODO      8 B  PlantPassionFlower::CanApplyPlantfood                _ZN18PlantPassionFlower17CanApplyPlantfoodEv
// TODO      4 B  PlantPassionFlower::UpdateActions                    _ZN18PlantPassionFlower13UpdateActionsEv
