// PvZ2/waveactions/BarrelWaveAction.cpp
//
// 22 function(s), 2256 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: BarrelWaveAction, BarrelWaveActionProps
//
// TODO    376 B  BarrelWaveAction::WaveUpdate                         _ZN16BarrelWaveAction10WaveUpdateEiRN4Sexy6MTRandE
// TODO    280 B  BarrelWaveActionProps::StaticClassInit               _ZN21BarrelWaveActionProps15StaticClassInitEv
// TODO    268 B  BarrelWaveAction::SpawnBarrelStatic                  _ZN16BarrelWaveAction17SpawnBarrelStaticE17BarrelDescription
// TODO    180 B  BarrelWaveAction::StaticClassInit                    _ZN16BarrelWaveAction15StaticClassInitEv
// TODO    156 B  BarrelWaveAction::SpawnBarrel                        _ZN16BarrelWaveAction11SpawnBarrelE17BarrelDescription
// TODO    128 B  BarrelWaveAction::AddResourceRequirements            _ZN16BarrelWaveAction23AddResourceRequirementsERSt3setISsSt4lessISsESaISsEE
// TODO    124 B  BarrelWaveAction::StaticGetClass                     _ZN16BarrelWaveAction14StaticGetClassEv
// TODO    124 B  BarrelWaveActionProps::StaticGetClass                _ZN21BarrelWaveActionProps14StaticGetClassEv
// TODO     80 B  BarrelWaveAction::WaveStart                          _ZN16BarrelWaveAction9WaveStartEiN8WaveType8WaveTypeEbRN4Sexy6MTRandE
// TODO     60 B  BarrelWaveActionProps::BarrelWaveActionProps         _ZN21BarrelWaveActionPropsC2Ev
// TODO     60 B  BarrelWaveActionProps::BarrelWaveActionProps         _ZN21BarrelWaveActionPropsC1Ev
// TODO     52 B  BarrelWaveActionProps::~BarrelWaveActionProps        _ZN21BarrelWaveActionPropsD2Ev
// TODO     52 B  BarrelWaveActionProps::~BarrelWaveActionProps        _ZN21BarrelWaveActionPropsD1Ev
// TODO     48 B  BarrelWaveAction::BarrelWaveAction                   _ZN16BarrelWaveActionC2Ev
// TODO     48 B  BarrelWaveAction::BarrelWaveAction                   _ZN16BarrelWaveActionC1Ev
// TODO     44 B  BarrelWaveAction::StaticNew                          _ZN16BarrelWaveAction9StaticNewEv
// TODO     44 B  BarrelWaveActionProps::StaticNew                     _ZN21BarrelWaveActionProps9StaticNewEv
// TODO     36 B  BarrelWaveAction::~BarrelWaveAction                  _ZN16BarrelWaveActionD0Ev
// TODO     36 B  BarrelWaveActionProps::~BarrelWaveActionProps        _ZN21BarrelWaveActionPropsD0Ev
// TODO     20 B  BarrelWaveAction::WaveEnd                            _ZN16BarrelWaveAction7WaveEndEiRN4Sexy6MTRandE
// TODO     20 B  BarrelWaveAction::~BarrelWaveAction                  _ZN16BarrelWaveActionD2Ev
// TODO     20 B  BarrelWaveAction::~BarrelWaveAction                  _ZN16BarrelWaveActionD1Ev
