// PvZ2/plants/LavaGuava/PlantAnimRig_LavaGuava.cpp
//
// 21 function(s), 4684 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_LavaGuava
//
// TODO   1040 B  PlantAnimRig_LavaGuava::PlayAvatarCrackEffect        _ZN22PlantAnimRig_LavaGuava21PlayAvatarCrackEffectERKN4Sexy5PointE
// TODO    500 B  PlantAnimRig_LavaGuava::setCrackEmissionLocation     _ZN22PlantAnimRig_LavaGuava24setCrackEmissionLocationEv
// TODO    376 B  PlantAnimRig_LavaGuava::onUpdate                     _ZN22PlantAnimRig_LavaGuava8onUpdateEv
// TODO    364 B  PlantAnimRig_LavaGuava::initializeCrackEffects       _ZN22PlantAnimRig_LavaGuava22initializeCrackEffectsEv
// TODO    344 B  PlantAnimRig_LavaGuava::calcCrackState               _ZN22PlantAnimRig_LavaGuava14calcCrackStateEi13CrackLocation
// TODO    316 B  PlantAnimRig_LavaGuava::playPlantFoodOff             _ZN22PlantAnimRig_LavaGuava16playPlantFoodOffEv
// TODO    300 B  PlantAnimRig_LavaGuava::onCrackSpawned               _ZN22PlantAnimRig_LavaGuava14onCrackSpawnedERKSs
// TODO    228 B  PlantAnimRig_LavaGuava::onDestroy                    _ZN22PlantAnimRig_LavaGuava9onDestroyEv
// TODO    180 B  PlantAnimRig_LavaGuava::StaticClassInit              _ZN22PlantAnimRig_LavaGuava15StaticClassInitEv
// TODO    140 B  PlantAnimRig_LavaGuava::PlayCrackEffect              _ZN22PlantAnimRig_LavaGuava15PlayCrackEffectEiRKN4Sexy5PointE
// TODO    124 B  PlantAnimRig_LavaGuava::StaticGetClass               _ZN22PlantAnimRig_LavaGuava14StaticGetClassEv
// TODO    104 B  PlantAnimRig_LavaGuava::getPlantFoodOnAnimName       _ZN22PlantAnimRig_LavaGuava22getPlantFoodOnAnimNameEv
// TODO    104 B  PlantAnimRig_LavaGuava::getPlantFoodMainAnimName     _ZN22PlantAnimRig_LavaGuava24getPlantFoodMainAnimNameEv
// TODO    104 B  PlantAnimRig_LavaGuava::getPlantFoodOffAnimName      _ZN22PlantAnimRig_LavaGuava23getPlantFoodOffAnimNameEv
// TODO     88 B  PlantAnimRig_LavaGuava::PlantAnimRig_LavaGuava       _ZN22PlantAnimRig_LavaGuavaC2Ev
// TODO     88 B  PlantAnimRig_LavaGuava::PlantAnimRig_LavaGuava       _ZN22PlantAnimRig_LavaGuavaC1Ev
// TODO     76 B  PlantAnimRig_LavaGuava::calcCrackLoc                 _ZN22PlantAnimRig_LavaGuava12calcCrackLocEi
// TODO     64 B  PlantAnimRig_LavaGuava::~PlantAnimRig_LavaGuava      _ZN22PlantAnimRig_LavaGuavaD2Ev
// TODO     64 B  PlantAnimRig_LavaGuava::~PlantAnimRig_LavaGuava      _ZN22PlantAnimRig_LavaGuavaD1Ev
// TODO     44 B  PlantAnimRig_LavaGuava::StaticNew                    _ZN22PlantAnimRig_LavaGuava9StaticNewEv
// TODO     36 B  PlantAnimRig_LavaGuava::~PlantAnimRig_LavaGuava      _ZN22PlantAnimRig_LavaGuavaD0Ev
