// PvZ2/AttachedEffectManager.cpp
//
// 15 function(s), 1776 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: AttachedEffectManager
//
// TODO    336 B  AttachedEffectManager::UpdateDynamicScaleForAllEffects _ZN21AttachedEffectManager31UpdateDynamicScaleForAllEffectsEfRKSt6vectorISsSaISsEE
// TODO    304 B  AttachedEffectManager::update                        _ZN21AttachedEffectManager6updateEf
// TODO    196 B  AttachedEffectManager::Clear                         _ZN21AttachedEffectManager5ClearEv
// TODO    180 B  AttachedEffectManager::StaticClassInit               _ZN21AttachedEffectManager15StaticClassInitEv
// TODO    148 B  AttachedEffectManager::remove                        _ZN21AttachedEffectManager6removeEi
// TODO    140 B  AttachedEffectManager::add                           _ZN21AttachedEffectManager3addERKSs
// TODO    124 B  AttachedEffectManager::StaticGetClass                _ZN21AttachedEffectManager14StaticGetClassEv
// TODO     52 B  AttachedEffectManager::AttachedEffectManager         _ZN21AttachedEffectManagerC2Ev
// TODO     52 B  AttachedEffectManager::AttachedEffectManager         _ZN21AttachedEffectManagerC1Ev
// TODO     52 B  AttachedEffectManager::~AttachedEffectManager        _ZN21AttachedEffectManagerD2Ev
// TODO     52 B  AttachedEffectManager::~AttachedEffectManager        _ZN21AttachedEffectManagerD1Ev
// TODO     44 B  AttachedEffectManager::StaticNew                     _ZN21AttachedEffectManager9StaticNewEv
// TODO     36 B  AttachedEffectManager::~AttachedEffectManager        _ZN21AttachedEffectManagerD0Ev
// TODO     32 B  AttachedEffectManager::Count                         _ZN21AttachedEffectManager5CountEv
// TODO     28 B  AttachedEffectManager::at                            _ZN21AttachedEffectManager2atEi
