// PvZ2/plants/WireGelsemium/PlantAnimRig_WireGelsemium.cpp
//
// 12 function(s), 1292 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_WireGelsemium
//
// TODO    220 B  PlantAnimRig_WireGelsemium::PlayPlantFoodStart       _ZN26PlantAnimRig_WireGelsemium18PlayPlantFoodStartEi20RtReflectionDelegateIN4Sexy9Delegate0EES3_S3_
// TODO    208 B  PlantAnimRig_WireGelsemium::PlayAttack               _ZN26PlantAnimRig_WireGelsemium10PlayAttackE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    200 B  PlantAnimRig_WireGelsemium::PlaySelected             _ZN26PlantAnimRig_WireGelsemium12PlaySelectedEv
// TODO    180 B  PlantAnimRig_WireGelsemium::StaticClassInit          _ZN26PlantAnimRig_WireGelsemium15StaticClassInitEv
// TODO    124 B  PlantAnimRig_WireGelsemium::StaticGetClass           _ZN26PlantAnimRig_WireGelsemium14StaticGetClassEv
// TODO    104 B  PlantAnimRig_WireGelsemium::getIdleAnimationName     _ZN26PlantAnimRig_WireGelsemium20getIdleAnimationNameEv
// TODO     60 B  PlantAnimRig_WireGelsemium::PlantAnimRig_WireGelsemium _ZN26PlantAnimRig_WireGelsemiumC2Ev
// TODO     60 B  PlantAnimRig_WireGelsemium::PlantAnimRig_WireGelsemium _ZN26PlantAnimRig_WireGelsemiumC1Ev
// TODO     44 B  PlantAnimRig_WireGelsemium::StaticNew                _ZN26PlantAnimRig_WireGelsemium9StaticNewEv
// TODO     36 B  PlantAnimRig_WireGelsemium::~PlantAnimRig_WireGelsemium _ZN26PlantAnimRig_WireGelsemiumD0Ev
// TODO     28 B  PlantAnimRig_WireGelsemium::~PlantAnimRig_WireGelsemium _ZN26PlantAnimRig_WireGelsemiumD2Ev
// TODO     28 B  PlantAnimRig_WireGelsemium::~PlantAnimRig_WireGelsemium _ZN26PlantAnimRig_WireGelsemiumD1Ev
