// PvZ2/griditems/zombie/GridItemZombieMirrorQueenMirror.cpp
//
// 35 function(s), 6912 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: GridItemZombieMirrorQueenMirror, GridItemZombieMirrorQueenMirrorProps
//
// TODO    996 B  GridItemZombieMirrorQueenMirror::copyZombie          _ZN31GridItemZombieMirrorQueenMirror10copyZombieEP6Zombie
// TODO    732 B  GridItemZombieMirrorQueenMirror::walkOutZombie       _ZN31GridItemZombieMirrorQueenMirror13walkOutZombieERNS_16CopyZombieParamsE
// TODO    460 B  GridItemZombieMirrorQueenMirror::onUpdate            _ZN31GridItemZombieMirrorQueenMirror8onUpdateEv
// TODO    420 B  GridItemZombieMirrorQueenMirror::canCoypZombie       _ZN31GridItemZombieMirrorQueenMirror13canCoypZombieEP6Zombie
// TODO    372 B  GridItemZombieMirrorQueenMirror::onGridItemInitialize _ZN31GridItemZombieMirrorQueenMirror20onGridItemInitializeEv
// TODO    288 B  GridItemZombieMirrorQueenMirror::onDestroy           _ZN31GridItemZombieMirrorQueenMirror9onDestroyEv
// TODO    288 B  GridItemZombieMirrorQueenMirror::playSpawnAnim       _ZN31GridItemZombieMirrorQueenMirror13playSpawnAnimEv
// TODO    288 B  GridItemZombieMirrorQueenMirror::playCopyAnim        _ZN31GridItemZombieMirrorQueenMirror12playCopyAnimEv
// TODO    288 B  GridItemZombieMirrorQueenMirror::playZombieOutAnim   _ZN31GridItemZombieMirrorQueenMirror17playZombieOutAnimEv
// TODO    288 B  GridItemZombieMirrorQueenMirror::playBrokenAnim      _ZN31GridItemZombieMirrorQueenMirror14playBrokenAnimEv
// TODO    280 B  GridItemZombieMirrorQueenMirror::StaticClassInit     _ZN31GridItemZombieMirrorQueenMirror15StaticClassInitEv
// TODO    264 B  GridItemZombieMirrorQueenMirror::onAnimationDone     _ZN31GridItemZombieMirrorQueenMirror15onAnimationDoneERKSs
// TODO    244 B  GridItemZombieMirrorQueenMirror::calcDamageState     _ZN31GridItemZombieMirrorQueenMirror15calcDamageStateEv
// TODO    180 B  GridItemZombieMirrorQueenMirrorProps::StaticClassInit _ZN36GridItemZombieMirrorQueenMirrorProps15StaticClassInitEv
// TODO    152 B  GridItemZombieMirrorQueenMirror::onTakeDamage        _ZN31GridItemZombieMirrorQueenMirror12onTakeDamageERK10DamageInfo
// TODO    140 B  GridItemZombieMirrorQueenMirror::playIdleAnim        _ZN31GridItemZombieMirrorQueenMirror12playIdleAnimEv
// TODO    124 B  GridItemZombieMirrorQueenMirror::StaticGetClass      _ZN31GridItemZombieMirrorQueenMirror14StaticGetClassEv
// TODO    124 B  GridItemZombieMirrorQueenMirror::refreshStats        _ZN31GridItemZombieMirrorQueenMirror12refreshStatsEv
// TODO    124 B  GridItemZombieMirrorQueenMirrorProps::StaticGetClass _ZN36GridItemZombieMirrorQueenMirrorProps14StaticGetClassEv
// TODO    112 B  GridItemZombieMirrorQueenMirror::TakeDamage          _ZN31GridItemZombieMirrorQueenMirror10TakeDamageERK10DamageInfo
// TODO     80 B  GridItemZombieMirrorQueenMirror::GridItemZombieMirrorQueenMirror _ZN31GridItemZombieMirrorQueenMirrorC2Ev
// TODO     80 B  GridItemZombieMirrorQueenMirror::GridItemZombieMirrorQueenMirror _ZN31GridItemZombieMirrorQueenMirrorC1Ev
// TODO     72 B  GridItemZombieMirrorQueenMirror::~GridItemZombieMirrorQueenMirror _ZN31GridItemZombieMirrorQueenMirrorD2Ev
// TODO     72 B  GridItemZombieMirrorQueenMirror::~GridItemZombieMirrorQueenMirror _ZN31GridItemZombieMirrorQueenMirrorD1Ev
// TODO     68 B  GridItemZombieMirrorQueenMirrorProps::GridItemZombieMirrorQueenMirrorProps _ZN36GridItemZombieMirrorQueenMirrorPropsC2Ev
// TODO     68 B  GridItemZombieMirrorQueenMirrorProps::GridItemZombieMirrorQueenMirrorProps _ZN36GridItemZombieMirrorQueenMirrorPropsC1Ev
// TODO     52 B  GridItemZombieMirrorQueenMirrorProps::~GridItemZombieMirrorQueenMirrorProps _ZN36GridItemZombieMirrorQueenMirrorPropsD2Ev
// TODO     52 B  GridItemZombieMirrorQueenMirrorProps::~GridItemZombieMirrorQueenMirrorProps _ZN36GridItemZombieMirrorQueenMirrorPropsD1Ev
// TODO     44 B  GridItemZombieMirrorQueenMirror::StaticNew           _ZN31GridItemZombieMirrorQueenMirror9StaticNewEv
// TODO     44 B  GridItemZombieMirrorQueenMirrorProps::StaticNew      _ZN36GridItemZombieMirrorQueenMirrorProps9StaticNewEv
// TODO     36 B  GridItemZombieMirrorQueenMirror::calcCollisionRect   _ZN31GridItemZombieMirrorQueenMirror17calcCollisionRectEv
// TODO     36 B  GridItemZombieMirrorQueenMirror::~GridItemZombieMirrorQueenMirror _ZN31GridItemZombieMirrorQueenMirrorD0Ev
// TODO     36 B  GridItemZombieMirrorQueenMirrorProps::~GridItemZombieMirrorQueenMirrorProps _ZN36GridItemZombieMirrorQueenMirrorPropsD0Ev
// TODO      4 B  GridItemZombieMirrorQueenMirror::onDraw              _ZN31GridItemZombieMirrorQueenMirror6onDrawEPN4Sexy8GraphicsE
// TODO      4 B  GridItemZombieMirrorQueenMirror::registerForEvents   _ZN31GridItemZombieMirrorQueenMirror17registerForEventsEv
