// PvZ2/plants/Deodarcedar/Plant_Deodarcedar.cpp
//
// 55 function(s), 8548 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantDeodarcedar
//
// TODO    728 B  PlantDeodarcedar::gatherLightningEnergy              _ZN16PlantDeodarcedar21gatherLightningEnergyEi
// TODO    716 B  PlantDeodarcedar::fire                               _ZN16PlantDeodarcedar4fireEv
// TODO    592 B  PlantDeodarcedar::canFindTargets                     _ZN16PlantDeodarcedar14canFindTargetsEv
// TODO    492 B  PlantDeodarcedar::setState                           _ZN16PlantDeodarcedar8setStateE16DeodarcedarState
// TODO    456 B  PlantDeodarcedar::isElectricPlant                    _ZN16PlantDeodarcedar15isElectricPlantEP5Plantb
// TODO    432 B  PlantDeodarcedar::addPlantAttackUpEffect             _ZN16PlantDeodarcedar22addPlantAttackUpEffectEP5Plant
// TODO    408 B  PlantDeodarcedar::applyAttackUpFeatures              _ZN16PlantDeodarcedar21applyAttackUpFeaturesEv
// TODO    276 B  PlantDeodarcedar::onAnimStoppedCallback              _ZN16PlantDeodarcedar21onAnimStoppedCallbackERKSs
// TODO    232 B  PlantDeodarcedar::OnAnimCommand                      _ZN16PlantDeodarcedar13OnAnimCommandERKSsS1_
// TODO    200 B  PlantDeodarcedar::getCurrentRuneProjectileType       _ZN16PlantDeodarcedar28getCurrentRuneProjectileTypeEv
// TODO    184 B  PlantDeodarcedar::canAttackUpPlant                   _ZN16PlantDeodarcedar16canAttackUpPlantEP5Plant
// TODO    180 B  PlantDeodarcedar::StaticClassInit                    _ZN16PlantDeodarcedar15StaticClassInitEv
// TODO    168 B  PlantDeodarcedar::getCurrentRuneLightningArcAnimationToPlay _ZN16PlantDeodarcedar41getCurrentRuneLightningArcAnimationToPlayEv
// TODO    164 B  PlantDeodarcedar::getCurrentRuneIdleAnimationToPlay  _ZN16PlantDeodarcedar33getCurrentRuneIdleAnimationToPlayEv
// TODO    144 B  PlantDeodarcedar::getCurrentRuneLightningArcDamageAmount _ZN16PlantDeodarcedar38getCurrentRuneLightningArcDamageAmountEv
// TODO    132 B  PlantDeodarcedar::getCurrentRuneInitialVelocity      _ZN16PlantDeodarcedar29getCurrentRuneInitialVelocityEv
// TODO    128 B  PlantDeodarcedar::DoProjectileCombo                  _ZN16PlantDeodarcedar17DoProjectileComboEv
// TODO    128 B  PlantDeodarcedar::onEnergySaveSelfAnimationDone      _ZN16PlantDeodarcedar29onEnergySaveSelfAnimationDoneEv
// TODO    124 B  PlantDeodarcedar::StaticGetClass                     _ZN16PlantDeodarcedar14StaticGetClassEv
// TODO    124 B  PlantDeodarcedar::getCurrentRuneDiameterGridNum      _ZN16PlantDeodarcedar29getCurrentRuneDiameterGridNumEv
// TODO    124 B  PlantDeodarcedar::getCurrentRuneLightningNumPerSecond _ZN16PlantDeodarcedar35getCurrentRuneLightningNumPerSecondEv
// TODO    124 B  PlantDeodarcedar::getCurrentRuneLightningNumMax      _ZN16PlantDeodarcedar29getCurrentRuneLightningNumMaxEv
// TODO    124 B  PlantDeodarcedar::getCurrentRuneAliveDuration        _ZN16PlantDeodarcedar27getCurrentRuneAliveDurationEv
// TODO    116 B  PlantDeodarcedar::onAttackNormalAnimationDone        _ZN16PlantDeodarcedar27onAttackNormalAnimationDoneEv
// TODO    112 B  PlantDeodarcedar::getCurrentRuneNormalAttackDamageAmountOverride _ZN16PlantDeodarcedar46getCurrentRuneNormalAttackDamageAmountOverrideEv
// TODO    112 B  PlantDeodarcedar::updateShooter                      _ZN16PlantDeodarcedar13updateShooterEv
// TODO    108 B  PlantDeodarcedar::checkUpgradeStage                  _ZN16PlantDeodarcedar17checkUpgradeStageEv
// TODO    104 B  PlantDeodarcedar::ApplyPlantfood                     _ZN16PlantDeodarcedar14ApplyPlantfoodEv
// TODO    100 B  PlantDeodarcedar::getCurrentRuneCritRate             _ZN16PlantDeodarcedar22getCurrentRuneCritRateEv
// TODO    100 B  PlantDeodarcedar::getCurrentRuneLightningArcDiameterGridNum _ZN16PlantDeodarcedar41getCurrentRuneLightningArcDiameterGridNumEv
// TODO    100 B  PlantDeodarcedar::getCurrentRuneNormalAttackAnimationToPlay _ZN16PlantDeodarcedar41getCurrentRuneNormalAttackAnimationToPlayEv
// TODO    100 B  PlantDeodarcedar::getCurrentRuneCritAttackAnimationToPlay _ZN16PlantDeodarcedar39getCurrentRuneCritAttackAnimationToPlayEv
// TODO     96 B  PlantDeodarcedar::PlantDeodarcedar                   _ZN16PlantDeodarcedarC2Ev
// TODO     96 B  PlantDeodarcedar::PlantDeodarcedar                   _ZN16PlantDeodarcedarC1Ev
// TODO     96 B  PlantDeodarcedar::UpdateActions                      _ZN16PlantDeodarcedar13UpdateActionsEv
// TODO     88 B  PlantDeodarcedar::Initialize                         _ZN16PlantDeodarcedar10InitializeEv
// TODO     76 B  PlantDeodarcedar::getCurrentRuneLaunchInterval       _ZN16PlantDeodarcedar28getCurrentRuneLaunchIntervalEv
// TODO     72 B  PlantDeodarcedar::getCurrentRuneStuckRate            _ZN16PlantDeodarcedar23getCurrentRuneStuckRateEv
// TODO     72 B  PlantDeodarcedar::getCurrentRuneStuckDuration        _ZN16PlantDeodarcedar27getCurrentRuneStuckDurationEv
// TODO     72 B  PlantDeodarcedar::onUpgradeAnimationDone             _ZN16PlantDeodarcedar22onUpgradeAnimationDoneEv
// TODO     60 B  PlantDeodarcedar::getCurrentRuneLightningDamageFactor _ZN16PlantDeodarcedar35getCurrentRuneLightningDamageFactorEv
// TODO     52 B  PlantDeodarcedar::getCurrentPlantfoodRuneStageIndex  _ZN16PlantDeodarcedar33getCurrentPlantfoodRuneStageIndexEv
// TODO     52 B  PlantDeodarcedar::updateEnergySaveSelf               _ZN16PlantDeodarcedar20updateEnergySaveSelfEv
// TODO     48 B  PlantDeodarcedar::getEnergySavedByPlants             _ZN16PlantDeodarcedar22getEnergySavedByPlantsEv
// TODO     48 B  PlantDeodarcedar::CancelPlantfood                    _ZN16PlantDeodarcedar15CancelPlantfoodEv
// TODO     48 B  PlantDeodarcedar::Idle                               _ZN16PlantDeodarcedar4IdleEv
// TODO     44 B  PlantDeodarcedar::StaticNew                          _ZN16PlantDeodarcedar9StaticNewEv
// TODO     36 B  PlantDeodarcedar::~PlantDeodarcedar                  _ZN16PlantDeodarcedarD0Ev
// TODO     28 B  PlantDeodarcedar::getCurrentRuneLightningDamageFactorWithEnergy _ZN16PlantDeodarcedar45getCurrentRuneLightningDamageFactorWithEnergyEv
// TODO     28 B  PlantDeodarcedar::getCurrentRuneCritDamageAmountFactor _ZN16PlantDeodarcedar36getCurrentRuneCritDamageAmountFactorEv
// TODO     28 B  PlantDeodarcedar::getCurrentRuneBaseDamageAmount     _ZN16PlantDeodarcedar30getCurrentRuneBaseDamageAmountEv
// TODO     28 B  PlantDeodarcedar::getCurrentRuneVelocityXWithGridNum _ZN16PlantDeodarcedar34getCurrentRuneVelocityXWithGridNumEv
// TODO     20 B  PlantDeodarcedar::~PlantDeodarcedar                  _ZN16PlantDeodarcedarD2Ev
// TODO     20 B  PlantDeodarcedar::~PlantDeodarcedar                  _ZN16PlantDeodarcedarD1Ev
// TODO      8 B  PlantDeodarcedar::CanApplyPlantfood                  _ZN16PlantDeodarcedar17CanApplyPlantfoodEv
