// PvZ2/zombies/GeneralCaesar/ZombieGeneralCaesar.cpp
//
// 19 function(s), 1436 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieGeneralCaesar, ZombieGeneralCaesarProps
//
// TODO    276 B  ZombieGeneralCaesar::onApplyCondition                _ZN19ZombieGeneralCaesar16onApplyConditionE16ZombieConditions
// TODO    180 B  ZombieGeneralCaesar::StaticClassInit                 _ZN19ZombieGeneralCaesar15StaticClassInitEv
// TODO    180 B  ZombieGeneralCaesarProps::StaticClassInit            _ZN24ZombieGeneralCaesarProps15StaticClassInitEv
// TODO    124 B  ZombieGeneralCaesar::StaticGetClass                  _ZN19ZombieGeneralCaesar14StaticGetClassEv
// TODO    124 B  ZombieGeneralCaesarProps::StaticGetClass             _ZN24ZombieGeneralCaesarProps14StaticGetClassEv
// TODO     56 B  ZombieGeneralCaesar::ZombieGeneralCaesar             _ZN19ZombieGeneralCaesarC2Ev
// TODO     56 B  ZombieGeneralCaesar::ZombieGeneralCaesar             _ZN19ZombieGeneralCaesarC1Ev
// TODO     52 B  ZombieGeneralCaesarProps::ZombieGeneralCaesarProps   _ZN24ZombieGeneralCaesarPropsC2Ev
// TODO     52 B  ZombieGeneralCaesarProps::ZombieGeneralCaesarProps   _ZN24ZombieGeneralCaesarPropsC1Ev
// TODO     44 B  ZombieGeneralCaesar::StaticNew                       _ZN19ZombieGeneralCaesar9StaticNewEv
// TODO     44 B  ZombieGeneralCaesarProps::StaticNew                  _ZN24ZombieGeneralCaesarProps9StaticNewEv
// TODO     40 B  ZombieGeneralCaesar::onZombieInitialize              _ZN19ZombieGeneralCaesar18onZombieInitializeEv
// TODO     40 B  ZombieGeneralCaesar::onUpdate                        _ZN19ZombieGeneralCaesar8onUpdateEv
// TODO     36 B  ZombieGeneralCaesar::~ZombieGeneralCaesar            _ZN19ZombieGeneralCaesarD0Ev
// TODO     36 B  ZombieGeneralCaesarProps::~ZombieGeneralCaesarProps  _ZN24ZombieGeneralCaesarPropsD0Ev
// TODO     28 B  ZombieGeneralCaesar::~ZombieGeneralCaesar            _ZN19ZombieGeneralCaesarD2Ev
// TODO     28 B  ZombieGeneralCaesar::~ZombieGeneralCaesar            _ZN19ZombieGeneralCaesarD1Ev
// TODO     20 B  ZombieGeneralCaesarProps::~ZombieGeneralCaesarProps  _ZN24ZombieGeneralCaesarPropsD2Ev
// TODO     20 B  ZombieGeneralCaesarProps::~ZombieGeneralCaesarProps  _ZN24ZombieGeneralCaesarPropsD1Ev
