// PvZ2/zombies/PVPSkill/ZombiePVPSkill.cpp
//
// 28 function(s), 1836 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombiePVPSkill, ZombiePVPSkillProps
//
// TODO    468 B  ZombiePVPSkill::StaticClassInit                      _ZN14ZombiePVPSkill15StaticClassInitEv
// TODO    180 B  ZombiePVPSkillProps::StaticClassInit                 _ZN19ZombiePVPSkillProps15StaticClassInitEv
// TODO    124 B  ZombiePVPSkill::StaticGetClass                       _ZN14ZombiePVPSkill14StaticGetClassEv
// TODO    124 B  ZombiePVPSkillProps::StaticGetClass                  _ZN19ZombiePVPSkillProps14StaticGetClassEv
// TODO    100 B  ZombiePVPSkillProps::ZombiePVPSkillProps             _ZN19ZombiePVPSkillPropsC2Ev
// TODO    100 B  ZombiePVPSkillProps::ZombiePVPSkillProps             _ZN19ZombiePVPSkillPropsC1Ev
// TODO     92 B  ZombiePVPSkill::onPlaceOnBoard                       _ZN14ZombiePVPSkill14onPlaceOnBoardEv
// TODO     88 B  ZombiePVPSkillProps::GetReduceCost                   _ZN19ZombiePVPSkillProps13GetReduceCostEi
// TODO     80 B  ZombiePVPSkillProps::~ZombiePVPSkillProps            _ZN19ZombiePVPSkillPropsD2Ev
// TODO     80 B  ZombiePVPSkillProps::~ZombiePVPSkillProps            _ZN19ZombiePVPSkillPropsD1Ev
// TODO     56 B  ZombiePVPSkill::ZombiePVPSkill                       _ZN14ZombiePVPSkillC2Ev
// TODO     56 B  ZombiePVPSkill::ZombiePVPSkill                       _ZN14ZombiePVPSkillC1Ev
// TODO     44 B  ZombiePVPSkill::StaticNew                            _ZN14ZombiePVPSkill9StaticNewEv
// TODO     44 B  ZombiePVPSkillProps::StaticNew                       _ZN19ZombiePVPSkillProps9StaticNewEv
// TODO     36 B  ZombiePVPSkill::~ZombiePVPSkill                      _ZN14ZombiePVPSkillD0Ev
// TODO     36 B  ZombiePVPSkillProps::~ZombiePVPSkillProps            _ZN19ZombiePVPSkillPropsD0Ev
// TODO     32 B  ZombiePVPSkillProps::GetMaxLevel                     _ZN19ZombiePVPSkillProps11GetMaxLevelEv
// TODO     28 B  ZombiePVPSkill::~ZombiePVPSkill                      _ZN14ZombiePVPSkillD2Ev
// TODO     28 B  ZombiePVPSkill::~ZombiePVPSkill                      _ZN14ZombiePVPSkillD1Ev
// TODO      8 B  ZombiePVPSkill::findTarget                           _ZN14ZombiePVPSkill10findTargetEv
// TODO      4 B  ZombiePVPSkill::CreateArenaSpawnEffect               _ZN14ZombiePVPSkill22CreateArenaSpawnEffectEv
// TODO      4 B  ZombiePVPSkill::CreateZombieLevelEffect              _ZN14ZombiePVPSkill23CreateZombieLevelEffectEb
// TODO      4 B  ZombiePVPSkill::onEnterState_Playing                 _ZN14ZombiePVPSkill20onEnterState_PlayingE11ZombieState
// TODO      4 B  ZombiePVPSkill::updateState_Playing                  _ZN14ZombiePVPSkill19updateState_PlayingEv
// TODO      4 B  ZombiePVPSkill::onExitState_Playing                  _ZN14ZombiePVPSkill19onExitState_PlayingE11ZombieState
// TODO      4 B  ZombiePVPSkill::onZombieInitialize                   _ZN14ZombiePVPSkill18onZombieInitializeEv
// TODO      4 B  ZombiePVPSkill::onUpdate                             _ZN14ZombiePVPSkill8onUpdateEv
// TODO      4 B  ZombiePVPSkill::onPopAnimCommand                     _ZN14ZombiePVPSkill16onPopAnimCommandERKSsfS1_S1_
