// PvZ2/challenges/star/StarChallengeBeatTheLevel.cpp
//
// 18 function(s), 1360 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: StarChallengeBeatTheLevel, StarChallengeBeatTheLevelProps
//
// TODO    180 B  StarChallengeBeatTheLevelProps::StaticClassInit      _ZN30StarChallengeBeatTheLevelProps15StaticClassInitEv
// TODO    180 B  StarChallengeBeatTheLevel::StaticClassInit           _ZN25StarChallengeBeatTheLevel15StaticClassInitEv
// TODO    144 B  StarChallengeBeatTheLevel::registerForEvents         _ZN25StarChallengeBeatTheLevel17registerForEventsEv
// TODO    124 B  StarChallengeBeatTheLevelProps::StaticGetClass       _ZN30StarChallengeBeatTheLevelProps14StaticGetClassEv
// TODO    124 B  StarChallengeBeatTheLevel::StaticGetClass            _ZN25StarChallengeBeatTheLevel14StaticGetClassEv
// TODO     72 B  StarChallengeBeatTheLevel::gameplayEnded             _ZN25StarChallengeBeatTheLevel13gameplayEndedEv
// TODO     60 B  StarChallengeBeatTheLevelProps::StarChallengeBeatTheLevelProps _ZN30StarChallengeBeatTheLevelPropsC2Ev
// TODO     60 B  StarChallengeBeatTheLevelProps::StarChallengeBeatTheLevelProps _ZN30StarChallengeBeatTheLevelPropsC1Ev
// TODO     60 B  StarChallengeBeatTheLevelProps::~StarChallengeBeatTheLevelProps _ZN30StarChallengeBeatTheLevelPropsD2Ev
// TODO     60 B  StarChallengeBeatTheLevelProps::~StarChallengeBeatTheLevelProps _ZN30StarChallengeBeatTheLevelPropsD1Ev
// TODO     48 B  StarChallengeBeatTheLevel::StarChallengeBeatTheLevel _ZN25StarChallengeBeatTheLevelC2Ev
// TODO     48 B  StarChallengeBeatTheLevel::StarChallengeBeatTheLevel _ZN25StarChallengeBeatTheLevelC1Ev
// TODO     44 B  StarChallengeBeatTheLevelProps::StaticNew            _ZN30StarChallengeBeatTheLevelProps9StaticNewEv
// TODO     44 B  StarChallengeBeatTheLevel::StaticNew                 _ZN25StarChallengeBeatTheLevel9StaticNewEv
// TODO     36 B  StarChallengeBeatTheLevelProps::~StarChallengeBeatTheLevelProps _ZN30StarChallengeBeatTheLevelPropsD0Ev
// TODO     36 B  StarChallengeBeatTheLevel::~StarChallengeBeatTheLevel _ZN25StarChallengeBeatTheLevelD0Ev
// TODO     20 B  StarChallengeBeatTheLevel::~StarChallengeBeatTheLevel _ZN25StarChallengeBeatTheLevelD2Ev
// TODO     20 B  StarChallengeBeatTheLevel::~StarChallengeBeatTheLevel _ZN25StarChallengeBeatTheLevelD1Ev
