// PvZ2/challenges/star/StarChallengeModule.cpp
//
// 16 function(s), 1040 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: StarChallengeModule, StarChallengeModuleProperties
//
// TODO    180 B  StarChallengeModuleProperties::StaticClassInit       _ZN29StarChallengeModuleProperties15StaticClassInitEv
// TODO    180 B  StarChallengeModule::StaticClassInit                 _ZN19StarChallengeModule15StaticClassInitEv
// TODO    124 B  StarChallengeModuleProperties::StaticGetClass        _ZN29StarChallengeModuleProperties14StaticGetClassEv
// TODO    124 B  StarChallengeModule::StaticGetClass                  _ZN19StarChallengeModule14StaticGetClassEv
// TODO     48 B  StarChallengeModuleProperties::StarChallengeModuleProperties _ZN29StarChallengeModulePropertiesC2Ev
// TODO     48 B  StarChallengeModuleProperties::StarChallengeModuleProperties _ZN29StarChallengeModulePropertiesC1Ev
// TODO     48 B  StarChallengeModule::StarChallengeModule             _ZN19StarChallengeModuleC2Ev
// TODO     48 B  StarChallengeModule::StarChallengeModule             _ZN19StarChallengeModuleC1Ev
// TODO     44 B  StarChallengeModuleProperties::StaticNew             _ZN29StarChallengeModuleProperties9StaticNewEv
// TODO     44 B  StarChallengeModule::StaticNew                       _ZN19StarChallengeModule9StaticNewEv
// TODO     36 B  StarChallengeModuleProperties::~StarChallengeModuleProperties _ZN29StarChallengeModulePropertiesD0Ev
// TODO     36 B  StarChallengeModule::~StarChallengeModule            _ZN19StarChallengeModuleD0Ev
// TODO     20 B  StarChallengeModuleProperties::~StarChallengeModuleProperties _ZN29StarChallengeModulePropertiesD2Ev
// TODO     20 B  StarChallengeModuleProperties::~StarChallengeModuleProperties _ZN29StarChallengeModulePropertiesD1Ev
// TODO     20 B  StarChallengeModule::~StarChallengeModule            _ZN19StarChallengeModuleD2Ev
// TODO     20 B  StarChallengeModule::~StarChallengeModule            _ZN19StarChallengeModuleD1Ev
