// PvZ2/challenges/star/StarChallengeUnfreezePlants.cpp
//
// 23 function(s), 2984 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: StarChallengeUnfreezePlants, StarChallengeUnfreezePlantsProps
//
// TODO    400 B  StarChallengeUnfreezePlants::PlantConditionEnded     _ZN27StarChallengeUnfreezePlants19PlantConditionEndedEP5Planti
// TODO    368 B  StarChallengeUnfreezePlants::registerForEvents       _ZN27StarChallengeUnfreezePlants17registerForEventsEv
// TODO    296 B  StarChallengeUnfreezePlants::onGameplayStarted       _ZN27StarChallengeUnfreezePlants17onGameplayStartedEv
// TODO    180 B  StarChallengeUnfreezePlantsProps::StaticClassInit    _ZN32StarChallengeUnfreezePlantsProps15StaticClassInitEv
// TODO    180 B  StarChallengeUnfreezePlants::StaticClassInit         _ZN27StarChallengeUnfreezePlants15StaticClassInitEv
// TODO    180 B  StarChallengeUnfreezePlants::CheckPlantsInCondition  _ZN27StarChallengeUnfreezePlants22CheckPlantsInConditionEP5Plant
// TODO    176 B  StarChallengeUnfreezePlants::StarChallengeUnfreezePlants _ZN27StarChallengeUnfreezePlantsC2Ev
// TODO    176 B  StarChallengeUnfreezePlants::StarChallengeUnfreezePlants _ZN27StarChallengeUnfreezePlantsC1Ev
// TODO    172 B  StarChallengeUnfreezePlants::PlantConditionApplied   _ZN27StarChallengeUnfreezePlants21PlantConditionAppliedEP5Planti
// TODO    124 B  StarChallengeUnfreezePlantsProps::StaticGetClass     _ZN32StarChallengeUnfreezePlantsProps14StaticGetClassEv
// TODO    124 B  StarChallengeUnfreezePlants::StaticGetClass          _ZN27StarChallengeUnfreezePlants14StaticGetClassEv
// TODO    116 B  StarChallengeUnfreezePlants::gameplayEnded           _ZN27StarChallengeUnfreezePlants13gameplayEndedEv
// TODO     68 B  StarChallengeUnfreezePlants::getChallengeUI          _ZN27StarChallengeUnfreezePlants14getChallengeUIEv
// TODO     60 B  StarChallengeUnfreezePlants::~StarChallengeUnfreezePlants _ZN27StarChallengeUnfreezePlantsD2Ev
// TODO     60 B  StarChallengeUnfreezePlants::~StarChallengeUnfreezePlants _ZN27StarChallengeUnfreezePlantsD1Ev
// TODO     52 B  StarChallengeUnfreezePlantsProps::StarChallengeUnfreezePlantsProps _ZN32StarChallengeUnfreezePlantsPropsC2Ev
// TODO     52 B  StarChallengeUnfreezePlantsProps::StarChallengeUnfreezePlantsProps _ZN32StarChallengeUnfreezePlantsPropsC1Ev
// TODO     44 B  StarChallengeUnfreezePlantsProps::StaticNew          _ZN32StarChallengeUnfreezePlantsProps9StaticNewEv
// TODO     44 B  StarChallengeUnfreezePlants::StaticNew               _ZN27StarChallengeUnfreezePlants9StaticNewEv
// TODO     36 B  StarChallengeUnfreezePlantsProps::~StarChallengeUnfreezePlantsProps _ZN32StarChallengeUnfreezePlantsPropsD0Ev
// TODO     36 B  StarChallengeUnfreezePlants::~StarChallengeUnfreezePlants _ZN27StarChallengeUnfreezePlantsD0Ev
// TODO     20 B  StarChallengeUnfreezePlantsProps::~StarChallengeUnfreezePlantsProps _ZN32StarChallengeUnfreezePlantsPropsD2Ev
// TODO     20 B  StarChallengeUnfreezePlantsProps::~StarChallengeUnfreezePlantsProps _ZN32StarChallengeUnfreezePlantsPropsD1Ev
