// PvZ2/waveaction/WaveActionZombieTent.cpp
//
// 20 function(s), 1856 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: WaveActionZombieTent, WaveActionZombieTentProps
//
// TODO    460 B  WaveActionZombieTent::WaveStart                      _ZN20WaveActionZombieTent9WaveStartEiN8WaveType8WaveTypeEbRN4Sexy6MTRandE
// TODO    280 B  WaveActionZombieTentProps::StaticClassInit           _ZN25WaveActionZombieTentProps15StaticClassInitEv
// TODO    180 B  WaveActionZombieTent::StaticClassInit                _ZN20WaveActionZombieTent15StaticClassInitEv
// TODO    176 B  WaveActionZombieTent::AddResourceRequirements        _ZN20WaveActionZombieTent23AddResourceRequirementsERSt3setISsSt4lessISsESaISsEE
// TODO    124 B  WaveActionZombieTent::StaticGetClass                 _ZN20WaveActionZombieTent14StaticGetClassEv
// TODO    124 B  WaveActionZombieTentProps::StaticGetClass            _ZN25WaveActionZombieTentProps14StaticGetClassEv
// TODO     52 B  WaveActionZombieTentProps::WaveActionZombieTentProps _ZN25WaveActionZombieTentPropsC2Ev
// TODO     52 B  WaveActionZombieTentProps::WaveActionZombieTentProps _ZN25WaveActionZombieTentPropsC1Ev
// TODO     52 B  WaveActionZombieTentProps::~WaveActionZombieTentProps _ZN25WaveActionZombieTentPropsD2Ev
// TODO     52 B  WaveActionZombieTentProps::~WaveActionZombieTentProps _ZN25WaveActionZombieTentPropsD1Ev
// TODO     48 B  WaveActionZombieTent::WaveActionZombieTent           _ZN20WaveActionZombieTentC2Ev
// TODO     48 B  WaveActionZombieTent::WaveActionZombieTent           _ZN20WaveActionZombieTentC1Ev
// TODO     44 B  WaveActionZombieTent::StaticNew                      _ZN20WaveActionZombieTent9StaticNewEv
// TODO     44 B  WaveActionZombieTentProps::StaticNew                 _ZN25WaveActionZombieTentProps9StaticNewEv
// TODO     36 B  WaveActionZombieTent::~WaveActionZombieTent          _ZN20WaveActionZombieTentD0Ev
// TODO     36 B  WaveActionZombieTentProps::~WaveActionZombieTentProps _ZN25WaveActionZombieTentPropsD0Ev
// TODO     20 B  WaveActionZombieTent::~WaveActionZombieTent          _ZN20WaveActionZombieTentD2Ev
// TODO     20 B  WaveActionZombieTent::~WaveActionZombieTent          _ZN20WaveActionZombieTentD1Ev
// TODO      4 B  WaveActionZombieTent::WaveUpdate                     _ZN20WaveActionZombieTent10WaveUpdateEiRN4Sexy6MTRandE
// TODO      4 B  WaveActionZombieTent::WaveEnd                        _ZN20WaveActionZombieTent7WaveEndEiRN4Sexy6MTRandE
