// PvZ2/dangerroom/DangerRoomSpecialOfferConfig.cpp
//
// 16 function(s), 1692 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: DangerRoomSpecialOfferConfig
//
// TODO    404 B  DangerRoomSpecialOfferConfig::GetPlant               _ZN28DangerRoomSpecialOfferConfig8GetPlantEv
// TODO    180 B  DangerRoomSpecialOfferConfig::StaticClassInit        _ZN28DangerRoomSpecialOfferConfig15StaticClassInitEv
// TODO    136 B  DangerRoomSpecialOfferConfig::IsInLevelLimit         _ZN28DangerRoomSpecialOfferConfig14IsInLevelLimitEi
// TODO    124 B  DangerRoomSpecialOfferConfig::StaticGetClass         _ZN28DangerRoomSpecialOfferConfig14StaticGetClassEv
// TODO    112 B  DangerRoomSpecialOfferConfig::GetBonus               _ZN28DangerRoomSpecialOfferConfig8GetBonusEv
// TODO     92 B  DangerRoomSpecialOfferConfig::DangerRoomSpecialOfferConfig _ZN28DangerRoomSpecialOfferConfigC2EOS_
// TODO     92 B  DangerRoomSpecialOfferConfig::DangerRoomSpecialOfferConfig _ZN28DangerRoomSpecialOfferConfigC1EOS_
// TODO     92 B  DangerRoomSpecialOfferConfig::DangerRoomSpecialOfferConfig _ZN28DangerRoomSpecialOfferConfigC2ERKS_
// TODO     92 B  DangerRoomSpecialOfferConfig::DangerRoomSpecialOfferConfig _ZN28DangerRoomSpecialOfferConfigC1ERKS_
// TODO     80 B  DangerRoomSpecialOfferConfig::DangerRoomSpecialOfferConfig _ZN28DangerRoomSpecialOfferConfigC1Ev
// TODO     80 B  DangerRoomSpecialOfferConfig::DangerRoomSpecialOfferConfig _ZN28DangerRoomSpecialOfferConfigC2Ev
// TODO     60 B  DangerRoomSpecialOfferConfig::~DangerRoomSpecialOfferConfig _ZN28DangerRoomSpecialOfferConfigD2Ev
// TODO     60 B  DangerRoomSpecialOfferConfig::~DangerRoomSpecialOfferConfig _ZN28DangerRoomSpecialOfferConfigD1Ev
// TODO     44 B  DangerRoomSpecialOfferConfig::StaticNew              _ZN28DangerRoomSpecialOfferConfig9StaticNewEv
// TODO     36 B  DangerRoomSpecialOfferConfig::~DangerRoomSpecialOfferConfig _ZN28DangerRoomSpecialOfferConfigD0Ev
// TODO      8 B  DangerRoomSpecialOfferConfig::GetPlantList           _ZN28DangerRoomSpecialOfferConfig12GetPlantListEv
