// PvZ2/dangerroom/WorldMap_DangerRoomSpecialOfferButton.cpp
//
// 6 function(s), 928 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: WorldMap_DangerRoomSpecialOfferButton
//
// TODO    420 B  WorldMap_DangerRoomSpecialOfferButton::Draw          _ZN37WorldMap_DangerRoomSpecialOfferButton4DrawEPN4Sexy8GraphicsE
// TODO    208 B  WorldMap_DangerRoomSpecialOfferButton::WorldMap_DangerRoomSpecialOfferButton _ZN37WorldMap_DangerRoomSpecialOfferButtonC2EiPN4Sexy14ButtonListenerE
// TODO    208 B  WorldMap_DangerRoomSpecialOfferButton::WorldMap_DangerRoomSpecialOfferButton _ZN37WorldMap_DangerRoomSpecialOfferButtonC1EiPN4Sexy14ButtonListenerE
// TODO     36 B  WorldMap_DangerRoomSpecialOfferButton::~WorldMap_DangerRoomSpecialOfferButton _ZN37WorldMap_DangerRoomSpecialOfferButtonD0Ev
// TODO     28 B  WorldMap_DangerRoomSpecialOfferButton::~WorldMap_DangerRoomSpecialOfferButton _ZN37WorldMap_DangerRoomSpecialOfferButtonD2Ev
// TODO     28 B  WorldMap_DangerRoomSpecialOfferButton::~WorldMap_DangerRoomSpecialOfferButton _ZN37WorldMap_DangerRoomSpecialOfferButtonD1Ev
