// PvZ2/PVP/ArenaEditPlantCursor.cpp
//
// 20 function(s), 5100 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ArenaEditPlantCursor
//
// TODO    548 B  ArenaEditPlantCursor::ArenaEditPlantCursor           _ZN20ArenaEditPlantCursorC2ERKN4Sexy5TouchENS0_9RtWeakPtrI10SeedPacketEEP5Plant
// TODO    548 B  ArenaEditPlantCursor::ArenaEditPlantCursor           _ZN20ArenaEditPlantCursorC1ERKN4Sexy5TouchENS0_9RtWeakPtrI10SeedPacketEEP5Plant
// TODO    540 B  ArenaEditPlantCursor::ArenaEditPlantCursor           _ZN20ArenaEditPlantCursorC1ERKN4Sexy5TouchENS0_9RtWeakPtrIK9PlantTypeEENS0_5TRectIiEEbP5Plant
// TODO    540 B  ArenaEditPlantCursor::ArenaEditPlantCursor           _ZN20ArenaEditPlantCursorC2ERKN4Sexy5TouchENS0_9RtWeakPtrIK9PlantTypeEENS0_5TRectIiEEbP5Plant
// TODO    536 B  ArenaEditPlantCursor::tryToPlantAt                   _ZN20ArenaEditPlantCursor12tryToPlantAtEii
// TODO    532 B  ArenaEditPlantCursor::tryToUse                       _ZN20ArenaEditPlantCursor8tryToUseEv
// TODO    380 B  ArenaEditPlantCursor::tryReplaceExistingPlantAt      _ZN20ArenaEditPlantCursor25tryReplaceExistingPlantAtEii
// TODO    360 B  ArenaEditPlantCursor::tryMakeNewPlantAt              _ZN20ArenaEditPlantCursor17tryMakeNewPlantAtEiii
// TODO    248 B  ArenaEditPlantCursor::CanUseAtCurrentPosition        _ZN20ArenaEditPlantCursor23CanUseAtCurrentPositionEv
// TODO    228 B  ArenaEditPlantCursor::GetCurrentGridPosition         _ZN20ArenaEditPlantCursor22GetCurrentGridPositionEv
// TODO    120 B  ArenaEditPlantCursor::StaticGetClass                 _ZN20ArenaEditPlantCursor14StaticGetClassEv
// TODO     84 B  ArenaEditPlantCursor::payForPlant                    _ZN20ArenaEditPlantCursor11payForPlantEN4Sexy9RtWeakPtrIK9PlantTypeEE
// TODO     80 B  ArenaEditPlantCursor::ArenaEditPlantCursor           _ZN20ArenaEditPlantCursorC2Ev
// TODO     80 B  ArenaEditPlantCursor::ArenaEditPlantCursor           _ZN20ArenaEditPlantCursorC1Ev
// TODO     68 B  ArenaEditPlantCursor::onDestroy                      _ZN20ArenaEditPlantCursor9onDestroyEv
// TODO     60 B  ArenaEditPlantCursor::~ArenaEditPlantCursor          _ZN20ArenaEditPlantCursorD2Ev
// TODO     60 B  ArenaEditPlantCursor::~ArenaEditPlantCursor          _ZN20ArenaEditPlantCursorD1Ev
// TODO     44 B  ArenaEditPlantCursor::StaticNew                      _ZN20ArenaEditPlantCursor9StaticNewEv
// TODO     36 B  ArenaEditPlantCursor::~ArenaEditPlantCursor          _ZN20ArenaEditPlantCursorD0Ev
// TODO      8 B  ArenaEditPlantCursor::SetPlantingFreeForCursor       _ZN20ArenaEditPlantCursor24SetPlantingFreeForCursorEb
