// PvZ2/PVP/ArenaEndingButton.cpp
//
// 14 function(s), 2492 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ArenaEndingButton
//
// TODO    604 B  ArenaEndingButton::ArenaEndingButton                 _ZN17ArenaEndingButtonC2Ev
// TODO    604 B  ArenaEndingButton::ArenaEndingButton                 _ZN17ArenaEndingButtonC1Ev
// TODO    392 B  ArenaEndingButton::handleTouch                       _ZN17ArenaEndingButton11handleTouchERKN4Sexy5TouchE
// TODO    280 B  ArenaEndingButton::Draw                              _ZN17ArenaEndingButton4DrawEPN4Sexy8GraphicsE
// TODO    120 B  ArenaEndingButton::StaticGetClass                    _ZN17ArenaEndingButton14StaticGetClassEv
// TODO    104 B  ArenaEndingButton::~ArenaEndingButton                _ZN17ArenaEndingButtonD2Ev
// TODO    104 B  ArenaEndingButton::~ArenaEndingButton                _ZN17ArenaEndingButtonD1Ev
// TODO     68 B  ArenaEndingButton::onEnterState_Initializing         _ZN17ArenaEndingButton25onEnterState_InitializingE11WidgetState
// TODO     64 B  ArenaEndingButton::startTouch                        _ZN17ArenaEndingButton10startTouchEm
// TODO     60 B  ArenaEndingButton::cancelTouch                       _ZN17ArenaEndingButton11cancelTouchEv
// TODO     44 B  ArenaEndingButton::StaticNew                         _ZN17ArenaEndingButton9StaticNewEv
// TODO     36 B  ArenaEndingButton::~ArenaEndingButton                _ZN17ArenaEndingButtonD0Ev
// TODO      8 B  ArenaEndingButton::SetLabel                          _ZN17ArenaEndingButton8SetLabelERKSbIwSt11char_traitsIwESaIwEE
// TODO      4 B  ArenaEndingButton::initLoadingResourcesGroupList     _ZN17ArenaEndingButton29initLoadingResourcesGroupListEv
