// PvZ2/PVP/TrainingConfirmDlg.cpp
//
// 13 function(s), 1052 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: TrainingConfirmDlg
//
// TODO    244 B  TrainingConfirmDlg::SetMessage                       _ZN18TrainingConfirmDlg10SetMessageERKSbIwSt11char_traitsIwESaIwEES5_
// TODO    176 B  TrainingConfirmDlg::OnCreate                         _ZN18TrainingConfirmDlg8OnCreateEv
// TODO    164 B  TrainingConfirmDlg::SetBackground                    _ZN18TrainingConfirmDlg13SetBackgroundEPN4Sexy5ImageE
// TODO    104 B  TrainingConfirmDlg::GetLayoutName                    _ZN18TrainingConfirmDlg13GetLayoutNameEv
// TODO     72 B  TrainingConfirmDlg::DrawAll                          _ZN18TrainingConfirmDlg7DrawAllEPN4Sexy10ModalFlagsEPNS0_8GraphicsE
// TODO     64 B  TrainingConfirmDlg::TrainingConfirmDlg               _ZN18TrainingConfirmDlgC1Ev
// TODO     64 B  TrainingConfirmDlg::TrainingConfirmDlg               _ZN18TrainingConfirmDlgC2Ev
// TODO     60 B  TrainingConfirmDlg::ButtonDepress                    _ZN18TrainingConfirmDlg13ButtonDepressEi
// TODO     36 B  TrainingConfirmDlg::~TrainingConfirmDlg              _ZN18TrainingConfirmDlgD0Ev
// TODO     28 B  TrainingConfirmDlg::~TrainingConfirmDlg              _ZN18TrainingConfirmDlgD2Ev
// TODO     28 B  TrainingConfirmDlg::~TrainingConfirmDlg              _ZN18TrainingConfirmDlgD1Ev
// TODO      8 B  TrainingConfirmDlg::SetCallback                      _ZN18TrainingConfirmDlg11SetCallbackEN4Sexy9Delegate1IiEE
// TODO      4 B  TrainingConfirmDlg::Draw                             _ZN18TrainingConfirmDlg4DrawEPN4Sexy8GraphicsE
