// PvZ2/PVP/TrainingCamp.cpp
//
// 17 function(s), 3064 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: TrainingCamp
//
// TODO    616 B  TrainingCamp::Update                                 _ZN12TrainingCamp6UpdateEv
// TODO    252 B  TrainingCamp::AddTrainingData                        _ZN12TrainingCamp15AddTrainingDataERK12TrainingData
// TODO    248 B  TrainingCamp::GetSpaceUsed                           _ZN12TrainingCamp12GetSpaceUsedEv
// TODO    248 B  TrainingCamp::GetTrainingSpace                       _ZN12TrainingCamp16GetTrainingSpaceEv
// TODO    244 B  TrainingCamp::GetHaveDatas                           _ZN12TrainingCamp12GetHaveDatasERSt6vectorI12TrainingDataSaIS1_EE
// TODO    240 B  TrainingCamp::SetTrainingData                        _ZN12TrainingCamp15SetTrainingDataERKSsRK12TrainingData
// TODO    200 B  TrainingCamp::GetCurrentTrainingData                 _ZN12TrainingCamp22GetCurrentTrainingDataEv
// TODO    192 B  TrainingCamp::findTrainingData                       _ZN12TrainingCamp16findTrainingDataERKSs
// TODO    176 B  TrainingCamp::GetTypeNum                             _ZN12TrainingCamp10GetTypeNumEv
// TODO    160 B  TrainingCamp::GetTrainingData                        _ZN12TrainingCamp15GetTrainingDataERKSs
// TODO    152 B  TrainingCamp::SetTraining                            _ZN12TrainingCamp11SetTrainingERKSs20enumTrainingOperator
// TODO     76 B  TrainingCamp::TrainingCamp                           _ZN12TrainingCampC1Ev
// TODO     76 B  TrainingCamp::TrainingCamp                           _ZN12TrainingCampC2Ev
// TODO     52 B  TrainingCamp::~TrainingCamp                          _ZN12TrainingCampD2Ev
// TODO     52 B  TrainingCamp::~TrainingCamp                          _ZN12TrainingCampD1Ev
// TODO     44 B  TrainingCamp::ClearTrainingDatas                     _ZN12TrainingCamp18ClearTrainingDatasEv
// TODO     36 B  TrainingCamp::~TrainingCamp                          _ZN12TrainingCampD0Ev
