// PvZ2/plants/HatMushroom/PlantAnimRig_HatMushroom.cpp
//
// 11 function(s), 864 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_HatMushroom
//
// TODO    180 B  PlantAnimRig_HatMushroom::StaticClassInit            _ZN24PlantAnimRig_HatMushroom15StaticClassInitEv
// TODO    124 B  PlantAnimRig_HatMushroom::StaticGetClass             _ZN24PlantAnimRig_HatMushroom14StaticGetClassEv
// TODO    104 B  PlantAnimRig_HatMushroom::getPlantFoodOffAnimName    _ZN24PlantAnimRig_HatMushroom23getPlantFoodOffAnimNameEv
// TODO    104 B  PlantAnimRig_HatMushroom::getPlantFoodMainAnimName   _ZN24PlantAnimRig_HatMushroom24getPlantFoodMainAnimNameEv
// TODO    104 B  PlantAnimRig_HatMushroom::getPlantFoodOnAnimName     _ZN24PlantAnimRig_HatMushroom22getPlantFoodOnAnimNameEv
// TODO     56 B  PlantAnimRig_HatMushroom::PlantAnimRig_HatMushroom   _ZN24PlantAnimRig_HatMushroomC2Ev
// TODO     56 B  PlantAnimRig_HatMushroom::PlantAnimRig_HatMushroom   _ZN24PlantAnimRig_HatMushroomC1Ev
// TODO     44 B  PlantAnimRig_HatMushroom::StaticNew                  _ZN24PlantAnimRig_HatMushroom9StaticNewEv
// TODO     36 B  PlantAnimRig_HatMushroom::~PlantAnimRig_HatMushroom  _ZN24PlantAnimRig_HatMushroomD0Ev
// TODO     28 B  PlantAnimRig_HatMushroom::~PlantAnimRig_HatMushroom  _ZN24PlantAnimRig_HatMushroomD2Ev
// TODO     28 B  PlantAnimRig_HatMushroom::~PlantAnimRig_HatMushroom  _ZN24PlantAnimRig_HatMushroomD1Ev
