// PvZ2/collectables/CollectableSun.cpp
//
// 21 function(s), 1820 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: CollectableSun, CollectableSunType
//
// TODO    248 B  CollectableSun::StartCaptureEffect                   _ZN14CollectableSun18StartCaptureEffectESs
// TODO    204 B  CollectableSun::StopCaptureEffect                    _ZN14CollectableSun17StopCaptureEffectEv
// TODO    180 B  CollectableSun::StaticClassInit                      _ZN14CollectableSun15StaticClassInitEv
// TODO    180 B  CollectableSunType::StaticClassInit                  _ZN18CollectableSunType15StaticClassInitEv
// TODO    156 B  CollectableSun::onUpdate                             _ZN14CollectableSun8onUpdateEv
// TODO    124 B  CollectableSun::StaticGetClass                       _ZN14CollectableSun14StaticGetClassEv
// TODO    124 B  CollectableSunType::StaticGetClass                   _ZN18CollectableSunType14StaticGetClassEv
// TODO    112 B  CollectableSun::onFinishMotion                       _ZN14CollectableSun14onFinishMotionEv
// TODO     56 B  CollectableSun::CollectableSun                       _ZN14CollectableSunC2Ev
// TODO     56 B  CollectableSun::CollectableSun                       _ZN14CollectableSunC1Ev
// TODO     56 B  CollectableSunType::CollectableSunType               _ZN18CollectableSunTypeC2Ev
// TODO     56 B  CollectableSunType::CollectableSunType               _ZN18CollectableSunTypeC1Ev
// TODO     44 B  CollectableSun::StaticNew                            _ZN14CollectableSun9StaticNewEv
// TODO     44 B  CollectableSunType::StaticNew                        _ZN18CollectableSunType9StaticNewEv
// TODO     36 B  CollectableSun::~CollectableSun                      _ZN14CollectableSunD0Ev
// TODO     36 B  CollectableSunType::~CollectableSunType              _ZN18CollectableSunTypeD0Ev
// TODO     28 B  CollectableSun::~CollectableSun                      _ZN14CollectableSunD2Ev
// TODO     28 B  CollectableSun::~CollectableSun                      _ZN14CollectableSunD1Ev
// TODO     20 B  CollectableSunType::~CollectableSunType              _ZN18CollectableSunTypeD2Ev
// TODO     20 B  CollectableSunType::~CollectableSunType              _ZN18CollectableSunTypeD1Ev
// TODO     12 B  CollectableSun::onCollectableInitialize              _ZN14CollectableSun23onCollectableInitializeEv
