// PvZ2/collectables/CollectableArenaPlant.cpp
//
// 12 function(s), 1328 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: CollectableArenaPlant
//
// TODO    308 B  CollectableArenaPlant::StartMoving                   _ZN21CollectableArenaPlant11StartMovingEv
// TODO    216 B  CollectableArenaPlant::onFinishMotion                _ZN21CollectableArenaPlant14onFinishMotionEv
// TODO    180 B  CollectableArenaPlant::StaticClassInit               _ZN21CollectableArenaPlant15StaticClassInitEv
// TODO    156 B  CollectableArenaPlant::drawToBuffer                  _ZN21CollectableArenaPlant12drawToBufferEv
// TODO    124 B  CollectableArenaPlant::StaticGetClass                _ZN21CollectableArenaPlant14StaticGetClassEv
// TODO     64 B  CollectableArenaPlant::CollectableArenaPlant         _ZN21CollectableArenaPlantC2Ev
// TODO     64 B  CollectableArenaPlant::CollectableArenaPlant         _ZN21CollectableArenaPlantC1Ev
// TODO     64 B  CollectableArenaPlant::~CollectableArenaPlant        _ZN21CollectableArenaPlantD2Ev
// TODO     64 B  CollectableArenaPlant::~CollectableArenaPlant        _ZN21CollectableArenaPlantD1Ev
// TODO     44 B  CollectableArenaPlant::StaticNew                     _ZN21CollectableArenaPlant9StaticNewEv
// TODO     36 B  CollectableArenaPlant::~CollectableArenaPlant        _ZN21CollectableArenaPlantD0Ev
// TODO      8 B  CollectableArenaPlant::SetPlantSeedType              _ZN21CollectableArenaPlant16SetPlantSeedTypeEN4Sexy9RtWeakPtrIK9PlantTypeEE
