// PvZ2/zombies/SteamCoalMiner/ZombieSteamCoalMiner.cpp
//
// 36 function(s), 5608 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieSteamCoalMiner, ZombieSteamCoalMinerProps
//
// TODO    972 B  ZombieSteamCoalMiner::tryPlaceTruck                  _ZN20ZombieSteamCoalMiner13tryPlaceTruckERKN4Sexy5PointE
// TODO    568 B  ZombieSteamCoalMiner::spawnTruckShatterEffect        _ZN20ZombieSteamCoalMiner23spawnTruckShatterEffectERKN4Sexy5PointERKSs
// TODO    500 B  ZombieSteamCoalMiner::onTakeHelmDamage               _ZN20ZombieSteamCoalMiner16onTakeHelmDamageERK10DamageInfo
// TODO    468 B  ZombieSteamCoalMiner::StaticClassInit                _ZN20ZombieSteamCoalMiner15StaticClassInitEv
// TODO    320 B  ZombieSteamCoalMiner::StartWork                      _ZN20ZombieSteamCoalMiner9StartWorkEbi
// TODO    272 B  ZombieSteamCoalMiner::onHelmDropped                  _ZN20ZombieSteamCoalMiner13onHelmDroppedE8HelmTypei
// TODO    228 B  ZombieSteamCoalMiner::onApplyCondition               _ZN20ZombieSteamCoalMiner16onApplyConditionE16ZombieConditions
// TODO    228 B  ZombieSteamCoalMiner::onEnterState_StartWork         _ZN20ZombieSteamCoalMiner22onEnterState_StartWorkE11ZombieState
// TODO    180 B  ZombieSteamCoalMinerProps::StaticClassInit           _ZN25ZombieSteamCoalMinerProps15StaticClassInitEv
// TODO    148 B  ZombieSteamCoalMiner::onBurnedTruckAnimCompleted     _ZN20ZombieSteamCoalMiner26onBurnedTruckAnimCompletedERKSs
// TODO    148 B  ZombieSteamCoalMiner::onBrokenTruckAnimCompleted     _ZN20ZombieSteamCoalMiner26onBrokenTruckAnimCompletedERKSs
// TODO    124 B  ZombieSteamCoalMiner::StaticGetClass                 _ZN20ZombieSteamCoalMiner14StaticGetClassEv
// TODO    124 B  ZombieSteamCoalMinerProps::StaticGetClass            _ZN25ZombieSteamCoalMinerProps14StaticGetClassEv
// TODO    120 B  ZombieSteamCoalMiner::updateState_Walk               _ZN20ZombieSteamCoalMiner16updateState_WalkEv
// TODO    108 B  ZombieSteamCoalMiner::getDefaultTruckSpawnPosition   _ZN20ZombieSteamCoalMiner28getDefaultTruckSpawnPositionEv
// TODO    108 B  ZombieSteamCoalMiner::onPopAnimCommand               _ZN20ZombieSteamCoalMiner16onPopAnimCommandERKSsfS1_S1_
// TODO    100 B  ZombieSteamCoalMinerProps::ZombieSteamCoalMinerProps _ZN25ZombieSteamCoalMinerPropsC2Ev
// TODO    100 B  ZombieSteamCoalMinerProps::ZombieSteamCoalMinerProps _ZN25ZombieSteamCoalMinerPropsC1Ev
// TODO     88 B  ZombieSteamCoalMiner::CalcZombieAttackRect           _ZN20ZombieSteamCoalMiner20CalcZombieAttackRectEv
// TODO     68 B  ZombieSteamCoalMiner::onStartWorkAnimCompleted       _ZN20ZombieSteamCoalMiner24onStartWorkAnimCompletedERKSs
// TODO     64 B  ZombieSteamCoalMinerProps::~ZombieSteamCoalMinerProps _ZN25ZombieSteamCoalMinerPropsD2Ev
// TODO     64 B  ZombieSteamCoalMinerProps::~ZombieSteamCoalMinerProps _ZN25ZombieSteamCoalMinerPropsD1Ev
// TODO     60 B  ZombieSteamCoalMiner::ZombieSteamCoalMiner           _ZN20ZombieSteamCoalMinerC2Ev
// TODO     60 B  ZombieSteamCoalMiner::ZombieSteamCoalMiner           _ZN20ZombieSteamCoalMinerC1Ev
// TODO     60 B  ZombieSteamCoalMiner::updateTruckDamage              _ZN20ZombieSteamCoalMiner17updateTruckDamageEv
// TODO     44 B  ZombieSteamCoalMiner::StaticNew                      _ZN20ZombieSteamCoalMiner9StaticNewEv
// TODO     44 B  ZombieSteamCoalMinerProps::StaticNew                 _ZN25ZombieSteamCoalMinerProps9StaticNewEv
// TODO     36 B  ZombieSteamCoalMiner::~ZombieSteamCoalMiner          _ZN20ZombieSteamCoalMinerD0Ev
// TODO     36 B  ZombieSteamCoalMiner::onPlaceOnBoard                 _ZN20ZombieSteamCoalMiner14onPlaceOnBoardEv
// TODO     36 B  ZombieSteamCoalMiner::takeHelmDamage                 _ZN20ZombieSteamCoalMiner14takeHelmDamageERK10DamageInfo
// TODO     36 B  ZombieSteamCoalMinerProps::~ZombieSteamCoalMinerProps _ZN25ZombieSteamCoalMinerPropsD0Ev
// TODO     32 B  ZombieSteamCoalMiner::hasTruck                       _ZN20ZombieSteamCoalMiner8hasTruckEv
// TODO     28 B  ZombieSteamCoalMiner::~ZombieSteamCoalMiner          _ZN20ZombieSteamCoalMinerD2Ev
// TODO     28 B  ZombieSteamCoalMiner::~ZombieSteamCoalMiner          _ZN20ZombieSteamCoalMinerD1Ev
// TODO      4 B  ZombieSteamCoalMiner::updateState_StartWork          _ZN20ZombieSteamCoalMiner21updateState_StartWorkEv
// TODO      4 B  ZombieSteamCoalMiner::onExitState_StartWork          _ZN20ZombieSteamCoalMiner21onExitState_StartWorkE11ZombieState
