// PvZ2/zombies/Statue/ZombieAnimRig_Statue.cpp
//
// 8 function(s), 552 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieAnimRig_Statue
//
// TODO    180 B  ZombieAnimRig_Statue::StaticClassInit                _ZN20ZombieAnimRig_Statue15StaticClassInitEv
// TODO    124 B  ZombieAnimRig_Statue::StaticGetClass                 _ZN20ZombieAnimRig_Statue14StaticGetClassEv
// TODO     56 B  ZombieAnimRig_Statue::ZombieAnimRig_Statue           _ZN20ZombieAnimRig_StatueC2Ev
// TODO     56 B  ZombieAnimRig_Statue::ZombieAnimRig_Statue           _ZN20ZombieAnimRig_StatueC1Ev
// TODO     44 B  ZombieAnimRig_Statue::StaticNew                      _ZN20ZombieAnimRig_Statue9StaticNewEv
// TODO     36 B  ZombieAnimRig_Statue::~ZombieAnimRig_Statue          _ZN20ZombieAnimRig_StatueD0Ev
// TODO     28 B  ZombieAnimRig_Statue::~ZombieAnimRig_Statue          _ZN20ZombieAnimRig_StatueD2Ev
// TODO     28 B  ZombieAnimRig_Statue::~ZombieAnimRig_Statue          _ZN20ZombieAnimRig_StatueD1Ev
