// PvZ2/plants/TupistraStalker/PlantAnimRig_TupistraStalker.cpp
//
// 17 function(s), 1740 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_TupistraStalker
//
// TODO    208 B  PlantAnimRig_TupistraStalker::LoopAttack             _ZN28PlantAnimRig_TupistraStalker10LoopAttackE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEEb
// TODO    184 B  PlantAnimRig_TupistraStalker::Jumping                _ZN28PlantAnimRig_TupistraStalker7JumpingE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEEb
// TODO    184 B  PlantAnimRig_TupistraStalker::Submerging             _ZN28PlantAnimRig_TupistraStalker10SubmergingE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    184 B  PlantAnimRig_TupistraStalker::Rising                 _ZN28PlantAnimRig_TupistraStalker6RisingE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    180 B  PlantAnimRig_TupistraStalker::StaticClassInit        _ZN28PlantAnimRig_TupistraStalker15StaticClassInitEv
// TODO    136 B  PlantAnimRig_TupistraStalker::getIdleAnimationName   _ZN28PlantAnimRig_TupistraStalker20getIdleAnimationNameEv
// TODO    124 B  PlantAnimRig_TupistraStalker::StaticGetClass         _ZN28PlantAnimRig_TupistraStalker14StaticGetClassEv
// TODO    104 B  PlantAnimRig_TupistraStalker::getPlantFoodOffAnimName _ZN28PlantAnimRig_TupistraStalker23getPlantFoodOffAnimNameEv
// TODO    104 B  PlantAnimRig_TupistraStalker::getPlantFoodOnAnimName _ZN28PlantAnimRig_TupistraStalker22getPlantFoodOnAnimNameEv
// TODO     64 B  PlantAnimRig_TupistraStalker::PlantAnimRig_TupistraStalker _ZN28PlantAnimRig_TupistraStalkerC2Ev
// TODO     64 B  PlantAnimRig_TupistraStalker::PlantAnimRig_TupistraStalker _ZN28PlantAnimRig_TupistraStalkerC1Ev
// TODO     44 B  PlantAnimRig_TupistraStalker::StaticNew              _ZN28PlantAnimRig_TupistraStalker9StaticNewEv
// TODO     36 B  PlantAnimRig_TupistraStalker::~PlantAnimRig_TupistraStalker _ZN28PlantAnimRig_TupistraStalkerD0Ev
// TODO     36 B  PlantAnimRig_TupistraStalker::onPopAnimInitialized   _ZN28PlantAnimRig_TupistraStalker20onPopAnimInitializedEv
// TODO     32 B  PlantAnimRig_TupistraStalker::PlayPreviewAnim        _ZN28PlantAnimRig_TupistraStalker15PlayPreviewAnimEb
// TODO     28 B  PlantAnimRig_TupistraStalker::~PlantAnimRig_TupistraStalker _ZN28PlantAnimRig_TupistraStalkerD2Ev
// TODO     28 B  PlantAnimRig_TupistraStalker::~PlantAnimRig_TupistraStalker _ZN28PlantAnimRig_TupistraStalkerD1Ev
