// PvZ2/plants/Cypripedium/PlantAnimRig_Cypripedium.cpp
//
// 13 function(s), 1016 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_Cypripedium
//
// TODO    180 B  PlantAnimRig_Cypripedium::StaticClassInit            _ZN24PlantAnimRig_Cypripedium15StaticClassInitEv
// TODO    160 B  PlantAnimRig_Cypripedium::getAttackAnimationName     _ZN24PlantAnimRig_Cypripedium22getAttackAnimationNameEv
// TODO    136 B  PlantAnimRig_Cypripedium::getIdleAnimationName       _ZN24PlantAnimRig_Cypripedium20getIdleAnimationNameEv
// TODO    128 B  PlantAnimRig_Cypripedium::getPlantFoodMainAnimName   _ZN24PlantAnimRig_Cypripedium24getPlantFoodMainAnimNameEv
// TODO    124 B  PlantAnimRig_Cypripedium::StaticGetClass             _ZN24PlantAnimRig_Cypripedium14StaticGetClassEv
// TODO     68 B  PlantAnimRig_Cypripedium::PlantAnimRig_Cypripedium   _ZN24PlantAnimRig_CypripediumC2Ev
// TODO     68 B  PlantAnimRig_Cypripedium::PlantAnimRig_Cypripedium   _ZN24PlantAnimRig_CypripediumC1Ev
// TODO     44 B  PlantAnimRig_Cypripedium::StaticNew                  _ZN24PlantAnimRig_Cypripedium9StaticNewEv
// TODO     36 B  PlantAnimRig_Cypripedium::~PlantAnimRig_Cypripedium  _ZN24PlantAnimRig_CypripediumD0Ev
// TODO     28 B  PlantAnimRig_Cypripedium::~PlantAnimRig_Cypripedium  _ZN24PlantAnimRig_CypripediumD2Ev
// TODO     28 B  PlantAnimRig_Cypripedium::~PlantAnimRig_Cypripedium  _ZN24PlantAnimRig_CypripediumD1Ev
// TODO      8 B  PlantAnimRig_Cypripedium::SetAttackMode              _ZN24PlantAnimRig_Cypripedium13SetAttackModeEi
// TODO      8 B  PlantAnimRig_Cypripedium::SetIsLevel5                _ZN24PlantAnimRig_Cypripedium11SetIsLevel5Eb
