// PvZ2/plants/Dartichoke/Plant_Dartichoke.cpp
//
// 25 function(s), 4288 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantDartichoke
//
// TODO    848 B  PlantDartichoke::Fire                                _ZN15PlantDartichoke4FireEN4Sexy9RtWeakPtrI6ZombieEEi11PlantWeapon
// TODO    504 B  PlantDartichoke::FindDangerousTarget                 _ZN15PlantDartichoke19FindDangerousTargetE11PlantWeapon
// TODO    332 B  PlantDartichoke::ApplyPlantfood                      _ZN15PlantDartichoke14ApplyPlantfoodEv
// TODO    288 B  PlantDartichoke::FindTargetZombie                    _ZN15PlantDartichoke16FindTargetZombieERN4Sexy5TRectIiEE11PlantWeaponR17PlantTargetParams
// TODO    260 B  PlantDartichoke::fireRotatedProjectile               _ZN15PlantDartichoke21fireRotatedProjectileE11PlantWeaponi
// TODO    244 B  PlantDartichoke::calcZombieTargetWeight              _ZN15PlantDartichoke22calcZombieTargetWeightEP6ZombieR17PlantTargetParams
// TODO    216 B  PlantDartichoke::UpdateActions                       _ZN15PlantDartichoke13UpdateActionsEv
// TODO    208 B  PlantDartichoke::GetPlantFoodPlayCount               _ZN15PlantDartichoke21GetPlantFoodPlayCountEv
// TODO    180 B  PlantDartichoke::StaticClassInit                     _ZN15PlantDartichoke15StaticClassInitEv
// TODO    152 B  PlantDartichoke::PlantDartichoke                     _ZN15PlantDartichokeC2Ev
// TODO    152 B  PlantDartichoke::PlantDartichoke                     _ZN15PlantDartichokeC1Ev
// TODO    136 B  PlantDartichoke::updateAmmo                          _ZN15PlantDartichoke10updateAmmoEv
// TODO    128 B  PlantDartichoke::fillAmmo                            _ZN15PlantDartichoke8fillAmmoEv
// TODO    124 B  PlantDartichoke::StaticGetClass                      _ZN15PlantDartichoke14StaticGetClassEv
// TODO    116 B  PlantDartichoke::Initialize                          _ZN15PlantDartichoke10InitializeEv
// TODO    104 B  PlantDartichoke::GetPlantAttackRect                  _ZN15PlantDartichoke18GetPlantAttackRectE11PlantWeapon
// TODO     76 B  PlantDartichoke::~PlantDartichoke                    _ZN15PlantDartichokeD2Ev
// TODO     76 B  PlantDartichoke::~PlantDartichoke                    _ZN15PlantDartichokeD1Ev
// TODO     44 B  PlantDartichoke::StaticNew                           _ZN15PlantDartichoke9StaticNewEv
// TODO     36 B  PlantDartichoke::CancelExhausted                     _ZN15PlantDartichoke15CancelExhaustedEv
// TODO     36 B  PlantDartichoke::~PlantDartichoke                    _ZN15PlantDartichokeD0Ev
// TODO      8 B  PlantDartichoke::GetTargetEntityTypesForWeapon       _ZN15PlantDartichoke29GetTargetEntityTypesForWeaponE11PlantWeapon
// TODO      8 B  PlantDartichoke::UpdateUnconditionally               _ZN15PlantDartichoke21UpdateUnconditionallyEv
// TODO      8 B  PlantDartichoke::CanApplyPlantfood                   _ZN15PlantDartichoke17CanApplyPlantfoodEv
// TODO      4 B  PlantDartichoke::PostInitialize                      _ZN15PlantDartichoke14PostInitializeEv
