// PvZ2/PVP/joust/adaptorjoust/AdaptorJoustTourneyResultsScreen.cpp
//
// 48 function(s), 12224 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: AdaptorJoustTourneyResultsScreen
//
// TODO   1844 B  AdaptorJoustTourneyResultsScreen::setupAnimationsPromotion _ZN32AdaptorJoustTourneyResultsScreen24setupAnimationsPromotionEv
// TODO   1140 B  AdaptorJoustTourneyResultsScreen::setupAnimationsDemotion _ZN32AdaptorJoustTourneyResultsScreen23setupAnimationsDemotionEv
// TODO   1064 B  AdaptorJoustTourneyResultsScreen::HandleStateMachine_TournamentResultsScreenState _ZN32AdaptorJoustTourneyResultsScreen47HandleStateMachine_TournamentResultsScreenStateE28TournamentResultsScreenState11StateAction
// TODO    940 B  AdaptorJoustTourneyResultsScreen::updateLeagueData   _ZN32AdaptorJoustTourneyResultsScreen16updateLeagueDataEv
// TODO    716 B  AdaptorJoustTourneyResultsScreen::setupAnimationsStay _ZN32AdaptorJoustTourneyResultsScreen19setupAnimationsStayEv
// TODO    536 B  AdaptorJoustTourneyResultsScreen::updateRewardData   _ZN32AdaptorJoustTourneyResultsScreen16updateRewardDataEv
// TODO    516 B  AdaptorJoustTourneyResultsScreen::giveRewards        _ZN32AdaptorJoustTourneyResultsScreen11giveRewardsEv
// TODO    432 B  AdaptorJoustTourneyResultsScreen::showAwardScreen    _ZN32AdaptorJoustTourneyResultsScreen15showAwardScreenEv
// TODO    272 B  AdaptorJoustTourneyResultsScreen::updateFTUE         _ZN32AdaptorJoustTourneyResultsScreen10updateFTUEEv
// TODO    272 B  AdaptorJoustTourneyResultsScreen::startHotUIAnim     _ZN32AdaptorJoustTourneyResultsScreen14startHotUIAnimEP19WidgetAnimationData
// TODO    268 B  AdaptorJoustTourneyResultsScreen::setup              _ZN32AdaptorJoustTourneyResultsScreen5setupEv
// TODO    256 B  AdaptorJoustTourneyResultsScreen::AdaptorJoustTourneyResultsScreen _ZN32AdaptorJoustTourneyResultsScreenC2Ev
// TODO    256 B  AdaptorJoustTourneyResultsScreen::AdaptorJoustTourneyResultsScreen _ZN32AdaptorJoustTourneyResultsScreenC1Ev
// TODO    248 B  AdaptorJoustTourneyResultsScreen::updateHotUIImageWidgetFromAnimationAlpha _ZN32AdaptorJoustTourneyResultsScreen40updateHotUIImageWidgetFromAnimationAlphaEP19WidgetAnimationDataf
// TODO    240 B  AdaptorJoustTourneyResultsScreen::setInputEnabled    _ZN32AdaptorJoustTourneyResultsScreen15setInputEnabledEb
// TODO    236 B  AdaptorJoustTourneyResultsScreen::updateAnimsForState _ZN32AdaptorJoustTourneyResultsScreen19updateAnimsForStateE28TournamentResultsScreenStatef
// TODO    220 B  AdaptorJoustTourneyResultsScreen::startAnimsForState _ZN32AdaptorJoustTourneyResultsScreen18startAnimsForStateE28TournamentResultsScreenStatef
// TODO    208 B  AdaptorJoustTourneyResultsScreen::endAnimsForState   _ZN32AdaptorJoustTourneyResultsScreen16endAnimsForStateE28TournamentResultsScreenState
// TODO    180 B  AdaptorJoustTourneyResultsScreen::StaticClassInit    _ZN32AdaptorJoustTourneyResultsScreen15StaticClassInitEv
// TODO    180 B  AdaptorJoustTourneyResultsScreen::EnableFullScreenDismiss _ZN32AdaptorJoustTourneyResultsScreen23EnableFullScreenDismissEb
// TODO    168 B  AdaptorJoustTourneyResultsScreen::updateWidgetFromAnimationTranslation _ZN32AdaptorJoustTourneyResultsScreen36updateWidgetFromAnimationTranslationEP19WidgetAnimationDataf
// TODO    160 B  AdaptorJoustTourneyResultsScreen::onLoadUIView       _ZN32AdaptorJoustTourneyResultsScreen12onLoadUIViewEv
// TODO    156 B  AdaptorJoustTourneyResultsScreen::onJoustNetworkResponse _ZN32AdaptorJoustTourneyResultsScreen22onJoustNetworkResponseEii
// TODO    148 B  AdaptorJoustTourneyResultsScreen::updateWidgetFromAnimation _ZN32AdaptorJoustTourneyResultsScreen25updateWidgetFromAnimationEP19WidgetAnimationDataf
// TODO    144 B  AdaptorJoustTourneyResultsScreen::updateHotUIImageWidgetFromAnimationScale _ZN32AdaptorJoustTourneyResultsScreen40updateHotUIImageWidgetFromAnimationScaleEP19WidgetAnimationDataf
// TODO    144 B  AdaptorJoustTourneyResultsScreen::updateHotUIAnimWidgetFromAnimationScale _ZN32AdaptorJoustTourneyResultsScreen39updateHotUIAnimWidgetFromAnimationScaleEP19WidgetAnimationDataf
// TODO    128 B  AdaptorJoustTourneyResultsScreen::sendTournamentRegistrationRequest _ZN32AdaptorJoustTourneyResultsScreen33sendTournamentRegistrationRequestEv
// TODO    124 B  AdaptorJoustTourneyResultsScreen::StaticGetClass     _ZN32AdaptorJoustTourneyResultsScreen14StaticGetClassEv
// TODO     96 B  AdaptorJoustTourneyResultsScreen::setState_TournamentResultsScreenState _ZN32AdaptorJoustTourneyResultsScreen37setState_TournamentResultsScreenStateE28TournamentResultsScreenState
// TODO     88 B  AdaptorJoustTourneyResultsScreen::onAwardScreenDismissed _ZN32AdaptorJoustTourneyResultsScreen22onAwardScreenDismissedEv
// TODO     88 B  AdaptorJoustTourneyResultsScreen::~AdaptorJoustTourneyResultsScreen _ZN32AdaptorJoustTourneyResultsScreenD2Ev
// TODO     88 B  AdaptorJoustTourneyResultsScreen::~AdaptorJoustTourneyResultsScreen _ZN32AdaptorJoustTourneyResultsScreenD1Ev
// TODO     88 B  AdaptorJoustTourneyResultsScreen::startWidgetAnimation _ZN32AdaptorJoustTourneyResultsScreen20startWidgetAnimationEP19WidgetAnimationDataf
// TODO     80 B  AdaptorJoustTourneyResultsScreen::onRegistrationDone _ZN32AdaptorJoustTourneyResultsScreen18onRegistrationDoneEv
// TODO     64 B  AdaptorJoustTourneyResultsScreen::refresh            _ZN32AdaptorJoustTourneyResultsScreen7refreshEv
// TODO     64 B  AdaptorJoustTourneyResultsScreen::Update             _ZN32AdaptorJoustTourneyResultsScreen6UpdateEv
// TODO     52 B  AdaptorJoustTourneyResultsScreen::onJoustNetworkIssueDecision _ZN32AdaptorJoustTourneyResultsScreen27onJoustNetworkIssueDecisionEii
// TODO     48 B  AdaptorJoustTourneyResultsScreen::onContinueClick    _ZN32AdaptorJoustTourneyResultsScreen15onContinueClickEv
// TODO     44 B  AdaptorJoustTourneyResultsScreen::StaticNew          _ZN32AdaptorJoustTourneyResultsScreen9StaticNewEv
// TODO     40 B  AdaptorJoustTourneyResultsScreen::SetParams          _ZN32AdaptorJoustTourneyResultsScreen9SetParamsERK38AdaptorJoustTourneyResultsScreenParams
// TODO     36 B  AdaptorJoustTourneyResultsScreen::~AdaptorJoustTourneyResultsScreen _ZN32AdaptorJoustTourneyResultsScreenD0Ev
// TODO     32 B  AdaptorJoustTourneyResultsScreen::Close              _ZN32AdaptorJoustTourneyResultsScreen5CloseEv
// TODO     32 B  AdaptorJoustTourneyResultsScreen::onHotUIAnimLoopFinished _ZN32AdaptorJoustTourneyResultsScreen23onHotUIAnimLoopFinishedERKSsS1_i
// TODO     32 B  AdaptorJoustTourneyResultsScreen::onHotUIAnimFinished _ZN32AdaptorJoustTourneyResultsScreen19onHotUIAnimFinishedERKSs
// TODO     24 B  AdaptorJoustTourneyResultsScreen::OnBackButtonPressed _ZN32AdaptorJoustTourneyResultsScreen19OnBackButtonPressedEv
// TODO     24 B  AdaptorJoustTourneyResultsScreen::ButtonDepress      _ZN32AdaptorJoustTourneyResultsScreen13ButtonDepressEi
// TODO      4 B  AdaptorJoustTourneyResultsScreen::HandleSuperFSMAction_TournamentResultsScreenState _ZN32AdaptorJoustTourneyResultsScreen49HandleSuperFSMAction_TournamentResultsScreenStateE28TournamentResultsScreenState11StateAction
// TODO      4 B  AdaptorJoustTourneyResultsScreen::onLinkToUIViewCreated _ZN32AdaptorJoustTourneyResultsScreen21onLinkToUIViewCreatedEv
