// PvZ2/PVP/joust/adaptorjoust/AdaptorJoustWinStreakDialog.cpp
//
// 13 function(s), 1248 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: AdaptorJoustWinStreakDialog
//
// TODO    296 B  AdaptorJoustWinStreakDialog::onLoadUIView            _ZN27AdaptorJoustWinStreakDialog12onLoadUIViewEv
// TODO    188 B  AdaptorJoustWinStreakDialog::refresh                 _ZN27AdaptorJoustWinStreakDialog7refreshEv
// TODO    180 B  AdaptorJoustWinStreakDialog::StaticClassInit         _ZN27AdaptorJoustWinStreakDialog15StaticClassInitEv
// TODO    124 B  AdaptorJoustWinStreakDialog::StaticGetClass          _ZN27AdaptorJoustWinStreakDialog14StaticGetClassEv
// TODO     72 B  AdaptorJoustWinStreakDialog::~AdaptorJoustWinStreakDialog _ZN27AdaptorJoustWinStreakDialogD2Ev
// TODO     72 B  AdaptorJoustWinStreakDialog::~AdaptorJoustWinStreakDialog _ZN27AdaptorJoustWinStreakDialogD1Ev
// TODO     68 B  AdaptorJoustWinStreakDialog::AdaptorJoustWinStreakDialog _ZN27AdaptorJoustWinStreakDialogC2Ev
// TODO     68 B  AdaptorJoustWinStreakDialog::AdaptorJoustWinStreakDialog _ZN27AdaptorJoustWinStreakDialogC1Ev
// TODO     48 B  AdaptorJoustWinStreakDialog::Close                   _ZN27AdaptorJoustWinStreakDialog5CloseEv
// TODO     44 B  AdaptorJoustWinStreakDialog::StaticNew               _ZN27AdaptorJoustWinStreakDialog9StaticNewEv
// TODO     44 B  AdaptorJoustWinStreakDialog::ButtonDepress           _ZN27AdaptorJoustWinStreakDialog13ButtonDepressEi
// TODO     36 B  AdaptorJoustWinStreakDialog::~AdaptorJoustWinStreakDialog _ZN27AdaptorJoustWinStreakDialogD0Ev
// TODO      8 B  AdaptorJoustWinStreakDialog::Setup                   _ZN27AdaptorJoustWinStreakDialog5SetupERK20RtReflectionDelegateIN4Sexy9Delegate0EE
