// PvZ2/PVP/joust/adaptorjoust/AdaptorJoustLeaderboardEntry.cpp
//
// 17 function(s), 3328 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: AdaptorJoustLeaderboardEntry
//
// TODO   1356 B  AdaptorJoustLeaderboardEntry::onLoadUIView           _ZN28AdaptorJoustLeaderboardEntry12onLoadUIViewEv
// TODO    412 B  AdaptorJoustLeaderboardEntry::updateAvatarIcon       _ZN28AdaptorJoustLeaderboardEntry16updateAvatarIconEv
// TODO    312 B  AdaptorJoustLeaderboardEntry::onRankListEffectUpdate _ZN28AdaptorJoustLeaderboardEntry22onRankListEffectUpdateERKSt6vectorIiSaIiEE
// TODO    244 B  AdaptorJoustLeaderboardEntry::getGemReward           _ZN28AdaptorJoustLeaderboardEntry12getGemRewardEv
// TODO    180 B  AdaptorJoustLeaderboardEntry::StaticClassInit        _ZN28AdaptorJoustLeaderboardEntry15StaticClassInitEv
// TODO    160 B  AdaptorJoustLeaderboardEntry::getFirstRewardObject   _ZN28AdaptorJoustLeaderboardEntry20getFirstRewardObjectEv
// TODO    144 B  AdaptorJoustLeaderboardEntry::getFirstReward         _ZN28AdaptorJoustLeaderboardEntry14getFirstRewardEv
// TODO    124 B  AdaptorJoustLeaderboardEntry::StaticGetClass         _ZN28AdaptorJoustLeaderboardEntry14StaticGetClassEv
// TODO     72 B  AdaptorJoustLeaderboardEntry::AdaptorJoustLeaderboardEntry _ZN28AdaptorJoustLeaderboardEntryC1Ev
// TODO     72 B  AdaptorJoustLeaderboardEntry::~AdaptorJoustLeaderboardEntry _ZN28AdaptorJoustLeaderboardEntryD2Ev
// TODO     72 B  AdaptorJoustLeaderboardEntry::~AdaptorJoustLeaderboardEntry _ZN28AdaptorJoustLeaderboardEntryD1Ev
// TODO     72 B  AdaptorJoustLeaderboardEntry::AdaptorJoustLeaderboardEntry _ZN28AdaptorJoustLeaderboardEntryC2Ev
// TODO     44 B  AdaptorJoustLeaderboardEntry::StaticNew              _ZN28AdaptorJoustLeaderboardEntry9StaticNewEv
// TODO     36 B  AdaptorJoustLeaderboardEntry::~AdaptorJoustLeaderboardEntry _ZN28AdaptorJoustLeaderboardEntryD0Ev
// TODO     20 B  AdaptorJoustLeaderboardEntry::Configure              _ZN28AdaptorJoustLeaderboardEntry9ConfigureEPN4Sexy15WidgetContainerERK34AdaptorJoustLeaderboardEntryConfig
// TODO      4 B  AdaptorJoustLeaderboardEntry::onLinkToUIViewCreated  _ZN28AdaptorJoustLeaderboardEntry21onLinkToUIViewCreatedEv
// TODO      4 B  AdaptorJoustLeaderboardEntry::onLayoutFinished       _ZN28AdaptorJoustLeaderboardEntry16onLayoutFinishedEv
