// PvZ2/PVP/joust/adaptorjoust/AdaptorJoustMatchmakingScreen.cpp
//
// 32 function(s), 4320 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: AdaptorJoustMatchmakingScreen
//
// TODO    608 B  AdaptorJoustMatchmakingScreen::onLinkToUIViewCreated _ZN29AdaptorJoustMatchmakingScreen21onLinkToUIViewCreatedEv
// TODO    456 B  AdaptorJoustMatchmakingScreen::HandleStateMachine_MatchmakingScreenState _ZN29AdaptorJoustMatchmakingScreen41HandleStateMachine_MatchmakingScreenStateE22MatchmakingScreenState11StateAction
// TODO    304 B  AdaptorJoustMatchmakingScreen::updateSearchingDisplay _ZN29AdaptorJoustMatchmakingScreen22updateSearchingDisplayEv
// TODO    276 B  AdaptorJoustMatchmakingScreen::updateOpponentDisplay _ZN29AdaptorJoustMatchmakingScreen21updateOpponentDisplayEv
// TODO    260 B  AdaptorJoustMatchmakingScreen::AdaptorJoustMatchmakingScreen _ZN29AdaptorJoustMatchmakingScreenC2Ev
// TODO    260 B  AdaptorJoustMatchmakingScreen::AdaptorJoustMatchmakingScreen _ZN29AdaptorJoustMatchmakingScreenC1Ev
// TODO    192 B  AdaptorJoustMatchmakingScreen::configureSeedPackets  _ZN29AdaptorJoustMatchmakingScreen20configureSeedPacketsERKSt6vectorI21HotUISeedPacketConfigSaIS1_EE
// TODO    180 B  AdaptorJoustMatchmakingScreen::StaticClassInit       _ZN29AdaptorJoustMatchmakingScreen15StaticClassInitEv
// TODO    160 B  AdaptorJoustMatchmakingScreen::onLoadUIView          _ZN29AdaptorJoustMatchmakingScreen12onLoadUIViewEv
// TODO    144 B  AdaptorJoustMatchmakingScreen::showFindingOpponentDisplay _ZN29AdaptorJoustMatchmakingScreen26showFindingOpponentDisplayEb
// TODO    144 B  AdaptorJoustMatchmakingScreen::showFoundOpponentDisplay _ZN29AdaptorJoustMatchmakingScreen24showFoundOpponentDisplayEb
// TODO    132 B  AdaptorJoustMatchmakingScreen::ShowSwapButton        _ZN29AdaptorJoustMatchmakingScreen14ShowSwapButtonEv
// TODO    124 B  AdaptorJoustMatchmakingScreen::StaticGetClass        _ZN29AdaptorJoustMatchmakingScreen14StaticGetClassEv
// TODO    116 B  AdaptorJoustMatchmakingScreen::clearSeedPacketDisplay _ZN29AdaptorJoustMatchmakingScreen22clearSeedPacketDisplayEv
// TODO     96 B  AdaptorJoustMatchmakingScreen::setState_MatchmakingScreenState _ZN29AdaptorJoustMatchmakingScreen31setState_MatchmakingScreenStateE22MatchmakingScreenState
// TODO     92 B  AdaptorJoustMatchmakingScreen::onJoustNetworkIssueDecision _ZN29AdaptorJoustMatchmakingScreen27onJoustNetworkIssueDecisionEii
// TODO     88 B  AdaptorJoustMatchmakingScreen::~AdaptorJoustMatchmakingScreen _ZN29AdaptorJoustMatchmakingScreenD2Ev
// TODO     88 B  AdaptorJoustMatchmakingScreen::~AdaptorJoustMatchmakingScreen _ZN29AdaptorJoustMatchmakingScreenD1Ev
// TODO     88 B  AdaptorJoustMatchmakingScreen::onJoustNetworkResponse _ZN29AdaptorJoustMatchmakingScreen22onJoustNetworkResponseEii
// TODO     72 B  AdaptorJoustMatchmakingScreen::onMatchReceived       _ZN29AdaptorJoustMatchmakingScreen15onMatchReceivedEv
// TODO     72 B  AdaptorJoustMatchmakingScreen::Close                 _ZN29AdaptorJoustMatchmakingScreen5CloseEv
// TODO     68 B  AdaptorJoustMatchmakingScreen::ButtonDepress         _ZN29AdaptorJoustMatchmakingScreen13ButtonDepressEi
// TODO     64 B  AdaptorJoustMatchmakingScreen::OnBackButtonPressed   _ZN29AdaptorJoustMatchmakingScreen19OnBackButtonPressedEv
// TODO     64 B  AdaptorJoustMatchmakingScreen::Update                _ZN29AdaptorJoustMatchmakingScreen6UpdateEv
// TODO     60 B  AdaptorJoustMatchmakingScreen::signalCancel          _ZN29AdaptorJoustMatchmakingScreen12signalCancelEv
// TODO     44 B  AdaptorJoustMatchmakingScreen::StaticNew             _ZN29AdaptorJoustMatchmakingScreen9StaticNewEv
// TODO     36 B  AdaptorJoustMatchmakingScreen::~AdaptorJoustMatchmakingScreen _ZN29AdaptorJoustMatchmakingScreenD0Ev
// TODO      8 B  AdaptorJoustMatchmakingScreen::SetOnCancelAction     _ZN29AdaptorJoustMatchmakingScreen17SetOnCancelActionESt8functionIFvvEE
// TODO      8 B  AdaptorJoustMatchmakingScreen::SetOnFailAction       _ZN29AdaptorJoustMatchmakingScreen15SetOnFailActionESt8functionIFvvEE
// TODO      8 B  AdaptorJoustMatchmakingScreen::SetOnPlayAction       _ZN29AdaptorJoustMatchmakingScreen15SetOnPlayActionESt8functionIFvvEE
// TODO      4 B  AdaptorJoustMatchmakingScreen::HandleSuperFSMAction_MatchmakingScreenState _ZN29AdaptorJoustMatchmakingScreen43HandleSuperFSMAction_MatchmakingScreenStateE22MatchmakingScreenState11StateAction
// TODO      4 B  AdaptorJoustMatchmakingScreen::sendMatchRequest      _ZN29AdaptorJoustMatchmakingScreen16sendMatchRequestEv
