// PvZ2/plants/Dusklobber/PlantAnimRig_Dusklobber.cpp
//
// 15 function(s), 3948 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_Dusklobber
//
// TODO   2452 B  PlantAnimRig_Dusklobber::onPopAnimInitialized        _ZN23PlantAnimRig_Dusklobber20onPopAnimInitializedEv
// TODO    336 B  PlantAnimRig_Dusklobber::playIdleAnimation           _ZN23PlantAnimRig_Dusklobber17playIdleAnimationEv
// TODO    180 B  PlantAnimRig_Dusklobber::StaticClassInit             _ZN23PlantAnimRig_Dusklobber15StaticClassInitEv
// TODO    140 B  PlantAnimRig_Dusklobber::AddBoostedLayerSet          _ZN23PlantAnimRig_Dusklobber18AddBoostedLayerSetESsSt6vectorISsSaISsEE
// TODO    124 B  PlantAnimRig_Dusklobber::StaticGetClass              _ZN23PlantAnimRig_Dusklobber14StaticGetClassEv
// TODO    124 B  PlantAnimRig_Dusklobber::PlayPreviewAnim             _ZN23PlantAnimRig_Dusklobber15PlayPreviewAnimEb
// TODO    120 B  PlantAnimRig_Dusklobber::PlayZenGardenIdleAnim       _ZN23PlantAnimRig_Dusklobber21PlayZenGardenIdleAnimEv
// TODO    108 B  PlantAnimRig_Dusklobber::ShowBoostedLayerSet         _ZN23PlantAnimRig_Dusklobber19ShowBoostedLayerSetESs
// TODO     72 B  PlantAnimRig_Dusklobber::~PlantAnimRig_Dusklobber    _ZN23PlantAnimRig_DusklobberD2Ev
// TODO     72 B  PlantAnimRig_Dusklobber::~PlantAnimRig_Dusklobber    _ZN23PlantAnimRig_DusklobberD1Ev
// TODO     68 B  PlantAnimRig_Dusklobber::PlantAnimRig_Dusklobber     _ZN23PlantAnimRig_DusklobberC2Ev
// TODO     68 B  PlantAnimRig_Dusklobber::PlantAnimRig_Dusklobber     _ZN23PlantAnimRig_DusklobberC1Ev
// TODO     44 B  PlantAnimRig_Dusklobber::StaticNew                   _ZN23PlantAnimRig_Dusklobber9StaticNewEv
// TODO     36 B  PlantAnimRig_Dusklobber::~PlantAnimRig_Dusklobber    _ZN23PlantAnimRig_DusklobberD0Ev
// TODO      4 B  PlantAnimRig_Dusklobber::PlayIdleLooped              _ZN23PlantAnimRig_Dusklobber14PlayIdleLoopedEv
