// PvZ2/zombies/Gum/ZombieGum.cpp
//
// 31 function(s), 3940 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieGum, ZombieGumProps
//
// TODO    636 B  ZombieGum::StaticClassInit                           _ZN9ZombieGum15StaticClassInitEv
// TODO    628 B  ZombieGum::TakeDamage                                _ZN9ZombieGum10TakeDamageERK10DamageInfo
// TODO    468 B  ZombieGum::HypnoZombie                               _ZN9ZombieGum11HypnoZombieEN4Sexy9RtWeakPtrI6ZombieEE
// TODO    216 B  ZombieGum::onEnterState_GumIntro                     _ZN9ZombieGum21onEnterState_GumIntroE11ZombieState
// TODO    216 B  ZombieGum::onEnterState_GumDeath                     _ZN9ZombieGum21onEnterState_GumDeathE11ZombieState
// TODO    180 B  ZombieGumProps::StaticClassInit                      _ZN14ZombieGumProps15StaticClassInitEv
// TODO    164 B  ZombieGum::ZombieGum                                 _ZN9ZombieGumC2Ev
// TODO    164 B  ZombieGum::ZombieGum                                 _ZN9ZombieGumC1Ev
// TODO    124 B  ZombieGum::StaticGetClass                            _ZN9ZombieGum14StaticGetClassEv
// TODO    124 B  ZombieGumProps::StaticGetClass                       _ZN14ZombieGumProps14StaticGetClassEv
// TODO    100 B  ZombieGum::InitializeGum                             _ZN9ZombieGum13InitializeGumEfN4Sexy9RtWeakPtrI6ZombieEEi
// TODO     84 B  ZombieGum::~ZombieGum                                _ZN9ZombieGumD2Ev
// TODO     84 B  ZombieGum::~ZombieGum                                _ZN9ZombieGumD1Ev
// TODO     84 B  ZombieGum::onUpdate                                  _ZN9ZombieGum8onUpdateEv
// TODO     80 B  ZombieGum::onZombieConditionEnded                    _ZN9ZombieGum22onZombieConditionEndedEP6Zombiei
// TODO     80 B  ZombieGum::onPlaceOnBoard                            _ZN9ZombieGum14onPlaceOnBoardEv
// TODO     76 B  ZombieGum::onDestroy                                 _ZN9ZombieGum9onDestroyEv
// TODO     56 B  ZombieGumProps::~ZombieGumProps                      _ZN14ZombieGumPropsD2Ev
// TODO     56 B  ZombieGumProps::~ZombieGumProps                      _ZN14ZombieGumPropsD1Ev
// TODO     52 B  ZombieGumProps::ZombieGumProps                       _ZN14ZombieGumPropsC2Ev
// TODO     52 B  ZombieGumProps::ZombieGumProps                       _ZN14ZombieGumPropsC1Ev
// TODO     44 B  ZombieGum::StaticNew                                 _ZN9ZombieGum9StaticNewEv
// TODO     44 B  ZombieGumProps::StaticNew                            _ZN14ZombieGumProps9StaticNewEv
// TODO     36 B  ZombieGum::~ZombieGum                                _ZN9ZombieGumD0Ev
// TODO     36 B  ZombieGumProps::~ZombieGumProps                      _ZN14ZombieGumPropsD0Ev
// TODO     28 B  ZombieGum::onDeathAnimComplete                       _ZN9ZombieGum19onDeathAnimCompleteESs
// TODO     12 B  ZombieGum::onIntroAnimComplete                       _ZN9ZombieGum19onIntroAnimCompleteESs
// TODO      4 B  ZombieGum::updateState_GumIntro                      _ZN9ZombieGum20updateState_GumIntroEv
// TODO      4 B  ZombieGum::onExitState_GumIntro                      _ZN9ZombieGum20onExitState_GumIntroE11ZombieState
// TODO      4 B  ZombieGum::updateState_GumDeath                      _ZN9ZombieGum20updateState_GumDeathEv
// TODO      4 B  ZombieGum::onExitState_GumDeath                      _ZN9ZombieGum20onExitState_GumDeathE11ZombieState
