// PvZ2/effects/anim/EffectAnimRig_LinkedTileConnect.cpp
//
// 12 function(s), 948 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: EffectAnimRig_LinkedTileConnect
//
// TODO    180 B  EffectAnimRig_LinkedTileConnect::PlayOff             _ZN31EffectAnimRig_LinkedTileConnect7PlayOffEN4Sexy9Delegate1IRKSsEE
// TODO    172 B  EffectAnimRig_LinkedTileConnect::PlayOn              _ZN31EffectAnimRig_LinkedTileConnect6PlayOnEv
// TODO    168 B  EffectAnimRig_LinkedTileConnect::PlayGlow            _ZN31EffectAnimRig_LinkedTileConnect8PlayGlowEv
// TODO    120 B  EffectAnimRig_LinkedTileConnect::StaticGetClass      _ZN31EffectAnimRig_LinkedTileConnect14StaticGetClassEv
// TODO     60 B  EffectAnimRig_LinkedTileConnect::EffectAnimRig_LinkedTileConnect _ZN31EffectAnimRig_LinkedTileConnectC2Ev
// TODO     60 B  EffectAnimRig_LinkedTileConnect::EffectAnimRig_LinkedTileConnect _ZN31EffectAnimRig_LinkedTileConnectC1Ev
// TODO     44 B  EffectAnimRig_LinkedTileConnect::StaticNew           _ZN31EffectAnimRig_LinkedTileConnect9StaticNewEv
// TODO     36 B  EffectAnimRig_LinkedTileConnect::onPopAnimInitialized _ZN31EffectAnimRig_LinkedTileConnect20onPopAnimInitializedEv
// TODO     36 B  EffectAnimRig_LinkedTileConnect::~EffectAnimRig_LinkedTileConnect _ZN31EffectAnimRig_LinkedTileConnectD0Ev
// TODO     28 B  EffectAnimRig_LinkedTileConnect::~EffectAnimRig_LinkedTileConnect _ZN31EffectAnimRig_LinkedTileConnectD2Ev
// TODO     28 B  EffectAnimRig_LinkedTileConnect::~EffectAnimRig_LinkedTileConnect _ZN31EffectAnimRig_LinkedTileConnectD1Ev
// TODO     16 B  EffectAnimRig_LinkedTileConnect::onAnimStopped       _ZN31EffectAnimRig_LinkedTileConnect13onAnimStoppedEv
