// PvZ2/effects/anim/EffectAnimRig_FirePeashooterFireSquare.cpp
//
// 17 function(s), 1824 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: EffectAnimRig_FirePeashooterFireSquare
//
// TODO    420 B  EffectAnimRig_FirePeashooterFireSquare::playDelayedAnimationSequence _ZN38EffectAnimRig_FirePeashooterFireSquare28playDelayedAnimationSequenceEv
// TODO    280 B  EffectAnimRig_FirePeashooterFireSquare::onFireSequenceContinued _ZN38EffectAnimRig_FirePeashooterFireSquare23onFireSequenceContinuedERKSsS1_i
// TODO    180 B  EffectAnimRig_FirePeashooterFireSquare::StaticClassInit _ZN38EffectAnimRig_FirePeashooterFireSquare15StaticClassInitEv
// TODO    124 B  EffectAnimRig_FirePeashooterFireSquare::StaticGetClass _ZN38EffectAnimRig_FirePeashooterFireSquare14StaticGetClassEv
// TODO    116 B  EffectAnimRig_FirePeashooterFireSquare::SetOwningEffect _ZN38EffectAnimRig_FirePeashooterFireSquare15SetOwningEffectEP14Effect_PopAnim
// TODO    100 B  EffectAnimRig_FirePeashooterFireSquare::onUpdate     _ZN38EffectAnimRig_FirePeashooterFireSquare8onUpdateEv
// TODO     80 B  EffectAnimRig_FirePeashooterFireSquare::EffectAnimRig_FirePeashooterFireSquare _ZN38EffectAnimRig_FirePeashooterFireSquareC2Ev
// TODO     80 B  EffectAnimRig_FirePeashooterFireSquare::EffectAnimRig_FirePeashooterFireSquare _ZN38EffectAnimRig_FirePeashooterFireSquareC1Ev
// TODO     68 B  EffectAnimRig_FirePeashooterFireSquare::onFireSequenceEnded _ZN38EffectAnimRig_FirePeashooterFireSquare19onFireSequenceEndedERKSsS1_i
// TODO     64 B  EffectAnimRig_FirePeashooterFireSquare::~EffectAnimRig_FirePeashooterFireSquare _ZN38EffectAnimRig_FirePeashooterFireSquareD2Ev
// TODO     64 B  EffectAnimRig_FirePeashooterFireSquare::~EffectAnimRig_FirePeashooterFireSquare _ZN38EffectAnimRig_FirePeashooterFireSquareD1Ev
// TODO     48 B  EffectAnimRig_FirePeashooterFireSquare::determineActivationTime _ZN38EffectAnimRig_FirePeashooterFireSquare23determineActivationTimeEf
// TODO     44 B  EffectAnimRig_FirePeashooterFireSquare::StaticNew    _ZN38EffectAnimRig_FirePeashooterFireSquare9StaticNewEv
// TODO     44 B  EffectAnimRig_FirePeashooterFireSquare::onPopAnimInitialized _ZN38EffectAnimRig_FirePeashooterFireSquare20onPopAnimInitializedEv
// TODO     40 B  EffectAnimRig_FirePeashooterFireSquare::StopPlayingFireEffect _ZN38EffectAnimRig_FirePeashooterFireSquare21StopPlayingFireEffectEf
// TODO     36 B  EffectAnimRig_FirePeashooterFireSquare::~EffectAnimRig_FirePeashooterFireSquare _ZN38EffectAnimRig_FirePeashooterFireSquareD0Ev
// TODO     36 B  EffectAnimRig_FirePeashooterFireSquare::StartPlayingFireEffect _ZN38EffectAnimRig_FirePeashooterFireSquare22StartPlayingFireEffectEf
