// PvZ2/effects/anim/EffectAnimRig_HotDateFireSquare.cpp
//
// 10 function(s), 1124 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: EffectAnimRig_HotDateFireSquare
//
// TODO    412 B  EffectAnimRig_HotDateFireSquare::onFireEnd           _ZN31EffectAnimRig_HotDateFireSquare9onFireEndEv
// TODO    180 B  EffectAnimRig_HotDateFireSquare::StaticClassInit     _ZN31EffectAnimRig_HotDateFireSquare15StaticClassInitEv
// TODO    124 B  EffectAnimRig_HotDateFireSquare::StaticGetClass      _ZN31EffectAnimRig_HotDateFireSquare14StaticGetClassEv
// TODO     84 B  EffectAnimRig_HotDateFireSquare::EffectAnimRig_HotDateFireSquare _ZN31EffectAnimRig_HotDateFireSquareC2Ev
// TODO     84 B  EffectAnimRig_HotDateFireSquare::EffectAnimRig_HotDateFireSquare _ZN31EffectAnimRig_HotDateFireSquareC1Ev
// TODO     64 B  EffectAnimRig_HotDateFireSquare::~EffectAnimRig_HotDateFireSquare _ZN31EffectAnimRig_HotDateFireSquareD2Ev
// TODO     64 B  EffectAnimRig_HotDateFireSquare::~EffectAnimRig_HotDateFireSquare _ZN31EffectAnimRig_HotDateFireSquareD1Ev
// TODO     44 B  EffectAnimRig_HotDateFireSquare::StaticNew           _ZN31EffectAnimRig_HotDateFireSquare9StaticNewEv
// TODO     36 B  EffectAnimRig_HotDateFireSquare::~EffectAnimRig_HotDateFireSquare _ZN31EffectAnimRig_HotDateFireSquareD0Ev
// TODO     32 B  EffectAnimRig_HotDateFireSquare::setLastFireInfo     _ZN31EffectAnimRig_HotDateFireSquare15setLastFireInfoEffN4Sexy5PointENS0_9RtWeakPtrI5PlantEE
