// PvZ2/effects/anim/EffectAnimRig_EndLevel.cpp
//
// 19 function(s), 2080 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: EffectAnimRig_EndLevel
//
// TODO    404 B  EffectAnimRig_EndLevel::setAchieveStarNum            _ZN22EffectAnimRig_EndLevel17setAchieveStarNumEi
// TODO    208 B  EffectAnimRig_EndLevel::onPopAnimCommand             _ZN22EffectAnimRig_EndLevel16onPopAnimCommandEfRKSsS1_
// TODO    184 B  EffectAnimRig_EndLevel::playWindowsOut               _ZN22EffectAnimRig_EndLevel14playWindowsOutEv
// TODO    180 B  EffectAnimRig_EndLevel::StaticClassInit              _ZN22EffectAnimRig_EndLevel15StaticClassInitEv
// TODO    172 B  EffectAnimRig_EndLevel::WindowsInAnimStop            _ZN22EffectAnimRig_EndLevel17WindowsInAnimStopEv
// TODO    164 B  EffectAnimRig_EndLevel::playWindowsIn                _ZN22EffectAnimRig_EndLevel13playWindowsInEv
// TODO    124 B  EffectAnimRig_EndLevel::StaticGetClass               _ZN22EffectAnimRig_EndLevel14StaticGetClassEv
// TODO    124 B  EffectAnimRig_EndLevel::onAnimStopped                _ZN22EffectAnimRig_EndLevel13onAnimStoppedEv
// TODO     92 B  EffectAnimRig_EndLevel::EffectAnimRig_EndLevel       _ZN22EffectAnimRig_EndLevelC2Ev
// TODO     92 B  EffectAnimRig_EndLevel::EffectAnimRig_EndLevel       _ZN22EffectAnimRig_EndLevelC1Ev
// TODO     76 B  EffectAnimRig_EndLevel::EndLevel                     _ZN22EffectAnimRig_EndLevel8EndLevelEv
// TODO     64 B  EffectAnimRig_EndLevel::setParentEndLevelUI          _ZN22EffectAnimRig_EndLevel19setParentEndLevelUIEP10EndLevelUI
// TODO     44 B  EffectAnimRig_EndLevel::StaticNew                    _ZN22EffectAnimRig_EndLevel9StaticNewEv
// TODO     36 B  EffectAnimRig_EndLevel::~EffectAnimRig_EndLevel      _ZN22EffectAnimRig_EndLevelD0Ev
// TODO     36 B  EffectAnimRig_EndLevel::onBoxOutAnimStopped          _ZN22EffectAnimRig_EndLevel19onBoxOutAnimStoppedEv
// TODO     28 B  EffectAnimRig_EndLevel::~EffectAnimRig_EndLevel      _ZN22EffectAnimRig_EndLevelD2Ev
// TODO     28 B  EffectAnimRig_EndLevel::~EffectAnimRig_EndLevel      _ZN22EffectAnimRig_EndLevelD1Ev
// TODO     12 B  EffectAnimRig_EndLevel::adjustParentSize             _ZN22EffectAnimRig_EndLevel16adjustParentSizeEii
// TODO     12 B  EffectAnimRig_EndLevel::WindowsOutAnimStop           _ZN22EffectAnimRig_EndLevel18WindowsOutAnimStopEv
