// PvZ2/effects/anim/EffectAnimRig_SpikeweedSaw.cpp
//
// 13 function(s), 1124 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: EffectAnimRig_SpikeweedSaw
//
// TODO    180 B  EffectAnimRig_SpikeweedSaw::StaticClassInit          _ZN26EffectAnimRig_SpikeweedSaw15StaticClassInitEv
// TODO    176 B  EffectAnimRig_SpikeweedSaw::PlayDeath                _ZN26EffectAnimRig_SpikeweedSaw9PlayDeathEv
// TODO    172 B  EffectAnimRig_SpikeweedSaw::PlayRise                 _ZN26EffectAnimRig_SpikeweedSaw8PlayRiseEv
// TODO    172 B  EffectAnimRig_SpikeweedSaw::PlayIdle                 _ZN26EffectAnimRig_SpikeweedSaw8PlayIdleEv
// TODO    124 B  EffectAnimRig_SpikeweedSaw::StaticGetClass           _ZN26EffectAnimRig_SpikeweedSaw14StaticGetClassEv
// TODO     56 B  EffectAnimRig_SpikeweedSaw::EffectAnimRig_SpikeweedSaw _ZN26EffectAnimRig_SpikeweedSawC2Ev
// TODO     56 B  EffectAnimRig_SpikeweedSaw::EffectAnimRig_SpikeweedSaw _ZN26EffectAnimRig_SpikeweedSawC1Ev
// TODO     44 B  EffectAnimRig_SpikeweedSaw::StaticNew                _ZN26EffectAnimRig_SpikeweedSaw9StaticNewEv
// TODO     36 B  EffectAnimRig_SpikeweedSaw::onPopAnimInitialized     _ZN26EffectAnimRig_SpikeweedSaw20onPopAnimInitializedEv
// TODO     36 B  EffectAnimRig_SpikeweedSaw::~EffectAnimRig_SpikeweedSaw _ZN26EffectAnimRig_SpikeweedSawD0Ev
// TODO     28 B  EffectAnimRig_SpikeweedSaw::~EffectAnimRig_SpikeweedSaw _ZN26EffectAnimRig_SpikeweedSawD2Ev
// TODO     28 B  EffectAnimRig_SpikeweedSaw::~EffectAnimRig_SpikeweedSaw _ZN26EffectAnimRig_SpikeweedSawD1Ev
// TODO     16 B  EffectAnimRig_SpikeweedSaw::onAnimStopped            _ZN26EffectAnimRig_SpikeweedSaw13onAnimStoppedEv
