// PvZ2/effects/anim/EffectAnimRig_EndLevelBox.cpp
//
// 22 function(s), 6944 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: EffectAnimRig_EndLevelBox
//
// TODO   2004 B  EffectAnimRig_EndLevelBox::hardLevelAward            _ZN25EffectAnimRig_EndLevelBox14hardLevelAwardEPK13HardAwardItem
// TODO    644 B  EffectAnimRig_EndLevelBox::onPostDraw                _ZN25EffectAnimRig_EndLevelBox10onPostDrawEPN4Sexy8GraphicsE
// TODO    640 B  EffectAnimRig_EndLevelBox::SetAwardImageAndScale     _ZN25EffectAnimRig_EndLevelBox21SetAwardImageAndScaleEPK13HardAwardItemRPN4Sexy5ImageERf
// TODO    616 B  EffectAnimRig_EndLevelBox::GetAwardBoxByRand         _ZN25EffectAnimRig_EndLevelBox17GetAwardBoxByRandERKSsb
// TODO    328 B  EffectAnimRig_EndLevelBox::showHardAward             _ZN25EffectAnimRig_EndLevelBox13showHardAwardEv
// TODO    296 B  EffectAnimRig_EndLevelBox::initHardAwardItems        _ZN25EffectAnimRig_EndLevelBox18initHardAwardItemsERKSsb
// TODO    264 B  EffectAnimRig_EndLevelBox::~EffectAnimRig_EndLevelBox _ZN25EffectAnimRig_EndLevelBoxD2Ev
// TODO    264 B  EffectAnimRig_EndLevelBox::~EffectAnimRig_EndLevelBox _ZN25EffectAnimRig_EndLevelBoxD1Ev
// TODO    252 B  EffectAnimRig_EndLevelBox::adjustParentSize          _ZN25EffectAnimRig_EndLevelBox16adjustParentSizeEii
// TODO    248 B  EffectAnimRig_EndLevelBox::collectHardAward          _ZN25EffectAnimRig_EndLevelBox16collectHardAwardEv
// TODO    196 B  EffectAnimRig_EndLevelBox::EffectAnimRig_EndLevelBox _ZN25EffectAnimRig_EndLevelBoxC2Ev
// TODO    196 B  EffectAnimRig_EndLevelBox::EffectAnimRig_EndLevelBox _ZN25EffectAnimRig_EndLevelBoxC1Ev
// TODO    180 B  EffectAnimRig_EndLevelBox::StaticClassInit           _ZN25EffectAnimRig_EndLevelBox15StaticClassInitEv
// TODO    164 B  EffectAnimRig_EndLevelBox::playBoxCome               _ZN25EffectAnimRig_EndLevelBox11playBoxComeEv
// TODO    124 B  EffectAnimRig_EndLevelBox::StaticGetClass            _ZN25EffectAnimRig_EndLevelBox14StaticGetClassEv
// TODO    112 B  EffectAnimRig_EndLevelBox::onAnimStopped             _ZN25EffectAnimRig_EndLevelBox13onAnimStoppedEv
// TODO    112 B  EffectAnimRig_EndLevelBox::GetCurrentLevel           _ZN25EffectAnimRig_EndLevelBox15GetCurrentLevelEv
// TODO     80 B  EffectAnimRig_EndLevelBox::initHardAwardItems        _ZN25EffectAnimRig_EndLevelBox18initHardAwardItemsEv
// TODO     72 B  EffectAnimRig_EndLevelBox::onPopAnimCommand          _ZN25EffectAnimRig_EndLevelBox16onPopAnimCommandEfRKSsS1_
// TODO     72 B  EffectAnimRig_EndLevelBox::onUpdate                  _ZN25EffectAnimRig_EndLevelBox8onUpdateEv
// TODO     44 B  EffectAnimRig_EndLevelBox::StaticNew                 _ZN25EffectAnimRig_EndLevelBox9StaticNewEv
// TODO     36 B  EffectAnimRig_EndLevelBox::~EffectAnimRig_EndLevelBox _ZN25EffectAnimRig_EndLevelBoxD0Ev
