// PvZ2/effects/anim/EffectAnimRig_IceHole.cpp
//
// 10 function(s), 888 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: EffectAnimRig_IceHole
//
// TODO    180 B  EffectAnimRig_IceHole::StaticClassInit               _ZN21EffectAnimRig_IceHole15StaticClassInitEv
// TODO    168 B  EffectAnimRig_IceHole::PlayFoodIn                    _ZN21EffectAnimRig_IceHole10PlayFoodInEN4Sexy9Delegate1IRKSsEE
// TODO    168 B  EffectAnimRig_IceHole::PlayFood                      _ZN21EffectAnimRig_IceHole8PlayFoodEN4Sexy9Delegate1IRKSsEE
// TODO    124 B  EffectAnimRig_IceHole::StaticGetClass                _ZN21EffectAnimRig_IceHole14StaticGetClassEv
// TODO     56 B  EffectAnimRig_IceHole::EffectAnimRig_IceHole         _ZN21EffectAnimRig_IceHoleC2Ev
// TODO     56 B  EffectAnimRig_IceHole::EffectAnimRig_IceHole         _ZN21EffectAnimRig_IceHoleC1Ev
// TODO     44 B  EffectAnimRig_IceHole::StaticNew                     _ZN21EffectAnimRig_IceHole9StaticNewEv
// TODO     36 B  EffectAnimRig_IceHole::~EffectAnimRig_IceHole        _ZN21EffectAnimRig_IceHoleD0Ev
// TODO     28 B  EffectAnimRig_IceHole::~EffectAnimRig_IceHole        _ZN21EffectAnimRig_IceHoleD2Ev
// TODO     28 B  EffectAnimRig_IceHole::~EffectAnimRig_IceHole        _ZN21EffectAnimRig_IceHoleD1Ev
