// PvZ2/zombies/LostCityJane/ZombieLostCityJane.cpp
//
// 17 function(s), 1620 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieLostCityJane, ZombieLostCityJaneProps
//
// TODO    412 B  ZombieLostCityJane::OverrideProjectileCollision      _ZN18ZombieLostCityJane27OverrideProjectileCollisionEP10Projectile
// TODO    180 B  ZombieLostCityJane::StaticClassInit                  _ZN18ZombieLostCityJane15StaticClassInitEv
// TODO    180 B  ZombieLostCityJaneProps::StaticClassInit             _ZN23ZombieLostCityJaneProps15StaticClassInitEv
// TODO    124 B  ZombieLostCityJane::StaticGetClass                   _ZN18ZombieLostCityJane14StaticGetClassEv
// TODO    124 B  ZombieLostCityJaneProps::StaticGetClass              _ZN23ZombieLostCityJaneProps14StaticGetClassEv
// TODO     80 B  ZombieLostCityJaneProps::ZombieLostCityJaneProps     _ZN23ZombieLostCityJanePropsC2Ev
// TODO     80 B  ZombieLostCityJaneProps::ZombieLostCityJaneProps     _ZN23ZombieLostCityJanePropsC1Ev
// TODO     56 B  ZombieLostCityJane::ZombieLostCityJane               _ZN18ZombieLostCityJaneC2Ev
// TODO     56 B  ZombieLostCityJane::ZombieLostCityJane               _ZN18ZombieLostCityJaneC1Ev
// TODO     56 B  ZombieLostCityJaneProps::~ZombieLostCityJaneProps    _ZN23ZombieLostCityJanePropsD2Ev
// TODO     56 B  ZombieLostCityJaneProps::~ZombieLostCityJaneProps    _ZN23ZombieLostCityJanePropsD1Ev
// TODO     44 B  ZombieLostCityJane::StaticNew                        _ZN18ZombieLostCityJane9StaticNewEv
// TODO     44 B  ZombieLostCityJaneProps::StaticNew                   _ZN23ZombieLostCityJaneProps9StaticNewEv
// TODO     36 B  ZombieLostCityJane::~ZombieLostCityJane              _ZN18ZombieLostCityJaneD0Ev
// TODO     36 B  ZombieLostCityJaneProps::~ZombieLostCityJaneProps    _ZN23ZombieLostCityJanePropsD0Ev
// TODO     28 B  ZombieLostCityJane::~ZombieLostCityJane              _ZN18ZombieLostCityJaneD2Ev
// TODO     28 B  ZombieLostCityJane::~ZombieLostCityJane              _ZN18ZombieLostCityJaneD1Ev
