// PvZ2/zombies/FairyTaleWitch/ZombieAnimRig_FairyTaleWitch.cpp
//
// 11 function(s), 1608 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieAnimRig_FairyTaleWitch
//
// TODO    376 B  ZombieAnimRig_FairyTaleWitch::getHeadLayerNames      _ZN28ZombieAnimRig_FairyTaleWitch17getHeadLayerNamesEv
// TODO    320 B  ZombieAnimRig_FairyTaleWitch::getArmLayerNames       _ZN28ZombieAnimRig_FairyTaleWitch16getArmLayerNamesEv
// TODO    320 B  ZombieAnimRig_FairyTaleWitch::getArmReplacementPairNames _ZN28ZombieAnimRig_FairyTaleWitch26getArmReplacementPairNamesEv
// TODO    224 B  ZombieAnimRig_FairyTaleWitch::StartCasting           _ZN28ZombieAnimRig_FairyTaleWitch12StartCastingE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    120 B  ZombieAnimRig_FairyTaleWitch::StaticGetClass         _ZN28ZombieAnimRig_FairyTaleWitch14StaticGetClassEv
// TODO     56 B  ZombieAnimRig_FairyTaleWitch::ZombieAnimRig_FairyTaleWitch _ZN28ZombieAnimRig_FairyTaleWitchC2Ev
// TODO     56 B  ZombieAnimRig_FairyTaleWitch::ZombieAnimRig_FairyTaleWitch _ZN28ZombieAnimRig_FairyTaleWitchC1Ev
// TODO     44 B  ZombieAnimRig_FairyTaleWitch::StaticNew              _ZN28ZombieAnimRig_FairyTaleWitch9StaticNewEv
// TODO     36 B  ZombieAnimRig_FairyTaleWitch::~ZombieAnimRig_FairyTaleWitch _ZN28ZombieAnimRig_FairyTaleWitchD0Ev
// TODO     28 B  ZombieAnimRig_FairyTaleWitch::~ZombieAnimRig_FairyTaleWitch _ZN28ZombieAnimRig_FairyTaleWitchD2Ev
// TODO     28 B  ZombieAnimRig_FairyTaleWitch::~ZombieAnimRig_FairyTaleWitch _ZN28ZombieAnimRig_FairyTaleWitchD1Ev
