// PvZ2/zombies/Chicken/ZombieChicken.cpp
//
// 26 function(s), 2316 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieChicken, ZombieChickenProps
//
// TODO    460 B  ZombieChicken::playBirdLossAnimation                 _ZN13ZombieChicken21playBirdLossAnimationEb
// TODO    336 B  ZombieChicken::updateState_Walk                      _ZN13ZombieChicken16updateState_WalkEv
// TODO    180 B  ZombieChicken::StaticClassInit                       _ZN13ZombieChicken15StaticClassInitEv
// TODO    180 B  ZombieChickenProps::StaticClassInit                  _ZN18ZombieChickenProps15StaticClassInitEv
// TODO    132 B  ZombieChicken::onEnterState_Walk                     _ZN13ZombieChicken17onEnterState_WalkE11ZombieState
// TODO    124 B  ZombieChicken::StaticGetClass                        _ZN13ZombieChicken14StaticGetClassEv
// TODO    124 B  ZombieChickenProps::StaticGetClass                   _ZN18ZombieChickenProps14StaticGetClassEv
// TODO    108 B  ZombieChicken::onElectrocuted                        _ZN13ZombieChicken14onElectrocutedEv
// TODO     72 B  ZombieChickenProps::ZombieChickenProps               _ZN18ZombieChickenPropsC2Ev
// TODO     72 B  ZombieChickenProps::ZombieChickenProps               _ZN18ZombieChickenPropsC1Ev
// TODO     60 B  ZombieChicken::onTakeFatalDamage                     _ZN13ZombieChicken17onTakeFatalDamageERK10DamageInfo
// TODO     56 B  ZombieChicken::ZombieChicken                         _ZN13ZombieChickenC2Ev
// TODO     56 B  ZombieChicken::ZombieChicken                         _ZN13ZombieChickenC1Ev
// TODO     56 B  ZombieChickenProps::~ZombieChickenProps              _ZN18ZombieChickenPropsD2Ev
// TODO     56 B  ZombieChickenProps::~ZombieChickenProps              _ZN18ZombieChickenPropsD1Ev
// TODO     44 B  ZombieChicken::StaticNew                             _ZN13ZombieChicken9StaticNewEv
// TODO     44 B  ZombieChickenProps::StaticNew                        _ZN18ZombieChickenProps9StaticNewEv
// TODO     36 B  ZombieChicken::~ZombieChicken                        _ZN13ZombieChickenD0Ev
// TODO     36 B  ZombieChickenProps::~ZombieChickenProps              _ZN18ZombieChickenPropsD0Ev
// TODO     28 B  ZombieChicken::~ZombieChicken                        _ZN13ZombieChickenD2Ev
// TODO     28 B  ZombieChicken::~ZombieChicken                        _ZN13ZombieChickenD1Ev
// TODO      8 B  ZombieChicken::willDieToShrinking                    _ZN13ZombieChicken18willDieToShrinkingEv
// TODO      8 B  ZombieChicken::GetAmberScale                         _ZN13ZombieChicken13GetAmberScaleEv
// TODO      4 B  ZombieChicken::onTurnedToAsh                         _ZN13ZombieChicken13onTurnedToAshEv
// TODO      4 B  ZombieChicken::onExitState_Walk                      _ZN13ZombieChicken16onExitState_WalkE11ZombieState
// TODO      4 B  ZombieChicken::CreateZombieLevelEffect               _ZN13ZombieChicken23CreateZombieLevelEffectEb
