// PvZ2/plants/ThymeWarp/Plant_ThymeWarp.cpp
//
// 38 function(s), 6784 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantThymeWarp
//
// TODO    900 B  PlantThymeWarp::UpdateActions                        _ZN14PlantThymeWarp13UpdateActionsEv
// TODO    440 B  PlantThymeWarp::findTargetsForWarp                   _ZN14PlantThymeWarp18findTargetsForWarpEv
// TODO    420 B  PlantThymeWarp::warpZombieOut                        _ZN14PlantThymeWarp13warpZombieOutEN4Sexy9RtWeakPtrI6ZombieEE
// TODO    376 B  PlantThymeWarp::createQuickKillEffectAt              _ZN14PlantThymeWarp23createQuickKillEffectAtEN4Sexy9RtWeakPtrI6ZombieEESs
// TODO    368 B  PlantThymeWarp::startDisapearingZombies              _ZN14PlantThymeWarp23startDisapearingZombiesEv
// TODO    356 B  PlantThymeWarp::createWarpingEffectAt                _ZN14PlantThymeWarp21createWarpingEffectAtEN4Sexy9RtWeakPtrI6ZombieEESs
// TODO    352 B  PlantThymeWarp::onKilled                             _ZN14PlantThymeWarp8onKilledEb
// TODO    312 B  PlantThymeWarp::shouldDoStuffTo                      _ZN14PlantThymeWarp15shouldDoStuffToEN4Sexy9RtWeakPtrI6ZombieEE
// TODO    252 B  PlantThymeWarp::startDancing                         _ZN14PlantThymeWarp12startDancingEv
// TODO    252 B  PlantThymeWarp::warpZombieIn                         _ZN14PlantThymeWarp12warpZombieInEN4Sexy9RtWeakPtrI6ZombieEE
// TODO    244 B  PlantThymeWarp::startWarpingZombiesOut               _ZN14PlantThymeWarp22startWarpingZombiesOutEv
// TODO    240 B  PlantThymeWarp::startWarpingZombiesIn                _ZN14PlantThymeWarp21startWarpingZombiesInEv
// TODO    208 B  PlantThymeWarp::placeZombieInNewPosition             _ZN14PlantThymeWarp24placeZombieInNewPositionEN4Sexy9RtWeakPtrI6ZombieEE
// TODO    188 B  PlantThymeWarp::getWarpingEffectNameFor              _ZN14PlantThymeWarp23getWarpingEffectNameForEN4Sexy9RtWeakPtrI6ZombieEE
// TODO    180 B  PlantThymeWarp::StaticClassInit                      _ZN14PlantThymeWarp15StaticClassInitEv
// TODO    180 B  PlantThymeWarp::reapearZombie                        _ZN14PlantThymeWarp13reapearZombieEN4Sexy9RtWeakPtrI6ZombieEE
// TODO    164 B  PlantThymeWarp::healZombie                           _ZN14PlantThymeWarp10healZombieEN4Sexy9RtWeakPtrI6ZombieEE
// TODO    160 B  PlantThymeWarp::createWarpingOutEffectAt             _ZN14PlantThymeWarp24createWarpingOutEffectAtEN4Sexy9RtWeakPtrI6ZombieEE
// TODO    160 B  PlantThymeWarp::createWarpingInEffectAt              _ZN14PlantThymeWarp23createWarpingInEffectAtEN4Sexy9RtWeakPtrI6ZombieEE
// TODO    124 B  PlantThymeWarp::StaticGetClass                       _ZN14PlantThymeWarp14StaticGetClassEv
// TODO    112 B  PlantThymeWarp::Initialize                           _ZN14PlantThymeWarp10InitializeEv
// TODO    104 B  PlantThymeWarp::disapearZombie                       _ZN14PlantThymeWarp14disapearZombieEN4Sexy9RtWeakPtrI6ZombieEE
// TODO     76 B  PlantThymeWarp::onAnimStoppedCallback                _ZN14PlantThymeWarp21onAnimStoppedCallbackERKSs
// TODO     68 B  PlantThymeWarp::shouldWarpZombiesOut                 _ZN14PlantThymeWarp20shouldWarpZombiesOutEv
// TODO     68 B  PlantThymeWarp::shouldDisapearZombies                _ZN14PlantThymeWarp21shouldDisapearZombiesEv
// TODO     68 B  PlantThymeWarp::shouldWarpZombiesIn                  _ZN14PlantThymeWarp19shouldWarpZombiesInEv
// TODO     60 B  PlantThymeWarp::shouldStartDance                     _ZN14PlantThymeWarp16shouldStartDanceEv
// TODO     60 B  PlantThymeWarp::PlantThymeWarp                       _ZN14PlantThymeWarpC2Ev
// TODO     60 B  PlantThymeWarp::PlantThymeWarp                       _ZN14PlantThymeWarpC1Ev
// TODO     60 B  PlantThymeWarp::~PlantThymeWarp                      _ZN14PlantThymeWarpD2Ev
// TODO     60 B  PlantThymeWarp::~PlantThymeWarp                      _ZN14PlantThymeWarpD1Ev
// TODO     44 B  PlantThymeWarp::StaticNew                            _ZN14PlantThymeWarp9StaticNewEv
// TODO     36 B  PlantThymeWarp::~PlantThymeWarp                      _ZN14PlantThymeWarpD0Ev
// TODO      8 B  PlantThymeWarp::HasShadow                            _ZN14PlantThymeWarp9HasShadowEv
// TODO      8 B  PlantThymeWarp::CanBeShoveled                        _ZN14PlantThymeWarp13CanBeShoveledEv
// TODO      8 B  PlantThymeWarp::CanBeTargeted                        _ZN14PlantThymeWarp13CanBeTargetedEv
// TODO      4 B  PlantThymeWarp::TakeSmashAttack                      _ZN14PlantThymeWarp15TakeSmashAttackEN4Sexy9RtWeakPtrI6ZombieEE
// TODO      4 B  PlantThymeWarp::quickKillZombie                      _ZN14PlantThymeWarp15quickKillZombieEN4Sexy9RtWeakPtrI6ZombieEE
