// PvZ2/dinosaur/DinosaurRunner.cpp
//
// 52 function(s), 5800 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: DinosaurRunner, DinosaurRunnerPropertySheet
//
// TODO    812 B  DinosaurRunner::StaticClassInit                      _ZN14DinosaurRunner15StaticClassInitEv
// TODO    448 B  DinosaurRunner::FindTargetZombie                     _ZN14DinosaurRunner16FindTargetZombieEv
// TODO    384 B  DinosaurRunner::GenerateSmoke                        _ZN14DinosaurRunner13GenerateSmokeERKSsff
// TODO    264 B  DinosaurRunner::FindTargetPlant                      _ZN14DinosaurRunner15FindTargetPlantEv
// TODO    252 B  DinosaurRunner::updateState_RunLeft                  _ZN14DinosaurRunner19updateState_RunLeftEv
// TODO    244 B  DinosaurRunner::onEnterState_TurnLeftToRight         _ZN14DinosaurRunner28onEnterState_TurnLeftToRightE15DinoRunnerState
// TODO    232 B  DinosaurRunner::updateState_RunRight                 _ZN14DinosaurRunner20updateState_RunRightEv
// TODO    224 B  DinosaurRunner::updateState_TurnLeftToRight          _ZN14DinosaurRunner27updateState_TurnLeftToRightEv
// TODO    220 B  DinosaurRunner::onEnterState_RunRight                _ZN14DinosaurRunner21onEnterState_RunRightE15DinoRunnerState
// TODO    184 B  DinosaurRunner::onPlaceOnBoard                       _ZN14DinosaurRunner14onPlaceOnBoardEv
// TODO    180 B  DinosaurRunnerPropertySheet::StaticClassInit         _ZN27DinosaurRunnerPropertySheet15StaticClassInitEv
// TODO    164 B  DinosaurRunner::Move                                 _ZN14DinosaurRunner4MoveEff
// TODO    160 B  DinosaurRunner::SetRunRight                          _ZN14DinosaurRunner11SetRunRightEf
// TODO    152 B  DinosaurRunnerPropertySheet::DinosaurRunnerPropertySheet _ZN27DinosaurRunnerPropertySheetC2Ev
// TODO    152 B  DinosaurRunnerPropertySheet::DinosaurRunnerPropertySheet _ZN27DinosaurRunnerPropertySheetC1Ev
// TODO    140 B  DinosaurRunner::IsInTargetHistory                    _ZN14DinosaurRunner17IsInTargetHistoryEN4Sexy9RtWeakPtrI11BoardEntityEE
// TODO    124 B  DinosaurRunner::StaticGetClass                       _ZN14DinosaurRunner14StaticGetClassEv
// TODO    124 B  DinosaurRunner::isValidZombieTarget                  _ZN14DinosaurRunner19isValidZombieTargetEP6Zombie
// TODO    124 B  DinosaurRunner::onEnterState_RunLeft                 _ZN14DinosaurRunner20onEnterState_RunLeftE15DinoRunnerState
// TODO    124 B  DinosaurRunnerPropertySheet::StaticGetClass          _ZN27DinosaurRunnerPropertySheet14StaticGetClassEv
// TODO     88 B  DinosaurRunner::AddToHistoryTargets                  _ZN14DinosaurRunner19AddToHistoryTargetsEN4Sexy9RtWeakPtrI11BoardEntityEE
// TODO     80 B  DinosaurRunner::onTurnLeftToRightAnimDone            _ZN14DinosaurRunner25onTurnLeftToRightAnimDoneERKSs
// TODO     68 B  DinosaurRunner::CanBeScaredAway                      _ZN14DinosaurRunner15CanBeScaredAwayEv
// TODO     68 B  DinosaurRunner::DinosaurRunner                       _ZN14DinosaurRunnerC2Ev
// TODO     68 B  DinosaurRunner::DinosaurRunner                       _ZN14DinosaurRunnerC1Ev
// TODO     64 B  DinosaurRunner::onEnterState_Idle                    _ZN14DinosaurRunner17onEnterState_IdleE13CreatureState
// TODO     64 B  DinosaurRunner::~DinosaurRunner                      _ZN14DinosaurRunnerD2Ev
// TODO     64 B  DinosaurRunner::~DinosaurRunner                      _ZN14DinosaurRunnerD1Ev
// TODO     60 B  DinosaurRunner::TurnLeftToRight                      _ZN14DinosaurRunner15TurnLeftToRightEv
// TODO     56 B  DinosaurRunner::GetSmokeRenderOrder                  _ZN14DinosaurRunner19GetSmokeRenderOrderEv
// TODO     56 B  DinosaurRunner::updateState_Idle                     _ZN14DinosaurRunner16updateState_IdleEv
// TODO     44 B  DinosaurRunner::StaticNew                            _ZN14DinosaurRunner9StaticNewEv
// TODO     44 B  DinosaurRunnerPropertySheet::StaticNew               _ZN27DinosaurRunnerPropertySheet9StaticNewEv
// TODO     36 B  DinosaurRunner::~DinosaurRunner                      _ZN14DinosaurRunnerD0Ev
// TODO     36 B  DinosaurRunnerPropertySheet::~DinosaurRunnerPropertySheet _ZN27DinosaurRunnerPropertySheetD0Ev
// TODO     20 B  DinosaurRunner::CanAttackPlants                      _ZN14DinosaurRunner15CanAttackPlantsEv
// TODO     20 B  DinosaurRunner::CanAttackZombies                     _ZN14DinosaurRunner16CanAttackZombiesEv
// TODO     20 B  DinosaurRunner::GetSmokeOffsetY                      _ZN14DinosaurRunner15GetSmokeOffsetYEv
// TODO     20 B  DinosaurRunnerPropertySheet::~DinosaurRunnerPropertySheet _ZN27DinosaurRunnerPropertySheetD2Ev
// TODO     20 B  DinosaurRunnerPropertySheet::~DinosaurRunnerPropertySheet _ZN27DinosaurRunnerPropertySheetD1Ev
// TODO     16 B  DinosaurRunner::NumPlantsKilledInc                   _ZN14DinosaurRunner18NumPlantsKilledIncEv
// TODO     16 B  DinosaurRunner::NumZombiesKilledInc                  _ZN14DinosaurRunner19NumZombiesKilledIncEv
// TODO     12 B  DinosaurRunner::GetSmokeTimeInterval                 _ZN14DinosaurRunner20GetSmokeTimeIntervalEv
// TODO     12 B  DinosaurRunner::GetSmokeAnimScale                    _ZN14DinosaurRunner17GetSmokeAnimScaleEv
// TODO      8 B  DinosaurRunner::CanBeCharmed                         _ZN14DinosaurRunner12CanBeCharmedEv
// TODO      8 B  DinosaurRunner::SetSmokeEnabled                      _ZN14DinosaurRunner15SetSmokeEnabledEb
// TODO      4 B  DinosaurRunner::Charm                                _ZN14DinosaurRunner5CharmEv
// TODO      4 B  DinosaurRunner::onExitState_Idle                     _ZN14DinosaurRunner16onExitState_IdleE13CreatureState
// TODO      4 B  DinosaurRunner::onExitState_RunLeft                  _ZN14DinosaurRunner19onExitState_RunLeftE15DinoRunnerState
// TODO      4 B  DinosaurRunner::onExitState_TurnLeftToRight          _ZN14DinosaurRunner27onExitState_TurnLeftToRightE15DinoRunnerState
// TODO      4 B  DinosaurRunner::onExitState_RunRight                 _ZN14DinosaurRunner20onExitState_RunRightE15DinoRunnerState
// TODO      4 B  DinosaurRunner::ScaredAway                           _ZN14DinosaurRunner10ScaredAwayEP11BoardEntity
