// PvZ2/plants/WaterRabbit/Plant_WaterRabbit.cpp
//
// 35 function(s), 7996 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantWaterRabbit
//
// TODO   1064 B  PlantWaterRabbit::thunderAttackUseAction             _ZN16PlantWaterRabbit22thunderAttackUseActionEbb
// TODO    968 B  PlantWaterRabbit::attackUseAction                    _ZN16PlantWaterRabbit15attackUseActionEv
// TODO    832 B  PlantWaterRabbit::setState                           _ZN16PlantWaterRabbit8setStateEj
// TODO    532 B  PlantWaterRabbit::onAnimStoppedCallback              _ZN16PlantWaterRabbit21onAnimStoppedCallbackERKSs
// TODO    472 B  PlantWaterRabbit::onTouchEvent                       _ZN16PlantWaterRabbit12onTouchEventERKN4Sexy5TouchE
// TODO    444 B  PlantWaterRabbit::isValidTarget                      _ZN16PlantWaterRabbit13isValidTargetEP11BoardEntity
// TODO    424 B  PlantWaterRabbit::getZombieTarget                    _ZN16PlantWaterRabbit15getZombieTargetERSt6vectorIN4Sexy9RtWeakPtrI11BoardEntityEESaIS4_EE
// TODO    344 B  PlantWaterRabbit::OnAnimCommand                      _ZN16PlantWaterRabbit13OnAnimCommandERKSsS1_
// TODO    332 B  PlantWaterRabbit::UpdateActions                      _ZN16PlantWaterRabbit13UpdateActionsEv
// TODO    256 B  PlantWaterRabbit::Initialize                         _ZN16PlantWaterRabbit10InitializeEv
// TODO    236 B  PlantWaterRabbit::registerForEvents                  _ZN16PlantWaterRabbit17registerForEventsEv
// TODO    204 B  PlantWaterRabbit::shouldChangeTarget                 _ZN16PlantWaterRabbit18shouldChangeTargetEv
// TODO    200 B  PlantWaterRabbit::findTargetAndPlayAttackAnim        _ZN16PlantWaterRabbit27findTargetAndPlayAttackAnimEv
// TODO    192 B  PlantWaterRabbit::getTarget                          _ZN16PlantWaterRabbit9getTargetERSt6vectorIN4Sexy9RtWeakPtrI11BoardEntityEESaIS4_EE
// TODO    180 B  PlantWaterRabbit::StaticClassInit                    _ZN16PlantWaterRabbit15StaticClassInitEv
// TODO    124 B  PlantWaterRabbit::StaticGetClass                     _ZN16PlantWaterRabbit14StaticGetClassEv
// TODO    112 B  PlantWaterRabbit::canKnockBack                       _ZN16PlantWaterRabbit12canKnockBackEP6Zombie
// TODO    104 B  PlantWaterRabbit::updateChiStacks                    _ZN16PlantWaterRabbit15updateChiStacksEib
// TODO     96 B  PlantWaterRabbit::GetPlantAttackRect                 _ZN16PlantWaterRabbit18GetPlantAttackRectE11PlantWeapon
// TODO     88 B  PlantWaterRabbit::CalcRenderOrder                    _ZN16PlantWaterRabbit15CalcRenderOrderEv
// TODO     84 B  PlantWaterRabbit::PlantWaterRabbit                   _ZN16PlantWaterRabbitC2Ev
// TODO     84 B  PlantWaterRabbit::PlantWaterRabbit                   _ZN16PlantWaterRabbitC1Ev
// TODO     80 B  PlantWaterRabbit::canAffectEatDPS                    _ZN16PlantWaterRabbit15canAffectEatDPSEP6Zombie
// TODO     76 B  PlantWaterRabbit::Idle                               _ZN16PlantWaterRabbit4IdleEv
// TODO     72 B  PlantWaterRabbit::DoEventCall                        _ZN16PlantWaterRabbit11DoEventCallEP10RealObject
// TODO     60 B  PlantWaterRabbit::CanBeWatered                       _ZN16PlantWaterRabbit12CanBeWateredEv
// TODO     52 B  PlantWaterRabbit::~PlantWaterRabbit                  _ZN16PlantWaterRabbitD2Ev
// TODO     52 B  PlantWaterRabbit::~PlantWaterRabbit                  _ZN16PlantWaterRabbitD1Ev
// TODO     52 B  PlantWaterRabbit::CancelPlantfood                    _ZN16PlantWaterRabbit15CancelPlantfoodEv
// TODO     48 B  PlantWaterRabbit::ApplyPlantfood                     _ZN16PlantWaterRabbit14ApplyPlantfoodEv
// TODO     44 B  PlantWaterRabbit::StaticNew                          _ZN16PlantWaterRabbit9StaticNewEv
// TODO     36 B  PlantWaterRabbit::~PlantWaterRabbit                  _ZN16PlantWaterRabbitD0Ev
// TODO     24 B  PlantWaterRabbit::unregisterForEvents                _ZN16PlantWaterRabbit19unregisterForEventsEv
// TODO     20 B  PlantWaterRabbit::CanEndPlantfood                    _ZN16PlantWaterRabbit15CanEndPlantfoodEv
// TODO      8 B  PlantWaterRabbit::CanApplyPlantfood                  _ZN16PlantWaterRabbit17CanApplyPlantfoodEv
