// PvZ2/griditems/GridItemProjectileTrap.cpp
//
// 19 function(s), 2484 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: GridItemProjectileTrap, GridItemProjectileTrapProps
//
// TODO    472 B  GridItemProjectileTrapProps::StaticClassInit         _ZN27GridItemProjectileTrapProps15StaticClassInitEv
// TODO    408 B  GridItemProjectileTrap::handleTargetCollisions       _ZN22GridItemProjectileTrap22handleTargetCollisionsERKSt6vectorIP11BoardEntitySaIS2_EE
// TODO    240 B  GridItemProjectileTrap::onUpdate                     _ZN22GridItemProjectileTrap8onUpdateEv
// TODO    180 B  GridItemProjectileTrap::StaticClassInit              _ZN22GridItemProjectileTrap15StaticClassInitEv
// TODO    176 B  GridItemProjectileTrap::onGridItemInitialize         _ZN22GridItemProjectileTrap20onGridItemInitializeEv
// TODO    136 B  GridItemProjectileTrapProps::GridItemProjectileTrapProps _ZN27GridItemProjectileTrapPropsC2Ev
// TODO    136 B  GridItemProjectileTrapProps::GridItemProjectileTrapProps _ZN27GridItemProjectileTrapPropsC1Ev
// TODO    124 B  GridItemProjectileTrap::StaticGetClass               _ZN22GridItemProjectileTrap14StaticGetClassEv
// TODO    124 B  GridItemProjectileTrapProps::StaticGetClass          _ZN27GridItemProjectileTrapProps14StaticGetClassEv
// TODO     72 B  GridItemProjectileTrapProps::~GridItemProjectileTrapProps _ZN27GridItemProjectileTrapPropsD2Ev
// TODO     72 B  GridItemProjectileTrapProps::~GridItemProjectileTrapProps _ZN27GridItemProjectileTrapPropsD1Ev
// TODO     64 B  GridItemProjectileTrap::GridItemProjectileTrap       _ZN22GridItemProjectileTrapC2Ev
// TODO     64 B  GridItemProjectileTrap::GridItemProjectileTrap       _ZN22GridItemProjectileTrapC1Ev
// TODO     44 B  GridItemProjectileTrap::StaticNew                    _ZN22GridItemProjectileTrap9StaticNewEv
// TODO     44 B  GridItemProjectileTrapProps::StaticNew               _ZN27GridItemProjectileTrapProps9StaticNewEv
// TODO     36 B  GridItemProjectileTrap::~GridItemProjectileTrap      _ZN22GridItemProjectileTrapD0Ev
// TODO     36 B  GridItemProjectileTrapProps::~GridItemProjectileTrapProps _ZN27GridItemProjectileTrapPropsD0Ev
// TODO     28 B  GridItemProjectileTrap::~GridItemProjectileTrap      _ZN22GridItemProjectileTrapD2Ev
// TODO     28 B  GridItemProjectileTrap::~GridItemProjectileTrap      _ZN22GridItemProjectileTrapD1Ev
