// PvZ2/griditems/GridItemBonfire.cpp
//
// 11 function(s), 1440 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: GridItemBonfire
//
// TODO    308 B  GridItemBonfire::onUpdate                            _ZN15GridItemBonfire8onUpdateEv
// TODO    296 B  GridItemBonfire::onGridItemInitialize                _ZN15GridItemBonfire20onGridItemInitializeEv
// TODO    284 B  GridItemBonfire::onAnimStoppedCallback               _ZN15GridItemBonfire21onAnimStoppedCallbackERKSs
// TODO    180 B  GridItemBonfire::StaticClassInit                     _ZN15GridItemBonfire15StaticClassInitEv
// TODO    124 B  GridItemBonfire::StaticGetClass                      _ZN15GridItemBonfire14StaticGetClassEv
// TODO     56 B  GridItemBonfire::GridItemBonfire                     _ZN15GridItemBonfireC2Ev
// TODO     56 B  GridItemBonfire::GridItemBonfire                     _ZN15GridItemBonfireC1Ev
// TODO     44 B  GridItemBonfire::StaticNew                           _ZN15GridItemBonfire9StaticNewEv
// TODO     36 B  GridItemBonfire::~GridItemBonfire                    _ZN15GridItemBonfireD0Ev
// TODO     28 B  GridItemBonfire::~GridItemBonfire                    _ZN15GridItemBonfireD2Ev
// TODO     28 B  GridItemBonfire::~GridItemBonfire                    _ZN15GridItemBonfireD1Ev
