// PvZ2/griditems/GridItemSliderTileAnimRig.cpp
//
// 12 function(s), 1224 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: GridItemSliderTileAnimRig
//
// TODO    180 B  GridItemSliderTileAnimRig::StaticClassInit           _ZN25GridItemSliderTileAnimRig15StaticClassInitEv
// TODO    172 B  GridItemSliderTileAnimRig::PlaySlideStart            _ZN25GridItemSliderTileAnimRig14PlaySlideStartE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    172 B  GridItemSliderTileAnimRig::PlaySlideEnd              _ZN25GridItemSliderTileAnimRig12PlaySlideEndE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    164 B  GridItemSliderTileAnimRig::PlaySlideIdle             _ZN25GridItemSliderTileAnimRig13PlaySlideIdleEv
// TODO    164 B  GridItemSliderTileAnimRig::PlaySlideLoop             _ZN25GridItemSliderTileAnimRig13PlaySlideLoopEv
// TODO    124 B  GridItemSliderTileAnimRig::StaticGetClass            _ZN25GridItemSliderTileAnimRig14StaticGetClassEv
// TODO     56 B  GridItemSliderTileAnimRig::GridItemSliderTileAnimRig _ZN25GridItemSliderTileAnimRigC2Ev
// TODO     56 B  GridItemSliderTileAnimRig::GridItemSliderTileAnimRig _ZN25GridItemSliderTileAnimRigC1Ev
// TODO     44 B  GridItemSliderTileAnimRig::StaticNew                 _ZN25GridItemSliderTileAnimRig9StaticNewEv
// TODO     36 B  GridItemSliderTileAnimRig::~GridItemSliderTileAnimRig _ZN25GridItemSliderTileAnimRigD0Ev
// TODO     28 B  GridItemSliderTileAnimRig::~GridItemSliderTileAnimRig _ZN25GridItemSliderTileAnimRigD2Ev
// TODO     28 B  GridItemSliderTileAnimRig::~GridItemSliderTileAnimRig _ZN25GridItemSliderTileAnimRigD1Ev
