// PvZ2/griditems/GridItemWaterHole.cpp
//
// 28 function(s), 5656 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: GridItemWaterHole, GridItemWaterHoleProps
//
// TODO    784 B  GridItemWaterHole::setupZombieToBeDevoured           _ZN17GridItemWaterHole23setupZombieToBeDevouredEN4Sexy9RtWeakPtrI6ZombieEE
// TODO    556 B  GridItemWaterHole::setState                          _ZN17GridItemWaterHole8setStateE22GridItemWaterHoleState
// TODO    440 B  GridItemWaterHole::canDevour                         _ZN17GridItemWaterHole9canDevourEP6Zombie
// TODO    424 B  GridItemWaterHole::onUpdate                          _ZN17GridItemWaterHole8onUpdateEv
// TODO    392 B  GridItemWaterHole::devouring                         _ZN17GridItemWaterHole9devouringEN4Sexy9RtWeakPtrI6ZombieEEf
// TODO    360 B  GridItemWaterHole::applydevour                       _ZN17GridItemWaterHole11applydevourEv
// TODO    344 B  GridItemWaterHole::playDropEffect                    _ZN17GridItemWaterHole14playDropEffectEb
// TODO    336 B  GridItemWaterHole::tryBeginDevour                    _ZN17GridItemWaterHole14tryBeginDevourEP6Zombie
// TODO    260 B  GridItemWaterHole::killZombie                        _ZN17GridItemWaterHole10killZombieEN4Sexy9RtWeakPtrI6ZombieEE
// TODO    256 B  GridItemWaterHole::isStraightDevouredZombie          _ZN17GridItemWaterHole24isStraightDevouredZombieEP6Zombie
// TODO    180 B  GridItemWaterHole::StaticClassInit                   _ZN17GridItemWaterHole15StaticClassInitEv
// TODO    180 B  GridItemWaterHoleProps::StaticClassInit              _ZN22GridItemWaterHoleProps15StaticClassInitEv
// TODO    140 B  GridItemWaterHole::onAnimation                       _ZN17GridItemWaterHole11onAnimationERKSs
// TODO    124 B  GridItemWaterHole::StaticGetClass                    _ZN17GridItemWaterHole14StaticGetClassEv
// TODO    124 B  GridItemWaterHoleProps::StaticGetClass               _ZN22GridItemWaterHoleProps14StaticGetClassEv
// TODO     92 B  GridItemWaterHole::onGridItemInitialize              _ZN17GridItemWaterHole20onGridItemInitializeEv
// TODO     68 B  GridItemWaterHole::GridItemWaterHole                 _ZN17GridItemWaterHoleC2Ev
// TODO     68 B  GridItemWaterHole::GridItemWaterHole                 _ZN17GridItemWaterHoleC1Ev
// TODO     68 B  GridItemWaterHoleProps::GridItemWaterHoleProps       _ZN22GridItemWaterHolePropsC2Ev
// TODO     68 B  GridItemWaterHoleProps::GridItemWaterHoleProps       _ZN22GridItemWaterHolePropsC1Ev
// TODO     64 B  GridItemWaterHole::~GridItemWaterHole                _ZN17GridItemWaterHoleD2Ev
// TODO     64 B  GridItemWaterHole::~GridItemWaterHole                _ZN17GridItemWaterHoleD1Ev
// TODO     52 B  GridItemWaterHoleProps::~GridItemWaterHoleProps      _ZN22GridItemWaterHolePropsD2Ev
// TODO     52 B  GridItemWaterHoleProps::~GridItemWaterHoleProps      _ZN22GridItemWaterHolePropsD1Ev
// TODO     44 B  GridItemWaterHole::StaticNew                         _ZN17GridItemWaterHole9StaticNewEv
// TODO     44 B  GridItemWaterHoleProps::StaticNew                    _ZN22GridItemWaterHoleProps9StaticNewEv
// TODO     36 B  GridItemWaterHole::~GridItemWaterHole                _ZN17GridItemWaterHoleD0Ev
// TODO     36 B  GridItemWaterHoleProps::~GridItemWaterHoleProps      _ZN22GridItemWaterHolePropsD0Ev
