// PvZ2/griditems/GridItemEggAnimRig.cpp
//
// 12 function(s), 1384 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: GridItemEggAnimRig
//
// TODO    412 B  GridItemEggAnimRig::SetDamageState                   _ZN18GridItemEggAnimRig14SetDamageStateEi
// TODO    180 B  GridItemEggAnimRig::StaticClassInit                  _ZN18GridItemEggAnimRig15StaticClassInitEv
// TODO    172 B  GridItemEggAnimRig::PlayTurnToAsh                    _ZN18GridItemEggAnimRig13PlayTurnToAshE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    140 B  GridItemEggAnimRig::PlayIdle                         _ZN18GridItemEggAnimRig8PlayIdleEv
// TODO    124 B  GridItemEggAnimRig::StaticGetClass                   _ZN18GridItemEggAnimRig14StaticGetClassEv
// TODO     72 B  GridItemEggAnimRig::GridItemEggAnimRig               _ZN18GridItemEggAnimRigC2Ev
// TODO     72 B  GridItemEggAnimRig::GridItemEggAnimRig               _ZN18GridItemEggAnimRigC1Ev
// TODO     64 B  GridItemEggAnimRig::~GridItemEggAnimRig              _ZN18GridItemEggAnimRigD2Ev
// TODO     64 B  GridItemEggAnimRig::~GridItemEggAnimRig              _ZN18GridItemEggAnimRigD1Ev
// TODO     44 B  GridItemEggAnimRig::StaticNew                        _ZN18GridItemEggAnimRig9StaticNewEv
// TODO     36 B  GridItemEggAnimRig::~GridItemEggAnimRig              _ZN18GridItemEggAnimRigD0Ev
// TODO      4 B  GridItemEggAnimRig::PlayRoll                         _ZN18GridItemEggAnimRig8PlayRollE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
