// PvZ2/griditems/GridItemWhackPuddle.cpp
//
// 12 function(s), 616 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: GridItemWhackPuddle
//
// TODO    180 B  GridItemWhackPuddle::StaticClassInit                 _ZN19GridItemWhackPuddle15StaticClassInitEv
// TODO    124 B  GridItemWhackPuddle::StaticGetClass                  _ZN19GridItemWhackPuddle14StaticGetClassEv
// TODO     56 B  GridItemWhackPuddle::GridItemWhackPuddle             _ZN19GridItemWhackPuddleC2Ev
// TODO     56 B  GridItemWhackPuddle::GridItemWhackPuddle             _ZN19GridItemWhackPuddleC1Ev
// TODO     48 B  GridItemWhackPuddle::onGridItemInitialize            _ZN19GridItemWhackPuddle20onGridItemInitializeEv
// TODO     44 B  GridItemWhackPuddle::StaticNew                       _ZN19GridItemWhackPuddle9StaticNewEv
// TODO     36 B  GridItemWhackPuddle::~GridItemWhackPuddle            _ZN19GridItemWhackPuddleD0Ev
// TODO     28 B  GridItemWhackPuddle::~GridItemWhackPuddle            _ZN19GridItemWhackPuddleD2Ev
// TODO     28 B  GridItemWhackPuddle::~GridItemWhackPuddle            _ZN19GridItemWhackPuddleD1Ev
// TODO      8 B  GridItemWhackPuddle::IsAbleToSpawn                   _ZN19GridItemWhackPuddle13IsAbleToSpawnEv
// TODO      4 B  GridItemWhackPuddle::registerForEvents               _ZN19GridItemWhackPuddle17registerForEventsEv
// TODO      4 B  GridItemWhackPuddle::onTakeDamage                    _ZN19GridItemWhackPuddle12onTakeDamageERK10DamageInfo
