// PvZ2/griditems/GridItemWizardCrucibleAnimRig.cpp
//
// 18 function(s), 1756 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: GridItemWizardCrucibleAnimRig
//
// TODO    180 B  GridItemWizardCrucibleAnimRig::StaticClassInit       _ZN29GridItemWizardCrucibleAnimRig15StaticClassInitEv
// TODO    140 B  GridItemWizardCrucibleAnimRig::PlayCrucibleDisabling _ZN29GridItemWizardCrucibleAnimRig21PlayCrucibleDisablingE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    140 B  GridItemWizardCrucibleAnimRig::PlayCrucibleActivating _ZN29GridItemWizardCrucibleAnimRig22PlayCrucibleActivatingE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    140 B  GridItemWizardCrucibleAnimRig::PlayCrucibleDying     _ZN29GridItemWizardCrucibleAnimRig17PlayCrucibleDyingE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    132 B  GridItemWizardCrucibleAnimRig::PlayCrucibleDisabled  _ZN29GridItemWizardCrucibleAnimRig20PlayCrucibleDisabledEv
// TODO    132 B  GridItemWizardCrucibleAnimRig::PlayCrucibleActivated _ZN29GridItemWizardCrucibleAnimRig21PlayCrucibleActivatedEv
// TODO    124 B  GridItemWizardCrucibleAnimRig::StaticGetClass        _ZN29GridItemWizardCrucibleAnimRig14StaticGetClassEv
// TODO    104 B  GridItemWizardCrucibleAnimRig::getDisabledAnimName   _ZN29GridItemWizardCrucibleAnimRig19getDisabledAnimNameEv
// TODO    104 B  GridItemWizardCrucibleAnimRig::getDisablingAnimName  _ZN29GridItemWizardCrucibleAnimRig20getDisablingAnimNameEv
// TODO    104 B  GridItemWizardCrucibleAnimRig::getActivatingAnimName _ZN29GridItemWizardCrucibleAnimRig21getActivatingAnimNameEv
// TODO    104 B  GridItemWizardCrucibleAnimRig::getActivatedAnimName  _ZN29GridItemWizardCrucibleAnimRig20getActivatedAnimNameEv
// TODO    104 B  GridItemWizardCrucibleAnimRig::getDyingAnimName      _ZN29GridItemWizardCrucibleAnimRig16getDyingAnimNameEv
// TODO     56 B  GridItemWizardCrucibleAnimRig::GridItemWizardCrucibleAnimRig _ZN29GridItemWizardCrucibleAnimRigC2Ev
// TODO     56 B  GridItemWizardCrucibleAnimRig::GridItemWizardCrucibleAnimRig _ZN29GridItemWizardCrucibleAnimRigC1Ev
// TODO     44 B  GridItemWizardCrucibleAnimRig::StaticNew             _ZN29GridItemWizardCrucibleAnimRig9StaticNewEv
// TODO     36 B  GridItemWizardCrucibleAnimRig::~GridItemWizardCrucibleAnimRig _ZN29GridItemWizardCrucibleAnimRigD0Ev
// TODO     28 B  GridItemWizardCrucibleAnimRig::~GridItemWizardCrucibleAnimRig _ZN29GridItemWizardCrucibleAnimRigD2Ev
// TODO     28 B  GridItemWizardCrucibleAnimRig::~GridItemWizardCrucibleAnimRig _ZN29GridItemWizardCrucibleAnimRigD1Ev
