// PvZ2/griditems/GridSquareMoonFlowerGlow.cpp
//
// 15 function(s), 2216 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: GridSquareMoonFlowerGlow
//
// TODO    372 B  GridSquareMoonFlowerGlow::createExitEffect           _ZN24GridSquareMoonFlowerGlow16createExitEffectEN4Sexy11SexyVector3E
// TODO    372 B  GridSquareMoonFlowerGlow::createSpawnAndLoopEffect   _ZN24GridSquareMoonFlowerGlow24createSpawnAndLoopEffectEN4Sexy11SexyVector3E
// TODO    228 B  GridSquareMoonFlowerGlow::addStartingAnimationSequence _ZN24GridSquareMoonFlowerGlow28addStartingAnimationSequenceEP14Effect_PopAnim
// TODO    220 B  GridSquareMoonFlowerGlow::StartEffect                _ZN24GridSquareMoonFlowerGlow11StartEffectEN4Sexy5PointE
// TODO    180 B  GridSquareMoonFlowerGlow::StaticClassInit            _ZN24GridSquareMoonFlowerGlow15StaticClassInitEv
// TODO    160 B  GridSquareMoonFlowerGlow::GridSquareMoonFlowerGlow   _ZN24GridSquareMoonFlowerGlowC2Ev
// TODO    160 B  GridSquareMoonFlowerGlow::GridSquareMoonFlowerGlow   _ZN24GridSquareMoonFlowerGlowC1Ev
// TODO    124 B  GridSquareMoonFlowerGlow::StaticGetClass             _ZN24GridSquareMoonFlowerGlow14StaticGetClassEv
// TODO    112 B  GridSquareMoonFlowerGlow::DoExit                     _ZN24GridSquareMoonFlowerGlow6DoExitEv
// TODO     68 B  GridSquareMoonFlowerGlow::onDestroy                  _ZN24GridSquareMoonFlowerGlow9onDestroyEv
// TODO     64 B  GridSquareMoonFlowerGlow::~GridSquareMoonFlowerGlow  _ZN24GridSquareMoonFlowerGlowD2Ev
// TODO     64 B  GridSquareMoonFlowerGlow::~GridSquareMoonFlowerGlow  _ZN24GridSquareMoonFlowerGlowD1Ev
// TODO     44 B  GridSquareMoonFlowerGlow::StaticNew                  _ZN24GridSquareMoonFlowerGlow9StaticNewEv
// TODO     36 B  GridSquareMoonFlowerGlow::~GridSquareMoonFlowerGlow  _ZN24GridSquareMoonFlowerGlowD0Ev
// TODO     12 B  GridSquareMoonFlowerGlow::getPamName                 _ZN24GridSquareMoonFlowerGlow10getPamNameEv
