// PvZ2/GridItemGravestone.cpp
//
// 36 function(s), 5388 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: GridItemGravestone, GridItemGravestonePropertySheet
//
// TODO    704 B  GridItemGravestone::onGridItemInitialize             _ZN18GridItemGravestone20onGridItemInitializeEv
// TODO    516 B  GridItemGravestone::spawnBreakEffect                 _ZN18GridItemGravestone16spawnBreakEffectEi
// TODO    320 B  GridItemGravestone::updateState                      _ZN18GridItemGravestone11updateStateEv
// TODO    304 B  GridItemGravestone::onTakeDamage                     _ZN18GridItemGravestone12onTakeDamageERK10DamageInfo
// TODO    288 B  GridItemGravestone::calcCollisionRect                _ZN18GridItemGravestone17calcCollisionRectEv
// TODO    272 B  GridItemGravestone::setRiseHeight                    _ZN18GridItemGravestone13setRiseHeightEf
// TODO    268 B  GridItemGravestone::setState                         _ZN18GridItemGravestone8setStateE15GravestoneState
// TODO    240 B  GridItemGravestone::calcDamageState                  _ZN18GridItemGravestone15calcDamageStateEv
// TODO    240 B  GridItemGravestonePropertySheet::GridItemGravestonePropertySheet _ZN31GridItemGravestonePropertySheetC2Ev
// TODO    240 B  GridItemGravestonePropertySheet::GridItemGravestonePropertySheet _ZN31GridItemGravestonePropertySheetC1Ev
// TODO    180 B  GridItemGravestone::StaticClassInit                  _ZN18GridItemGravestone15StaticClassInitEv
// TODO    180 B  GridItemGravestonePropertySheet::StaticClassInit     _ZN31GridItemGravestonePropertySheet15StaticClassInitEv
// TODO    156 B  GridItemGravestone::registerForEvents                _ZN18GridItemGravestone17registerForEventsEv
// TODO    144 B  GridItemGravestone::initializeAnimRig                _ZN18GridItemGravestone17initializeAnimRigEv
// TODO    124 B  GridItemGravestone::StaticGetClass                   _ZN18GridItemGravestone14StaticGetClassEv
// TODO    124 B  GridItemGravestonePropertySheet::StaticGetClass      _ZN31GridItemGravestonePropertySheet14StaticGetClassEv
// TODO    108 B  GridItemGravestone::CancelBeingEaten                 _ZN18GridItemGravestone16CancelBeingEatenEf
// TODO    104 B  GridItemGravestone::GridItemGravestone               _ZN18GridItemGravestoneC2Ev
// TODO    104 B  GridItemGravestone::GridItemGravestone               _ZN18GridItemGravestoneC1Ev
// TODO     84 B  GridItemGravestone::onUpdate                         _ZN18GridItemGravestone8onUpdateEv
// TODO     72 B  GridItemGravestone::FinishEatingAndDestroy           _ZN18GridItemGravestone22FinishEatingAndDestroyEv
// TODO     64 B  GridItemGravestone::~GridItemGravestone              _ZN18GridItemGravestoneD2Ev
// TODO     64 B  GridItemGravestone::~GridItemGravestone              _ZN18GridItemGravestoneD1Ev
// TODO     64 B  GridItemGravestone::onDestroy                        _ZN18GridItemGravestone9onDestroyEv
// TODO     60 B  GridItemGravestonePropertySheet::~GridItemGravestonePropertySheet _ZN31GridItemGravestonePropertySheetD2Ev
// TODO     60 B  GridItemGravestonePropertySheet::~GridItemGravestonePropertySheet _ZN31GridItemGravestonePropertySheetD1Ev
// TODO     48 B  GridItemGravestone::getGridExtents                   _ZN18GridItemGravestone14getGridExtentsEv
// TODO     44 B  GridItemGravestone::StaticNew                        _ZN18GridItemGravestone9StaticNewEv
// TODO     44 B  GridItemGravestonePropertySheet::StaticNew           _ZN31GridItemGravestonePropertySheet9StaticNewEv
// TODO     40 B  GridItemGravestone::getRenderOffset                  _ZN18GridItemGravestone15getRenderOffsetEv
// TODO     36 B  GridItemGravestone::~GridItemGravestone              _ZN18GridItemGravestoneD0Ev
// TODO     36 B  GridItemGravestonePropertySheet::~GridItemGravestonePropertySheet _ZN31GridItemGravestonePropertySheetD0Ev
// TODO     20 B  GridItemGravestone::spawnDirt                        _ZN18GridItemGravestone9spawnDirtEv
// TODO     20 B  GridItemGravestone::onEnableGridItems                _ZN18GridItemGravestone17onEnableGridItemsEv
// TODO      8 B  GridItemGravestone::SetRiseDelay                     _ZN18GridItemGravestone12SetRiseDelayEf
// TODO      8 B  GridItemGravestone::SetBeingEaten                    _ZN18GridItemGravestone13SetBeingEatenEv
