// PvZ2/zombies/Tutorial/ZombieAnimRig_Tutorial.cpp
//
// 15 function(s), 2824 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieAnimRig_Tutorial
//
// TODO    376 B  ZombieAnimRig_Tutorial::getArmLayerNames             _ZN22ZombieAnimRig_Tutorial16getArmLayerNamesEv
// TODO    348 B  ZombieAnimRig_Tutorial::getConeLayerNames            _ZN22ZombieAnimRig_Tutorial17getConeLayerNamesEv
// TODO    348 B  ZombieAnimRig_Tutorial::getBucketLayerNames          _ZN22ZombieAnimRig_Tutorial19getBucketLayerNamesEv
// TODO    320 B  ZombieAnimRig_Tutorial::getHeadLayerNames            _ZN22ZombieAnimRig_Tutorial17getHeadLayerNamesEv
// TODO    320 B  ZombieAnimRig_Tutorial::getArmReplacementPairNames   _ZN22ZombieAnimRig_Tutorial26getArmReplacementPairNamesEv
// TODO    280 B  ZombieAnimRig_Tutorial::getFlagHandLayerNames        _ZN22ZombieAnimRig_Tutorial21getFlagHandLayerNamesEv
// TODO    280 B  ZombieAnimRig_Tutorial::getNoFlagHandLayerNames      _ZN22ZombieAnimRig_Tutorial23getNoFlagHandLayerNamesEv
// TODO    180 B  ZombieAnimRig_Tutorial::StaticClassInit              _ZN22ZombieAnimRig_Tutorial15StaticClassInitEv
// TODO    124 B  ZombieAnimRig_Tutorial::StaticGetClass               _ZN22ZombieAnimRig_Tutorial14StaticGetClassEv
// TODO     56 B  ZombieAnimRig_Tutorial::ZombieAnimRig_Tutorial       _ZN22ZombieAnimRig_TutorialC2Ev
// TODO     56 B  ZombieAnimRig_Tutorial::ZombieAnimRig_Tutorial       _ZN22ZombieAnimRig_TutorialC1Ev
// TODO     44 B  ZombieAnimRig_Tutorial::StaticNew                    _ZN22ZombieAnimRig_Tutorial9StaticNewEv
// TODO     36 B  ZombieAnimRig_Tutorial::~ZombieAnimRig_Tutorial      _ZN22ZombieAnimRig_TutorialD0Ev
// TODO     28 B  ZombieAnimRig_Tutorial::~ZombieAnimRig_Tutorial      _ZN22ZombieAnimRig_TutorialD2Ev
// TODO     28 B  ZombieAnimRig_Tutorial::~ZombieAnimRig_Tutorial      _ZN22ZombieAnimRig_TutorialD1Ev
