// PvZ2/ui/BirthdayRewardDialog.cpp
//
// 16 function(s), 3768 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: BirthdayRewardDialog
//
// TODO    700 B  BirthdayRewardDialog::DrawAll                        _ZN20BirthdayRewardDialog7DrawAllEPN4Sexy10ModalFlagsEPNS0_8GraphicsE
// TODO    452 B  BirthdayRewardDialog::Draw                           _ZN20BirthdayRewardDialog4DrawEPN4Sexy8GraphicsE
// TODO    432 B  BirthdayRewardDialog::AddControlButton               _ZN20BirthdayRewardDialog16AddControlButtonEv
// TODO    384 B  BirthdayRewardDialog::AddCloseButton                 _ZN20BirthdayRewardDialog14AddCloseButtonEv
// TODO    376 B  BirthdayRewardDialog::AddScrollWidght                _ZN20BirthdayRewardDialog15AddScrollWidghtEv
// TODO    260 B  BirthdayRewardDialog::BirthdayRewardDialog           _ZN20BirthdayRewardDialogC1Ev
// TODO    260 B  BirthdayRewardDialog::BirthdayRewardDialog           _ZN20BirthdayRewardDialogC2Ev
// TODO    252 B  BirthdayRewardDialog::~BirthdayRewardDialog          _ZN20BirthdayRewardDialogD2Ev
// TODO    252 B  BirthdayRewardDialog::~BirthdayRewardDialog          _ZN20BirthdayRewardDialogD1Ev
// TODO    164 B  BirthdayRewardDialog::ButtonDepress                  _ZN20BirthdayRewardDialog13ButtonDepressEi
// TODO    156 B  BirthdayRewardDialog::InitView                       _ZN20BirthdayRewardDialog8InitViewEv
// TODO     36 B  BirthdayRewardDialog::~BirthdayRewardDialog          _ZN20BirthdayRewardDialogD0Ev
// TODO     32 B  BirthdayRewardDialog::ButtonPress                    _ZN20BirthdayRewardDialog11ButtonPressEi
// TODO      4 B  BirthdayRewardDialog::ScrollTargetReached            _ZN20BirthdayRewardDialog19ScrollTargetReachedEPN4Sexy12ScrollWidgetE
// TODO      4 B  BirthdayRewardDialog::ScrollTargetInterrupted        _ZN20BirthdayRewardDialog23ScrollTargetInterruptedEPN4Sexy12ScrollWidgetE
// TODO      4 B  BirthdayRewardDialog::Update                         _ZN20BirthdayRewardDialog6UpdateEv
