// PvZ2/MessageWidget.cpp
//
// 16 function(s), 4568 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: MessageWidget
//
// TODO   1748 B  MessageWidget::Draw                                  _ZN13MessageWidget4DrawEPN4Sexy8GraphicsE
// TODO    808 B  MessageWidget::layoutReanimText                      _ZN13MessageWidget16layoutReanimTextEv
// TODO    720 B  MessageWidget::SetLabel                              _ZN13MessageWidget8SetLabelERKSbIwSt11char_traitsIwESaIwEE12MessageStyle
// TODO    456 B  MessageWidget::SetLabel                              _ZN13MessageWidget8SetLabelERKSbIwSt11char_traitsIwESaIwEE12MessageStylef
// TODO    208 B  MessageWidget::Update                                _ZN13MessageWidget6UpdateEv
// TODO    112 B  MessageWidget::getFont                               _ZN13MessageWidget7getFontEv
// TODO    104 B  MessageWidget::MessageWidget                         _ZN13MessageWidgetC1Ev
// TODO    104 B  MessageWidget::MessageWidget                         _ZN13MessageWidgetC2Ev
// TODO     96 B  MessageWidget::clearPAMs                             _ZN13MessageWidget9clearPAMsEv
// TODO     68 B  MessageWidget::~MessageWidget                        _ZN13MessageWidgetD1Ev
// TODO     68 B  MessageWidget::~MessageWidget                        _ZN13MessageWidgetD2Ev
// TODO     36 B  MessageWidget::~MessageWidget                        _ZN13MessageWidgetD0Ev
// TODO     16 B  MessageWidget::IsBeingDisplayed                      _ZN13MessageWidget16IsBeingDisplayedEv
// TODO     12 B  MessageWidget::GetRenderLayer                        _ZN13MessageWidget14GetRenderLayerEv
// TODO      8 B  MessageWidget::clearLabel                            _ZN13MessageWidget10clearLabelEv
// TODO      4 B  MessageWidget::Clear                                 _ZN13MessageWidget5ClearEv
