// PvZ2/ui/PlantAccessoryUI.cpp
//
// 37 function(s), 23748 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAccessoryUI
//
// TODO   4228 B  PlantAccessoryUI::DrawAll                            _ZN16PlantAccessoryUI7DrawAllEPN4Sexy10ModalFlagsEPNS0_8GraphicsE
// TODO   4060 B  PlantAccessoryUI::createPanel                        _ZN16PlantAccessoryUI11createPanelE24PlantAccessoryUITabPanel
// TODO   3700 B  PlantAccessoryUI::OnMainUINoticed                    _ZN16PlantAccessoryUI15OnMainUINoticedEP16AccessoryContent
// TODO   2704 B  PlantAccessoryUI::ButtonDepress                      _ZN16PlantAccessoryUI13ButtonDepressEi
// TODO   1308 B  PlantAccessoryUI::InitView                           _ZN16PlantAccessoryUI8InitViewEv
// TODO   1068 B  PlantAccessoryUI::PlantAccessoryUI                   _ZN16PlantAccessoryUIC1EN4Sexy9RtWeakPtrIK9PlantTypeEE
// TODO   1068 B  PlantAccessoryUI::PlantAccessoryUI                   _ZN16PlantAccessoryUIC2EN4Sexy9RtWeakPtrIK9PlantTypeEE
// TODO    752 B  PlantAccessoryUI::OnSteadySuccess                    _ZN16PlantAccessoryUI15OnSteadySuccessEi
// TODO    632 B  PlantAccessoryUI::GetCurrentSteadyCost               _ZN16PlantAccessoryUI20GetCurrentSteadyCostEv
// TODO    492 B  PlantAccessoryUI::OnConfirmExchange                  _ZN16PlantAccessoryUI17OnConfirmExchangeEv
// TODO    420 B  PlantAccessoryUI::~PlantAccessoryUI                  _ZN16PlantAccessoryUID2Ev
// TODO    420 B  PlantAccessoryUI::~PlantAccessoryUI                  _ZN16PlantAccessoryUID1Ev
// TODO    372 B  PlantAccessoryUI::OnExchangeComplete                 _ZN16PlantAccessoryUI18OnExchangeCompleteEb
// TODO    336 B  PlantAccessoryUI::OnAccessorySaleComplete            _ZN16PlantAccessoryUI23OnAccessorySaleCompleteEv
// TODO    316 B  PlantAccessoryUI::OnResetSuccess                     _ZN16PlantAccessoryUI14OnResetSuccessEi
// TODO    248 B  PlantAccessoryUI::showSuperAccessoryDescription      _ZN16PlantAccessoryUI29showSuperAccessoryDescriptionEv
// TODO    204 B  PlantAccessoryUI::ShowSteadySuccessSuperPacket       _ZN16PlantAccessoryUI28ShowSteadySuccessSuperPacketEi
// TODO    196 B  PlantAccessoryUI::ShowAccessorySuperPacket           _ZN16PlantAccessoryUI24ShowAccessorySuperPacketEv
// TODO    176 B  PlantAccessoryUI::TriggerTutorial                    _ZN16PlantAccessoryUI15TriggerTutorialEv
// TODO    132 B  PlantAccessoryUI::DoSwitchTargetAccessory            _ZN16PlantAccessoryUI23DoSwitchTargetAccessoryEv
// TODO    132 B  PlantAccessoryUI::ToPanel                            _ZN16PlantAccessoryUI7ToPanelEi
// TODO    112 B  PlantAccessoryUI::CloseAccessorySuperPacket          _ZN16PlantAccessoryUI25CloseAccessorySuperPacketEv
// TODO    112 B  PlantAccessoryUI::CloseSteadySuccessSuperPacket      _ZN16PlantAccessoryUI29CloseSteadySuccessSuperPacketEv
// TODO    112 B  PlantAccessoryUI::closeSuperAccessoryDescription     _ZN16PlantAccessoryUI30closeSuperAccessoryDescriptionEv
// TODO     96 B  PlantAccessoryUI::OnConfirmReset                     _ZN16PlantAccessoryUI14OnConfirmResetEv
// TODO     96 B  PlantAccessoryUI::OnConfirmSteady                    _ZN16PlantAccessoryUI15OnConfirmSteadyEv
// TODO     80 B  PlantAccessoryUI::OnConfirmSale                      _ZN16PlantAccessoryUI13OnConfirmSaleEv
// TODO     56 B  PlantAccessoryUI::onNarrationFinished                _ZN16PlantAccessoryUI19onNarrationFinishedEv
// TODO     40 B  PlantAccessoryUI::OnSoldTargetAccessory              _ZN16PlantAccessoryUI21OnSoldTargetAccessoryEi
// TODO     36 B  PlantAccessoryUI::~PlantAccessoryUI                  _ZN16PlantAccessoryUID0Ev
// TODO     16 B  PlantAccessoryUI::OnCloseDialog                      _ZN16PlantAccessoryUI13OnCloseDialogEv
// TODO      8 B  PlantAccessoryUI::RecreateCurrentPanel               _ZN16PlantAccessoryUI20RecreateCurrentPanelEv
// TODO      4 B  PlantAccessoryUI::ScrollTargetReached                _ZN16PlantAccessoryUI19ScrollTargetReachedEPN4Sexy12ScrollWidgetE
// TODO      4 B  PlantAccessoryUI::ScrollTargetInterrupted            _ZN16PlantAccessoryUI23ScrollTargetInterruptedEPN4Sexy12ScrollWidgetE
// TODO      4 B  PlantAccessoryUI::Update                             _ZN16PlantAccessoryUI6UpdateEv
// TODO      4 B  PlantAccessoryUI::Draw                               _ZN16PlantAccessoryUI4DrawEPN4Sexy8GraphicsE
// TODO      4 B  PlantAccessoryUI::OnActionComplete                   _ZN16PlantAccessoryUI16OnActionCompleteEv
