// PvZ2/ui/PVZ2UIBuyGiftDialog.cpp
//
// 11 function(s), 8604 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PVZ2UIBuyGiftDialog
//
// TODO   2760 B  PVZ2UIBuyGiftDialog::PVZ2UIBuyGiftDialog             _ZN19PVZ2UIBuyGiftDialogC1EN4Sexy9RtWeakPtrI19MagentoProductPropsEEb
// TODO   2760 B  PVZ2UIBuyGiftDialog::PVZ2UIBuyGiftDialog             _ZN19PVZ2UIBuyGiftDialogC2EN4Sexy9RtWeakPtrI19MagentoProductPropsEEb
// TODO   1488 B  PVZ2UIBuyGiftDialog::ButtonDepress                   _ZN19PVZ2UIBuyGiftDialog13ButtonDepressEi
// TODO    908 B  PVZ2UIBuyGiftDialog::Resize                          _ZN19PVZ2UIBuyGiftDialog6ResizeEiiii
// TODO    428 B  PVZ2UIBuyGiftDialog::DrawAll                         _ZN19PVZ2UIBuyGiftDialog7DrawAllEPN4Sexy10ModalFlagsEPNS0_8GraphicsE
// TODO    100 B  PVZ2UIBuyGiftDialog::~PVZ2UIBuyGiftDialog            _ZN19PVZ2UIBuyGiftDialogD2Ev
// TODO    100 B  PVZ2UIBuyGiftDialog::~PVZ2UIBuyGiftDialog            _ZN19PVZ2UIBuyGiftDialogD1Ev
// TODO     36 B  PVZ2UIBuyGiftDialog::~PVZ2UIBuyGiftDialog            _ZN19PVZ2UIBuyGiftDialogD0Ev
// TODO     16 B  PVZ2UIBuyGiftDialog::onPopRewardPressed              _ZN19PVZ2UIBuyGiftDialog18onPopRewardPressedEv
// TODO      4 B  PVZ2UIBuyGiftDialog::ConfigGiftContent               _ZN19PVZ2UIBuyGiftDialog17ConfigGiftContentEv
// TODO      4 B  PVZ2UIBuyGiftDialog::Draw                            _ZN19PVZ2UIBuyGiftDialog4DrawEPN4Sexy8GraphicsE
