// PvZ2/PVZ2UICreditsScreen.cpp
//
// 12 function(s), 7452 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PVZ2UICreditsScreen
//
// TODO   2264 B  PVZ2UICreditsScreen::PVZ2UICreditsScreen             _ZN19PVZ2UICreditsScreenC2Ev
// TODO   2264 B  PVZ2UICreditsScreen::PVZ2UICreditsScreen             _ZN19PVZ2UICreditsScreenC1Ev
// TODO    744 B  PVZ2UICreditsScreen::SpawnRandomDebris               _ZN19PVZ2UICreditsScreen17SpawnRandomDebrisEi
// TODO    528 B  PVZ2UICreditsScreen::~PVZ2UICreditsScreen            _ZN19PVZ2UICreditsScreenD2Ev
// TODO    528 B  PVZ2UICreditsScreen::~PVZ2UICreditsScreen            _ZN19PVZ2UICreditsScreenD1Ev
// TODO    504 B  PVZ2UICreditsScreen::DrawAll                         _ZN19PVZ2UICreditsScreen7DrawAllEPN4Sexy10ModalFlagsEPNS0_8GraphicsE
// TODO    296 B  PVZ2UICreditsScreen::Update                          _ZN19PVZ2UICreditsScreen6UpdateEv
// TODO    132 B  PVZ2UICreditsScreen::DrawSpaceDebris                 _ZN19PVZ2UICreditsScreen15DrawSpaceDebrisEPN4Sexy8GraphicsE
// TODO     88 B  PVZ2UICreditsScreen::ButtonDepress                   _ZN19PVZ2UICreditsScreen13ButtonDepressEi
// TODO     52 B  PVZ2UICreditsScreen::ButtonPress                     _ZN19PVZ2UICreditsScreen11ButtonPressEi
// TODO     36 B  PVZ2UICreditsScreen::~PVZ2UICreditsScreen            _ZN19PVZ2UICreditsScreenD0Ev
// TODO     16 B  PVZ2UICreditsScreen::IsDone                          _ZN19PVZ2UICreditsScreen6IsDoneEv
