// PvZ2/ui/RewardUI.cpp
//
// 19 function(s), 1500 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: RewardUI
//
// TODO    812 B  RewardUI::StaticClassInit                            _ZN8RewardUI15StaticClassInitEv
// TODO    160 B  RewardUI::setState                                   _ZN8RewardUI8setStateE14RewardAniState
// TODO    124 B  RewardUI::StaticGetClass                             _ZN8RewardUI14StaticGetClassEv
// TODO     88 B  RewardUI::RewardUI                                   _ZN8RewardUIC2Ev
// TODO     88 B  RewardUI::RewardUI                                   _ZN8RewardUIC1Ev
// TODO     52 B  RewardUI::~RewardUI                                  _ZN8RewardUID2Ev
// TODO     52 B  RewardUI::~RewardUI                                  _ZN8RewardUID1Ev
// TODO     44 B  RewardUI::StaticNew                                  _ZN8RewardUI9StaticNewEv
// TODO     36 B  RewardUI::~RewardUI                                  _ZN8RewardUID0Ev
// TODO      8 B  RewardUI::Update                                     _ZN8RewardUI6UpdateEv
// TODO      4 B  RewardUI::onEnterState_Init                          _ZN8RewardUI17onEnterState_InitE14RewardAniState
// TODO      4 B  RewardUI::updateState_Init                           _ZN8RewardUI16updateState_InitEv
// TODO      4 B  RewardUI::onExitState_Init                           _ZN8RewardUI16onExitState_InitE14RewardAniState
// TODO      4 B  RewardUI::onEnterState_Update                        _ZN8RewardUI19onEnterState_UpdateE14RewardAniState
// TODO      4 B  RewardUI::updateState_Update                         _ZN8RewardUI18updateState_UpdateEv
// TODO      4 B  RewardUI::onExitState_Update                         _ZN8RewardUI18onExitState_UpdateE14RewardAniState
// TODO      4 B  RewardUI::onEnterState_End                           _ZN8RewardUI16onEnterState_EndE14RewardAniState
// TODO      4 B  RewardUI::updateState_End                            _ZN8RewardUI15updateState_EndEv
// TODO      4 B  RewardUI::onExitState_End                            _ZN8RewardUI15onExitState_EndE14RewardAniState
