// PvZ2/ui/TitleScreen.cpp
//
// 25 function(s), 15288 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: TitleScreen
//
// TODO   2896 B  TitleScreen::LoadRsbs                                _ZN11TitleScreen8LoadRsbsEv
// TODO   2896 B  TitleScreen::LoadRsbsExtra                           _ZN11TitleScreen13LoadRsbsExtraEv
// TODO   2268 B  TitleScreen::Draw                                    _ZN11TitleScreen4DrawEPN4Sexy8GraphicsE
// TODO   1724 B  TitleScreen::Update                                  _ZN11TitleScreen6UpdateEv
// TODO    932 B  TitleScreen::InitDecompressImage                     _ZN11TitleScreen19InitDecompressImageEv
// TODO    672 B  TitleScreen::DrawDecompressTips                      _ZN11TitleScreen18DrawDecompressTipsEPN4Sexy8GraphicsE
// TODO    512 B  TitleScreen::InitForDecompressRsbs                   _ZN11TitleScreen21InitForDecompressRsbsEv
// TODO    432 B  TitleScreen::TitleScreen                             _ZN11TitleScreenC1Ev
// TODO    432 B  TitleScreen::TitleScreen                             _ZN11TitleScreenC2Ev
// TODO    328 B  TitleScreen::LoadRsbsProc                            _ZN11TitleScreen12LoadRsbsProcEv
// TODO    328 B  TitleScreen::LoadRsbsExtraProc                       _ZN11TitleScreen17LoadRsbsExtraProcEv
// TODO    316 B  TitleScreen::NeedDecompressRsbs                      _ZN11TitleScreen18NeedDecompressRsbsEv
// TODO    316 B  TitleScreen::NeedDecompressRsbsExtra                 _ZN11TitleScreen23NeedDecompressRsbsExtraEv
// TODO    240 B  TitleScreen::GetTargetRSBDecompressSize              _ZN11TitleScreen26GetTargetRSBDecompressSizeERKSs
// TODO    188 B  TitleScreen::~TitleScreen                            _ZN11TitleScreenD2Ev
// TODO    188 B  TitleScreen::~TitleScreen                            _ZN11TitleScreenD1Ev
// TODO    184 B  TitleScreen::GetPreviousDecompressTime               _ZN11TitleScreen25GetPreviousDecompressTimeEv
// TODO    184 B  TitleScreen::GetTotalDecompressTime                  _ZN11TitleScreen22GetTotalDecompressTimeEv
// TODO    136 B  TitleScreen::GetLeftDecompressTime                   _ZN11TitleScreen21GetLeftDecompressTimeEv
// TODO     52 B  TitleScreen::SetState                                _ZN11TitleScreen8SetStateE10TitleState
// TODO     36 B  TitleScreen::~TitleScreen                            _ZN11TitleScreenD0Ev
// TODO      8 B  TitleScreen::SetSkipIntro                            _ZN11TitleScreen12SetSkipIntroEb
// TODO      8 B  TitleScreen::GetFirstDecompressTotalAmount           _ZN11TitleScreen29GetFirstDecompressTotalAmountEv
// TODO      8 B  TitleScreen::GetSecondDecompressTotalAmount          _ZN11TitleScreen30GetSecondDecompressTotalAmountEv
// TODO      4 B  TitleScreen::Resize                                  _ZN11TitleScreen6ResizeEiiii
