// PvZ2/ui/ToolTipWidget.cpp
//
// 12 function(s), 3296 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ToolTipWidget
//
// TODO   1380 B  ToolTipWidget::Draw                                  _ZN13ToolTipWidget4DrawEPN4Sexy8GraphicsE
// TODO    700 B  ToolTipWidget::CalculateSize                         _ZN13ToolTipWidget13CalculateSizeEv
// TODO    520 B  ToolTipWidget::GetLines                              _ZN13ToolTipWidget8GetLinesERSt6vectorISbIwSt11char_traitsIwESaIwEESaIS4_EE
// TODO    116 B  ToolTipWidget::SetLabel                              _ZN13ToolTipWidget8SetLabelERKSbIwSt11char_traitsIwESaIwEE
// TODO    116 B  ToolTipWidget::SetTitle                              _ZN13ToolTipWidget8SetTitleERKSbIwSt11char_traitsIwESaIwEE
// TODO    116 B  ToolTipWidget::SetWarningText                        _ZN13ToolTipWidget14SetWarningTextERKSbIwSt11char_traitsIwESaIwEE
// TODO    108 B  ToolTipWidget::ToolTipWidget                         _ZN13ToolTipWidgetC1Ev
// TODO    108 B  ToolTipWidget::ToolTipWidget                         _ZN13ToolTipWidgetC2Ev
// TODO     48 B  ToolTipWidget::~ToolTipWidget                        _ZN13ToolTipWidgetD2Ev
// TODO     48 B  ToolTipWidget::~ToolTipWidget                        _ZN13ToolTipWidgetD1Ev
// TODO     24 B  ToolTipWidget::Update                                _ZN13ToolTipWidget6UpdateEv
// TODO     12 B  ToolTipWidget::FlashWarning                          _ZN13ToolTipWidget12FlashWarningEv
