// PvZ2/ui/UICarnival.cpp
//
// 26 function(s), 9092 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: UICarnival
//
// TODO   1420 B  UICarnival::InitPersonReward                         _ZN10UICarnival16InitPersonRewardEv
// TODO   1316 B  UICarnival::InitTotalReward                          _ZN10UICarnival15InitTotalRewardEv
// TODO   1280 B  UICarnival::InitBundle                               _ZN10UICarnival10InitBundleEv
// TODO    768 B  UICarnival::Update                                   _ZN10UICarnival6UpdateEv
// TODO    480 B  UICarnival::Refresh                                  _ZN10UICarnival7RefreshEv
// TODO    460 B  UICarnival::TabSelectionChanged                      _ZN10UICarnival19TabSelectionChangedEi
// TODO    400 B  UICarnival::showDescriptionWidget                    _ZN10UICarnival21showDescriptionWidgetEv
// TODO    352 B  UICarnival::InitView                                 _ZN10UICarnival8InitViewEv
// TODO    324 B  UICarnival::OnNotifyRefreshActivityList              _ZN10UICarnival27OnNotifyRefreshActivityListEbRKSt3setIiSt4lessIiESaIiEE
// TODO    320 B  UICarnival::ButtonDepress                            _ZN10UICarnival13ButtonDepressEi
// TODO    304 B  UICarnival::UICarnival                               _ZN10UICarnivalC1Ev
// TODO    304 B  UICarnival::UICarnival                               _ZN10UICarnivalC2Ev
// TODO    256 B  UICarnival::OnCreate                                 _ZN10UICarnival8OnCreateEv
// TODO    196 B  UICarnival::ShowPacketList                           _ZN10UICarnival14ShowPacketListEv
// TODO    196 B  UICarnival::ShowBundlePreview                        _ZN10UICarnival17ShowBundlePreviewEv
// TODO    112 B  UICarnival::closeDescriptionWidget                   _ZN10UICarnival22closeDescriptionWidgetEv
// TODO    112 B  UICarnival::CloseBundlePreview                       _ZN10UICarnival18CloseBundlePreviewEv
// TODO    112 B  UICarnival::ClosePacketList                          _ZN10UICarnival15ClosePacketListEv
// TODO    104 B  UICarnival::GetLayoutName                            _ZN10UICarnival13GetLayoutNameEv
// TODO    100 B  UICarnival::~UICarnival                              _ZN10UICarnivalD2Ev
// TODO    100 B  UICarnival::~UICarnival                              _ZN10UICarnivalD1Ev
// TODO     36 B  UICarnival::~UICarnival                              _ZN10UICarnivalD0Ev
// TODO     28 B  UICarnival::OnBuyBundle                              _ZN10UICarnival11OnBuyBundleEv
// TODO      4 B  UICarnival::ScrollTargetReached                      _ZN10UICarnival19ScrollTargetReachedEPN4Sexy12ScrollWidgetE
// TODO      4 B  UICarnival::ScrollTargetInterrupted                  _ZN10UICarnival23ScrollTargetInterruptedEPN4Sexy12ScrollWidgetE
// TODO      4 B  UICarnival::OnBuyCarnivalPacket                      _ZN10UICarnival19OnBuyCarnivalPacketEi
