// PvZ2/ui/UIChestAward.cpp
//
// 8 function(s), 3012 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: UIChestAward
//
// TODO    960 B  UIChestAward::Initialize                             _ZN12UIChestAward10InitializeEv
// TODO    824 B  UIChestAward::UIChestAward                           _ZN12UIChestAwardC2ERKSt6vectorI17ChestAwardContentSaIS1_EESs
// TODO    824 B  UIChestAward::UIChestAward                           _ZN12UIChestAwardC1ERKSt6vectorI17ChestAwardContentSaIS1_EESs
// TODO    192 B  UIChestAward::create                                 _ZN12UIChestAward6createERKSt6vectorI17ChestAwardContentSaIS1_EESs
// TODO     84 B  UIChestAward::~UIChestAward                          _ZN12UIChestAwardD2Ev
// TODO     84 B  UIChestAward::~UIChestAward                          _ZN12UIChestAwardD1Ev
// TODO     36 B  UIChestAward::~UIChestAward                          _ZN12UIChestAwardD0Ev
// TODO      8 B  UIChestAward::setEndCallBack                         _ZN12UIChestAward14setEndCallBackERKSt8functionIFvP14DTransformNodeEE
