// PvZ2/ui/UICustomLevelSetting.cpp
//
// 9 function(s), 2500 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: UICustomLevelSetting
//
// TODO   1920 B  UICustomLevelSetting::RefreshView                    _ZN20UICustomLevelSetting11RefreshViewEv
// TODO    184 B  UICustomLevelSetting::OnCreate                       _ZN20UICustomLevelSetting8OnCreateEv
// TODO    104 B  UICustomLevelSetting::GetLayoutName                  _ZN20UICustomLevelSetting13GetLayoutNameEv
// TODO     88 B  UICustomLevelSetting::ButtonDepress                  _ZN20UICustomLevelSetting13ButtonDepressEi
// TODO     56 B  UICustomLevelSetting::UICustomLevelSetting           _ZN20UICustomLevelSettingC1Ev
// TODO     56 B  UICustomLevelSetting::UICustomLevelSetting           _ZN20UICustomLevelSettingC2Ev
// TODO     36 B  UICustomLevelSetting::~UICustomLevelSetting          _ZN20UICustomLevelSettingD0Ev
// TODO     28 B  UICustomLevelSetting::~UICustomLevelSetting          _ZN20UICustomLevelSettingD2Ev
// TODO     28 B  UICustomLevelSetting::~UICustomLevelSetting          _ZN20UICustomLevelSettingD1Ev
