// PvZ2/ui/UIFightZodiac.cpp
//
// 30 function(s), 9552 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: UIFightZodiac
//
// TODO   1720 B  UIFightZodiac::InitView                              _ZN13UIFightZodiac8InitViewEv
// TODO    720 B  UIFightZodiac::UIFightZodiac                         _ZN13UIFightZodiacC1Ev
// TODO    720 B  UIFightZodiac::setZodiacHP                           _ZN13UIFightZodiac11setZodiacHPEib
// TODO    720 B  UIFightZodiac::UIFightZodiac                         _ZN13UIFightZodiacC2Ev
// TODO    596 B  UIFightZodiac::FightZodiacWithFireWorks              _ZN13UIFightZodiac24FightZodiacWithFireWorksEi
// TODO    504 B  UIFightZodiac::showDisplayBoardWidget                _ZN13UIFightZodiac22showDisplayBoardWidgetEv
// TODO    500 B  UIFightZodiac::~UIFightZodiac                        _ZN13UIFightZodiacD2Ev
// TODO    500 B  UIFightZodiac::~UIFightZodiac                        _ZN13UIFightZodiacD1Ev
// TODO    480 B  UIFightZodiac::updateTimer                           _ZN13UIFightZodiac11updateTimerEv
// TODO    404 B  UIFightZodiac::CheckTips                             _ZN13UIFightZodiac9CheckTipsEb
// TODO    368 B  UIFightZodiac::showDescriptionWidget                 _ZN13UIFightZodiac21showDescriptionWidgetEv
// TODO    292 B  UIFightZodiac::ButtonDepress                         _ZN13UIFightZodiac13ButtonDepressEi
// TODO    252 B  UIFightZodiac::showRewardDisplay                     _ZN13UIFightZodiac17showRewardDisplayEv
// TODO    240 B  UIFightZodiac::closeRewardDisplay                    _ZN13UIFightZodiac18closeRewardDisplayEv
// TODO    216 B  UIFightZodiac::setZodiacIndex                        _ZN13UIFightZodiac14setZodiacIndexEi
// TODO    196 B  UIFightZodiac::setFireWorksNumber                    _ZN13UIFightZodiac18setFireWorksNumberEi
// TODO    180 B  UIFightZodiac::OnCreate                              _ZN13UIFightZodiac8OnCreateEv
// TODO    160 B  UIFightZodiac::onBuyGacha                            _ZN13UIFightZodiac10onBuyGachaEi
// TODO    160 B  UIFightZodiac::UpdateFireWorksNumber                 _ZN13UIFightZodiac21UpdateFireWorksNumberEv
// TODO    136 B  UIFightZodiac::StartEffect                           _ZN13UIFightZodiac11StartEffectEii
// TODO    112 B  UIFightZodiac::closeDescriptionWidget                _ZN13UIFightZodiac22closeDescriptionWidgetEv
// TODO    112 B  UIFightZodiac::closeDisplayBoardWidget               _ZN13UIFightZodiac23closeDisplayBoardWidgetEv
// TODO    104 B  UIFightZodiac::GetLayoutName                         _ZN13UIFightZodiac13GetLayoutNameEv
// TODO     72 B  UIFightZodiac::DrawAll                               _ZN13UIFightZodiac7DrawAllEPN4Sexy10ModalFlagsEPNS0_8GraphicsE
// TODO     36 B  UIFightZodiac::~UIFightZodiac                        _ZN13UIFightZodiacD0Ev
// TODO     36 B  UIFightZodiac::Update                                _ZN13UIFightZodiac6UpdateEv
// TODO      4 B  UIFightZodiac::ScrollTargetReached                   _ZN13UIFightZodiac19ScrollTargetReachedEPN4Sexy12ScrollWidgetE
// TODO      4 B  UIFightZodiac::ScrollTargetInterrupted               _ZN13UIFightZodiac23ScrollTargetInterruptedEPN4Sexy12ScrollWidgetE
// TODO      4 B  UIFightZodiac::TabSelectionChanged                   _ZN13UIFightZodiac19TabSelectionChangedEi
// TODO      4 B  UIFightZodiac::Draw                                  _ZN13UIFightZodiac4DrawEPN4Sexy8GraphicsE
