// PvZ2/ui/UISpacetimeEnergy.cpp
//
// 27 function(s), 5604 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: UISpacetimeEnergy
//
// TODO   1112 B  UISpacetimeEnergy::Draw                              _ZN17UISpacetimeEnergy4DrawEPN4Sexy8GraphicsE
// TODO    512 B  UISpacetimeEnergy::onLoadComplete                    _ZN17UISpacetimeEnergy14onLoadCompleteEv
// TODO    480 B  UISpacetimeEnergy::InitDigitalNumber                 _ZN17UISpacetimeEnergy17InitDigitalNumberEv
// TODO    384 B  UISpacetimeEnergy::InitSpiralEffect                  _ZN17UISpacetimeEnergy16InitSpiralEffectEv
// TODO    376 B  UISpacetimeEnergy::UISpacetimeEnergy                 _ZN17UISpacetimeEnergyC2Ev
// TODO    376 B  UISpacetimeEnergy::UISpacetimeEnergy                 _ZN17UISpacetimeEnergyC1Ev
// TODO    296 B  UISpacetimeEnergy::~UISpacetimeEnergy                _ZN17UISpacetimeEnergyD2Ev
// TODO    296 B  UISpacetimeEnergy::~UISpacetimeEnergy                _ZN17UISpacetimeEnergyD1Ev
// TODO    268 B  UISpacetimeEnergy::UpdateDigitalNumber               _ZN17UISpacetimeEnergy19UpdateDigitalNumberEv
// TODO    224 B  UISpacetimeEnergy::UpdateSpiralMachineImage          _ZN17UISpacetimeEnergy24UpdateSpiralMachineImageEv
// TODO    208 B  UISpacetimeEnergy::InitEnergyRect                    _ZN17UISpacetimeEnergy14InitEnergyRectEv
// TODO    180 B  UISpacetimeEnergy::StaticClassInit                   _ZN17UISpacetimeEnergy15StaticClassInitEv
// TODO    164 B  UISpacetimeEnergy::DrawDigitalNumber                 _ZN17UISpacetimeEnergy17DrawDigitalNumberEPN4Sexy8GraphicsEii
// TODO    152 B  UISpacetimeEnergy::UpdateEnergyImage                 _ZN17UISpacetimeEnergy17UpdateEnergyImageEi
// TODO    124 B  UISpacetimeEnergy::StaticGetClass                    _ZN17UISpacetimeEnergy14StaticGetClassEv
// TODO    120 B  UISpacetimeEnergy::onUpdate                          _ZN17UISpacetimeEnergy8onUpdateEv
// TODO     92 B  UISpacetimeEnergy::registerForEvents                 _ZN17UISpacetimeEnergy17registerForEventsEv
// TODO     68 B  UISpacetimeEnergy::onCollectableCollectionFinished   _ZN17UISpacetimeEnergy31onCollectableCollectionFinishedEP11Collectable
// TODO     56 B  UISpacetimeEnergy::TimeEnergyTrigger                 _ZN17UISpacetimeEnergy17TimeEnergyTriggerEi
// TODO     44 B  UISpacetimeEnergy::StaticNew                         _ZN17UISpacetimeEnergy9StaticNewEv
// TODO     36 B  UISpacetimeEnergy::~UISpacetimeEnergy                _ZN17UISpacetimeEnergyD0Ev
// TODO     12 B  UISpacetimeEnergy::SetValueMax                       _ZN17UISpacetimeEnergy11SetValueMaxEf
// TODO      8 B  UISpacetimeEnergy::GetMaxValue                       _ZN17UISpacetimeEnergy11GetMaxValueEv
// TODO      4 B  UISpacetimeEnergy::initLoadingResourcesGroupList     _ZN17UISpacetimeEnergy29initLoadingResourcesGroupListEv
// TODO      4 B  UISpacetimeEnergy::unregisterForEvents               _ZN17UISpacetimeEnergy19unregisterForEventsEv
// TODO      4 B  UISpacetimeEnergy::updateState_Ready                 _ZN17UISpacetimeEnergy17updateState_ReadyEv
// TODO      4 B  UISpacetimeEnergy::onExitState_Loading               _ZN17UISpacetimeEnergy19onExitState_LoadingE11WidgetState
