// PvZ2/zombies/Weasel/ZombieAnimRig_Weasel.cpp
//
// 9 function(s), 656 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieAnimRig_Weasel
//
// TODO    180 B  ZombieAnimRig_Weasel::StaticClassInit                _ZN20ZombieAnimRig_Weasel15StaticClassInitEv
// TODO    124 B  ZombieAnimRig_Weasel::StaticGetClass                 _ZN20ZombieAnimRig_Weasel14StaticGetClassEv
// TODO    104 B  ZombieAnimRig_Weasel::getWalkAnimationName           _ZN20ZombieAnimRig_Weasel20getWalkAnimationNameEv
// TODO     56 B  ZombieAnimRig_Weasel::ZombieAnimRig_Weasel           _ZN20ZombieAnimRig_WeaselC2Ev
// TODO     56 B  ZombieAnimRig_Weasel::ZombieAnimRig_Weasel           _ZN20ZombieAnimRig_WeaselC1Ev
// TODO     44 B  ZombieAnimRig_Weasel::StaticNew                      _ZN20ZombieAnimRig_Weasel9StaticNewEv
// TODO     36 B  ZombieAnimRig_Weasel::~ZombieAnimRig_Weasel          _ZN20ZombieAnimRig_WeaselD0Ev
// TODO     28 B  ZombieAnimRig_Weasel::~ZombieAnimRig_Weasel          _ZN20ZombieAnimRig_WeaselD2Ev
// TODO     28 B  ZombieAnimRig_Weasel::~ZombieAnimRig_Weasel          _ZN20ZombieAnimRig_WeaselD1Ev
