// PvZ2/worldmap/WorldMap_BagButton.cpp
//
// 9 function(s), 1304 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: WorldMap_BagButton
//
// TODO    296 B  WorldMap_BagButton::WorldMap_BagButton               _ZN18WorldMap_BagButtonC2Ev
// TODO    296 B  WorldMap_BagButton::WorldMap_BagButton               _ZN18WorldMap_BagButtonC1Ev
// TODO    272 B  WorldMap_BagButton::onLoadComplete                   _ZN18WorldMap_BagButton14onLoadCompleteEv
// TODO    180 B  WorldMap_BagButton::StaticClassInit                  _ZN18WorldMap_BagButton15StaticClassInitEv
// TODO    124 B  WorldMap_BagButton::StaticGetClass                   _ZN18WorldMap_BagButton14StaticGetClassEv
// TODO     44 B  WorldMap_BagButton::StaticNew                        _ZN18WorldMap_BagButton9StaticNewEv
// TODO     36 B  WorldMap_BagButton::~WorldMap_BagButton              _ZN18WorldMap_BagButtonD0Ev
// TODO     28 B  WorldMap_BagButton::~WorldMap_BagButton              _ZN18WorldMap_BagButtonD2Ev
// TODO     28 B  WorldMap_BagButton::~WorldMap_BagButton              _ZN18WorldMap_BagButtonD1Ev
