// PvZ2/worldmap/WorldMap_AcFirstRechargeButton.cpp
//
// 18 function(s), 3640 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: WorldMap_AcFirstRechargeButton
//
// TODO    568 B  WorldMap_AcFirstRechargeButton::WorldMap_AcFirstRechargeButton _ZN30WorldMap_AcFirstRechargeButtonC2Ev
// TODO    568 B  WorldMap_AcFirstRechargeButton::WorldMap_AcFirstRechargeButton _ZN30WorldMap_AcFirstRechargeButtonC1Ev
// TODO    468 B  WorldMap_AcFirstRechargeButton::InitShinningAnim     _ZN30WorldMap_AcFirstRechargeButton16InitShinningAnimEv
// TODO    380 B  WorldMap_AcFirstRechargeButton::onButtonClicked      _ZN30WorldMap_AcFirstRechargeButton15onButtonClickedEv
// TODO    308 B  WorldMap_AcFirstRechargeButton::onNotifyRefreshActivityList _ZN30WorldMap_AcFirstRechargeButton27onNotifyRefreshActivityListEbRKSt3setIiSt4lessIiESaIiEE
// TODO    280 B  WorldMap_AcFirstRechargeButton::CheckActivated       _ZN30WorldMap_AcFirstRechargeButton14CheckActivatedEv
// TODO    224 B  WorldMap_AcFirstRechargeButton::CheckEnable          _ZN30WorldMap_AcFirstRechargeButton11CheckEnableEv
// TODO    188 B  WorldMap_AcFirstRechargeButton::Draw                 _ZN30WorldMap_AcFirstRechargeButton4DrawEPN4Sexy8GraphicsE
// TODO    180 B  WorldMap_AcFirstRechargeButton::StaticClassInit      _ZN30WorldMap_AcFirstRechargeButton15StaticClassInitEv
// TODO    124 B  WorldMap_AcFirstRechargeButton::StaticGetClass       _ZN30WorldMap_AcFirstRechargeButton14StaticGetClassEv
// TODO    100 B  WorldMap_AcFirstRechargeButton::~WorldMap_AcFirstRechargeButton _ZN30WorldMap_AcFirstRechargeButtonD2Ev
// TODO    100 B  WorldMap_AcFirstRechargeButton::~WorldMap_AcFirstRechargeButton _ZN30WorldMap_AcFirstRechargeButtonD1Ev
// TODO     60 B  WorldMap_AcFirstRechargeButton::onUpdate             _ZN30WorldMap_AcFirstRechargeButton8onUpdateEv
// TODO     44 B  WorldMap_AcFirstRechargeButton::StaticNew            _ZN30WorldMap_AcFirstRechargeButton9StaticNewEv
// TODO     36 B  WorldMap_AcFirstRechargeButton::~WorldMap_AcFirstRechargeButton _ZN30WorldMap_AcFirstRechargeButtonD0Ev
// TODO      4 B  WorldMap_AcFirstRechargeButton::OnNotyFirstRechargeSuc _ZN30WorldMap_AcFirstRechargeButton22OnNotyFirstRechargeSucEb
// TODO      4 B  WorldMap_AcFirstRechargeButton::BackToMap            _ZN30WorldMap_AcFirstRechargeButton9BackToMapEv
// TODO      4 B  WorldMap_AcFirstRechargeButton::onWorldLoaded        _ZN30WorldMap_AcFirstRechargeButton13onWorldLoadedEv
