// PvZ2/worldmap/WorldMapChooseDialog.cpp
//
// 27 function(s), 18700 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: WorldMapChooseDialog
//
// TODO   7308 B  WorldMapChooseDialog::InitView                       _ZN20WorldMapChooseDialog8InitViewEv
// TODO   1964 B  WorldMapChooseDialog::WorldMapChooseDialog           _ZN20WorldMapChooseDialogC1E12EDIALOG_TYPE
// TODO   1964 B  WorldMapChooseDialog::WorldMapChooseDialog           _ZN20WorldMapChooseDialogC2E12EDIALOG_TYPE
// TODO   1096 B  WorldMapChooseDialog::Draw                           _ZN20WorldMapChooseDialog4DrawEPN4Sexy8GraphicsE
// TODO    932 B  WorldMapChooseDialog::DrawOverlay                    _ZN20WorldMapChooseDialog11DrawOverlayEPN4Sexy8GraphicsE
// TODO    860 B  WorldMapChooseDialog::ButtonDepress                  _ZN20WorldMapChooseDialog13ButtonDepressEi
// TODO    552 B  WorldMapChooseDialog::ShowTheNoticeAboutPlantLevelUp _ZN20WorldMapChooseDialog30ShowTheNoticeAboutPlantLevelUpEv
// TODO    536 B  WorldMapChooseDialog::CreateButton                   _ZN20WorldMapChooseDialog12CreateButtonEiPN4Sexy5ImageEbb
// TODO    348 B  WorldMapChooseDialog::AddLaternTips                  _ZN20WorldMapChooseDialog13AddLaternTipsEv
// TODO    348 B  WorldMapChooseDialog::AddRedPackTips                 _ZN20WorldMapChooseDialog14AddRedPackTipsEv
// TODO    344 B  WorldMapChooseDialog::ShowTheNoticeAboutAvatar       _ZN20WorldMapChooseDialog24ShowTheNoticeAboutAvatarEv
// TODO    300 B  WorldMapChooseDialog::onDangerroomTutorialFinished   _ZN20WorldMapChooseDialog28onDangerroomTutorialFinishedEv
// TODO    276 B  WorldMapChooseDialog::onStarTutorialFinished         _ZN20WorldMapChooseDialog22onStarTutorialFinishedEv
// TODO    276 B  WorldMapChooseDialog::onLevelUpTutorialFinished      _ZN20WorldMapChooseDialog25onLevelUpTutorialFinishedEv
// TODO    276 B  WorldMapChooseDialog::onStoreTutorialFinished        _ZN20WorldMapChooseDialog23onStoreTutorialFinishedEv
// TODO    276 B  WorldMapChooseDialog::~WorldMapChooseDialog          _ZN20WorldMapChooseDialogD2Ev
// TODO    276 B  WorldMapChooseDialog::~WorldMapChooseDialog          _ZN20WorldMapChooseDialogD1Ev
// TODO    260 B  WorldMapChooseDialog::ShouldDrawTGIcon               _ZN20WorldMapChooseDialog16ShouldDrawTGIconEv
// TODO    156 B  WorldMapChooseDialog::Update                         _ZN20WorldMapChooseDialog6UpdateEv
// TODO    144 B  WorldMapChooseDialog::KillMyChildren                 _ZN20WorldMapChooseDialog14KillMyChildrenEv
// TODO     88 B  WorldMapChooseDialog::GetButtonPosition              _ZN20WorldMapChooseDialog17GetButtonPositionEi
// TODO     36 B  WorldMapChooseDialog::~WorldMapChooseDialog          _ZN20WorldMapChooseDialogD0Ev
// TODO     32 B  WorldMapChooseDialog::ButtonPress                    _ZN20WorldMapChooseDialog11ButtonPressEi
// TODO     16 B  WorldMapChooseDialog::OnOK                           _ZN20WorldMapChooseDialog4OnOKEv
// TODO     16 B  WorldMapChooseDialog::onCloseDialog                  _ZN20WorldMapChooseDialog13onCloseDialogEv
// TODO     12 B  WorldMapChooseDialog::GetButton                      _ZN20WorldMapChooseDialog9GetButtonEi
// TODO      8 B  WorldMapChooseDialog::ShowTheNoticeAbourTG           _ZN20WorldMapChooseDialog20ShowTheNoticeAbourTGEv
