//
//  PVZVersion.cpp
//
//  Base PvZ2C (arm64-v8a, 3.5.7).
//  Reconstructed by EvilHack28 on 2026-09-04.
//

#include "PVZVersion.h"

TotalRewardData& PVZVersion::GetUpdateReward(bool i_firstReward)
{
	return i_firstReward ? first_reward : second_reward;
}

PVZVersion::~PVZVersion()
{
}

#include "ReflectionBuilder.h"
#include <sstream>

bool PVZVersion::operator==(const PVZVersion& i_rhs) const
{
	return major == i_rhs.major && minor == i_rhs.minor && content == i_rhs.content;
}

bool PVZVersion::operator<(const PVZVersion& i_rhs) const
{
	if (major < i_rhs.major) return true;
	if (major == i_rhs.major)
	{
		if (minor < i_rhs.minor) return true;
		if (minor == i_rhs.minor) return content < i_rhs.content;
	}
	return false;
}

void PVZVersion::FromString(const std::string& i_version)
{
	if (i_version != "")
	{
		std::stringstream aStream(i_version, std::ios_base::out | std::ios_base::in);
		char aDot;
		aStream >> major;
		aStream >> aDot;
		aStream >> minor;
		aStream >> aDot;
		aStream >> content;
	}
}

RT_CLASS_IMPLEMENT(PVZVersion);

void PVZVersion::StaticClassInit()
{
	REFLECTION_ENUMBUILDER_BEGIN(PVZDB::TableIndex);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_INVALID, (PVZDB::TableIndex)-1);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_SCRATCHSPACE, (PVZDB::TableIndex)0);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_GAME, (PVZDB::TableIndex)1);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_VERSION, (PVZDB::TableIndex)2);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_MANIFEST, (PVZDB::TableIndex)3);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_LIVECONFIG, (PVZDB::TableIndex)4);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PROPERTYSHEETS, (PVZDB::TableIndex)5);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PLANTTYPES, (PVZDB::TableIndex)6);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_ZOMBIETYPES, (PVZDB::TableIndex)9);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PROJECTILETYPES, (PVZDB::TableIndex)12);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_GRIDITEMTYPES, (PVZDB::TableIndex)13);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_COLLECTABLETYPES, (PVZDB::TableIndex)15);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PRESENTTABLES, (PVZDB::TableIndex)16);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PRESENTTYPES, (PVZDB::TableIndex)17);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_UISHEETS, (PVZDB::TableIndex)18);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_NPCSHEETS, (PVZDB::TableIndex)19);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_LEVELMODULES, (PVZDB::TableIndex)20);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_POWERUPTYPES, (PVZDB::TableIndex)21);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_GAMEFEATURES, (PVZDB::TableIndex)22);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_BONUSTYPES, (PVZDB::TableIndex)24);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_STREAMINGMUSIC, (PVZDB::TableIndex)25);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_MAGENTO, (PVZDB::TableIndex)26);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_WORLDMAPS, (PVZDB::TableIndex)27);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_WORLDMAPLIST_NEW, (PVZDB::TableIndex)28);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_WORLDMAPEDITORDATA, (PVZDB::TableIndex)34);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_WORLDRESOURCES, (PVZDB::TableIndex)35);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_UIWIDGETS, (PVZDB::TableIndex)36);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_CURRENTLEVEL, (PVZDB::TableIndex)37);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_BOARDSTATE, (PVZDB::TableIndex)38);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_GAMEOBJECTS, (PVZDB::TableIndex)39);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_BOARDENTITIES, (PVZDB::TableIndex)40);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_ZOMBIES, (PVZDB::TableIndex)41);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PROJECTILES, (PVZDB::TableIndex)43);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PLANTS, (PVZDB::TableIndex)44);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_COLLECTABLES, (PVZDB::TableIndex)46);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_GRIDITEMS, (PVZDB::TableIndex)47);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_EFFECTS, (PVZDB::TableIndex)49);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_POPANIMRIGS, (PVZDB::TableIndex)50);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_SUBSYSTEMS, (PVZDB::TableIndex)51);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_LEVELMODULEINSTANCES, (PVZDB::TableIndex)52);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_POWERUPINSTANCES, (PVZDB::TableIndex)54);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PLAYER_PROFILES, (PVZDB::TableIndex)55);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PLAYER_INFO_DELTA, (PVZDB::TableIndex)56);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_SERVER_CONFIG, (PVZDB::TableIndex)59);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PURCHASE_CONFIG, (PVZDB::TableIndex)60);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_LOOTSAVEDATA, (PVZDB::TableIndex)61);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_DROP_ITEM_GROUPS, (PVZDB::TableIndex)62);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_DROP_ITEMS, (PVZDB::TableIndex)63);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_CHALLENGE_DROP_ITEMS, (PVZDB::TableIndex)64);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PROFILELOCALSAVEDATA, (PVZDB::TableIndex)65);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_DRAPERSAVEDATA, (PVZDB::TableIndex)66);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_TLogCache, (PVZDB::TableIndex)67);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_ACTIVITY_CONFIG, (PVZDB::TableIndex)68);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_STORE_GIFT_CONFIG, (PVZDB::TableIndex)74);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_UILAYOUT, (PVZDB::TableIndex)87);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_TRAVELLOG_STATUS, (PVZDB::TableIndex)154);
	REFLECTION_ENUMBUILDER_END(PVZDB::TableIndex);

	REFLECTION_CLASSBUILDER_BEGIN(FileVersionEntry);
		REFLECTION_CLASSBUILDER_FIELD(std::string, FileName);
		REFLECTION_CLASSBUILDER_FIELD(std::string, FileMD5);
		REFLECTION_CLASSBUILDER_FIELD(int, FileVersion);
		REFLECTION_CLASSBUILDER_FIELD(PVZDB::TableIndex, TableIndex);
	REFLECTION_CLASSBUILDER_END(FileVersionEntry);

	REFLECTION_CLASSBUILDER_BEGIN(VersionUpdateInfo);
		REFLECTION_CLASSBUILDER_FIELD(int, VersionCode);
		REFLECTION_CLASSBUILDER_FIELD(std::string, TitleImage);
		REFLECTION_CLASSBUILDER_FIELD(std::string, NoticeTextContent);
		REFLECTION_CLASSBUILDER_FIELD(std::string, VersionUrl);
	REFLECTION_CLASSBUILDER_END(VersionUpdateInfo);

	REFLECTION_ENUMBUILDER_BEGIN(UpdateRewardType);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(coins, (UpdateRewardType)0);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(gems, (UpdateRewardType)1);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(key, (UpdateRewardType)2);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(plant, (UpdateRewardType)3);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(avatar, (UpdateRewardType)4);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(plant_piece, (UpdateRewardType)5);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(avatar_piece, (UpdateRewardType)6);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(accessory, (UpdateRewardType)7);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(accessory_piece, (UpdateRewardType)8);
	REFLECTION_ENUMBUILDER_END(UpdateRewardType);

	REFLECTION_CLASSBUILDER_BEGIN(UpdateRewardData);
		REFLECTION_CLASSBUILDER_FIELD_RENAME(std::string, rewardItem, Item);
		REFLECTION_CLASSBUILDER_FIELD_RENAME(UpdateRewardType, rewardType, Type);
		REFLECTION_CLASSBUILDER_FIELD_RENAME(int, rewardAmount, Count);
	REFLECTION_CLASSBUILDER_END(UpdateRewardData);

	REFLECTION_CLASSBUILDER_BEGIN(RandomRewardData);
		REFLECTION_CLASSBUILDER_FIELD_RENAME(UpdateRewardData, randomData, ItemInfo);
		REFLECTION_CLASSBUILDER_FIELD_RENAME(int, weight, Weight);
	REFLECTION_CLASSBUILDER_END(RandomRewardData);

	REFLECTION_CLASSBUILDER_BEGIN(TotalRewardData);
		REFLECTION_CLASSBUILDER_FIELD_RENAME(std::vector<UpdateRewardData>, regularRewardList, RegularRewardList);
		REFLECTION_CLASSBUILDER_FIELD_RENAME(std::vector<RandomRewardData>, randomRewardList, RandomRewardList);
	REFLECTION_CLASSBUILDER_END(TotalRewardData);

	REFLECTION_CLASSBUILDER_BEGIN(PVZVersion);
	REFLECTION_CLASSBUILDER_RTCLASS_BIND;

		REFLECTION_CLASSBUILDER_ANCESTOR(PropertySheetBase);

		REFLECTION_CLASSBUILDER_FIELD(int, major);
		REFLECTION_CLASSBUILDER_FIELD(int, minor);
		REFLECTION_CLASSBUILDER_FIELD(int, content);
		REFLECTION_CLASSBUILDER_FIELD(bool, rvs_enable);
		REFLECTION_CLASSBUILDER_FIELD(std::string, version_app);
		REFLECTION_CLASSBUILDER_FIELD(std::string, new_version_app);
		REFLECTION_CLASSBUILDER_FIELD(std::string, update_url);
		REFLECTION_CLASSBUILDER_FIELD(VersionUpdateInfo, version_notice);
		REFLECTION_CLASSBUILDER_FIELD(std::vector<FileVersionEntry>, FilesVersion);
		REFLECTION_CLASSBUILDER_FIELD(std::string, manifest_md5);
		REFLECTION_CLASSBUILDER_FIELD(TotalRewardData, first_reward);
		REFLECTION_CLASSBUILDER_FIELD(TotalRewardData, second_reward);
		REFLECTION_CLASSBUILDER_FIELD(bool, reward_activated);
		REFLECTION_CLASSBUILDER_FIELD(int, reward_valid_date);
		REFLECTION_CLASSBUILDER_FIELD(std::string, reward_text_content);
	REFLECTION_CLASSBUILDER_END(PVZVersion);

}


PVZVersion::PVZVersion(const PVZVersion&) = default;
PVZVersion& PVZVersion::operator=(const PVZVersion&) = default;
PVZVersion& PVZVersion::operator=(PVZVersion&&) = default;
