//
//  PVZVersion.cpp
//
//  Base PvZ2C (arm64-v8a, 3.5.7).
//  Reconstructed by EvilHack28 on 2026-09-04.
//

#include "PVZVersion.h"
#include "ReflectionBuilder.h"
#include <sstream>

/////////////// Lifecycle ///////////////

PVZVersion::~PVZVersion()
{
}

PVZVersion::PVZVersion(const PVZVersion&) = default;

/////////////// Reflection ///////////////

RT_CLASS_IMPLEMENT(PVZVersion);

void PVZVersion::StaticClassInit()
{
	REFLECTION_ENUMBUILDER_BEGIN(PVZDB::TableIndex);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_INVALID, PVZDB::TABLE_INVALID);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_SCRATCHSPACE, PVZDB::TABLE_SCRATCHSPACE);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_GAME, PVZDB::TABLE_GAME);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_VERSION, PVZDB::TABLE_VERSION);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_MANIFEST, PVZDB::TABLE_MANIFEST);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_LIVECONFIG, PVZDB::TABLE_LIVECONFIG);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PROPERTYSHEETS, PVZDB::TABLE_PROPERTYSHEETS);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PLANTTYPES, PVZDB::TABLE_PLANTTYPES);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_ZOMBIETYPES, PVZDB::TABLE_ZOMBIETYPES);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PROJECTILETYPES, PVZDB::TABLE_PROJECTILETYPES);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_GRIDITEMTYPES, PVZDB::TABLE_GRIDITEMTYPES);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_COLLECTABLETYPES, PVZDB::TABLE_COLLECTABLETYPES);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PRESENTTABLES, PVZDB::TABLE_PRESENTTABLES);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PRESENTTYPES, PVZDB::TABLE_PRESENTTYPES);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_UISHEETS, PVZDB::TABLE_UISHEETS);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_NPCSHEETS, PVZDB::TABLE_NPCSHEETS);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_LEVELMODULES, PVZDB::TABLE_LEVELMODULES);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_POWERUPTYPES, PVZDB::TABLE_POWERUPTYPES);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_GAMEFEATURES, PVZDB::TABLE_GAMEFEATURES);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_BONUSTYPES, PVZDB::TABLE_BONUSTYPES);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_STREAMINGMUSIC, PVZDB::TABLE_STREAMINGMUSIC);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_MAGENTO, PVZDB::TABLE_MAGENTO);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_WORLDMAPS, PVZDB::TABLE_WORLDMAPS);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_WORLDMAPLIST_NEW, PVZDB::TABLE_WORLDMAPLIST_NEW);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_WORLDMAPEDITORDATA, PVZDB::TABLE_WORLDRESOURCES);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_WORLDRESOURCES, PVZDB::TABLE_RESERVED_35);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_UIWIDGETS, PVZDB::TABLE_UIWIDGETS);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_CURRENTLEVEL, PVZDB::TABLE_CURRENTLEVEL);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_BOARDSTATE, PVZDB::TABLE_BOARDSTATE);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_GAMEOBJECTS, PVZDB::TABLE_GAMEOBJECTS);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_BOARDENTITIES, PVZDB::TABLE_BOARDENTITIES);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_ZOMBIES, PVZDB::TABLE_ZOMBIES);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PROJECTILES, PVZDB::TABLE_PROJECTILES);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PLANTS, PVZDB::TABLE_PLANTS);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_COLLECTABLES, PVZDB::TABLE_COLLECTABLES);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_GRIDITEMS, PVZDB::TABLE_GRIDITEMS);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_EFFECTS, PVZDB::TABLE_EFFECTS);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_POPANIMRIGS, PVZDB::TABLE_POPANIMRIGS);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_SUBSYSTEMS, PVZDB::TABLE_SUBSYSTEMS);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_LEVELMODULEINSTANCES, PVZDB::TABLE_LEVELMODULEINSTANCES);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_POWERUPINSTANCES, PVZDB::TABLE_POWERUPINSTANCES);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PLAYER_PROFILES, PVZDB::TABLE_PLAYER_PROFILES);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PLAYER_INFO_DELTA, PVZDB::TABLE_PLAYER_INFO_DELTA);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_SERVER_CONFIG, PVZDB::TABLE_SERVER_CONFIG);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PURCHASE_CONFIG, PVZDB::TABLE_PURCHASE_CONFIG);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_LOOTSAVEDATA, PVZDB::TABLE_LOOTSAVEDATA);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_DROP_ITEM_GROUPS, PVZDB::TABLE_DROP_ITEM_GROUPS);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_DROP_ITEMS, PVZDB::TABLE_DROP_ITEMS);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_CHALLENGE_DROP_ITEMS, PVZDB::TABLE_CHALLENGE_DROP_ITEMS);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_PROFILELOCALSAVEDATA, PVZDB::TABLE_PROFILELOCALSAVEDATA);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_DRAPERSAVEDATA, PVZDB::TABLE_DRAPERSAVEDATA);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_TLogCache, PVZDB::TABLE_TLogCache);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_ACTIVITY_CONFIG, PVZDB::TABLE_ACTIVITY_CONFIG);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_STORE_GIFT_CONFIG, PVZDB::TABLE_STORE_GIFT_CONFIG);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_UILAYOUT, PVZDB::TABLE_UILAYOUT);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(TABLE_TRAVELLOG_STATUS, (PVZDB::TableIndex)154);
	REFLECTION_ENUMBUILDER_END(PVZDB::TableIndex);

	REFLECTION_CLASSBUILDER_BEGIN(FileVersionEntry);
		REFLECTION_CLASSBUILDER_FIELD(std::string, FileName);
		REFLECTION_CLASSBUILDER_FIELD(std::string, FileMD5);
		REFLECTION_CLASSBUILDER_FIELD(int, FileVersion);
		REFLECTION_CLASSBUILDER_FIELD(PVZDB::TableIndex, TableIndex);
	REFLECTION_CLASSBUILDER_END(FileVersionEntry);

	REFLECTION_CLASSBUILDER_BEGIN(VersionUpdateInfo);
		REFLECTION_CLASSBUILDER_FIELD(int, VersionCode);
		REFLECTION_CLASSBUILDER_FIELD(std::string, TitleImage);
		REFLECTION_CLASSBUILDER_FIELD(std::string, NoticeTextContent);
		REFLECTION_CLASSBUILDER_FIELD(std::string, VersionUrl);
	REFLECTION_CLASSBUILDER_END(VersionUpdateInfo);

	REFLECTION_ENUMBUILDER_BEGIN(UpdateRewardType);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(coins, E_UPDATE_COINS_REWARD);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(gems, E_UPDATE_GEMS_REWARD);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(key, E_UPDATE_KEY_REWARD);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(plant, E_UPDATE_PLANT_REWARD);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(avatar, E_UPDATE_AVATAR_REWARD);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(plant_piece, E_UPDATE_PLANT_PIECE_REWARD);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(avatar_piece, E_UPDATE_AVATAR_PIECE_REWARD);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(accessory, E_UPDATE_ACCESSORY_REWARD);
		REFLECTION_ENUMBUILDER_MEMBER_RENAME(accessory_piece, E_UPDATE_ACCESSORY_PIECE_REWARD);
	REFLECTION_ENUMBUILDER_END(UpdateRewardType);

	REFLECTION_CLASSBUILDER_BEGIN(UpdateRewardData);
		REFLECTION_CLASSBUILDER_FIELD_RENAME(std::string, rewardItem, Item);
		REFLECTION_CLASSBUILDER_FIELD_RENAME(UpdateRewardType, rewardType, Type);
		REFLECTION_CLASSBUILDER_FIELD_RENAME(int, rewardAmount, Count);
	REFLECTION_CLASSBUILDER_END(UpdateRewardData);

	REFLECTION_CLASSBUILDER_BEGIN(RandomRewardData);
		REFLECTION_CLASSBUILDER_FIELD_RENAME(UpdateRewardData, randomData, ItemInfo);
		REFLECTION_CLASSBUILDER_FIELD_RENAME(int, weight, Weight);
	REFLECTION_CLASSBUILDER_END(RandomRewardData);

	REFLECTION_CLASSBUILDER_BEGIN(TotalRewardData);
		REFLECTION_CLASSBUILDER_FIELD_RENAME(std::vector<UpdateRewardData>, regularRewardList, RegularRewardList);
		REFLECTION_CLASSBUILDER_FIELD_RENAME(std::vector<RandomRewardData>, randomRewardList, RandomRewardList);
	REFLECTION_CLASSBUILDER_END(TotalRewardData);

	REFLECTION_CLASSBUILDER_BEGIN(PVZVersion);
	REFLECTION_CLASSBUILDER_RTCLASS_BIND;

		REFLECTION_CLASSBUILDER_ANCESTOR(PropertySheetBase);

		REFLECTION_CLASSBUILDER_FIELD(int, major);
		REFLECTION_CLASSBUILDER_FIELD(int, minor);
		REFLECTION_CLASSBUILDER_FIELD(int, content);
		REFLECTION_CLASSBUILDER_FIELD(bool, rvs_enable);
		REFLECTION_CLASSBUILDER_FIELD(std::string, version_app);
		REFLECTION_CLASSBUILDER_FIELD(std::string, new_version_app);
		REFLECTION_CLASSBUILDER_FIELD(std::string, update_url);
		REFLECTION_CLASSBUILDER_FIELD(VersionUpdateInfo, version_notice);
		REFLECTION_CLASSBUILDER_FIELD(std::vector<FileVersionEntry>, FilesVersion);
		REFLECTION_CLASSBUILDER_FIELD(std::string, manifest_md5);
		REFLECTION_CLASSBUILDER_FIELD(TotalRewardData, first_reward);
		REFLECTION_CLASSBUILDER_FIELD(TotalRewardData, second_reward);
		REFLECTION_CLASSBUILDER_FIELD(bool, reward_activated);
		REFLECTION_CLASSBUILDER_FIELD(int, reward_valid_date);
		REFLECTION_CLASSBUILDER_FIELD(std::string, reward_text_content);
	REFLECTION_CLASSBUILDER_END(PVZVersion);

}

/////////////// Accessors ///////////////

TotalRewardData& PVZVersion::GetUpdateReward(bool i_firstReward)
{
	return i_firstReward ? first_reward : second_reward;
}

/////////////// Logic ///////////////

bool PVZVersion::operator==(const PVZVersion& i_rhs) const
{
	return major == i_rhs.major && minor == i_rhs.minor && content == i_rhs.content;
}

bool PVZVersion::operator<(const PVZVersion& i_rhs) const
{
	if (major < i_rhs.major) return true;
	if (major == i_rhs.major)
	{
		if (minor < i_rhs.minor) return true;
		if (minor == i_rhs.minor) return content < i_rhs.content;
	}
	return false;
}

void PVZVersion::FromString(const std::string& i_version)
{
	if (i_version != "")
	{
		std::stringstream aStream(i_version, std::ios_base::out | std::ios_base::in);
		char aDot;
		aStream >> major;
		aStream >> aDot;
		aStream >> minor;
		aStream >> aDot;
		aStream >> content;
	}
}

PVZVersion& PVZVersion::operator=(const PVZVersion&) = default;

PVZVersion& PVZVersion::operator=(PVZVersion&&) = default;
