// PvZ2/plants/Bromelblade/PlantAnimRig_Bromelblade.cpp
//
// 10 function(s), 696 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_Bromelblade
//
// TODO    180 B  PlantAnimRig_Bromelblade::StaticClassInit            _ZN24PlantAnimRig_Bromelblade15StaticClassInitEv
// TODO    128 B  PlantAnimRig_Bromelblade::getPlantFoodMainAnimName   _ZN24PlantAnimRig_Bromelblade24getPlantFoodMainAnimNameEv
// TODO    124 B  PlantAnimRig_Bromelblade::StaticGetClass             _ZN24PlantAnimRig_Bromelblade14StaticGetClassEv
// TODO     60 B  PlantAnimRig_Bromelblade::PlantAnimRig_Bromelblade   _ZN24PlantAnimRig_BromelbladeC2Ev
// TODO     60 B  PlantAnimRig_Bromelblade::PlantAnimRig_Bromelblade   _ZN24PlantAnimRig_BromelbladeC1Ev
// TODO     44 B  PlantAnimRig_Bromelblade::StaticNew                  _ZN24PlantAnimRig_Bromelblade9StaticNewEv
// TODO     36 B  PlantAnimRig_Bromelblade::~PlantAnimRig_Bromelblade  _ZN24PlantAnimRig_BromelbladeD0Ev
// TODO     28 B  PlantAnimRig_Bromelblade::~PlantAnimRig_Bromelblade  _ZN24PlantAnimRig_BromelbladeD2Ev
// TODO     28 B  PlantAnimRig_Bromelblade::~PlantAnimRig_Bromelblade  _ZN24PlantAnimRig_BromelbladeD1Ev
// TODO      8 B  PlantAnimRig_Bromelblade::SetAvatar                  _ZN24PlantAnimRig_Bromelblade9SetAvatarEb
