// PvZ2/plants/Wintersweet/PlantAnimRig_Wintersweet.cpp
//
// 10 function(s), 1220 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_Wintersweet
//
// TODO    580 B  PlantAnimRig_Wintersweet::updateIdleAnimState        _ZN24PlantAnimRig_Wintersweet19updateIdleAnimStateERKSsi
// TODO    144 B  PlantAnimRig_Wintersweet::playGrowAnim               _ZN24PlantAnimRig_Wintersweet12playGrowAnimERKSs20RtReflectionDelegateIN4Sexy9Delegate1IS1_EEE
// TODO    128 B  PlantAnimRig_Wintersweet::getPlantFoodMainAnimName   _ZN24PlantAnimRig_Wintersweet24getPlantFoodMainAnimNameEv
// TODO    120 B  PlantAnimRig_Wintersweet::StaticGetClass             _ZN24PlantAnimRig_Wintersweet14StaticGetClassEv
// TODO     56 B  PlantAnimRig_Wintersweet::PlantAnimRig_Wintersweet   _ZN24PlantAnimRig_WintersweetC2Ev
// TODO     56 B  PlantAnimRig_Wintersweet::PlantAnimRig_Wintersweet   _ZN24PlantAnimRig_WintersweetC1Ev
// TODO     44 B  PlantAnimRig_Wintersweet::StaticNew                  _ZN24PlantAnimRig_Wintersweet9StaticNewEv
// TODO     36 B  PlantAnimRig_Wintersweet::~PlantAnimRig_Wintersweet  _ZN24PlantAnimRig_WintersweetD0Ev
// TODO     28 B  PlantAnimRig_Wintersweet::~PlantAnimRig_Wintersweet  _ZN24PlantAnimRig_WintersweetD2Ev
// TODO     28 B  PlantAnimRig_Wintersweet::~PlantAnimRig_Wintersweet  _ZN24PlantAnimRig_WintersweetD1Ev
