// PvZ2/plants/Wintersweet/Plant_Wintersweet.cpp
//
// 18 function(s), 3460 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantWintersweet
//
// TODO    876 B  PlantWintersweet::normalFire                         _ZN16PlantWintersweet10normalFireEN4Sexy9RtWeakPtrI6ZombieEEi11PlantWeapon
// TODO    524 B  PlantWintersweet::setState                           _ZN16PlantWintersweet8setStateEj
// TODO    484 B  PlantWintersweet::onAnimStoppedCallback              _ZN16PlantWintersweet21onAnimStoppedCallbackERKSs
// TODO    240 B  PlantWintersweet::separatePlantfoodFlower            _ZN16PlantWintersweet23separatePlantfoodFlowerEv
// TODO    224 B  PlantWintersweet::UpdateActions                      _ZN16PlantWintersweet13UpdateActionsEv
// TODO    180 B  PlantWintersweet::StaticClassInit                    _ZN16PlantWintersweet15StaticClassInitEv
// TODO    168 B  PlantWintersweet::CancelPlantfood                    _ZN16PlantWintersweet15CancelPlantfoodEv
// TODO    160 B  PlantWintersweet::ApplyPlantfood                     _ZN16PlantWintersweet14ApplyPlantfoodEv
// TODO    128 B  PlantWintersweet::Fire                               _ZN16PlantWintersweet4FireEN4Sexy9RtWeakPtrI6ZombieEEi11PlantWeapon
// TODO    124 B  PlantWintersweet::StaticGetClass                     _ZN16PlantWintersweet14StaticGetClassEv
// TODO     56 B  PlantWintersweet::Initialize                         _ZN16PlantWintersweet10InitializeEv
// TODO     52 B  PlantWintersweet::PlantWintersweet                   _ZN16PlantWintersweetC2Ev
// TODO     52 B  PlantWintersweet::PlantWintersweet                   _ZN16PlantWintersweetC1Ev
// TODO     52 B  PlantWintersweet::~PlantWintersweet                  _ZN16PlantWintersweetD2Ev
// TODO     52 B  PlantWintersweet::~PlantWintersweet                  _ZN16PlantWintersweetD1Ev
// TODO     44 B  PlantWintersweet::StaticNew                          _ZN16PlantWintersweet9StaticNewEv
// TODO     36 B  PlantWintersweet::~PlantWintersweet                  _ZN16PlantWintersweetD0Ev
// TODO      8 B  PlantWintersweet::CanApplyPlantfood                  _ZN16PlantWintersweet17CanApplyPlantfoodEv
