// PvZ2/plants/PrimalSunflower/PlantAnimRig_PrimalSunflower.cpp
//
// 16 function(s), 1664 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_PrimalSunflower
//
// TODO    288 B  PlantAnimRig_PrimalSunflower::PlayIdleLooped         _ZN28PlantAnimRig_PrimalSunflower14PlayIdleLoopedEv
// TODO    232 B  PlantAnimRig_PrimalSunflower::PlayLevel5Sun          _ZN28PlantAnimRig_PrimalSunflower13PlayLevel5SunEiN4Sexy9Delegate1IRKSsEE
// TODO    180 B  PlantAnimRig_PrimalSunflower::StaticClassInit        _ZN28PlantAnimRig_PrimalSunflower15StaticClassInitEv
// TODO    148 B  PlantAnimRig_PrimalSunflower::PlayLevel5CoolDown     _ZN28PlantAnimRig_PrimalSunflower18PlayLevel5CoolDownEN4Sexy9Delegate1IRKSsEE
// TODO    124 B  PlantAnimRig_PrimalSunflower::StaticGetClass         _ZN28PlantAnimRig_PrimalSunflower14StaticGetClassEv
// TODO    104 B  PlantAnimRig_PrimalSunflower::getLevel5Sun1          _ZN28PlantAnimRig_PrimalSunflower13getLevel5Sun1Ev
// TODO    104 B  PlantAnimRig_PrimalSunflower::getLevel5Sun2          _ZN28PlantAnimRig_PrimalSunflower13getLevel5Sun2Ev
// TODO    104 B  PlantAnimRig_PrimalSunflower::getLevel5Sun3          _ZN28PlantAnimRig_PrimalSunflower13getLevel5Sun3Ev
// TODO    104 B  PlantAnimRig_PrimalSunflower::getLevel5CoolDown      _ZN28PlantAnimRig_PrimalSunflower17getLevel5CoolDownEv
// TODO     60 B  PlantAnimRig_PrimalSunflower::PlantAnimRig_PrimalSunflower _ZN28PlantAnimRig_PrimalSunflowerC2Ev
// TODO     60 B  PlantAnimRig_PrimalSunflower::PlantAnimRig_PrimalSunflower _ZN28PlantAnimRig_PrimalSunflowerC1Ev
// TODO     44 B  PlantAnimRig_PrimalSunflower::StaticNew              _ZN28PlantAnimRig_PrimalSunflower9StaticNewEv
// TODO     36 B  PlantAnimRig_PrimalSunflower::~PlantAnimRig_PrimalSunflower _ZN28PlantAnimRig_PrimalSunflowerD0Ev
// TODO     28 B  PlantAnimRig_PrimalSunflower::~PlantAnimRig_PrimalSunflower _ZN28PlantAnimRig_PrimalSunflowerD2Ev
// TODO     28 B  PlantAnimRig_PrimalSunflower::~PlantAnimRig_PrimalSunflower _ZN28PlantAnimRig_PrimalSunflowerD1Ev
// TODO     20 B  PlantAnimRig_PrimalSunflower::onAnimStopped          _ZN28PlantAnimRig_PrimalSunflower13onAnimStoppedEv
