// PvZ2/zombies/ZombossMech_SkyCity/ZombieAnimRig_ZombossMech_SkyCity.cpp
//
// 23 function(s), 3188 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieAnimRig_ZombossMech_SkyCity
//
// TODO    200 B  ZombieAnimRig_ZombossMech_SkyCity::PlayRushDownFly   _ZN33ZombieAnimRig_ZombossMech_SkyCity15PlayRushDownFlyE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    200 B  ZombieAnimRig_ZombossMech_SkyCity::PlayRushDown      _ZN33ZombieAnimRig_ZombossMech_SkyCity12PlayRushDownE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    200 B  ZombieAnimRig_ZombossMech_SkyCity::PlayThrowAircraftStart _ZN33ZombieAnimRig_ZombossMech_SkyCity22PlayThrowAircraftStartE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    200 B  ZombieAnimRig_ZombossMech_SkyCity::PlayLineShootStart _ZN33ZombieAnimRig_ZombossMech_SkyCity18PlayLineShootStartE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    200 B  ZombieAnimRig_ZombossMech_SkyCity::PlaySandstorm     _ZN33ZombieAnimRig_ZombossMech_SkyCity13PlaySandstormE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    200 B  ZombieAnimRig_ZombossMech_SkyCity::PlayAttackMiddleNearBy _ZN33ZombieAnimRig_ZombossMech_SkyCity22PlayAttackMiddleNearByE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    200 B  ZombieAnimRig_ZombossMech_SkyCity::PlayAttackUpNearBy _ZN33ZombieAnimRig_ZombossMech_SkyCity18PlayAttackUpNearByE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    200 B  ZombieAnimRig_ZombossMech_SkyCity::PlayAttackDownNearBy _ZN33ZombieAnimRig_ZombossMech_SkyCity20PlayAttackDownNearByE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    200 B  ZombieAnimRig_ZombossMech_SkyCity::PlaySpwanInAirplane _ZN33ZombieAnimRig_ZombossMech_SkyCity19PlaySpwanInAirplaneE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    200 B  ZombieAnimRig_ZombossMech_SkyCity::PlayCollectEnergy _ZN33ZombieAnimRig_ZombossMech_SkyCity17PlayCollectEnergyE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    200 B  ZombieAnimRig_ZombossMech_SkyCity::PlayBarrageEnd    _ZN33ZombieAnimRig_ZombossMech_SkyCity14PlayBarrageEndE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    180 B  ZombieAnimRig_ZombossMech_SkyCity::StaticClassInit   _ZN33ZombieAnimRig_ZombossMech_SkyCity15StaticClassInitEv
// TODO    176 B  ZombieAnimRig_ZombossMech_SkyCity::PlayBarrage       _ZN33ZombieAnimRig_ZombossMech_SkyCity11PlayBarrageEv
// TODO    124 B  ZombieAnimRig_ZombossMech_SkyCity::StaticGetClass    _ZN33ZombieAnimRig_ZombossMech_SkyCity14StaticGetClassEv
// TODO    124 B  ZombieAnimRig_ZombossMech_SkyCity::PlayIdle          _ZN33ZombieAnimRig_ZombossMech_SkyCity8PlayIdleE20RtReflectionDelegateIN4Sexy9Delegate3IRKSsS4_iEEE
// TODO    112 B  ZombieAnimRig_ZombossMech_SkyCity::PlayWalkForDirection _ZN33ZombieAnimRig_ZombossMech_SkyCity20PlayWalkForDirectionE20ZombossWalkDirection20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO     64 B  ZombieAnimRig_ZombossMech_SkyCity::ZombieAnimRig_ZombossMech_SkyCity _ZN33ZombieAnimRig_ZombossMech_SkyCityC2Ev
// TODO     64 B  ZombieAnimRig_ZombossMech_SkyCity::ZombieAnimRig_ZombossMech_SkyCity _ZN33ZombieAnimRig_ZombossMech_SkyCityC1Ev
// TODO     44 B  ZombieAnimRig_ZombossMech_SkyCity::StaticNew         _ZN33ZombieAnimRig_ZombossMech_SkyCity9StaticNewEv
// TODO     36 B  ZombieAnimRig_ZombossMech_SkyCity::~ZombieAnimRig_ZombossMech_SkyCity _ZN33ZombieAnimRig_ZombossMech_SkyCityD0Ev
// TODO     28 B  ZombieAnimRig_ZombossMech_SkyCity::~ZombieAnimRig_ZombossMech_SkyCity _ZN33ZombieAnimRig_ZombossMech_SkyCityD2Ev
// TODO     28 B  ZombieAnimRig_ZombossMech_SkyCity::~ZombieAnimRig_ZombossMech_SkyCity _ZN33ZombieAnimRig_ZombossMech_SkyCityD1Ev
// TODO      8 B  ZombieAnimRig_ZombossMech_SkyCity::onPostPlayCalled  _ZN33ZombieAnimRig_ZombossMech_SkyCity16onPostPlayCalledEv
