// PvZ2/AnimRigLayerSet.cpp
//
// 10 function(s), 1012 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: AnimRigLayerSet
//
// TODO    352 B  AnimRigLayerSet::ShowSet                             _ZN15AnimRigLayerSet7ShowSetEP10PopAnimRigSs
// TODO    180 B  AnimRigLayerSet::StaticClassInit                     _ZN15AnimRigLayerSet15StaticClassInitEv
// TODO    124 B  AnimRigLayerSet::StaticGetClass                      _ZN15AnimRigLayerSet14StaticGetClassEv
// TODO     60 B  AnimRigLayerSet::~AnimRigLayerSet                    _ZN15AnimRigLayerSetD2Ev
// TODO     60 B  AnimRigLayerSet::~AnimRigLayerSet                    _ZN15AnimRigLayerSetD1Ev
// TODO     60 B  AnimRigLayerSet::AnimRigLayerSet                     _ZN15AnimRigLayerSetC1Ev
// TODO     60 B  AnimRigLayerSet::AnimRigLayerSet                     _ZN15AnimRigLayerSetC2Ev
// TODO     44 B  AnimRigLayerSet::StaticNew                           _ZN15AnimRigLayerSet9StaticNewEv
// TODO     36 B  AnimRigLayerSet::~AnimRigLayerSet                    _ZN15AnimRigLayerSetD0Ev
// TODO     36 B  AnimRigLayerSet::AddSet                              _ZN15AnimRigLayerSet6AddSetESsSt6vectorISsSaISsEE
