// PvZ2/DandelionBomb.cpp
//
// 27 function(s), 9056 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: DandelionBomb
//
// TODO   2764 B  DandelionBomb::onUpdate                              _ZN13DandelionBomb8onUpdateEv
// TODO   1400 B  DandelionBomb::findTarget                            _ZN13DandelionBomb10findTargetEv
// TODO    924 B  DandelionBomb::calcAreaDamage                        _ZN13DandelionBomb14calcAreaDamageEii
// TODO    544 B  DandelionBomb::dropBomb                              _ZN13DandelionBomb8dropBombEv
// TODO    464 B  DandelionBomb::onBombExplode                         _ZN13DandelionBomb13onBombExplodeEP16StandaloneEffect
// TODO    440 B  DandelionBomb::DandelionBomb                         _ZN13DandelionBombC2Ev
// TODO    440 B  DandelionBomb::DandelionBomb                         _ZN13DandelionBombC1Ev
// TODO    320 B  DandelionBomb::onPlantFinished                       _ZN13DandelionBomb15onPlantFinishedERKSs
// TODO    256 B  DandelionBomb::onDraw                                _ZN13DandelionBomb6onDrawEPN4Sexy8GraphicsE
// TODO    244 B  DandelionBomb::SetOwner                              _ZN13DandelionBomb8SetOwnerEN4Sexy9RtWeakPtrI11BoardEntityEE
// TODO    212 B  DandelionBomb::onBombRespawn                         _ZN13DandelionBomb13onBombRespawnERKSs
// TODO    180 B  DandelionBomb::StaticClassInit                       _ZN13DandelionBomb15StaticClassInitEv
// TODO    164 B  DandelionBomb::CreateAnimRig                         _ZN13DandelionBomb13CreateAnimRigEb
// TODO    124 B  DandelionBomb::StaticGetClass                        _ZN13DandelionBomb14StaticGetClassEv
// TODO    104 B  DandelionBomb::~DandelionBomb                        _ZN13DandelionBombD2Ev
// TODO    104 B  DandelionBomb::~DandelionBomb                        _ZN13DandelionBombD1Ev
// TODO     92 B  DandelionBomb::onPlaceOnBoard                        _ZN13DandelionBomb14onPlaceOnBoardEv
// TODO     48 B  DandelionBomb::setState                              _ZN13DandelionBomb8setStateEj
// TODO     44 B  DandelionBomb::StaticNew                             _ZN13DandelionBomb9StaticNewEv
// TODO     40 B  DandelionBomb::getAnimRig                            _ZN13DandelionBomb10getAnimRigEv
// TODO     36 B  DandelionBomb::onDestroy                             _ZN13DandelionBomb9onDestroyEv
// TODO     36 B  DandelionBomb::~DandelionBomb                        _ZN13DandelionBombD0Ev
// TODO     28 B  DandelionBomb::SetPlantfood                          _ZN13DandelionBomb12SetPlantfoodEb
// TODO     28 B  DandelionBomb::onDieFinished                         _ZN13DandelionBomb13onDieFinishedERKSs
// TODO      8 B  DandelionBomb::SetPlantPos                           _ZN13DandelionBomb11SetPlantPosERKN4Sexy11SexyVector3E
// TODO      8 B  DandelionBomb::SetTarget                             _ZN13DandelionBomb9SetTargetEN4Sexy9RtWeakPtrI11BoardEntityEE
// TODO      4 B  DandelionBomb::onInitialized                         _ZN13DandelionBomb13onInitializedEv
