// PvZ2/EliminateItem.cpp
//
// 28 function(s), 6548 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: EliminateItem
//
// TODO    876 B  EliminateItem::IsNearBy                              _ZN13EliminateItem8IsNearByEPS_
// TODO    816 B  EliminateItem::takeBlockDamge                        _ZN13EliminateItem14takeBlockDamgeEv
// TODO    724 B  EliminateItem::setBlock                              _ZN13EliminateItem8setBlockEv
// TODO    556 B  EliminateItem::EliminateItemInitialize               _ZN13EliminateItem23EliminateItemInitializeE14EEliminateType
// TODO    504 B  EliminateItem::onPlantFoodAnimDone                   _ZN13EliminateItem19onPlantFoodAnimDoneERKSs
// TODO    468 B  EliminateItem::onDraw                                _ZN13EliminateItem6onDrawEPN4Sexy8GraphicsE
// TODO    356 B  EliminateItem::playShowTip                           _ZN13EliminateItem11playShowTipEb
// TODO    344 B  EliminateItem::setSelect                             _ZN13EliminateItem9setSelectEb
// TODO    324 B  EliminateItem::playPlantFood                         _ZN13EliminateItem13playPlantFoodEv
// TODO    320 B  EliminateItem::onUpdate                              _ZN13EliminateItem8onUpdateEv
// TODO    180 B  EliminateItem::StaticClassInit                       _ZN13EliminateItem15StaticClassInitEv
// TODO    128 B  EliminateItem::onDestroy                             _ZN13EliminateItem9onDestroyEv
// TODO    124 B  EliminateItem::StaticGetClass                        _ZN13EliminateItem14StaticGetClassEv
// TODO    120 B  EliminateItem::IsNearByPlantFood                     _ZN13EliminateItem17IsNearByPlantFoodEPS_
// TODO    120 B  EliminateItem::EliminateItem                         _ZN13EliminateItemC2Ev
// TODO    120 B  EliminateItem::EliminateItem                         _ZN13EliminateItemC1Ev
// TODO    100 B  EliminateItem::GetAttackRect                         _ZN13EliminateItem13GetAttackRectEv
// TODO     80 B  EliminateItem::onBlockDamge2                         _ZN13EliminateItem13onBlockDamge2EP16StandaloneEffect
// TODO     72 B  EliminateItem::~EliminateItem                        _ZN13EliminateItemD2Ev
// TODO     72 B  EliminateItem::~EliminateItem                        _ZN13EliminateItemD1Ev
// TODO     44 B  EliminateItem::StaticNew                             _ZN13EliminateItem9StaticNewEv
// TODO     36 B  EliminateItem::~EliminateItem                        _ZN13EliminateItemD0Ev
// TODO     32 B  EliminateItem::CanTouchable                          _ZN13EliminateItem12CanTouchableEv
// TODO      8 B  EliminateItem::IsSelect                              _ZN13EliminateItem8IsSelectEv
// TODO      8 B  EliminateItem::setAlpha                              _ZN13EliminateItem8setAlphaEb
// TODO      8 B  EliminateItem::IsBlock                               _ZN13EliminateItem7IsBlockEv
// TODO      4 B  EliminateItem::onBlockDamge1                         _ZN13EliminateItem13onBlockDamge1EP16StandaloneEffect
// TODO      4 B  EliminateItem::onDrawShadow                          _ZN13EliminateItem12onDrawShadowEPN4Sexy8GraphicsE
