// PvZ2/GameCenterProxy.cpp
//
// 13 function(s), 68 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: GameCenterProxy
//
// TODO     12 B  GameCenterProxy::GameCenterProxy                     _ZN15GameCenterProxyC1Ev
// TODO     12 B  GameCenterProxy::GameCenterProxy                     _ZN15GameCenterProxyC2Ev
// TODO      4 B  GameCenterProxy::FetchAchievements                   _ZN15GameCenterProxy17FetchAchievementsEv
// TODO      4 B  GameCenterProxy::~GameCenterProxy                    _ZN15GameCenterProxyD1Ev
// TODO      4 B  GameCenterProxy::Connect                             _ZN15GameCenterProxy7ConnectEv
// TODO      4 B  GameCenterProxy::QueueAchievement                    _ZN15GameCenterProxy16QueueAchievementERKSsf
// TODO      4 B  GameCenterProxy::SubmitAchievements                  _ZN15GameCenterProxy18SubmitAchievementsEv
// TODO      4 B  GameCenterProxy::ResetAchievements                   _ZN15GameCenterProxy17ResetAchievementsEv
// TODO      4 B  GameCenterProxy::ShowAchievementView                 _ZN15GameCenterProxy19ShowAchievementViewEv
// TODO      4 B  GameCenterProxy::~GameCenterProxy                    _ZN15GameCenterProxyD2Ev
// TODO      4 B  GameCenterProxy::QueueAchievement                    _ZN15GameCenterProxy16QueueAchievementERKSs
// TODO      4 B  GameCenterProxy::SubmitScoreToLeaderboard            _ZN15GameCenterProxy24SubmitScoreToLeaderboardEiRKSs
// TODO      4 B  GameCenterProxy::ShowLeaderboardView                 _ZN15GameCenterProxy19ShowLeaderboardViewERKSs
