// PvZ2/GameInfoUtil.cpp
//
// 4 function(s), 1216 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: GameInfoUtil
//
// TODO    712 B  GameInfoUtil::GetItemInfoById                        _ZN12GameInfoUtil15GetItemInfoByIdEiR12GameItemInfo
// TODO    224 B  GameInfoUtil::GetDescriptionById                     _ZN12GameInfoUtil18GetDescriptionByIdEi
// TODO    160 B  GameInfoUtil::GetRareByPlantName                     _ZN12GameInfoUtil18GetRareByPlantNameESsRi
// TODO    120 B  GameInfoUtil::GetRareByAccessaryName                 _ZN12GameInfoUtil22GetRareByAccessaryNameESsRi
