// PvZ2/GameStateTransitionController.cpp
//
// 28 function(s), 5348 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: GameStateTransitionController
//
// TODO   1052 B  GameStateTransitionController::continueTransition    _ZN29GameStateTransitionController18continueTransitionEv
// TODO   1000 B  GameStateTransitionController::TransitionToState     _ZN29GameStateTransitionController17TransitionToStateE9GameState18GameTransitionTypeS1_
// TODO    356 B  GameStateTransitionController::Draw                  _ZN29GameStateTransitionController4DrawEPN4Sexy8GraphicsE
// TODO    304 B  GameStateTransitionController::onEnterState_TransitionWarpTunnel _ZN29GameStateTransitionController33onEnterState_TransitionWarpTunnelE19GameTransitionState
// TODO    304 B  GameStateTransitionController::onEnterState_TransitionWarpTunnelPVZ1 _ZN29GameStateTransitionController37onEnterState_TransitionWarpTunnelPVZ1E19GameTransitionState
// TODO    284 B  GameStateTransitionController::startTransitionEffect _ZN29GameStateTransitionController21startTransitionEffectE18GameTransitionTypeb
// TODO    224 B  GameStateTransitionController::GameStateTransitionController _ZN29GameStateTransitionControllerC1Ev
// TODO    224 B  GameStateTransitionController::GameStateTransitionController _ZN29GameStateTransitionControllerC2Ev
// TODO    172 B  GameStateTransitionController::setTransitionState    _ZN29GameStateTransitionController18setTransitionStateERK15StateDefinitionI19GameTransitionStateE
// TODO    164 B  GameStateTransitionController::updateState_TransitionWarpTunnel _ZN29GameStateTransitionController32updateState_TransitionWarpTunnelEv
// TODO    164 B  GameStateTransitionController::updateState_TransitionWarpTunnelPVZ1 _ZN29GameStateTransitionController36updateState_TransitionWarpTunnelPVZ1Ev
// TODO    152 B  GameStateTransitionController::onEnterState_TransitionIn _ZN29GameStateTransitionController25onEnterState_TransitionInE19GameTransitionState
// TODO    128 B  GameStateTransitionController::onEnterState_TransitionOut _ZN29GameStateTransitionController26onEnterState_TransitionOutE19GameTransitionState
// TODO    120 B  GameStateTransitionController::StaticGetClass        _ZN29GameStateTransitionController14StaticGetClassEv
// TODO     88 B  GameStateTransitionController::updateState_TransitionOut _ZN29GameStateTransitionController25updateState_TransitionOutEv
// TODO     88 B  GameStateTransitionController::updateState_TransitionIn _ZN29GameStateTransitionController24updateState_TransitionInEv
// TODO     68 B  GameStateTransitionController::onExitState_TransitionWarpTunnel _ZN29GameStateTransitionController32onExitState_TransitionWarpTunnelE19GameTransitionState
// TODO     68 B  GameStateTransitionController::onExitState_TransitionWarpTunnelPVZ1 _ZN29GameStateTransitionController36onExitState_TransitionWarpTunnelPVZ1E19GameTransitionState
// TODO     56 B  GameStateTransitionController::onExitState_TransitionOut _ZN29GameStateTransitionController25onExitState_TransitionOutE19GameTransitionState
// TODO     52 B  GameStateTransitionController::~GameStateTransitionController _ZN29GameStateTransitionControllerD2Ev
// TODO     52 B  GameStateTransitionController::~GameStateTransitionController _ZN29GameStateTransitionControllerD1Ev
// TODO     52 B  GameStateTransitionController::SetOverlayRenderActive _ZN29GameStateTransitionController22SetOverlayRenderActiveEb
// TODO     48 B  GameStateTransitionController::doQueuedStateChange   _ZN29GameStateTransitionController19doQueuedStateChangeEv
// TODO     44 B  GameStateTransitionController::StaticNew             _ZN29GameStateTransitionController9StaticNewEv
// TODO     36 B  GameStateTransitionController::~GameStateTransitionController _ZN29GameStateTransitionControllerD0Ev
// TODO     32 B  GameStateTransitionController::onExitState_TransitionIn _ZN29GameStateTransitionController24onExitState_TransitionInE19GameTransitionState
// TODO      8 B  GameStateTransitionController::GetTransitionState    _ZN29GameStateTransitionController18GetTransitionStateEv
// TODO      8 B  GameStateTransitionController::Update                _ZN29GameStateTransitionController6UpdateEv
