// PvZ2/LightningBoltToGround.cpp
//
// 18 function(s), 3588 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: LightningBoltToGround
//
// TODO    844 B  LightningBoltToGround::SetInitialTarget              _ZN21LightningBoltToGround16SetInitialTargetEN4Sexy11SexyVector3E
// TODO    436 B  LightningBoltToGround::onDraw                        _ZN21LightningBoltToGround6onDrawEPN4Sexy8GraphicsE
// TODO    368 B  LightningBoltToGround::setRenderTransformForRig      _ZN21LightningBoltToGround24setRenderTransformForRigEP10PopAnimRigf
// TODO    292 B  LightningBoltToGround::onUpdate                      _ZN21LightningBoltToGround8onUpdateEv
// TODO    264 B  LightningBoltToGround::LightningBoltToGround         _ZN21LightningBoltToGroundC2Ev
// TODO    264 B  LightningBoltToGround::LightningBoltToGround         _ZN21LightningBoltToGroundC1Ev
// TODO    180 B  LightningBoltToGround::StaticClassInit               _ZN21LightningBoltToGround15StaticClassInitEv
// TODO    172 B  LightningBoltToGround::ClearChild                    _ZN21LightningBoltToGround10ClearChildEv
// TODO    164 B  LightningBoltToGround::onDestroy                     _ZN21LightningBoltToGround9onDestroyEv
// TODO    124 B  LightningBoltToGround::StaticGetClass                _ZN21LightningBoltToGround14StaticGetClassEv
// TODO    104 B  LightningBoltToGround::~LightningBoltToGround        _ZN21LightningBoltToGroundD2Ev
// TODO    104 B  LightningBoltToGround::~LightningBoltToGround        _ZN21LightningBoltToGroundD1Ev
// TODO     72 B  LightningBoltToGround::SetPopAnim                    _ZN21LightningBoltToGround10SetPopAnimERKSsS1_S1_
// TODO     72 B  LightningBoltToGround::SetPopAnimNames               _ZN21LightningBoltToGround15SetPopAnimNamesERKSsS1_S1_
// TODO     44 B  LightningBoltToGround::StaticNew                     _ZN21LightningBoltToGround9StaticNewEv
// TODO     40 B  LightningBoltToGround::onInitialized                 _ZN21LightningBoltToGround13onInitializedEv
// TODO     36 B  LightningBoltToGround::~LightningBoltToGround        _ZN21LightningBoltToGroundD0Ev
// TODO      8 B  LightningBoltToGround::SetOwner                      _ZN21LightningBoltToGround8SetOwnerEN4Sexy9RtWeakPtrI11BoardEntityEE
