// PvZ2/MomotaroTornado.cpp
//
// 12 function(s), 988 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: MomotaroTornado
//
// TODO    180 B  MomotaroTornado::StaticClassInit                     _ZN15MomotaroTornado15StaticClassInitEv
// TODO    124 B  MomotaroTornado::GetDrawOffet                        _ZN15MomotaroTornado12GetDrawOffetEv
// TODO    124 B  MomotaroTornado::StaticGetClass                      _ZN15MomotaroTornado14StaticGetClassEv
// TODO    104 B  MomotaroTornado::GetPam                              _ZN15MomotaroTornado6GetPamEv
// TODO    104 B  MomotaroTornado::GetUpPamLabel                       _ZN15MomotaroTornado13GetUpPamLabelEv
// TODO    104 B  MomotaroTornado::GetDownPamLabel                     _ZN15MomotaroTornado15GetDownPamLabelEv
// TODO     56 B  MomotaroTornado::MomotaroTornado                     _ZN15MomotaroTornadoC2Ev
// TODO     56 B  MomotaroTornado::MomotaroTornado                     _ZN15MomotaroTornadoC1Ev
// TODO     44 B  MomotaroTornado::StaticNew                           _ZN15MomotaroTornado9StaticNewEv
// TODO     36 B  MomotaroTornado::~MomotaroTornado                    _ZN15MomotaroTornadoD0Ev
// TODO     28 B  MomotaroTornado::~MomotaroTornado                    _ZN15MomotaroTornadoD2Ev
// TODO     28 B  MomotaroTornado::~MomotaroTornado                    _ZN15MomotaroTornadoD1Ev
