// PvZ2/SpeedChange.cpp
//
// 19 function(s), 2328 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: SpeedChange
//
// TODO    284 B  SpeedChange::OnMouseUp                               _ZN11SpeedChange9OnMouseUpEii
// TODO    264 B  SpeedChange::registerForEvents                       _ZN11SpeedChange17registerForEventsEv
// TODO    248 B  SpeedChange::~SpeedChange                            _ZN11SpeedChangeD2Ev
// TODO    248 B  SpeedChange::~SpeedChange                            _ZN11SpeedChangeD1Ev
// TODO    220 B  SpeedChange::Draw                                    _ZN11SpeedChange4DrawEPN4Sexy8GraphicsE
// TODO    188 B  SpeedChange::onGameStart                             _ZN11SpeedChange11onGameStartEv
// TODO    180 B  SpeedChange::StaticClassInit                         _ZN11SpeedChange15StaticClassInitEv
// TODO    124 B  SpeedChange::StaticGetClass                          _ZN11SpeedChange14StaticGetClassEv
// TODO    108 B  SpeedChange::onInitialized                           _ZN11SpeedChange13onInitializedEv
// TODO     92 B  SpeedChange::onRechargeNow                           _ZN11SpeedChange13onRechargeNowEv
// TODO     84 B  SpeedChange::onCancel                                _ZN11SpeedChange8onCancelEv
// TODO     64 B  SpeedChange::SpeedChange                             _ZN11SpeedChangeC2Ev
// TODO     64 B  SpeedChange::SpeedChange                             _ZN11SpeedChangeC1Ev
// TODO     64 B  SpeedChange::updateState_Ready                       _ZN11SpeedChange17updateState_ReadyEv
// TODO     44 B  SpeedChange::StaticNew                               _ZN11SpeedChange9StaticNewEv
// TODO     36 B  SpeedChange::~SpeedChange                            _ZN11SpeedChangeD0Ev
// TODO      8 B  SpeedChange::onGameplayEnded                         _ZN11SpeedChange15onGameplayEndedEv
// TODO      4 B  SpeedChange::unregisterForEvents                     _ZN11SpeedChange19unregisterForEventsEv
// TODO      4 B  SpeedChange::initLoadingResourcesGroupList           _ZN11SpeedChange29initLoadingResourcesGroupListEv
