// PvZ2/StormZombieSpawner.cpp
//
// 27 function(s), 4832 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: StormZombieSpawner, StormZombieSpawnerProps
//
// TODO    964 B  StormZombieSpawner::initializeAction                 _ZN18StormZombieSpawner16initializeActionERN4Sexy6MTRandEi
// TODO    548 B  StormZombieSpawner::createZombies                    _ZN18StormZombieSpawner13createZombiesEiRN4Sexy6MTRandEii
// TODO    516 B  StormZombieSpawnerProps::StaticClassInit             _ZN23StormZombieSpawnerProps15StaticClassInitEv
// TODO    464 B  StormZombieSpawner::WaveStart                        _ZN18StormZombieSpawner9WaveStartEiN8WaveType8WaveTypeEbRN4Sexy6MTRandE
// TODO    320 B  StormZombieSpawner::AddResourceRequirements          _ZN18StormZombieSpawner23AddResourceRequirementsERSt3setISsSt4lessISsESaISsEE
// TODO    188 B  StormZombieSpawner::GetZombies                       _ZN18StormZombieSpawner10GetZombiesERSt6vectorIPK10ZombieTypeSaIS3_EE
// TODO    184 B  StormZombieSpawnerProps::GatherSpawnedZombieTypes    _ZN23StormZombieSpawnerProps24GatherSpawnedZombieTypesERSt3setIPK10ZombieTypeSt4lessIS3_ESaIS3_EE
// TODO    180 B  StormZombieSpawner::StaticClassInit                  _ZN18StormZombieSpawner15StaticClassInitEv
// TODO    176 B  StormZombieSpawner::WaveUpdate                       _ZN18StormZombieSpawner10WaveUpdateEiRN4Sexy6MTRandE
// TODO    168 B  StormZombieSpawner::spawnGroup                       _ZN18StormZombieSpawner10spawnGroupEiiRN4Sexy6MTRandE
// TODO    124 B  StormZombieSpawnerProps::StaticGetClass              _ZN23StormZombieSpawnerProps14StaticGetClassEv
// TODO    124 B  StormZombieSpawner::StaticGetClass                   _ZN18StormZombieSpawner14StaticGetClassEv
// TODO    112 B  StormZombieSpawner::spawnAllTheThings                _ZN18StormZombieSpawner17spawnAllTheThingsEiRN4Sexy6MTRandE
// TODO    104 B  StormZombieSpawnerProps::StormZombieSpawnerProps     _ZN23StormZombieSpawnerPropsC2Ev
// TODO    104 B  StormZombieSpawnerProps::StormZombieSpawnerProps     _ZN23StormZombieSpawnerPropsC1Ev
// TODO     80 B  StormZombieSpawner::StormZombieSpawner               _ZN18StormZombieSpawnerC2Ev
// TODO     80 B  StormZombieSpawner::StormZombieSpawner               _ZN18StormZombieSpawnerC1Ev
// TODO     60 B  StormZombieSpawner::~StormZombieSpawner              _ZN18StormZombieSpawnerD2Ev
// TODO     60 B  StormZombieSpawner::~StormZombieSpawner              _ZN18StormZombieSpawnerD1Ev
// TODO     52 B  StormZombieSpawnerProps::~StormZombieSpawnerProps    _ZN23StormZombieSpawnerPropsD2Ev
// TODO     52 B  StormZombieSpawnerProps::~StormZombieSpawnerProps    _ZN23StormZombieSpawnerPropsD1Ev
// TODO     44 B  StormZombieSpawnerProps::StaticNew                   _ZN23StormZombieSpawnerProps9StaticNewEv
// TODO     44 B  StormZombieSpawner::StaticNew                        _ZN18StormZombieSpawner9StaticNewEv
// TODO     36 B  StormZombieSpawnerProps::~StormZombieSpawnerProps    _ZN23StormZombieSpawnerPropsD0Ev
// TODO     36 B  StormZombieSpawner::~StormZombieSpawner              _ZN18StormZombieSpawnerD0Ev
// TODO      8 B  StormZombieSpawner::SetLoot                          _ZN18StormZombieSpawner7SetLootERKSt6vectorI4LootSaIS1_EE
// TODO      4 B  StormZombieSpawner::WaveEnd                          _ZN18StormZombieSpawner7WaveEndEiRN4Sexy6MTRandE
