// PvZ2/Whitelistable.cpp
//
// 10 function(s), 504 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: Whitelistable
//
// TODO    140 B  Whitelistable::RegisterForWhitelistEvents            _ZN13Whitelistable26RegisterForWhitelistEventsEv
// TODO    140 B  Whitelistable::UnregisterForWhitelistEvents          _ZN13Whitelistable28UnregisterForWhitelistEventsEv
// TODO     68 B  Whitelistable::SetWhitelistID                        _ZN13Whitelistable14SetWhitelistIDERKSs
// TODO     36 B  Whitelistable::isDisabledByWhitelisting              _ZN13Whitelistable24isDisabledByWhitelistingEv
// TODO     36 B  Whitelistable::~Whitelistable                        _ZN13WhitelistableD0Ev
// TODO     20 B  Whitelistable::~Whitelistable                        _ZN13WhitelistableD2Ev
// TODO     20 B  Whitelistable::~Whitelistable                        _ZN13WhitelistableD1Ev
// TODO     20 B  Whitelistable::Whitelistable                         _ZN13WhitelistableC2Ev
// TODO     20 B  Whitelistable::Whitelistable                         _ZN13WhitelistableC1Ev
// TODO      4 B  Whitelistable::onWhitelistingChanged                 _ZN13Whitelistable21onWhitelistingChangedEv
