// PvZ2/PVP/rift/adaptorrift/AdaptorRiftPerkProgressionDisplay.cpp
//
// 18 function(s), 5196 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: AdaptorRiftPerkProgressionDisplay
//
// TODO    812 B  AdaptorRiftPerkProgressionDisplay::Update            _ZN33AdaptorRiftPerkProgressionDisplay6UpdateEv
// TODO    752 B  AdaptorRiftPerkProgressionDisplay::positionProgressBar _ZN33AdaptorRiftPerkProgressionDisplay19positionProgressBarEf
// TODO    636 B  AdaptorRiftPerkProgressionDisplay::ShowProgressAnimation _ZN33AdaptorRiftPerkProgressionDisplay21ShowProgressAnimationEv
// TODO    632 B  AdaptorRiftPerkProgressionDisplay::onLinkToUIViewCreated _ZN33AdaptorRiftPerkProgressionDisplay21onLinkToUIViewCreatedEv
// TODO    412 B  AdaptorRiftPerkProgressionDisplay::GetScrollPoint    _ZN33AdaptorRiftPerkProgressionDisplay14GetScrollPointEv
// TODO    320 B  AdaptorRiftPerkProgressionDisplay::~AdaptorRiftPerkProgressionDisplay _ZN33AdaptorRiftPerkProgressionDisplayD2Ev
// TODO    320 B  AdaptorRiftPerkProgressionDisplay::~AdaptorRiftPerkProgressionDisplay _ZN33AdaptorRiftPerkProgressionDisplayD1Ev
// TODO    284 B  AdaptorRiftPerkProgressionDisplay::getWidgetXLocations _ZN33AdaptorRiftPerkProgressionDisplay19getWidgetXLocationsEv
// TODO    284 B  AdaptorRiftPerkProgressionDisplay::refresh           _ZN33AdaptorRiftPerkProgressionDisplay7refreshEv
// TODO    180 B  AdaptorRiftPerkProgressionDisplay::StaticClassInit   _ZN33AdaptorRiftPerkProgressionDisplay15StaticClassInitEv
// TODO    172 B  AdaptorRiftPerkProgressionDisplay::GetSizeOfPerkRegion _ZN33AdaptorRiftPerkProgressionDisplay19GetSizeOfPerkRegionEv
// TODO    124 B  AdaptorRiftPerkProgressionDisplay::StaticGetClass    _ZN33AdaptorRiftPerkProgressionDisplay14StaticGetClassEv
// TODO     84 B  AdaptorRiftPerkProgressionDisplay::AdaptorRiftPerkProgressionDisplay _ZN33AdaptorRiftPerkProgressionDisplayC2Ev
// TODO     84 B  AdaptorRiftPerkProgressionDisplay::AdaptorRiftPerkProgressionDisplay _ZN33AdaptorRiftPerkProgressionDisplayC1Ev
// TODO     44 B  AdaptorRiftPerkProgressionDisplay::StaticNew         _ZN33AdaptorRiftPerkProgressionDisplay9StaticNewEv
// TODO     36 B  AdaptorRiftPerkProgressionDisplay::~AdaptorRiftPerkProgressionDisplay _ZN33AdaptorRiftPerkProgressionDisplayD0Ev
// TODO     12 B  AdaptorRiftPerkProgressionDisplay::startEntryAnimation _ZN33AdaptorRiftPerkProgressionDisplay19startEntryAnimationEP38AdaptorRiftPerkProgressionDisplayEntry
// TODO      8 B  AdaptorRiftPerkProgressionDisplay::finishEntryAnimation _ZN33AdaptorRiftPerkProgressionDisplay20finishEntryAnimationEP38AdaptorRiftPerkProgressionDisplayEntry
