// PvZ2/PVP/rift/adaptorrift/AdaptorRiftLeaderBoardScreen.cpp
//
// 21 function(s), 6452 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: AdaptorRiftLeaderBoardScreen
//
// TODO   2632 B  AdaptorRiftLeaderBoardScreen::setup                  _ZN28AdaptorRiftLeaderBoardScreen5setupEv
// TODO    432 B  AdaptorRiftLeaderBoardScreen::showOverview           _ZN28AdaptorRiftLeaderBoardScreen12showOverviewEv
// TODO    424 B  AdaptorRiftLeaderBoardScreen::GetLegendReward        _ZN28AdaptorRiftLeaderBoardScreen15GetLegendRewardEi
// TODO    404 B  AdaptorRiftLeaderBoardScreen::ButtonDepress          _ZN28AdaptorRiftLeaderBoardScreen13ButtonDepressEi
// TODO    376 B  AdaptorRiftLeaderBoardScreen::addLeaderboardOpponents _ZN28AdaptorRiftLeaderBoardScreen23addLeaderboardOpponentsER28AdaptorRiftLeaderboardConfig
// TODO    376 B  AdaptorRiftLeaderBoardScreen::ShowLegendReward       _ZN28AdaptorRiftLeaderBoardScreen16ShowLegendRewardEi
// TODO    336 B  AdaptorRiftLeaderBoardScreen::updateAvatarIcon       _ZN28AdaptorRiftLeaderBoardScreen16updateAvatarIconEii
// TODO    288 B  AdaptorRiftLeaderBoardScreen::onLoadUIView           _ZN28AdaptorRiftLeaderBoardScreen12onLoadUIViewEv
// TODO    256 B  AdaptorRiftLeaderBoardScreen::GetScreenType          _ZN28AdaptorRiftLeaderBoardScreen13GetScreenTypeEv
// TODO    180 B  AdaptorRiftLeaderBoardScreen::StaticClassInit        _ZN28AdaptorRiftLeaderBoardScreen15StaticClassInitEv
// TODO    124 B  AdaptorRiftLeaderBoardScreen::StaticGetClass         _ZN28AdaptorRiftLeaderBoardScreen14StaticGetClassEv
// TODO    116 B  AdaptorRiftLeaderBoardScreen::~AdaptorRiftLeaderBoardScreen _ZN28AdaptorRiftLeaderBoardScreenD2Ev
// TODO    116 B  AdaptorRiftLeaderBoardScreen::~AdaptorRiftLeaderBoardScreen _ZN28AdaptorRiftLeaderBoardScreenD1Ev
// TODO     68 B  AdaptorRiftLeaderBoardScreen::AdaptorRiftLeaderBoardScreen _ZN28AdaptorRiftLeaderBoardScreenC2Ev
// TODO     68 B  AdaptorRiftLeaderBoardScreen::AdaptorRiftLeaderBoardScreen _ZN28AdaptorRiftLeaderBoardScreenC1Ev
// TODO     64 B  AdaptorRiftLeaderBoardScreen::buildLeaderboard       _ZN28AdaptorRiftLeaderBoardScreen16buildLeaderboardEv
// TODO     60 B  AdaptorRiftLeaderBoardScreen::getWeeklyRewards       _ZN28AdaptorRiftLeaderBoardScreen16getWeeklyRewardsEv
// TODO     48 B  AdaptorRiftLeaderBoardScreen::Close                  _ZN28AdaptorRiftLeaderBoardScreen5CloseEv
// TODO     44 B  AdaptorRiftLeaderBoardScreen::StaticNew              _ZN28AdaptorRiftLeaderBoardScreen9StaticNewEv
// TODO     36 B  AdaptorRiftLeaderBoardScreen::~AdaptorRiftLeaderBoardScreen _ZN28AdaptorRiftLeaderBoardScreenD0Ev
// TODO      4 B  AdaptorRiftLeaderBoardScreen::onLinkToUIViewCreated  _ZN28AdaptorRiftLeaderBoardScreen21onLinkToUIViewCreatedEv
