// PvZ2/PVP/zombiepv/ZombiePVPPirateCaptain.cpp
//
// 36 function(s), 6844 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombiePVPPirateCaptain, ZombiePvpPirateCaptainProps
//
// TODO   1156 B  ZombiePVPPirateCaptain::onPopAnimCommand             _ZN22ZombiePVPPirateCaptain16onPopAnimCommandERKSsfS1_S1_
// TODO   1120 B  ZombiePVPPirateCaptain::findPlantForParrotToBigAttack _ZN22ZombiePVPPirateCaptain29findPlantForParrotToBigAttackEv
// TODO    628 B  ZombiePVPPirateCaptain::findPlantForParrotToAttack   _ZN22ZombiePVPPirateCaptain26findPlantForParrotToAttackEv
// TODO    468 B  ZombiePVPPirateCaptain::StaticClassInit              _ZN22ZombiePVPPirateCaptain15StaticClassInitEv
// TODO    444 B  ZombiePVPPirateCaptain::releaseParrot                _ZN22ZombiePVPPirateCaptain13releaseParrotEP5Plant
// TODO    352 B  ZombiePVPPirateCaptain::onEnterState_BigCasting      _ZN22ZombiePVPPirateCaptain23onEnterState_BigCastingE11ZombieState
// TODO    288 B  ZombiePVPPirateCaptain::onZombieInitialize           _ZN22ZombiePVPPirateCaptain18onZombieInitializeEv
// TODO    284 B  ZombiePVPPirateCaptain::onLostHead                   _ZN22ZombiePVPPirateCaptain10onLostHeadEv
// TODO    216 B  ZombiePVPPirateCaptain::OnParrotReturned             _ZN22ZombiePVPPirateCaptain16OnParrotReturnedEv
// TODO    180 B  ZombiePvpPirateCaptainProps::StaticClassInit         _ZN27ZombiePvpPirateCaptainProps15StaticClassInitEv
// TODO    152 B  ZombiePVPPirateCaptain::checkForParrotRelease        _ZN22ZombiePVPPirateCaptain21checkForParrotReleaseEv
// TODO    128 B  ZombiePVPPirateCaptain::onAnimationDone              _ZN22ZombiePVPPirateCaptain15onAnimationDoneERKSs
// TODO    124 B  ZombiePVPPirateCaptain::StaticGetClass               _ZN22ZombiePVPPirateCaptain14StaticGetClassEv
// TODO    124 B  ZombiePVPPirateCaptain::onApplyCondition             _ZN22ZombiePVPPirateCaptain16onApplyConditionE16ZombieConditions
// TODO    124 B  ZombiePvpPirateCaptainProps::StaticGetClass          _ZN27ZombiePvpPirateCaptainProps14StaticGetClassEv
// TODO     84 B  ZombiePVPPirateCaptain::updateState_Walk             _ZN22ZombiePVPPirateCaptain16updateState_WalkEv
// TODO     84 B  ZombiePVPPirateCaptain::updateState_Eat              _ZN22ZombiePVPPirateCaptain15updateState_EatEv
// TODO     72 B  ZombiePVPPirateCaptain::ZombiePVPPirateCaptain       _ZN22ZombiePVPPirateCaptainC2Ev
// TODO     72 B  ZombiePVPPirateCaptain::ZombiePVPPirateCaptain       _ZN22ZombiePVPPirateCaptainC1Ev
// TODO     72 B  ZombiePVPPirateCaptain::~ZombiePVPPirateCaptain      _ZN22ZombiePVPPirateCaptainD2Ev
// TODO     72 B  ZombiePVPPirateCaptain::~ZombiePVPPirateCaptain      _ZN22ZombiePVPPirateCaptainD1Ev
// TODO     68 B  ZombiePVPPirateCaptain::onPlaceOnBoard               _ZN22ZombiePVPPirateCaptain14onPlaceOnBoardEv
// TODO     64 B  ZombiePVPPirateCaptain::showParrot                   _ZN22ZombiePVPPirateCaptain10showParrotEb
// TODO     64 B  ZombiePVPPirateCaptain::ApplyZombieFood              _ZN22ZombiePVPPirateCaptain15ApplyZombieFoodEv
// TODO     64 B  ZombiePVPPirateCaptain::CancelZombieFood             _ZN22ZombiePVPPirateCaptain16CancelZombieFoodEv
// TODO     64 B  ZombiePvpPirateCaptainProps::ZombiePvpPirateCaptainProps _ZN27ZombiePvpPirateCaptainPropsC2Ev
// TODO     64 B  ZombiePvpPirateCaptainProps::ZombiePvpPirateCaptainProps _ZN27ZombiePvpPirateCaptainPropsC1Ev
// TODO     44 B  ZombiePVPPirateCaptain::StaticNew                    _ZN22ZombiePVPPirateCaptain9StaticNewEv
// TODO     44 B  ZombiePvpPirateCaptainProps::StaticNew               _ZN27ZombiePvpPirateCaptainProps9StaticNewEv
// TODO     36 B  ZombiePVPPirateCaptain::~ZombiePVPPirateCaptain      _ZN22ZombiePVPPirateCaptainD0Ev
// TODO     36 B  ZombiePvpPirateCaptainProps::~ZombiePvpPirateCaptainProps _ZN27ZombiePvpPirateCaptainPropsD0Ev
// TODO     20 B  ZombiePvpPirateCaptainProps::~ZombiePvpPirateCaptainProps _ZN27ZombiePvpPirateCaptainPropsD2Ev
// TODO     20 B  ZombiePvpPirateCaptainProps::~ZombiePvpPirateCaptainProps _ZN27ZombiePvpPirateCaptainPropsD1Ev
// TODO      4 B  ZombiePVPPirateCaptain::updateState_BigCasting       _ZN22ZombiePVPPirateCaptain22updateState_BigCastingEv
// TODO      4 B  ZombiePVPPirateCaptain::onExitState_BigCasting       _ZN22ZombiePVPPirateCaptain22onExitState_BigCastingE11ZombieState
// TODO      4 B  ZombiePVPPirateCaptain::onTakeFatalDamage            _ZN22ZombiePVPPirateCaptain17onTakeFatalDamageERK10DamageInfo
