// PvZ2/PVP/zombiepv/ZombiePVPSkill_Invisible.cpp
//
// 26 function(s), 3208 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombiePVPSkillInvisibleProps, ZombiePVPSkill_Invisible
//
// TODO    360 B  ZombiePVPSkill_Invisible::updateState_Playing        _ZN24ZombiePVPSkill_Invisible19updateState_PlayingEv
// TODO    336 B  ZombiePVPSkill_Invisible::onPopAnimCommand           _ZN24ZombiePVPSkill_Invisible16onPopAnimCommandERKSsfS1_S1_
// TODO    328 B  ZombiePVPSkill_Invisible::CreateRangeEffect          _ZN24ZombiePVPSkill_Invisible17CreateRangeEffectEv
// TODO    276 B  ZombiePVPSkill_Invisible::onEnterState_Playing       _ZN24ZombiePVPSkill_Invisible20onEnterState_PlayingE11ZombieState
// TODO    256 B  ZombiePVPSkill_Invisible::onAnimationDone            _ZN24ZombiePVPSkill_Invisible15onAnimationDoneERKSs
// TODO    180 B  ZombiePVPSkill_Invisible::StaticClassInit            _ZN24ZombiePVPSkill_Invisible15StaticClassInitEv
// TODO    180 B  ZombiePVPSkillInvisibleProps::StaticClassInit        _ZN28ZombiePVPSkillInvisibleProps15StaticClassInitEv
// TODO    176 B  ZombiePVPSkill_Invisible::onDestroy                  _ZN24ZombiePVPSkill_Invisible9onDestroyEv
// TODO    124 B  ZombiePVPSkill_Invisible::StaticGetClass             _ZN24ZombiePVPSkill_Invisible14StaticGetClassEv
// TODO    124 B  ZombiePVPSkill_Invisible::GetSkillTime               _ZN24ZombiePVPSkill_Invisible12GetSkillTimeEv
// TODO    124 B  ZombiePVPSkillInvisibleProps::StaticGetClass         _ZN28ZombiePVPSkillInvisibleProps14StaticGetClassEv
// TODO     80 B  ZombiePVPSkill_Invisible::DestroyRangeEffect         _ZN24ZombiePVPSkill_Invisible18DestroyRangeEffectEv
// TODO     76 B  ZombiePVPSkill_Invisible::ZombiePVPSkill_Invisible   _ZN24ZombiePVPSkill_InvisibleC2Ev
// TODO     76 B  ZombiePVPSkill_Invisible::ZombiePVPSkill_Invisible   _ZN24ZombiePVPSkill_InvisibleC1Ev
// TODO     64 B  ZombiePVPSkill_Invisible::~ZombiePVPSkill_Invisible  _ZN24ZombiePVPSkill_InvisibleD2Ev
// TODO     64 B  ZombiePVPSkill_Invisible::~ZombiePVPSkill_Invisible  _ZN24ZombiePVPSkill_InvisibleD1Ev
// TODO     56 B  ZombiePVPSkillInvisibleProps::~ZombiePVPSkillInvisibleProps _ZN28ZombiePVPSkillInvisiblePropsD2Ev
// TODO     56 B  ZombiePVPSkillInvisibleProps::~ZombiePVPSkillInvisibleProps _ZN28ZombiePVPSkillInvisiblePropsD1Ev
// TODO     52 B  ZombiePVPSkillInvisibleProps::ZombiePVPSkillInvisibleProps _ZN28ZombiePVPSkillInvisiblePropsC2Ev
// TODO     52 B  ZombiePVPSkillInvisibleProps::ZombiePVPSkillInvisibleProps _ZN28ZombiePVPSkillInvisiblePropsC1Ev
// TODO     44 B  ZombiePVPSkill_Invisible::StaticNew                  _ZN24ZombiePVPSkill_Invisible9StaticNewEv
// TODO     44 B  ZombiePVPSkillInvisibleProps::StaticNew              _ZN28ZombiePVPSkillInvisibleProps9StaticNewEv
// TODO     36 B  ZombiePVPSkill_Invisible::~ZombiePVPSkill_Invisible  _ZN24ZombiePVPSkill_InvisibleD0Ev
// TODO     36 B  ZombiePVPSkillInvisibleProps::~ZombiePVPSkillInvisibleProps _ZN28ZombiePVPSkillInvisiblePropsD0Ev
// TODO      4 B  ZombiePVPSkill_Invisible::onExitState_Playing        _ZN24ZombiePVPSkill_Invisible19onExitState_PlayingE11ZombieState
// TODO      4 B  ZombiePVPSkill_Invisible::onZombieInitialize         _ZN24ZombiePVPSkill_Invisible18onZombieInitializeEv
