// PvZ2/zombies/Dove/ZombieAnimRig_Dove.cpp
//
// 11 function(s), 1080 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieAnimRig_Dove
//
// TODO    180 B  ZombieAnimRig_Dove::StaticClassInit                  _ZN18ZombieAnimRig_Dove15StaticClassInitEv
// TODO    176 B  ZombieAnimRig_Dove::PlayFly                          _ZN18ZombieAnimRig_Dove7PlayFlyEv
// TODO    176 B  ZombieAnimRig_Dove::PlayFlyBack                      _ZN18ZombieAnimRig_Dove11PlayFlyBackEv
// TODO    176 B  ZombieAnimRig_Dove::PlayCarry                        _ZN18ZombieAnimRig_Dove9PlayCarryEv
// TODO    124 B  ZombieAnimRig_Dove::StaticGetClass                   _ZN18ZombieAnimRig_Dove14StaticGetClassEv
// TODO     56 B  ZombieAnimRig_Dove::ZombieAnimRig_Dove               _ZN18ZombieAnimRig_DoveC2Ev
// TODO     56 B  ZombieAnimRig_Dove::ZombieAnimRig_Dove               _ZN18ZombieAnimRig_DoveC1Ev
// TODO     44 B  ZombieAnimRig_Dove::StaticNew                        _ZN18ZombieAnimRig_Dove9StaticNewEv
// TODO     36 B  ZombieAnimRig_Dove::~ZombieAnimRig_Dove              _ZN18ZombieAnimRig_DoveD0Ev
// TODO     28 B  ZombieAnimRig_Dove::~ZombieAnimRig_Dove              _ZN18ZombieAnimRig_DoveD2Ev
// TODO     28 B  ZombieAnimRig_Dove::~ZombieAnimRig_Dove              _ZN18ZombieAnimRig_DoveD1Ev
