// PvZ2/challenges/ApplyZombieConditionsChallenge.cpp
//
// 23 function(s), 2612 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ApplyZombieConditionsChallenge, ApplyZombieConditionsChallengeProps
//
// TODO    432 B  ApplyZombieConditionsChallenge::registerForEvents    _ZN30ApplyZombieConditionsChallenge17registerForEventsEv
// TODO    288 B  ApplyZombieConditionsChallenge::incrementNumConditionApplied _ZN30ApplyZombieConditionsChallenge28incrementNumConditionAppliedEv
// TODO    236 B  ApplyZombieConditionsChallenge::gameplayStarted      _ZN30ApplyZombieConditionsChallenge15gameplayStartedEv
// TODO    208 B  ApplyZombieConditionsChallenge::onZombieConditionApplied _ZN30ApplyZombieConditionsChallenge24onZombieConditionAppliedEP6Zombieif
// TODO    180 B  ApplyZombieConditionsChallenge::StaticClassInit      _ZN30ApplyZombieConditionsChallenge15StaticClassInitEv
// TODO    180 B  ApplyZombieConditionsChallengeProps::StaticClassInit _ZN35ApplyZombieConditionsChallengeProps15StaticClassInitEv
// TODO    124 B  ApplyZombieConditionsChallenge::StaticGetClass       _ZN30ApplyZombieConditionsChallenge14StaticGetClassEv
// TODO    124 B  ApplyZombieConditionsChallengeProps::StaticGetClass  _ZN35ApplyZombieConditionsChallengeProps14StaticGetClassEv
// TODO     76 B  ApplyZombieConditionsChallenge::onZombieBurnedToAsh  _ZN30ApplyZombieConditionsChallenge19onZombieBurnedToAshEP6Zombie
// TODO     76 B  ApplyZombieConditionsChallenge::onZombieElectrified  _ZN30ApplyZombieConditionsChallenge19onZombieElectrifiedEP6Zombie
// TODO     68 B  ApplyZombieConditionsChallengeProps::ApplyZombieConditionsChallengeProps _ZN35ApplyZombieConditionsChallengePropsC2Ev
// TODO     68 B  ApplyZombieConditionsChallengeProps::ApplyZombieConditionsChallengeProps _ZN35ApplyZombieConditionsChallengePropsC1Ev
// TODO     64 B  ApplyZombieConditionsChallenge::ApplyZombieConditionsChallenge _ZN30ApplyZombieConditionsChallengeC2Ev
// TODO     64 B  ApplyZombieConditionsChallenge::ApplyZombieConditionsChallenge _ZN30ApplyZombieConditionsChallengeC1Ev
// TODO     56 B  ApplyZombieConditionsChallenge::gameplayEnded        _ZN30ApplyZombieConditionsChallenge13gameplayEndedEv
// TODO     52 B  ApplyZombieConditionsChallenge::~ApplyZombieConditionsChallenge _ZN30ApplyZombieConditionsChallengeD2Ev
// TODO     52 B  ApplyZombieConditionsChallenge::~ApplyZombieConditionsChallenge _ZN30ApplyZombieConditionsChallengeD1Ev
// TODO     52 B  ApplyZombieConditionsChallengeProps::~ApplyZombieConditionsChallengeProps _ZN35ApplyZombieConditionsChallengePropsD2Ev
// TODO     52 B  ApplyZombieConditionsChallengeProps::~ApplyZombieConditionsChallengeProps _ZN35ApplyZombieConditionsChallengePropsD1Ev
// TODO     44 B  ApplyZombieConditionsChallenge::StaticNew            _ZN30ApplyZombieConditionsChallenge9StaticNewEv
// TODO     44 B  ApplyZombieConditionsChallengeProps::StaticNew       _ZN35ApplyZombieConditionsChallengeProps9StaticNewEv
// TODO     36 B  ApplyZombieConditionsChallenge::~ApplyZombieConditionsChallenge _ZN30ApplyZombieConditionsChallengeD0Ev
// TODO     36 B  ApplyZombieConditionsChallengeProps::~ApplyZombieConditionsChallengeProps _ZN35ApplyZombieConditionsChallengePropsD0Ev
