// PvZ2/plants/ZoybeanPod/PlantAnimRig_ZoybeanPod.cpp
//
// 18 function(s), 2744 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_ZoybeanPod
//
// TODO    364 B  PlantAnimRig_ZoybeanPod::onPopAnimCommand            _ZN23PlantAnimRig_ZoybeanPod16onPopAnimCommandEfRKSsS1_
// TODO    352 B  PlantAnimRig_ZoybeanPod::CalcTransitionTime          _ZN23PlantAnimRig_ZoybeanPod18CalcTransitionTimeEv
// TODO    196 B  PlantAnimRig_ZoybeanPod::PlayTransition              _ZN23PlantAnimRig_ZoybeanPod14PlayTransitionESs
// TODO    184 B  PlantAnimRig_ZoybeanPod::PlayAttack                  _ZN23PlantAnimRig_ZoybeanPod10PlayAttackE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    180 B  PlantAnimRig_ZoybeanPod::StaticClassInit             _ZN23PlantAnimRig_ZoybeanPod15StaticClassInitEv
// TODO    176 B  PlantAnimRig_ZoybeanPod::PlayInitialFrame            _ZN23PlantAnimRig_ZoybeanPod16PlayInitialFrameEv
// TODO    176 B  PlantAnimRig_ZoybeanPod::PlayCharging                _ZN23PlantAnimRig_ZoybeanPod12PlayChargingEv
// TODO    176 B  PlantAnimRig_ZoybeanPod::PlayFullyCharged            _ZN23PlantAnimRig_ZoybeanPod16PlayFullyChargedEv
// TODO    176 B  PlantAnimRig_ZoybeanPod::PlayRecovery                _ZN23PlantAnimRig_ZoybeanPod12PlayRecoveryEv
// TODO    176 B  PlantAnimRig_ZoybeanPod::PlayPreviewAnim             _ZN23PlantAnimRig_ZoybeanPod15PlayPreviewAnimEb
// TODO    124 B  PlantAnimRig_ZoybeanPod::StaticGetClass              _ZN23PlantAnimRig_ZoybeanPod14StaticGetClassEv
// TODO     84 B  PlantAnimRig_ZoybeanPod::PlantAnimRig_ZoybeanPod     _ZN23PlantAnimRig_ZoybeanPodC2Ev
// TODO     84 B  PlantAnimRig_ZoybeanPod::PlantAnimRig_ZoybeanPod     _ZN23PlantAnimRig_ZoybeanPodC1Ev
// TODO     80 B  PlantAnimRig_ZoybeanPod::~PlantAnimRig_ZoybeanPod    _ZN23PlantAnimRig_ZoybeanPodD2Ev
// TODO     80 B  PlantAnimRig_ZoybeanPod::~PlantAnimRig_ZoybeanPod    _ZN23PlantAnimRig_ZoybeanPodD1Ev
// TODO     56 B  PlantAnimRig_ZoybeanPod::PlayZenGardenIdleAnim       _ZN23PlantAnimRig_ZoybeanPod21PlayZenGardenIdleAnimEv
// TODO     44 B  PlantAnimRig_ZoybeanPod::StaticNew                   _ZN23PlantAnimRig_ZoybeanPod9StaticNewEv
// TODO     36 B  PlantAnimRig_ZoybeanPod::~PlantAnimRig_ZoybeanPod    _ZN23PlantAnimRig_ZoybeanPodD0Ev
