// PvZ2/zombies/ZombossMech_Hydra/ZombieZombossMech_Hydra.cpp
//
// 30 function(s), 6584 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieZombossMech_Hydra
//
// TODO   1148 B  ZombieZombossMech_Hydra::onPopAnimCommand            _ZN23ZombieZombossMech_Hydra16onPopAnimCommandERKSsfS1_S1_
// TODO    740 B  ZombieZombossMech_Hydra::PlayDefendEffect            _ZN23ZombieZombossMech_Hydra16PlayDefendEffectEb
// TODO    624 B  ZombieZombossMech_Hydra::onEnterState_ZombossIntro   _ZN23ZombieZombossMech_Hydra25onEnterState_ZombossIntroE11ZombieState
// TODO    496 B  ZombieZombossMech_Hydra::onIntroAnimDone             _ZN23ZombieZombossMech_Hydra15onIntroAnimDoneERKSs
// TODO    468 B  ZombieZombossMech_Hydra::StaticClassInit             _ZN23ZombieZombossMech_Hydra15StaticClassInitEv
// TODO    464 B  ZombieZombossMech_Hydra::updateState_MagnetStun      _ZN23ZombieZombossMech_Hydra22updateState_MagnetStunEv
// TODO    444 B  ZombieZombossMech_Hydra::spawnHydraHead              _ZN23ZombieZombossMech_Hydra14spawnHydraHeadEv
// TODO    336 B  ZombieZombossMech_Hydra::onEnterState_MagnetStun     _ZN23ZombieZombossMech_Hydra23onEnterState_MagnetStunE11ZombieState
// TODO    336 B  ZombieZombossMech_Hydra::canBeMagnetStunned          _ZN23ZombieZombossMech_Hydra18canBeMagnetStunnedEv
// TODO    296 B  ZombieZombossMech_Hydra::Retreat                     _ZN23ZombieZombossMech_Hydra7RetreatE11ZombieState
// TODO    204 B  ZombieZombossMech_Hydra::onExitState_Die             _ZN23ZombieZombossMech_Hydra15onExitState_DieE11ZombieState
// TODO    156 B  ZombieZombossMech_Hydra::onExitState_ZombossStageChange _ZN23ZombieZombossMech_Hydra30onExitState_ZombossStageChangeE11ZombieState
// TODO    124 B  ZombieZombossMech_Hydra::RemoveHydraHead             _ZN23ZombieZombossMech_Hydra15RemoveHydraHeadEv
// TODO    124 B  ZombieZombossMech_Hydra::StaticGetClass              _ZN23ZombieZombossMech_Hydra14StaticGetClassEv
// TODO     88 B  ZombieZombossMech_Hydra::onUpdate                    _ZN23ZombieZombossMech_Hydra8onUpdateEv
// TODO     76 B  ZombieZombossMech_Hydra::ZombieZombossMech_Hydra     _ZN23ZombieZombossMech_HydraC2Ev
// TODO     76 B  ZombieZombossMech_Hydra::ZombieZombossMech_Hydra     _ZN23ZombieZombossMech_HydraC1Ev
// TODO     64 B  ZombieZombossMech_Hydra::~ZombieZombossMech_Hydra    _ZN23ZombieZombossMech_HydraD2Ev
// TODO     64 B  ZombieZombossMech_Hydra::~ZombieZombossMech_Hydra    _ZN23ZombieZombossMech_HydraD1Ev
// TODO     56 B  ZombieZombossMech_Hydra::onExitState_MagnetStun      _ZN23ZombieZombossMech_Hydra22onExitState_MagnetStunE11ZombieState
// TODO     44 B  ZombieZombossMech_Hydra::StaticNew                   _ZN23ZombieZombossMech_Hydra9StaticNewEv
// TODO     40 B  ZombieZombossMech_Hydra::onEnterState_ZombossStageChange _ZN23ZombieZombossMech_Hydra31onEnterState_ZombossStageChangeE11ZombieState
// TODO     36 B  ZombieZombossMech_Hydra::~ZombieZombossMech_Hydra    _ZN23ZombieZombossMech_HydraD0Ev
// TODO     32 B  ZombieZombossMech_Hydra::onMagnetStunEndAnimDone     _ZN23ZombieZombossMech_Hydra23onMagnetStunEndAnimDoneERKSs
// TODO     24 B  ZombieZombossMech_Hydra::onMagnetStunAnimDone        _ZN23ZombieZombossMech_Hydra20onMagnetStunAnimDoneERKSs
// TODO      8 B  ZombieZombossMech_Hydra::isPlantAllowedUnderZomboss  _ZN23ZombieZombossMech_Hydra26isPlantAllowedUnderZombossEPK9PlantType
// TODO      4 B  ZombieZombossMech_Hydra::buildStunMovementCurve      _ZN23ZombieZombossMech_Hydra22buildStunMovementCurveEv
// TODO      4 B  ZombieZombossMech_Hydra::onZombieInitialize          _ZN23ZombieZombossMech_Hydra18onZombieInitializeEv
// TODO      4 B  ZombieZombossMech_Hydra::onPlaceOnBoard              _ZN23ZombieZombossMech_Hydra14onPlaceOnBoardEv
// TODO      4 B  ZombieZombossMech_Hydra::onExitState_ZombossIntro    _ZN23ZombieZombossMech_Hydra24onExitState_ZombossIntroE11ZombieState
