// PvZ2/zombies/zomboss/ZombossBattleModule.cpp
//
// 41 function(s), 4492 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombossBattleModule, ZombossBattleModuleProperties
//
// TODO   1000 B  ZombossBattleModule::HandleStateMachine_ZombossBattleState _ZN19ZombossBattleModule37HandleStateMachine_ZombossBattleStateE18ZombossBattleState11StateAction
// TODO    756 B  ZombossBattleModule::registerForEvents               _ZN19ZombossBattleModule17registerForEventsEv
// TODO    212 B  ZombossBattleModule::onLoadComplete                  _ZN19ZombossBattleModule14onLoadCompleteEv
// TODO    180 B  ZombossBattleModule::StaticClassInit                 _ZN19ZombossBattleModule15StaticClassInitEv
// TODO    180 B  ZombossBattleModuleProperties::StaticClassInit       _ZN29ZombossBattleModuleProperties15StaticClassInitEv
// TODO    128 B  ZombossBattleModule::playZombossIntroMusic           _ZN19ZombossBattleModule21playZombossIntroMusicEv
// TODO    128 B  ZombossBattleModule::playZombossOutroMusic           _ZN19ZombossBattleModule21playZombossOutroMusicEv
// TODO    128 B  ZombossBattleModule::playZombossFailureMusic         _ZN19ZombossBattleModule23playZombossFailureMusicEv
// TODO    124 B  ZombossBattleModule::StaticGetClass                  _ZN19ZombossBattleModule14StaticGetClassEv
// TODO    124 B  ZombossBattleModuleProperties::StaticGetClass        _ZN29ZombossBattleModuleProperties14StaticGetClassEv
// TODO    108 B  ZombossBattleModule::gatherPlantingRestrictions      _ZN19ZombossBattleModule26gatherPlantingRestrictionsERKN4Sexy5PointEPK9PlantTypePSt6vectorI14PlantingReasonSaIS8_EE
// TODO    100 B  ZombossBattleModule::startZombossBattling            _ZN19ZombossBattleModule20startZombossBattlingEv
// TODO     96 B  ZombossBattleModule::setState_ZombossBattleState     _ZN19ZombossBattleModule27setState_ZombossBattleStateE18ZombossBattleState
// TODO     92 B  ZombossBattleModule::TriggerZombossExit              _ZN19ZombossBattleModule18TriggerZombossExitEv
// TODO     88 B  ZombossBattleModuleProperties::ZombossBattleModuleProperties _ZN29ZombossBattleModulePropertiesC2Ev
// TODO     88 B  ZombossBattleModuleProperties::ZombossBattleModuleProperties _ZN29ZombossBattleModulePropertiesC1Ev
// TODO     64 B  ZombossBattleModule::ZombossBattleModule             _ZN19ZombossBattleModuleC2Ev
// TODO     64 B  ZombossBattleModule::ZombossBattleModule             _ZN19ZombossBattleModuleC1Ev
// TODO     60 B  ZombossBattleModule::~ZombossBattleModule            _ZN19ZombossBattleModuleD2Ev
// TODO     60 B  ZombossBattleModule::~ZombossBattleModule            _ZN19ZombossBattleModuleD1Ev
// TODO     60 B  ZombossBattleModule::onUpdate                        _ZN19ZombossBattleModule8onUpdateEv
// TODO     56 B  ZombossBattleModule::SendZombossMusicEvent           _ZN19ZombossBattleModule21SendZombossMusicEventERKSs
// TODO     52 B  ZombossBattleModuleProperties::~ZombossBattleModuleProperties _ZN29ZombossBattleModulePropertiesD2Ev
// TODO     52 B  ZombossBattleModuleProperties::~ZombossBattleModuleProperties _ZN29ZombossBattleModulePropertiesD1Ev
// TODO     48 B  ZombossBattleModule::GetZombossMechType              _ZN19ZombossBattleModule18GetZombossMechTypeEv
// TODO     44 B  ZombossBattleModule::StaticNew                       _ZN19ZombossBattleModule9StaticNewEv
// TODO     44 B  ZombossBattleModuleProperties::StaticNew             _ZN29ZombossBattleModuleProperties9StaticNewEv
// TODO     40 B  ZombossBattleModule::onPostLoad                      _ZN19ZombossBattleModule10onPostLoadEv
// TODO     40 B  ZombossBattleModule::ShowZombossIntro                _ZN19ZombossBattleModule16ShowZombossIntroEv
// TODO     36 B  ZombossBattleModule::~ZombossBattleModule            _ZN19ZombossBattleModuleD0Ev
// TODO     36 B  ZombossBattleModule::checkWinCondition               _ZN19ZombossBattleModule17checkWinConditionEv
// TODO     36 B  ZombossBattleModuleProperties::~ZombossBattleModuleProperties _ZN29ZombossBattleModulePropertiesD0Ev
// TODO     32 B  ZombossBattleModule::onInitialized                   _ZN19ZombossBattleModule13onInitializedEv
// TODO     32 B  ZombossBattleModule::IsZombossDone                   _ZN19ZombossBattleModule13IsZombossDoneEv
// TODO     32 B  ZombossBattleModule::spawnInitialZomboss             _ZN19ZombossBattleModule19spawnInitialZombossEv
// TODO     24 B  ZombossBattleModule::initializeModule                _ZN19ZombossBattleModule16initializeModuleEv
// TODO     16 B  ZombossBattleModule::OnGameplayStarted               _ZN19ZombossBattleModule17OnGameplayStartedEv
// TODO     12 B  ZombossBattleModule::onLastStandInit                 _ZN19ZombossBattleModule15onLastStandInitEv
// TODO      8 B  ZombossBattleModule::spawnZomboss                    _ZN19ZombossBattleModule12spawnZombossEv
// TODO      8 B  ZombossBattleModule::onLastStandStart                _ZN19ZombossBattleModule16onLastStandStartEv
// TODO      4 B  ZombossBattleModule::HandleSuperFSMAction_ZombossBattleState _ZN19ZombossBattleModule39HandleSuperFSMAction_ZombossBattleStateE18ZombossBattleState11StateAction
