// PvZ2/plants/Tigerstool/Plant_Tigerstool.cpp
//
// 34 function(s), 17372 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantTigerstool
//
// TODO   5044 B  PlantTigerstool::onStandaloneEffectFinishedCallback  _ZN15PlantTigerstool34onStandaloneEffectFinishedCallbackEP16StandaloneEffect
// TODO   4104 B  PlantTigerstool::onStandaloneEffectFinishedCallback1 _ZN15PlantTigerstool35onStandaloneEffectFinishedCallback1EP16StandaloneEffect
// TODO   3492 B  PlantTigerstool::DoSpecial                           _ZN15PlantTigerstool9DoSpecialEi
// TODO    624 B  PlantTigerstool::TossZombieByAttackUppercut          _ZN15PlantTigerstool26TossZombieByAttackUppercutEP6Zombie
// TODO    500 B  PlantTigerstool::FindTargetsAndPlayAttackAnim        _ZN15PlantTigerstool28FindTargetsAndPlayAttackAnimEv
// TODO    468 B  PlantTigerstool::MayUppercutTarget                   _ZN15PlantTigerstool17MayUppercutTargetEN4Sexy9RtWeakPtrI6ZombieEE
// TODO    420 B  PlantTigerstool::Initialize                          _ZN15PlantTigerstool10InitializeEv
// TODO    344 B  PlantTigerstool::GetGridItemTarget                   _ZN15PlantTigerstool17GetGridItemTargetEb
// TODO    284 B  PlantTigerstool::WouldKillTarget                     _ZN15PlantTigerstool15WouldKillTargetEP8GridItem
// TODO    248 B  PlantTigerstool::WouldKillTarget                     _ZN15PlantTigerstool15WouldKillTargetEN4Sexy9RtWeakPtrI6ZombieEE
// TODO    196 B  PlantTigerstool::myrandom                            _ZN15PlantTigerstool8myrandomEv
// TODO    188 B  PlantTigerstool::UpdateActions                       _ZN15PlantTigerstool13UpdateActionsEv
// TODO    180 B  PlantTigerstool::StaticClassInit                     _ZN15PlantTigerstool15StaticClassInitEv
// TODO    152 B  PlantTigerstool::PlantTigerstool                     _ZN15PlantTigerstoolC2Ev
// TODO    152 B  PlantTigerstool::PlantTigerstool                     _ZN15PlantTigerstoolC1Ev
// TODO    148 B  PlantTigerstool::GetZombieTarget                     _ZN15PlantTigerstool15GetZombieTargetEb
// TODO    124 B  PlantTigerstool::StaticGetClass                      _ZN15PlantTigerstool14StaticGetClassEv
// TODO    100 B  PlantTigerstool::GetPlantAttackRect                  _ZN15PlantTigerstool18GetPlantAttackRectE11PlantWeapon
// TODO     88 B  PlantTigerstool::CalcRenderOrder                     _ZN15PlantTigerstool15CalcRenderOrderEv
// TODO     84 B  PlantTigerstool::StunZombies                         _ZN15PlantTigerstool11StunZombiesEv
// TODO     56 B  PlantTigerstool::CheckSupercut                       _ZN15PlantTigerstool13CheckSupercutEv
// TODO     52 B  PlantTigerstool::DoSpecialForAvatarNormal            _ZN15PlantTigerstool24DoSpecialForAvatarNormalEv
// TODO     52 B  PlantTigerstool::CanStunZombies                      _ZN15PlantTigerstool14CanStunZombiesEv
// TODO     44 B  PlantTigerstool::ApplyPlantfood                      _ZN15PlantTigerstool14ApplyPlantfoodEv
// TODO     44 B  PlantTigerstool::CancelPlantfood                     _ZN15PlantTigerstool15CancelPlantfoodEv
// TODO     44 B  PlantTigerstool::StaticNew                           _ZN15PlantTigerstool9StaticNewEv
// TODO     44 B  PlantTigerstool::CanTargetZombie                     _ZN15PlantTigerstool15CanTargetZombieEN4Sexy9RtWeakPtrI6ZombieEE11PlantWeapon
// TODO     36 B  PlantTigerstool::~PlantTigerstool                    _ZN15PlantTigerstoolD0Ev
// TODO     20 B  PlantTigerstool::~PlantTigerstool                    _ZN15PlantTigerstoolD2Ev
// TODO     20 B  PlantTigerstool::~PlantTigerstool                    _ZN15PlantTigerstoolD1Ev
// TODO      8 B  PlantTigerstool::CanApplyPlantfood                   _ZN15PlantTigerstool17CanApplyPlantfoodEv
// TODO      4 B  PlantTigerstool::UpdatePlantfood                     _ZN15PlantTigerstool15UpdatePlantfoodEv
// TODO      4 B  PlantTigerstool::onPFFinishedCallback                _ZN15PlantTigerstool20onPFFinishedCallbackEP16StandaloneEffect
// TODO      4 B  PlantTigerstool::MayUppercutTarget                   _ZN15PlantTigerstool17MayUppercutTargetEP8GridItem
