// PvZ2/Plant_Peach.cpp
//
// 25 function(s), 3768 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantPeach
//
// TODO    524 B  PlantPeach::CurePlant                                _ZN10PlantPeach9CurePlantERK11PlantAction
// TODO    432 B  PlantPeach::setAroundInvincible                      _ZN10PlantPeach19setAroundInvincibleEb
// TODO    396 B  PlantPeach::UpdateAttackUpValue                      _ZN10PlantPeach19UpdateAttackUpValueEv
// TODO    372 B  PlantPeach::UpdateActions                            _ZN10PlantPeach13UpdateActionsEv
// TODO    340 B  PlantPeach::PlantCanBeCured                          _ZN10PlantPeach15PlantCanBeCuredEP5Plant
// TODO    312 B  PlantPeach::PlayAttackUpEffect                       _ZN10PlantPeach18PlayAttackUpEffectEv
// TODO    296 B  PlantPeach::ApplyPlantfood                           _ZN10PlantPeach14ApplyPlantfoodEv
// TODO    288 B  PlantPeach::IsPlantNeedCure                          _ZN10PlantPeach15IsPlantNeedCureEv
// TODO    180 B  PlantPeach::StaticClassInit                          _ZN10PlantPeach15StaticClassInitEv
// TODO    124 B  PlantPeach::StaticGetClass                           _ZN10PlantPeach14StaticGetClassEv
// TODO     68 B  PlantPeach::onAnimStoppedCallback                    _ZN10PlantPeach21onAnimStoppedCallbackERKSs
// TODO     60 B  PlantPeach::Initialize                               _ZN10PlantPeach10InitializeEv
// TODO     60 B  PlantPeach::doTakeCure                               _ZN10PlantPeach10doTakeCureEP5Plant
// TODO     48 B  PlantPeach::PlantPeach                               _ZN10PlantPeachC2Ev
// TODO     48 B  PlantPeach::PlantPeach                               _ZN10PlantPeachC1Ev
// TODO     44 B  PlantPeach::CancelPlantfood                          _ZN10PlantPeach15CancelPlantfoodEv
// TODO     44 B  PlantPeach::StaticNew                                _ZN10PlantPeach9StaticNewEv
// TODO     36 B  PlantPeach::~PlantPeach                              _ZN10PlantPeachD0Ev
// TODO     32 B  PlantPeach::ShouldPlayAttactUpEffect                 _ZN10PlantPeach24ShouldPlayAttactUpEffectEv
// TODO     20 B  PlantPeach::~PlantPeach                              _ZN10PlantPeachD2Ev
// TODO     20 B  PlantPeach::~PlantPeach                              _ZN10PlantPeachD1Ev
// TODO      8 B  PlantPeach::CanApplyPlantfood                        _ZN10PlantPeach17CanApplyPlantfoodEv
// TODO      8 B  PlantPeach::onPlantfoodStarted                       _ZN10PlantPeach18onPlantfoodStartedEv
// TODO      4 B  PlantPeach::DoSpecial                                _ZN10PlantPeach9DoSpecialEi
// TODO      4 B  PlantPeach::onDestroy                                _ZN10PlantPeach9onDestroyEv
