// PvZ2/modules/ArtifactModule.cpp
//
// 20 function(s), 1608 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ArtifactModule, ArtifactModuleProperties
//
// TODO    268 B  ArtifactModule::initializeArtifacts                  _ZN14ArtifactModule19initializeArtifactsEv
// TODO    180 B  ArtifactModule::StaticClassInit                      _ZN14ArtifactModule15StaticClassInitEv
// TODO    180 B  ArtifactModuleProperties::StaticClassInit            _ZN24ArtifactModuleProperties15StaticClassInitEv
// TODO    144 B  ArtifactModule::registerForEvents                    _ZN14ArtifactModule17registerForEventsEv
// TODO    124 B  ArtifactModule::StaticGetClass                       _ZN14ArtifactModule14StaticGetClassEv
// TODO    124 B  ArtifactModuleProperties::StaticGetClass             _ZN24ArtifactModuleProperties14StaticGetClassEv
// TODO     64 B  ArtifactModule::onInit                               _ZN14ArtifactModule6onInitEv
// TODO     52 B  ArtifactModuleProperties::ArtifactModuleProperties   _ZN24ArtifactModulePropertiesC2Ev
// TODO     52 B  ArtifactModuleProperties::ArtifactModuleProperties   _ZN24ArtifactModulePropertiesC1Ev
// TODO     52 B  ArtifactModuleProperties::~ArtifactModuleProperties  _ZN24ArtifactModulePropertiesD2Ev
// TODO     52 B  ArtifactModuleProperties::~ArtifactModuleProperties  _ZN24ArtifactModulePropertiesD1Ev
// TODO     48 B  ArtifactModule::ArtifactModule                       _ZN14ArtifactModuleC2Ev
// TODO     48 B  ArtifactModule::ArtifactModule                       _ZN14ArtifactModuleC1Ev
// TODO     44 B  ArtifactModule::StaticNew                            _ZN14ArtifactModule9StaticNewEv
// TODO     44 B  ArtifactModuleProperties::StaticNew                  _ZN24ArtifactModuleProperties9StaticNewEv
// TODO     36 B  ArtifactModule::~ArtifactModule                      _ZN14ArtifactModuleD0Ev
// TODO     36 B  ArtifactModuleProperties::~ArtifactModuleProperties  _ZN24ArtifactModulePropertiesD0Ev
// TODO     20 B  ArtifactModule::~ArtifactModule                      _ZN14ArtifactModuleD2Ev
// TODO     20 B  ArtifactModule::~ArtifactModule                      _ZN14ArtifactModuleD1Ev
// TODO     20 B  ArtifactModule::onArtifactInit                       _ZN14ArtifactModule14onArtifactInitEv
