// PvZ2/modules/BeghouledModule.cpp
//
// 55 function(s), 22372 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: BeghouledModule
//
// TODO   4408 B  BeghouledModule::StaticClassInit                     _ZN15BeghouledModule15StaticClassInitEv
// TODO   1748 B  BeghouledModule::BeghouledTypeToString               _ZN15BeghouledModule21BeghouledTypeToStringE18BeghouledPlantType
// TODO   1080 B  BeghouledModule::CacheMatch                          _ZN15BeghouledModule10CacheMatchEiiP19BeghouledBoardStateibRb
// TODO   1036 B  BeghouledModule::DragUpdate                          _ZN15BeghouledModule10DragUpdateEN4Sexy5PointE
// TODO    696 B  BeghouledModule::updateSeedBank                      _ZN15BeghouledModule14updateSeedBankE18BeghouledPlantType
// TODO    664 B  BeghouledModule::registerForEvents                   _ZN15BeghouledModule17registerForEventsEv
// TODO    628 B  BeghouledModule::onUpdate                            _ZN15BeghouledModule8onUpdateEv
// TODO    624 B  BeghouledModule::calcCrossingPlants                  _ZN15BeghouledModule18calcCrossingPlantsEv
// TODO    580 B  BeghouledModule::Score                               _ZN15BeghouledModule5ScoreEiiibb
// TODO    568 B  BeghouledModule::CreatePlants                        _ZN15BeghouledModule12CreatePlantsEP19BeghouledBoardStateS1_
// TODO    520 B  BeghouledModule::RemoveMatches                       _ZN15BeghouledModule13RemoveMatchesEP19BeghouledBoardState
// TODO    492 B  BeghouledModule::updateBoardForUpgradedPlant         _ZN15BeghouledModule27updateBoardForUpgradedPlantE18BeghouledPlantType
// TODO    484 B  BeghouledModule::FlashFromBoardState                 _ZN15BeghouledModule19FlashFromBoardStateEP19BeghouledBoardStateiiii
// TODO    484 B  BeghouledModule::removeAllMatches                    _ZN15BeghouledModule16removeAllMatchesEv
// TODO    468 B  BeghouledModule::FallIntoSquare                      _ZN15BeghouledModule14FallIntoSquareEiiP19BeghouledBoardState
// TODO    444 B  BeghouledModule::postInitialize                      _ZN15BeghouledModule14postInitializeEv
// TODO    440 B  BeghouledModule::onTouchEvent                        _ZN15BeghouledModule12onTouchEventERKN4Sexy5TouchE
// TODO    416 B  BeghouledModule::FlashAMatch                         _ZN15BeghouledModule11FlashAMatchEv
// TODO    408 B  BeghouledModule::onPlantUpgraded                     _ZN15BeghouledModule15onPlantUpgradedERSs
// TODO    392 B  BeghouledModule::LoadBeghouledBoardState             _ZN15BeghouledModule23LoadBeghouledBoardStateEP19BeghouledBoardState
// TODO    348 B  BeghouledModule::setToolVisibility                   _ZN15BeghouledModule17setToolVisibilityEv
// TODO    320 B  BeghouledModule::PickPlant                           _ZN15BeghouledModule9PickPlantEiiP19BeghouledBoardStateb
// TODO    312 B  BeghouledModule::Shuffle                             _ZN15BeghouledModule7ShuffleEv
// TODO    288 B  BeghouledModule::IsValidMove                         _ZN15BeghouledModule11IsValidMoveEiiiiP19BeghouledBoardState
// TODO    272 B  BeghouledModule::onLocationCleared                   _ZN15BeghouledModule17onLocationClearedEii
// TODO    268 B  BeghouledModule::InitPlantUpgradeMap                 _ZN15BeghouledModule19InitPlantUpgradeMapEv
// TODO    248 B  BeghouledModule::updateZombieSpawner                 _ZN15BeghouledModule19updateZombieSpawnerEv
// TODO    248 B  BeghouledModule::checkWinCondition                   _ZN15BeghouledModule17checkWinConditionEv
// TODO    244 B  BeghouledModule::FlashPlant                          _ZN15BeghouledModule10FlashPlantEiiiiii
// TODO    236 B  BeghouledModule::onClearBoard                        _ZN15BeghouledModule12onClearBoardEv
// TODO    200 B  BeghouledModule::CheckForPossibleMoves               _ZN15BeghouledModule21CheckForPossibleMovesEP19BeghouledBoardState
// TODO    200 B  BeghouledModule::PopulateBoard                       _ZN15BeghouledModule13PopulateBoardEv
// TODO    176 B  BeghouledModule::onPlantDied                         _ZN15BeghouledModule11onPlantDiedEP5Plant
// TODO    172 B  BeghouledModule::HorizontalMatchLength               _ZN15BeghouledModule21HorizontalMatchLengthEiiP19BeghouledBoardState
// TODO    172 B  BeghouledModule::VerticalMatchLength                 _ZN15BeghouledModule19VerticalMatchLengthEiiP19BeghouledBoardState
// TODO    172 B  BeghouledModule::FillHoles                           _ZN15BeghouledModule9FillHolesEP19BeghouledBoardStateb
// TODO    152 B  BeghouledModule::BoardHasMatch                       _ZN15BeghouledModule13BoardHasMatchEP19BeghouledBoardState
// TODO    152 B  BeghouledModule::isPlantPlantfooded                  _ZN15BeghouledModule18isPlantPlantfoodedEN4Sexy9RtWeakPtrI5PlantEE
// TODO    152 B  BeghouledModule::BeghouledModule                     _ZN15BeghouledModuleC2Ev
// TODO    152 B  BeghouledModule::BeghouledModule                     _ZN15BeghouledModuleC1Ev
// TODO    152 B  BeghouledModule::InitPlantMap                        _ZN15BeghouledModule12InitPlantMapEv
// TODO    144 B  BeghouledModule::CalcBeghouledTypeFromPlantType      _ZN15BeghouledModule30CalcBeghouledTypeFromPlantTypeESs
// TODO    136 B  BeghouledModule::~BeghouledModule                    _ZN15BeghouledModuleD2Ev
// TODO    136 B  BeghouledModule::~BeghouledModule                    _ZN15BeghouledModuleD1Ev
// TODO    132 B  BeghouledModule::CheckStuckState                     _ZN15BeghouledModule15CheckStuckStateEv
// TODO    132 B  BeghouledModule::MakePlantsFall                      _ZN15BeghouledModule14MakePlantsFallEP19BeghouledBoardState
// TODO    124 B  BeghouledModule::StaticGetClass                      _ZN15BeghouledModule14StaticGetClassEv
// TODO    116 B  BeghouledModule::GetPlantAt                          _ZN15BeghouledModule10GetPlantAtEiiP19BeghouledBoardState
// TODO     68 B  BeghouledModule::EnableSwapping                      _ZN15BeghouledModule14EnableSwappingEb
// TODO     44 B  BeghouledModule::resetFlashTimer                     _ZN15BeghouledModule15resetFlashTimerEv
// TODO     44 B  BeghouledModule::StaticNew                           _ZN15BeghouledModule9StaticNewEv
// TODO     36 B  BeghouledModule::~BeghouledModule                    _ZN15BeghouledModuleD0Ev
// TODO     20 B  BeghouledModule::DragStart                           _ZN15BeghouledModule9DragStartEN4Sexy5PointE
// TODO     20 B  BeghouledModule::StartFalling                        _ZN15BeghouledModule12StartFallingE22BeghouledGameplayState
// TODO      4 B  BeghouledModule::GatherDependentModulePropertySheets _ZN15BeghouledModule35GatherDependentModulePropertySheetsERSt6vectorIN4Sexy9RtWeakPtrIK21LevelModulePropertiesEESaIS5_EE
