// PvZ2/modules/GoldRoadModule.cpp
//
// 14 function(s), 1200 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: GoldRoadModule
//
// TODO    264 B  GoldRoadModule::registerForEvents                    _ZN14GoldRoadModule17registerForEventsEv
// TODO    184 B  GoldRoadModule::onLoadComplete                       _ZN14GoldRoadModule14onLoadCompleteEv
// TODO    180 B  GoldRoadModule::StaticClassInit                      _ZN14GoldRoadModule15StaticClassInitEv
// TODO    136 B  GoldRoadModule::addBackgroundToRenderQueue           _ZN14GoldRoadModule26addBackgroundToRenderQueueEP11RenderQueue
// TODO    124 B  GoldRoadModule::StaticGetClass                       _ZN14GoldRoadModule14StaticGetClassEv
// TODO     88 B  GoldRoadModule::renderRunBackground                  _ZN14GoldRoadModule19renderRunBackgroundEPN4Sexy8GraphicsE
// TODO     48 B  GoldRoadModule::GoldRoadModule                       _ZN14GoldRoadModuleC2Ev
// TODO     48 B  GoldRoadModule::GoldRoadModule                       _ZN14GoldRoadModuleC1Ev
// TODO     44 B  GoldRoadModule::StaticNew                            _ZN14GoldRoadModule9StaticNewEv
// TODO     36 B  GoldRoadModule::~GoldRoadModule                      _ZN14GoldRoadModuleD0Ev
// TODO     20 B  GoldRoadModule::~GoldRoadModule                      _ZN14GoldRoadModuleD2Ev
// TODO     20 B  GoldRoadModule::~GoldRoadModule                      _ZN14GoldRoadModuleD1Ev
// TODO      4 B  GoldRoadModule::initializeModule                     _ZN14GoldRoadModule16initializeModuleEv
// TODO      4 B  GoldRoadModule::onGameplayStarted                    _ZN14GoldRoadModule17onGameplayStartedEv
