// PvZ2/modules/JuggledModule.cpp
//
// 20 function(s), 1704 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: JuggledModule, JuggledModuleProperties
//
// TODO    248 B  JuggledModule::onLoadComplete                        _ZN13JuggledModule14onLoadCompleteEv
// TODO    180 B  JuggledModule::StaticClassInit                       _ZN13JuggledModule15StaticClassInitEv
// TODO    180 B  JuggledModuleProperties::StaticClassInit             _ZN23JuggledModuleProperties15StaticClassInitEv
// TODO    144 B  JuggledModule::registerForEvents                     _ZN13JuggledModule17registerForEventsEv
// TODO    124 B  JuggledModule::StaticGetClass                        _ZN13JuggledModule14StaticGetClassEv
// TODO    124 B  JuggledModuleProperties::StaticGetClass              _ZN23JuggledModuleProperties14StaticGetClassEv
// TODO    124 B  JuggledModuleProperties::JuggledModuleProperties     _ZN23JuggledModulePropertiesC2Ev
// TODO    124 B  JuggledModuleProperties::JuggledModuleProperties     _ZN23JuggledModulePropertiesC1Ev
// TODO     68 B  JuggledModuleProperties::~JuggledModuleProperties    _ZN23JuggledModulePropertiesD2Ev
// TODO     68 B  JuggledModuleProperties::~JuggledModuleProperties    _ZN23JuggledModulePropertiesD1Ev
// TODO     48 B  JuggledModule::JuggledModule                         _ZN13JuggledModuleC2Ev
// TODO     48 B  JuggledModule::JuggledModule                         _ZN13JuggledModuleC1Ev
// TODO     44 B  JuggledModule::StaticNew                             _ZN13JuggledModule9StaticNewEv
// TODO     44 B  JuggledModuleProperties::StaticNew                   _ZN23JuggledModuleProperties9StaticNewEv
// TODO     36 B  JuggledModule::~JuggledModule                        _ZN13JuggledModuleD0Ev
// TODO     36 B  JuggledModuleProperties::~JuggledModuleProperties    _ZN23JuggledModulePropertiesD0Ev
// TODO     20 B  JuggledModule::unregisterForEvents                   _ZN13JuggledModule19unregisterForEventsEv
// TODO     20 B  JuggledModule::~JuggledModule                        _ZN13JuggledModuleD2Ev
// TODO     20 B  JuggledModule::~JuggledModule                        _ZN13JuggledModuleD1Ev
// TODO      4 B  JuggledModule::AddResourceRequirements               _ZN13JuggledModule23AddResourceRequirementsERSt3setISsSt4lessISsESaISsEE
