// PvZ2/griditems/protector/GridItemProtectorShieldSegmentAlpha.cpp
//
// 19 function(s), 3548 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: GridItemProtectorShieldSegmentAlpha
//
// TODO    604 B  GridItemProtectorShieldSegmentAlpha::OnCollideEntity _ZN35GridItemProtectorShieldSegmentAlpha15OnCollideEntityEP11BoardEntity
// TODO    424 B  GridItemProtectorShieldSegmentAlpha::onSetPosition   _ZN35GridItemProtectorShieldSegmentAlpha13onSetPositionERKN4Sexy11SexyVector3E
// TODO    416 B  GridItemProtectorShieldSegmentAlpha::flickZombie     _ZN35GridItemProtectorShieldSegmentAlpha11flickZombieEP6Zombie
// TODO    392 B  GridItemProtectorShieldSegmentAlpha::checkDistancedZombies _ZN35GridItemProtectorShieldSegmentAlpha21checkDistancedZombiesEv
// TODO    276 B  GridItemProtectorShieldSegmentAlpha::checkZombies    _ZN35GridItemProtectorShieldSegmentAlpha12checkZombiesEv
// TODO    256 B  GridItemProtectorShieldSegmentAlpha::checkEdge       _ZN35GridItemProtectorShieldSegmentAlpha9checkEdgeEv
// TODO    204 B  GridItemProtectorShieldSegmentAlpha::onDestroy       _ZN35GridItemProtectorShieldSegmentAlpha9onDestroyEv
// TODO    180 B  GridItemProtectorShieldSegmentAlpha::StaticClassInit _ZN35GridItemProtectorShieldSegmentAlpha15StaticClassInitEv
// TODO    176 B  GridItemProtectorShieldSegmentAlpha::isZombieAlreadyPushed _ZN35GridItemProtectorShieldSegmentAlpha21isZombieAlreadyPushedEN4Sexy9RtWeakPtrI6ZombieEE
// TODO    124 B  GridItemProtectorShieldSegmentAlpha::StaticGetClass  _ZN35GridItemProtectorShieldSegmentAlpha14StaticGetClassEv
// TODO     92 B  GridItemProtectorShieldSegmentAlpha::canCheckZombies _ZN35GridItemProtectorShieldSegmentAlpha15canCheckZombiesEv
// TODO     68 B  GridItemProtectorShieldSegmentAlpha::GridItemProtectorShieldSegmentAlpha _ZN35GridItemProtectorShieldSegmentAlphaC2Ev
// TODO     68 B  GridItemProtectorShieldSegmentAlpha::GridItemProtectorShieldSegmentAlpha _ZN35GridItemProtectorShieldSegmentAlphaC1Ev
// TODO     64 B  GridItemProtectorShieldSegmentAlpha::~GridItemProtectorShieldSegmentAlpha _ZN35GridItemProtectorShieldSegmentAlphaD2Ev
// TODO     64 B  GridItemProtectorShieldSegmentAlpha::~GridItemProtectorShieldSegmentAlpha _ZN35GridItemProtectorShieldSegmentAlphaD1Ev
// TODO     52 B  GridItemProtectorShieldSegmentAlpha::onUpdate        _ZN35GridItemProtectorShieldSegmentAlpha8onUpdateEv
// TODO     44 B  GridItemProtectorShieldSegmentAlpha::StaticNew       _ZN35GridItemProtectorShieldSegmentAlpha9StaticNewEv
// TODO     36 B  GridItemProtectorShieldSegmentAlpha::~GridItemProtectorShieldSegmentAlpha _ZN35GridItemProtectorShieldSegmentAlphaD0Ev
// TODO      8 B  GridItemProtectorShieldSegmentAlpha::RecordPreMotion _ZN35GridItemProtectorShieldSegmentAlpha15RecordPreMotionERKN4Sexy11SexyVector3E
