// PvZ2/zombies/FairyTaleImp/ZombieFairyTaleImp.cpp
//
// 35 function(s), 3012 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieFairyTaleImp, ZombieFairyTaleImpProps
//
// TODO    636 B  ZombieFairyTaleImp::StaticClassInit                  _ZN18ZombieFairyTaleImp15StaticClassInitEv
// TODO    408 B  ZombieFairyTaleImp::onEnterState_Running             _ZN18ZombieFairyTaleImp20onEnterState_RunningE11ZombieState
// TODO    344 B  ZombieFairyTaleImp::spawnZombie                      _ZN18ZombieFairyTaleImp11spawnZombieERKSsRKN4Sexy5PointE
// TODO    224 B  ZombieFairyTaleImp::callKnight                       _ZN18ZombieFairyTaleImp10callKnightEv
// TODO    180 B  ZombieFairyTaleImpProps::StaticClassInit             _ZN23ZombieFairyTaleImpProps15StaticClassInitEv
// TODO    124 B  ZombieFairyTaleImp::StaticGetClass                   _ZN18ZombieFairyTaleImp14StaticGetClassEv
// TODO    124 B  ZombieFairyTaleImpProps::StaticGetClass              _ZN23ZombieFairyTaleImpProps14StaticGetClassEv
// TODO     92 B  ZombieFairyTaleImp::onLandingAnimStopped             _ZN18ZombieFairyTaleImp20onLandingAnimStoppedERKSs
// TODO     84 B  ZombieFairyTaleImpProps::ZombieFairyTaleImpProps     _ZN23ZombieFairyTaleImpPropsC2Ev
// TODO     84 B  ZombieFairyTaleImpProps::ZombieFairyTaleImpProps     _ZN23ZombieFairyTaleImpPropsC1Ev
// TODO     64 B  ZombieFairyTaleImp::updateState_Entering             _ZN18ZombieFairyTaleImp20updateState_EnteringEv
// TODO     60 B  ZombieFairyTaleImp::updateState_Running              _ZN18ZombieFairyTaleImp19updateState_RunningEv
// TODO     56 B  ZombieFairyTaleImp::ZombieFairyTaleImp               _ZN18ZombieFairyTaleImpC2Ev
// TODO     56 B  ZombieFairyTaleImp::ZombieFairyTaleImp               _ZN18ZombieFairyTaleImpC1Ev
// TODO     56 B  ZombieFairyTaleImpProps::~ZombieFairyTaleImpProps    _ZN23ZombieFairyTaleImpPropsD2Ev
// TODO     56 B  ZombieFairyTaleImpProps::~ZombieFairyTaleImpProps    _ZN23ZombieFairyTaleImpPropsD1Ev
// TODO     48 B  ZombieFairyTaleImp::onExitState_Running              _ZN18ZombieFairyTaleImp19onExitState_RunningE11ZombieState
// TODO     44 B  ZombieFairyTaleImp::StaticNew                        _ZN18ZombieFairyTaleImp9StaticNewEv
// TODO     44 B  ZombieFairyTaleImpProps::StaticNew                   _ZN23ZombieFairyTaleImpProps9StaticNewEv
// TODO     40 B  ZombieFairyTaleImp::onInitialized                    _ZN18ZombieFairyTaleImp13onInitializedEv
// TODO     36 B  ZombieFairyTaleImp::~ZombieFairyTaleImp              _ZN18ZombieFairyTaleImpD0Ev
// TODO     36 B  ZombieFairyTaleImpProps::~ZombieFairyTaleImpProps    _ZN23ZombieFairyTaleImpPropsD0Ev
// TODO     28 B  ZombieFairyTaleImp::~ZombieFairyTaleImp              _ZN18ZombieFairyTaleImpD2Ev
// TODO     28 B  ZombieFairyTaleImp::~ZombieFairyTaleImp              _ZN18ZombieFairyTaleImpD1Ev
// TODO     12 B  ZombieFairyTaleImp::updateState_Ash                  _ZN18ZombieFairyTaleImp15updateState_AshEv
// TODO      8 B  ZombieFairyTaleImp::canAttack                        _ZN18ZombieFairyTaleImp9canAttackEv
// TODO      8 B  ZombieFairyTaleImp::CheckEdge                        _ZN18ZombieFairyTaleImp9CheckEdgeEv
// TODO      4 B  ZombieFairyTaleImp::onEnterState_Entering            _ZN18ZombieFairyTaleImp21onEnterState_EnteringE11ZombieState
// TODO      4 B  ZombieFairyTaleImp::onWalkAnimContinued              _ZN18ZombieFairyTaleImp19onWalkAnimContinuedERKSsS1_i
// TODO      4 B  ZombieFairyTaleImp::onExitState_Entering             _ZN18ZombieFairyTaleImp20onExitState_EnteringE11ZombieState
// TODO      4 B  ZombieFairyTaleImp::onEnterState_Ash                 _ZN18ZombieFairyTaleImp16onEnterState_AshE11ZombieState
// TODO      4 B  ZombieFairyTaleImp::onExitState_Ash                  _ZN18ZombieFairyTaleImp15onExitState_AshE11ZombieState
// TODO      4 B  ZombieFairyTaleImp::onZombieInitialize               _ZN18ZombieFairyTaleImp18onZombieInitializeEv
// TODO      4 B  ZombieFairyTaleImp::onEnterState_Walk                _ZN18ZombieFairyTaleImp17onEnterState_WalkE11ZombieState
// TODO      4 B  ZombieFairyTaleImp::onPopAnimCommand                 _ZN18ZombieFairyTaleImp16onPopAnimCommandERKSsfS1_S1_
