// PvZ2/plants/Mulberry/Plant_Mulberry.cpp
//
// 20 function(s), 4132 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantMulberry
//
// TODO   1596 B  PlantMulberry::DoSpecial                             _ZN13PlantMulberry9DoSpecialEi
// TODO    324 B  PlantMulberry::PlayAttackAnimation                   _ZN13PlantMulberry19PlayAttackAnimationEv
// TODO    316 B  PlantMulberry::Fire                                  _ZN13PlantMulberry4FireEN4Sexy9RtWeakPtrI6ZombieEEi11PlantWeapon
// TODO    252 B  PlantMulberry::DoNonSuperAttack                      _ZN13PlantMulberry16DoNonSuperAttackEv
// TODO    216 B  PlantMulberry::LaunchProjectileAt                    _ZN13PlantMulberry18LaunchProjectileAtEP10ProjectileRKN4Sexy11SexyVector3E11PlantWeapon
// TODO    180 B  PlantMulberry::StaticClassInit                       _ZN13PlantMulberry15StaticClassInitEv
// TODO    172 B  PlantMulberry::shootBerry                            _ZN13PlantMulberry10shootBerryEb
// TODO    164 B  PlantMulberry::ApplyPlantfood                        _ZN13PlantMulberry14ApplyPlantfoodEv
// TODO    152 B  PlantMulberry::launchSuperGrenade                    _ZN13PlantMulberry18launchSuperGrenadeEv
// TODO    152 B  PlantMulberry::launchFlashGrenade                    _ZN13PlantMulberry18launchFlashGrenadeEv
// TODO    152 B  PlantMulberry::launchGasGrenade                      _ZN13PlantMulberry16launchGasGrenadeEv
// TODO    124 B  PlantMulberry::StaticGetClass                        _ZN13PlantMulberry14StaticGetClassEv
// TODO     52 B  PlantMulberry::PlantMulberry                         _ZN13PlantMulberryC2Ev
// TODO     52 B  PlantMulberry::PlantMulberry                         _ZN13PlantMulberryC1Ev
// TODO     52 B  PlantMulberry::~PlantMulberry                        _ZN13PlantMulberryD2Ev
// TODO     52 B  PlantMulberry::~PlantMulberry                        _ZN13PlantMulberryD1Ev
// TODO     44 B  PlantMulberry::StaticNew                             _ZN13PlantMulberry9StaticNewEv
// TODO     36 B  PlantMulberry::Initialize                            _ZN13PlantMulberry10InitializeEv
// TODO     36 B  PlantMulberry::~PlantMulberry                        _ZN13PlantMulberryD0Ev
// TODO      8 B  PlantMulberry::CanApplyPlantfood                     _ZN13PlantMulberry17CanApplyPlantfoodEv
