// PvZ2/zombies/PirateBarrelPusher/ZombieAnimRig_PirateBarrelPusher.cpp
//
// 17 function(s), 2804 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieAnimRig_PirateBarrelPusher
//
// TODO    460 B  ZombieAnimRig_PirateBarrelPusher::getArmLayerNames   _ZN32ZombieAnimRig_PirateBarrelPusher16getArmLayerNamesEv
// TODO    444 B  ZombieAnimRig_PirateBarrelPusher::HideBarrel         _ZN32ZombieAnimRig_PirateBarrelPusher10HideBarrelEv
// TODO    320 B  ZombieAnimRig_PirateBarrelPusher::getHeadLayerNames  _ZN32ZombieAnimRig_PirateBarrelPusher17getHeadLayerNamesEv
// TODO    320 B  ZombieAnimRig_PirateBarrelPusher::getArmReplacementPairNames _ZN32ZombieAnimRig_PirateBarrelPusher26getArmReplacementPairNamesEv
// TODO    300 B  ZombieAnimRig_PirateBarrelPusher::PlayStreetIdle     _ZN32ZombieAnimRig_PirateBarrelPusher14PlayStreetIdleE20RtReflectionDelegateIN4Sexy9Delegate3IRKSsS4_iEEE
// TODO    180 B  ZombieAnimRig_PirateBarrelPusher::StaticClassInit    _ZN32ZombieAnimRig_PirateBarrelPusher15StaticClassInitEv
// TODO    128 B  ZombieAnimRig_PirateBarrelPusher::getWalkAnimationName _ZN32ZombieAnimRig_PirateBarrelPusher20getWalkAnimationNameEv
// TODO    128 B  ZombieAnimRig_PirateBarrelPusher::getEatAnimationName _ZN32ZombieAnimRig_PirateBarrelPusher19getEatAnimationNameEv
// TODO    128 B  ZombieAnimRig_PirateBarrelPusher::GetArmParticleName _ZN32ZombieAnimRig_PirateBarrelPusher18GetArmParticleNameEv
// TODO    124 B  ZombieAnimRig_PirateBarrelPusher::StaticGetClass     _ZN32ZombieAnimRig_PirateBarrelPusher14StaticGetClassEv
// TODO     64 B  ZombieAnimRig_PirateBarrelPusher::ZombieAnimRig_PirateBarrelPusher _ZN32ZombieAnimRig_PirateBarrelPusherC2Ev
// TODO     64 B  ZombieAnimRig_PirateBarrelPusher::ZombieAnimRig_PirateBarrelPusher _ZN32ZombieAnimRig_PirateBarrelPusherC1Ev
// TODO     44 B  ZombieAnimRig_PirateBarrelPusher::StaticNew          _ZN32ZombieAnimRig_PirateBarrelPusher9StaticNewEv
// TODO     36 B  ZombieAnimRig_PirateBarrelPusher::~ZombieAnimRig_PirateBarrelPusher _ZN32ZombieAnimRig_PirateBarrelPusherD0Ev
// TODO     28 B  ZombieAnimRig_PirateBarrelPusher::~ZombieAnimRig_PirateBarrelPusher _ZN32ZombieAnimRig_PirateBarrelPusherD2Ev
// TODO     28 B  ZombieAnimRig_PirateBarrelPusher::~ZombieAnimRig_PirateBarrelPusher _ZN32ZombieAnimRig_PirateBarrelPusherD1Ev
// TODO      8 B  ZombieAnimRig_PirateBarrelPusher::SetHasShield       _ZN32ZombieAnimRig_PirateBarrelPusher12SetHasShieldEb
