// PvZ2/plants/Maybee/PlantAnimRig_Maybee.cpp
//
// 12 function(s), 1224 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_Maybee
//
// TODO    200 B  PlantAnimRig_Maybee::PlayCooldownStart               _ZN19PlantAnimRig_Maybee17PlayCooldownStartE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    180 B  PlantAnimRig_Maybee::StaticClassInit                 _ZN19PlantAnimRig_Maybee15StaticClassInitEv
// TODO    172 B  PlantAnimRig_Maybee::PlayCooldownEnd                 _ZN19PlantAnimRig_Maybee15PlayCooldownEndE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    164 B  PlantAnimRig_Maybee::PlayCooldownLooped              _ZN19PlantAnimRig_Maybee18PlayCooldownLoopedEv
// TODO    136 B  PlantAnimRig_Maybee::getPlantFoodMainAnimName        _ZN19PlantAnimRig_Maybee24getPlantFoodMainAnimNameEv
// TODO    124 B  PlantAnimRig_Maybee::StaticGetClass                  _ZN19PlantAnimRig_Maybee14StaticGetClassEv
// TODO     56 B  PlantAnimRig_Maybee::PlantAnimRig_Maybee             _ZN19PlantAnimRig_MaybeeC2Ev
// TODO     56 B  PlantAnimRig_Maybee::PlantAnimRig_Maybee             _ZN19PlantAnimRig_MaybeeC1Ev
// TODO     44 B  PlantAnimRig_Maybee::StaticNew                       _ZN19PlantAnimRig_Maybee9StaticNewEv
// TODO     36 B  PlantAnimRig_Maybee::~PlantAnimRig_Maybee            _ZN19PlantAnimRig_MaybeeD0Ev
// TODO     28 B  PlantAnimRig_Maybee::~PlantAnimRig_Maybee            _ZN19PlantAnimRig_MaybeeD2Ev
// TODO     28 B  PlantAnimRig_Maybee::~PlantAnimRig_Maybee            _ZN19PlantAnimRig_MaybeeD1Ev
