// PvZ2/plants/Plantain/Plant_Plantain.cpp
//
// 27 function(s), 5360 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantPlantain
//
// TODO   1104 B  PlantPlantain::fireProjectileCallback                _ZN13PlantPlantain22fireProjectileCallbackEf
// TODO    596 B  PlantPlantain::onTouchEvent                          _ZN13PlantPlantain12onTouchEventERKN4Sexy5TouchE
// TODO    572 B  PlantPlantain::UpdateActions                         _ZN13PlantPlantain13UpdateActionsEv
// TODO    452 B  PlantPlantain::FindTargetAndFire                     _ZN13PlantPlantain17FindTargetAndFireE11PlantWeapon
// TODO    388 B  PlantPlantain::setState                              _ZN13PlantPlantain8setStateEi
// TODO    292 B  PlantPlantain::registerForEvents                     _ZN13PlantPlantain17registerForEventsEv
// TODO    208 B  PlantPlantain::SetPopAnimDelegates                   _ZN13PlantPlantain19SetPopAnimDelegatesEP12PlantAnimRig
// TODO    200 B  PlantPlantain::Idle                                  _ZN13PlantPlantain4IdleEv
// TODO    196 B  PlantPlantain::Initialize                            _ZN13PlantPlantain10InitializeEv
// TODO    180 B  PlantPlantain::StaticClassInit                       _ZN13PlantPlantain15StaticClassInitEv
// TODO    176 B  PlantPlantain::SetTargetZombie                       _ZN13PlantPlantain15SetTargetZombieEP6Zombie
// TODO    160 B  PlantPlantain::ApplyPlantfood                        _ZN13PlantPlantain14ApplyPlantfoodEv
// TODO    156 B  PlantPlantain::AutoFire                              _ZN13PlantPlantain8AutoFireEv
// TODO    124 B  PlantPlantain::StaticGetClass                        _ZN13PlantPlantain14StaticGetClassEv
// TODO     80 B  PlantPlantain::PlantPlantain                         _ZN13PlantPlantainC2Ev
// TODO     80 B  PlantPlantain::PlantPlantain                         _ZN13PlantPlantainC1Ev
// TODO     72 B  PlantPlantain::isReadyToFire                         _ZN13PlantPlantain13isReadyToFireEv
// TODO     68 B  PlantPlantain::unregisterForEvents                   _ZN13PlantPlantain19unregisterForEventsEv
// TODO     52 B  PlantPlantain::~PlantPlantain                        _ZN13PlantPlantainD2Ev
// TODO     52 B  PlantPlantain::~PlantPlantain                        _ZN13PlantPlantainD1Ev
// TODO     44 B  PlantPlantain::StaticNew                             _ZN13PlantPlantain9StaticNewEv
// TODO     40 B  PlantPlantain::CancelPlantfood                       _ZN13PlantPlantain15CancelPlantfoodEv
// TODO     36 B  PlantPlantain::~PlantPlantain                        _ZN13PlantPlantainD0Ev
// TODO      8 B  PlantPlantain::onCancelEvent                         _ZN13PlantPlantain13onCancelEventEv
// TODO      8 B  PlantPlantain::CanApplyPlantfood                     _ZN13PlantPlantain17CanApplyPlantfoodEv
// TODO      8 B  PlantPlantain::SetHitRowBelow                        _ZN13PlantPlantain14SetHitRowBelowEb
// TODO      8 B  PlantPlantain::SetTargetZombie                       _ZN13PlantPlantain15SetTargetZombieEN4Sexy9RtWeakPtrI6ZombieEE
