// PvZ2/plants/BurdockBatter/Plant_BurdockBatter.cpp
//
// 42 function(s), 9852 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantBurdockBatter
//
// TODO    816 B  PlantBurdockBatter::attackBoardEntity                _ZN18PlantBurdockBatter17attackBoardEntityEP11BoardEntity
// TODO    728 B  PlantBurdockBatter::setState                         _ZN18PlantBurdockBatter8setStateE18BurdockBatterStateb
// TODO    720 B  PlantBurdockBatter::getParabolicTargetPosition       _ZN18PlantBurdockBatter26getParabolicTargetPositionEP10Projectile
// TODO    672 B  PlantBurdockBatter::doHit                            _ZN18PlantBurdockBatter5doHitEv
// TODO    564 B  PlantBurdockBatter::getValidProjectiles              _ZN18PlantBurdockBatter19getValidProjectilesERSt6vectorIP10ProjectileSaIS2_EEN4Sexy5TRectIiEEb
// TODO    520 B  PlantBurdockBatter::enhanceAvatarToProjectile        _ZN18PlantBurdockBatter25enhanceAvatarToProjectileEP10Projectile
// TODO    456 B  PlantBurdockBatter::enhancePlantfoodToProjectile     _ZN18PlantBurdockBatter28enhancePlantfoodToProjectileEP10Projectile
// TODO    428 B  PlantBurdockBatter::getValidBoareEntities            _ZN18PlantBurdockBatter21getValidBoareEntitiesERSt6vectorIP11BoardEntitySaIS2_EEN4Sexy5TRectIiEE
// TODO    416 B  PlantBurdockBatter::addHomerTriggerEffect            _ZN18PlantBurdockBatter21addHomerTriggerEffectEv
// TODO    412 B  PlantBurdockBatter::enhanceHomerToProjectile         _ZN18PlantBurdockBatter24enhanceHomerToProjectileEP10Projectile
// TODO    380 B  PlantBurdockBatter::toHitProjectile                  _ZN18PlantBurdockBatter15toHitProjectileESt6vectorIP10ProjectileSaIS2_EE
// TODO    356 B  PlantBurdockBatter::getValidZombies                  _ZN18PlantBurdockBatter15getValidZombiesERSt6vectorIP6ZombieSaIS2_EEN4Sexy5TRectIiEE
// TODO    292 B  PlantBurdockBatter::scanBattleField                  _ZN18PlantBurdockBatter15scanBattleFieldEv
// TODO    284 B  PlantBurdockBatter::buildValidPropsList              _ZN18PlantBurdockBatter19buildValidPropsListEv
// TODO    236 B  PlantBurdockBatter::enhanceParabolicToProjectile     _ZN18PlantBurdockBatter28enhanceParabolicToProjectileEP10Projectile
// TODO    220 B  PlantBurdockBatter::onAnimStoppedCallback            _ZN18PlantBurdockBatter21onAnimStoppedCallbackERKSs
// TODO    216 B  PlantBurdockBatter::enhanceStraightToProjectile      _ZN18PlantBurdockBatter27enhanceStraightToProjectileEP10Projectile
// TODO    200 B  PlantBurdockBatter::isValidProjectile                _ZN18PlantBurdockBatter17isValidProjectileEP10Projectile
// TODO    180 B  PlantBurdockBatter::StaticClassInit                  _ZN18PlantBurdockBatter15StaticClassInitEv
// TODO    164 B  PlantBurdockBatter::getSearchRect                    _ZN18PlantBurdockBatter13getSearchRectEv
// TODO    164 B  PlantBurdockBatter::getHitRect                       _ZN18PlantBurdockBatter10getHitRectEv
// TODO    164 B  PlantBurdockBatter::toHitZombie                      _ZN18PlantBurdockBatter11toHitZombieESt6vectorIP6ZombieSaIS2_EE
// TODO    164 B  PlantBurdockBatter::toHitBoardEntities               _ZN18PlantBurdockBatter18toHitBoardEntitiesESt6vectorIP11BoardEntitySaIS2_EE
// TODO    148 B  PlantBurdockBatter::OnAnimCommand                    _ZN18PlantBurdockBatter13OnAnimCommandERKSsS1_
// TODO    124 B  PlantBurdockBatter::StaticGetClass                   _ZN18PlantBurdockBatter14StaticGetClassEv
// TODO    104 B  PlantBurdockBatter::UpdateActions                    _ZN18PlantBurdockBatter13UpdateActionsEv
// TODO     92 B  PlantBurdockBatter::Initialize                       _ZN18PlantBurdockBatter10InitializeEv
// TODO     72 B  PlantBurdockBatter::PlantBurdockBatter               _ZN18PlantBurdockBatterC2Ev
// TODO     72 B  PlantBurdockBatter::PlantBurdockBatter               _ZN18PlantBurdockBatterC1Ev
// TODO     60 B  PlantBurdockBatter::isCapturableProjectile           _ZN18PlantBurdockBatter22isCapturableProjectileEP10Projectile
// TODO     56 B  PlantBurdockBatter::captureProjectileForPlantfood    _ZN18PlantBurdockBatter29captureProjectileForPlantfoodEP10Projectile
// TODO     52 B  PlantBurdockBatter::~PlantBurdockBatter              _ZN18PlantBurdockBatterD2Ev
// TODO     52 B  PlantBurdockBatter::~PlantBurdockBatter              _ZN18PlantBurdockBatterD1Ev
// TODO     44 B  PlantBurdockBatter::ApplyPlantfood                   _ZN18PlantBurdockBatter14ApplyPlantfoodEv
// TODO     44 B  PlantBurdockBatter::StaticNew                        _ZN18PlantBurdockBatter9StaticNewEv
// TODO     44 B  PlantBurdockBatter::CancelPlantfood                  _ZN18PlantBurdockBatter15CancelPlantfoodEv
// TODO     44 B  PlantBurdockBatter::Idle                             _ZN18PlantBurdockBatter4IdleEv
// TODO     36 B  PlantBurdockBatter::~PlantBurdockBatter              _ZN18PlantBurdockBatterD0Ev
// TODO     24 B  PlantBurdockBatter::isAttacking                      _ZN18PlantBurdockBatter11isAttackingEv
// TODO     12 B  PlantBurdockBatter::isValidZombie                    _ZN18PlantBurdockBatter13isValidZombieEP6Zombie
// TODO     12 B  PlantBurdockBatter::onAttackAnimDone                 _ZN18PlantBurdockBatter16onAttackAnimDoneEv
// TODO      8 B  PlantBurdockBatter::CanApplyPlantfood                _ZN18PlantBurdockBatter17CanApplyPlantfoodEv
