// PvZ2/net/log/md5.cpp
//
// 20 function(s), 4220 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: MD5
//
// TODO   2664 B  MD5::transform                                       _ZN3MD59transformEPKh
// TODO    296 B  MD5::update                                          _ZN3MD56updateEPKhm
// TODO    232 B  MD5::update                                          _ZN3MD56updateERSt14basic_ifstreamIcSt11char_traitsIcEE
// TODO    216 B  MD5::final                                           _ZN3MD55finalEv
// TODO    144 B  MD5::bytesToHexString                                _ZN3MD516bytesToHexStringEPKhm
// TODO     72 B  MD5::encode                                          _ZN3MD56encodeEPKjPhm
// TODO     64 B  MD5::reset                                           _ZN3MD55resetEv
// TODO     64 B  MD5::decode                                          _ZN3MD56decodeEPKhPjm
// TODO     64 B  MD5::update                                          _ZN3MD56updateERKSs
// TODO     60 B  MD5::toString                                        _ZN3MD58toStringEv
// TODO     52 B  MD5::MD5                                             _ZN3MD5C1EPKvm
// TODO     52 B  MD5::MD5                                             _ZN3MD5C2EPKvm
// TODO     52 B  MD5::digest                                          _ZN3MD56digestEv
// TODO     44 B  MD5::MD5                                             _ZN3MD5C1ERKSs
// TODO     44 B  MD5::MD5                                             _ZN3MD5C2ERSt14basic_ifstreamIcSt11char_traitsIcEE
// TODO     44 B  MD5::MD5                                             _ZN3MD5C1ERSt14basic_ifstreamIcSt11char_traitsIcEE
// TODO     44 B  MD5::MD5                                             _ZN3MD5C2ERKSs
// TODO      4 B  MD5::MD5                                             _ZN3MD5C1Ev
// TODO      4 B  MD5::update                                          _ZN3MD56updateEPKvm
// TODO      4 B  MD5::MD5                                             _ZN3MD5C2Ev
