// PvZ2/net/log/TcpClient.cpp
//
// 8 function(s), 752 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: TcpClient
//
// TODO    228 B  TcpClient::ConnetServer                              _ZN9TcpClient12ConnetServerEv
// TODO    220 B  TcpClient::InitSocket                                _ZN9TcpClient10InitSocketEPKct
// TODO    180 B  TcpClient::SentMsg                                   _ZN9TcpClient7SentMsgEPKct
// TODO     60 B  TcpClient::CloseSocket                               _ZN9TcpClient11CloseSocketEv
// TODO     16 B  TcpClient::TcpClient                                 _ZN9TcpClientC1Ev
// TODO     16 B  TcpClient::~TcpClient                                _ZN9TcpClientD1Ev
// TODO     16 B  TcpClient::TcpClient                                 _ZN9TcpClientC2Ev
// TODO     16 B  TcpClient::~TcpClient                                _ZN9TcpClientD2Ev
