// PvZ2/zombies/FairyTaleGargantuar/ZombieAnimRig_FairyTaleGargantuar.cpp
//
// 9 function(s), 928 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieAnimRig_FairyTaleGargantuar
//
// TODO    376 B  ZombieAnimRig_FairyTaleGargantuar::getHeadLayerNames _ZN33ZombieAnimRig_FairyTaleGargantuar17getHeadLayerNamesEv
// TODO    180 B  ZombieAnimRig_FairyTaleGargantuar::StaticClassInit   _ZN33ZombieAnimRig_FairyTaleGargantuar15StaticClassInitEv
// TODO    124 B  ZombieAnimRig_FairyTaleGargantuar::StaticGetClass    _ZN33ZombieAnimRig_FairyTaleGargantuar14StaticGetClassEv
// TODO     56 B  ZombieAnimRig_FairyTaleGargantuar::ZombieAnimRig_FairyTaleGargantuar _ZN33ZombieAnimRig_FairyTaleGargantuarC2Ev
// TODO     56 B  ZombieAnimRig_FairyTaleGargantuar::ZombieAnimRig_FairyTaleGargantuar _ZN33ZombieAnimRig_FairyTaleGargantuarC1Ev
// TODO     44 B  ZombieAnimRig_FairyTaleGargantuar::StaticNew         _ZN33ZombieAnimRig_FairyTaleGargantuar9StaticNewEv
// TODO     36 B  ZombieAnimRig_FairyTaleGargantuar::~ZombieAnimRig_FairyTaleGargantuar _ZN33ZombieAnimRig_FairyTaleGargantuarD0Ev
// TODO     28 B  ZombieAnimRig_FairyTaleGargantuar::~ZombieAnimRig_FairyTaleGargantuar _ZN33ZombieAnimRig_FairyTaleGargantuarD2Ev
// TODO     28 B  ZombieAnimRig_FairyTaleGargantuar::~ZombieAnimRig_FairyTaleGargantuar _ZN33ZombieAnimRig_FairyTaleGargantuarD1Ev
