// PvZ2/plants/Broccoli/PlantAnimRig_Broccoli.cpp
//
// 15 function(s), 2252 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_Broccoli
//
// TODO    548 B  PlantAnimRig_Broccoli::PlayIdleLooped                _ZN21PlantAnimRig_Broccoli14PlayIdleLoopedEv
// TODO    408 B  PlantAnimRig_Broccoli::SetIsDamage                   _ZN21PlantAnimRig_Broccoli11SetIsDamageEb
// TODO    208 B  PlantAnimRig_Broccoli::PlayAdvancedAttack            _ZN21PlantAnimRig_Broccoli18PlayAdvancedAttackE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    208 B  PlantAnimRig_Broccoli::PlayPullFail                  _ZN21PlantAnimRig_Broccoli12PlayPullFailE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    200 B  PlantAnimRig_Broccoli::PlayRestLooped                _ZN21PlantAnimRig_Broccoli14PlayRestLoopedEv
// TODO    180 B  PlantAnimRig_Broccoli::StaticClassInit               _ZN21PlantAnimRig_Broccoli15StaticClassInitEv
// TODO    124 B  PlantAnimRig_Broccoli::StaticGetClass                _ZN21PlantAnimRig_Broccoli14StaticGetClassEv
// TODO     64 B  PlantAnimRig_Broccoli::~PlantAnimRig_Broccoli        _ZN21PlantAnimRig_BroccoliD2Ev
// TODO     64 B  PlantAnimRig_Broccoli::~PlantAnimRig_Broccoli        _ZN21PlantAnimRig_BroccoliD1Ev
// TODO     60 B  PlantAnimRig_Broccoli::PlantAnimRig_Broccoli         _ZN21PlantAnimRig_BroccoliC2Ev
// TODO     60 B  PlantAnimRig_Broccoli::PlantAnimRig_Broccoli         _ZN21PlantAnimRig_BroccoliC1Ev
// TODO     44 B  PlantAnimRig_Broccoli::StaticNew                     _ZN21PlantAnimRig_Broccoli9StaticNewEv
// TODO     40 B  PlantAnimRig_Broccoli::onPopAnimInitialized          _ZN21PlantAnimRig_Broccoli20onPopAnimInitializedEv
// TODO     36 B  PlantAnimRig_Broccoli::~PlantAnimRig_Broccoli        _ZN21PlantAnimRig_BroccoliD0Ev
// TODO      8 B  PlantAnimRig_Broccoli::CalcDamageStateCount          _ZN21PlantAnimRig_Broccoli20CalcDamageStateCountEv
