// PvZ2/plants/HoyaCordata/PlantAnimRig_HoyaCordata.cpp
//
// 11 function(s), 984 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_HoyaCordata
//
// TODO    180 B  PlantAnimRig_HoyaCordata::StaticClassInit            _ZN24PlantAnimRig_HoyaCordata15StaticClassInitEv
// TODO    160 B  PlantAnimRig_HoyaCordata::playSingleAnimation        _ZN24PlantAnimRig_HoyaCordata19playSingleAnimationESs20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    132 B  PlantAnimRig_HoyaCordata::PlantAnimRig_HoyaCordata   _ZN24PlantAnimRig_HoyaCordataC2Ev
// TODO    132 B  PlantAnimRig_HoyaCordata::PlantAnimRig_HoyaCordata   _ZN24PlantAnimRig_HoyaCordataC1Ev
// TODO    124 B  PlantAnimRig_HoyaCordata::StaticGetClass             _ZN24PlantAnimRig_HoyaCordata14StaticGetClassEv
// TODO     64 B  PlantAnimRig_HoyaCordata::~PlantAnimRig_HoyaCordata  _ZN24PlantAnimRig_HoyaCordataD2Ev
// TODO     64 B  PlantAnimRig_HoyaCordata::~PlantAnimRig_HoyaCordata  _ZN24PlantAnimRig_HoyaCordataD1Ev
// TODO     44 B  PlantAnimRig_HoyaCordata::StaticNew                  _ZN24PlantAnimRig_HoyaCordata9StaticNewEv
// TODO     40 B  PlantAnimRig_HoyaCordata::getIdleAnimationName       _ZN24PlantAnimRig_HoyaCordata20getIdleAnimationNameEv
// TODO     36 B  PlantAnimRig_HoyaCordata::~PlantAnimRig_HoyaCordata  _ZN24PlantAnimRig_HoyaCordataD0Ev
// TODO      8 B  PlantAnimRig_HoyaCordata::setIdleTag                 _ZN24PlantAnimRig_HoyaCordata10setIdleTagERKSs
