// PvZ2/level/LevelDefinition.cpp
//
// 8 function(s), 2760 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: LevelDefinition
//
// TODO    792 B  LevelDefinition::LevelDefinition                     _ZN15LevelDefinitionC2Ev
// TODO    792 B  LevelDefinition::LevelDefinition                     _ZN15LevelDefinitionC1Ev
// TODO    380 B  LevelDefinition::StaticClassInit                     _ZN15LevelDefinition15StaticClassInitEv
// TODO    296 B  LevelDefinition::~LevelDefinition                    _ZN15LevelDefinitionD2Ev
// TODO    296 B  LevelDefinition::~LevelDefinition                    _ZN15LevelDefinitionD1Ev
// TODO    124 B  LevelDefinition::StaticGetClass                      _ZN15LevelDefinition14StaticGetClassEv
// TODO     44 B  LevelDefinition::StaticNew                           _ZN15LevelDefinition9StaticNewEv
// TODO     36 B  LevelDefinition::~LevelDefinition                    _ZN15LevelDefinitionD0Ev
