// PvZ2/level/LevelReplaySubsystem.cpp
//
// 25 function(s), 1316 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: LevelReplaySubsystem
//
// TODO    188 B  LevelReplaySubsystem::LevelReplaySubsystem           _ZN20LevelReplaySubsystemC2Ev
// TODO    188 B  LevelReplaySubsystem::LevelReplaySubsystem           _ZN20LevelReplaySubsystemC1Ev
// TODO    180 B  LevelReplaySubsystem::StaticClassInit                _ZN20LevelReplaySubsystem15StaticClassInitEv
// TODO    180 B  LevelReplaySubsystem::Update                         _ZN20LevelReplaySubsystem6UpdateEv
// TODO    124 B  LevelReplaySubsystem::StaticGetClass                 _ZN20LevelReplaySubsystem14StaticGetClassEv
// TODO    120 B  LevelReplaySubsystem::start                          _ZN20LevelReplaySubsystem5startEv
// TODO     76 B  LevelReplaySubsystem::updateNextDelta                _ZN20LevelReplaySubsystem15updateNextDeltaEv
// TODO     44 B  LevelReplaySubsystem::StaticNew                      _ZN20LevelReplaySubsystem9StaticNewEv
// TODO     36 B  LevelReplaySubsystem::~LevelReplaySubsystem          _ZN20LevelReplaySubsystemD0Ev
// TODO     36 B  LevelReplaySubsystem::broadcastChanges               _ZN20LevelReplaySubsystem16broadcastChangesEv
// TODO     28 B  LevelReplaySubsystem::Init                           _ZN20LevelReplaySubsystem4InitEv
// TODO     20 B  LevelReplaySubsystem::~LevelReplaySubsystem          _ZN20LevelReplaySubsystemD2Ev
// TODO     20 B  LevelReplaySubsystem::~LevelReplaySubsystem          _ZN20LevelReplaySubsystemD1Ev
// TODO      8 B  LevelReplaySubsystem::GetFinalScore                  _ZN20LevelReplaySubsystem13GetFinalScoreEv
// TODO      8 B  LevelReplaySubsystem::HasPlantLoadout                _ZN20LevelReplaySubsystem15HasPlantLoadoutEv
// TODO      8 B  LevelReplaySubsystem::GetPlantLoadout                _ZN20LevelReplaySubsystem15GetPlantLoadoutEv
// TODO      8 B  LevelReplaySubsystem::hasData                        _ZN20LevelReplaySubsystem7hasDataEv
// TODO      8 B  LevelReplaySubsystem::stop                           _ZN20LevelReplaySubsystem4stopEv
// TODO      8 B  LevelReplaySubsystem::setCurrentScore                _ZN20LevelReplaySubsystem15setCurrentScoreEi
// TODO      8 B  LevelReplaySubsystem::setCurrentMultiplier           _ZN20LevelReplaySubsystem20setCurrentMultiplierEi
// TODO      4 B  LevelReplaySubsystem::Clear                          _ZN20LevelReplaySubsystem5ClearEv
// TODO      4 B  LevelReplaySubsystem::processNextEvents              _ZN20LevelReplaySubsystem17processNextEventsEb
// TODO      4 B  LevelReplaySubsystem::loadReplay                     _ZN20LevelReplaySubsystem10loadReplayEv
// TODO      4 B  LevelReplaySubsystem::calculateNextTimeDelta         _ZN20LevelReplaySubsystem22calculateNextTimeDeltaEv
// TODO      4 B  LevelReplaySubsystem::CheatSetCurrentScore           _ZN20LevelReplaySubsystem20CheatSetCurrentScoreEi
