// PvZ2/level/LevelMutatorModuleInserter.cpp
//
// 4 function(s), 1540 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: LevelMutatorModuleInserter
//
// TODO    532 B  LevelMutatorModuleInserter::Execute                  _ZN26LevelMutatorModuleInserter7ExecuteEN4Sexy9RtWeakPtrI15LevelDefinitionEERKNS0_4RtIdEiii
// TODO    360 B  LevelMutatorModuleInserter::addMainChallengeModules  _ZN26LevelMutatorModuleInserter23addMainChallengeModulesEN4Sexy9RtWeakPtrI15LevelDefinitionEERKSt6vectorINS0_4RtIdESaIS5_EE
// TODO    324 B  LevelMutatorModuleInserter::getOrCreateChallengeModule _ZN26LevelMutatorModuleInserter26getOrCreateChallengeModuleEN4Sexy9RtWeakPtrI15LevelDefinitionEE
// TODO    324 B  LevelMutatorModuleInserter::applyGridMutator         _ZN26LevelMutatorModuleInserter16applyGridMutatorEN4Sexy9RtWeakPtrI15LevelDefinitionEERK16MutatorGridEntry
