// PvZ2/LevelUtils.cpp
//
// 17 function(s), 4500 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: LevelUtils
//
// TODO   1488 B  LevelUtils::readLevelMetaData                        _ZN10LevelUtils17readLevelMetaDataERKSs
// TODO    928 B  LevelUtils::LoadLevelDefinition                      _ZN10LevelUtils19LoadLevelDefinitionERKSsb
// TODO    396 B  LevelUtils::InitializeMetaDataStore                  _ZN10LevelUtils23InitializeMetaDataStoreEv
// TODO    336 B  LevelUtils::loadLevelDefinitionFromResource          _ZN10LevelUtils31loadLevelDefinitionFromResourceEN4Sexy9RtWeakPtrINS0_14GenericResFileEEE
// TODO    296 B  LevelUtils::UnloadLevelDefinition                    _ZN10LevelUtils21UnloadLevelDefinitionEv
// TODO    212 B  LevelUtils::SimpleLoadLevelDefinition                _ZN10LevelUtils25SimpleLoadLevelDefinitionERKSsb
// TODO    180 B  LevelUtils::GetLevelInfo                             _ZN10LevelUtils12GetLevelInfoERKSs
// TODO    144 B  LevelUtils::GetLevelInfoByIndex                      _ZN10LevelUtils19GetLevelInfoByIndexEi
// TODO    112 B  LevelUtils::DoesHardLevelExist                       _ZN10LevelUtils18DoesHardLevelExistERKSs
// TODO     76 B  LevelUtils::LevelisEnableAutoHard                    _ZN10LevelUtils21LevelisEnableAutoHardEN4Sexy9RtWeakPtrI15LevelDefinitionEEb
// TODO     56 B  LevelUtils::LevelUtils                               _ZN10LevelUtilsC1Ev
// TODO     56 B  LevelUtils::LevelUtils                               _ZN10LevelUtilsC2Ev
// TODO     52 B  LevelUtils::GetHardLevelName                         _ZN10LevelUtils16GetHardLevelNameERKSs
// TODO     52 B  LevelUtils::~LevelUtils                              _ZN10LevelUtilsD2Ev
// TODO     52 B  LevelUtils::~LevelUtils                              _ZN10LevelUtilsD1Ev
// TODO     36 B  LevelUtils::~LevelUtils                              _ZN10LevelUtilsD0Ev
// TODO     28 B  LevelUtils::DoesLevelExist                           _ZN10LevelUtils14DoesLevelExistERKSs
