// PvZ2/zombies/Neuropathy/ZombieNeuropathy.cpp
//
// 27 function(s), 4704 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieNeuropathy, ZombieNeuropathyProps
//
// TODO   1308 B  ZombieNeuropathy::DoSpecial                          _ZN16ZombieNeuropathy9DoSpecialEv
// TODO    600 B  ZombieNeuropathy::onUpdate                           _ZN16ZombieNeuropathy8onUpdateEv
// TODO    552 B  ZombieNeuropathy::onBigBangAnimationDone             _ZN16ZombieNeuropathy22onBigBangAnimationDoneEP16StandaloneEffect
// TODO    288 B  ZombieNeuropathy::TryDetonatedBomb                   _ZN16ZombieNeuropathy16TryDetonatedBombEv
// TODO    196 B  ZombieNeuropathy::onPlaceOnBoard                     _ZN16ZombieNeuropathy14onPlaceOnBoardEv
// TODO    184 B  ZombieNeuropathy::onHelmDropped                      _ZN16ZombieNeuropathy13onHelmDroppedE8HelmTypei
// TODO    180 B  ZombieNeuropathy::StaticClassInit                    _ZN16ZombieNeuropathy15StaticClassInitEv
// TODO    180 B  ZombieNeuropathyProps::StaticClassInit               _ZN21ZombieNeuropathyProps15StaticClassInitEv
// TODO    148 B  ZombieNeuropathy::onDiscardBoxComplete               _ZN16ZombieNeuropathy20onDiscardBoxCompleteERKSs
// TODO    132 B  ZombieNeuropathy::playDeathAnimation                 _ZN16ZombieNeuropathy18playDeathAnimationEv
// TODO    124 B  ZombieNeuropathy::StaticGetClass                     _ZN16ZombieNeuropathy14StaticGetClassEv
// TODO    124 B  ZombieNeuropathyProps::StaticGetClass                _ZN21ZombieNeuropathyProps14StaticGetClassEv
// TODO    100 B  ZombieNeuropathy::ZombieNeuropathy                   _ZN16ZombieNeuropathyC2Ev
// TODO    100 B  ZombieNeuropathy::ZombieNeuropathy                   _ZN16ZombieNeuropathyC1Ev
// TODO     64 B  ZombieNeuropathyProps::ZombieNeuropathyProps         _ZN21ZombieNeuropathyPropsC2Ev
// TODO     64 B  ZombieNeuropathyProps::ZombieNeuropathyProps         _ZN21ZombieNeuropathyPropsC1Ev
// TODO     60 B  ZombieNeuropathy::onZombieInitialize                 _ZN16ZombieNeuropathy18onZombieInitializeEv
// TODO     44 B  ZombieNeuropathy::StaticNew                          _ZN16ZombieNeuropathy9StaticNewEv
// TODO     44 B  ZombieNeuropathyProps::StaticNew                     _ZN21ZombieNeuropathyProps9StaticNewEv
// TODO     40 B  ZombieNeuropathy::DropHead                           _ZN16ZombieNeuropathy8DropHeadEv
// TODO     36 B  ZombieNeuropathy::~ZombieNeuropathy                  _ZN16ZombieNeuropathyD0Ev
// TODO     36 B  ZombieNeuropathyProps::~ZombieNeuropathyProps        _ZN21ZombieNeuropathyPropsD0Ev
// TODO     28 B  ZombieNeuropathy::~ZombieNeuropathy                  _ZN16ZombieNeuropathyD2Ev
// TODO     28 B  ZombieNeuropathy::~ZombieNeuropathy                  _ZN16ZombieNeuropathyD1Ev
// TODO     20 B  ZombieNeuropathyProps::~ZombieNeuropathyProps        _ZN21ZombieNeuropathyPropsD2Ev
// TODO     20 B  ZombieNeuropathyProps::~ZombieNeuropathyProps        _ZN21ZombieNeuropathyPropsD1Ev
// TODO      4 B  ZombieNeuropathy::onDraw                             _ZN16ZombieNeuropathy6onDrawEPN4Sexy8GraphicsE
