// PvZ2/griditems/artifact/GridItemArtifactTimeSpeedUp.cpp
//
// 13 function(s), 1500 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: GridItemArtifactTimeSpeedUp
//
// TODO    304 B  GridItemArtifactTimeSpeedUp::OnCreatePlant           _ZN27GridItemArtifactTimeSpeedUp13OnCreatePlantEP5Plant
// TODO    236 B  GridItemArtifactTimeSpeedUp::onDestroy               _ZN27GridItemArtifactTimeSpeedUp9onDestroyEv
// TODO    180 B  GridItemArtifactTimeSpeedUp::StaticClassInit         _ZN27GridItemArtifactTimeSpeedUp15StaticClassInitEv
// TODO    148 B  GridItemArtifactTimeSpeedUp::GridItemArtifactTimeSpeedUp _ZN27GridItemArtifactTimeSpeedUpC2Ev
// TODO    148 B  GridItemArtifactTimeSpeedUp::GridItemArtifactTimeSpeedUp _ZN27GridItemArtifactTimeSpeedUpC1Ev
// TODO    124 B  GridItemArtifactTimeSpeedUp::StaticGetClass          _ZN27GridItemArtifactTimeSpeedUp14StaticGetClassEv
// TODO    100 B  GridItemArtifactTimeSpeedUp::ApplyEffectToPlant      _ZN27GridItemArtifactTimeSpeedUp18ApplyEffectToPlantEP5Plant
// TODO     76 B  GridItemArtifactTimeSpeedUp::~GridItemArtifactTimeSpeedUp _ZN27GridItemArtifactTimeSpeedUpD2Ev
// TODO     76 B  GridItemArtifactTimeSpeedUp::~GridItemArtifactTimeSpeedUp _ZN27GridItemArtifactTimeSpeedUpD1Ev
// TODO     44 B  GridItemArtifactTimeSpeedUp::StaticNew               _ZN27GridItemArtifactTimeSpeedUp9StaticNewEv
// TODO     36 B  GridItemArtifactTimeSpeedUp::~GridItemArtifactTimeSpeedUp _ZN27GridItemArtifactTimeSpeedUpD0Ev
// TODO     16 B  GridItemArtifactTimeSpeedUp::EndEffectToPlant        _ZN27GridItemArtifactTimeSpeedUp16EndEffectToPlantEP5Plant
// TODO     12 B  GridItemArtifactTimeSpeedUp::IsInEffectArea          _ZN27GridItemArtifactTimeSpeedUp14IsInEffectAreaEii
