// PvZ2/zombies/FutureBasic/ZombieAnimRig_FutureBasic.cpp
//
// 15 function(s), 2852 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieAnimRig_FutureBasic
//
// TODO    376 B  ZombieAnimRig_FutureBasic::getArmLayerNames          _ZN25ZombieAnimRig_FutureBasic16getArmLayerNamesEv
// TODO    348 B  ZombieAnimRig_FutureBasic::getHeadLayerNames         _ZN25ZombieAnimRig_FutureBasic17getHeadLayerNamesEv
// TODO    348 B  ZombieAnimRig_FutureBasic::getConeLayerNames         _ZN25ZombieAnimRig_FutureBasic17getConeLayerNamesEv
// TODO    348 B  ZombieAnimRig_FutureBasic::getBucketLayerNames       _ZN25ZombieAnimRig_FutureBasic19getBucketLayerNamesEv
// TODO    320 B  ZombieAnimRig_FutureBasic::getArmReplacementPairNames _ZN25ZombieAnimRig_FutureBasic26getArmReplacementPairNamesEv
// TODO    280 B  ZombieAnimRig_FutureBasic::getFlagHandLayerNames     _ZN25ZombieAnimRig_FutureBasic21getFlagHandLayerNamesEv
// TODO    280 B  ZombieAnimRig_FutureBasic::getNoFlagHandLayerNames   _ZN25ZombieAnimRig_FutureBasic23getNoFlagHandLayerNamesEv
// TODO    180 B  ZombieAnimRig_FutureBasic::StaticClassInit           _ZN25ZombieAnimRig_FutureBasic15StaticClassInitEv
// TODO    124 B  ZombieAnimRig_FutureBasic::StaticGetClass            _ZN25ZombieAnimRig_FutureBasic14StaticGetClassEv
// TODO     56 B  ZombieAnimRig_FutureBasic::ZombieAnimRig_FutureBasic _ZN25ZombieAnimRig_FutureBasicC2Ev
// TODO     56 B  ZombieAnimRig_FutureBasic::ZombieAnimRig_FutureBasic _ZN25ZombieAnimRig_FutureBasicC1Ev
// TODO     44 B  ZombieAnimRig_FutureBasic::StaticNew                 _ZN25ZombieAnimRig_FutureBasic9StaticNewEv
// TODO     36 B  ZombieAnimRig_FutureBasic::~ZombieAnimRig_FutureBasic _ZN25ZombieAnimRig_FutureBasicD0Ev
// TODO     28 B  ZombieAnimRig_FutureBasic::~ZombieAnimRig_FutureBasic _ZN25ZombieAnimRig_FutureBasicD2Ev
// TODO     28 B  ZombieAnimRig_FutureBasic::~ZombieAnimRig_FutureBasic _ZN25ZombieAnimRig_FutureBasicD1Ev
