// PvZ2/PowerupWizardFinger.cpp
//
// 19 function(s), 2136 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PowerupWizardFinger
//
// TODO    524 B  PowerupWizardFinger::handleTouch                     _ZN19PowerupWizardFinger11handleTouchERKN4Sexy5TouchE
// TODO    256 B  PowerupWizardFinger::shouldActivate                  _ZN19PowerupWizardFinger14shouldActivateERKN4Sexy5TouchE
// TODO    244 B  PowerupWizardFinger::activate                        _ZN19PowerupWizardFinger8activateERKN4Sexy5TouchE
// TODO    240 B  PowerupWizardFinger::registerForEvents               _ZN19PowerupWizardFinger17registerForEventsEv
// TODO    180 B  PowerupWizardFinger::StaticClassInit                 _ZN19PowerupWizardFinger15StaticClassInitEv
// TODO    124 B  PowerupWizardFinger::StaticGetClass                  _ZN19PowerupWizardFinger14StaticGetClassEv
// TODO     76 B  PowerupWizardFinger::cancelTouch                     _ZN19PowerupWizardFinger11cancelTouchEv
// TODO     64 B  PowerupWizardFinger::PowerupWizardFinger             _ZN19PowerupWizardFingerC2Ev
// TODO     64 B  PowerupWizardFinger::PowerupWizardFinger             _ZN19PowerupWizardFingerC1Ev
// TODO     60 B  PowerupWizardFinger::onEnterState_Idle               _ZN19PowerupWizardFinger17onEnterState_IdleE12PowerupState
// TODO     52 B  PowerupWizardFinger::~PowerupWizardFinger            _ZN19PowerupWizardFingerD2Ev
// TODO     52 B  PowerupWizardFinger::~PowerupWizardFinger            _ZN19PowerupWizardFingerD1Ev
// TODO     44 B  PowerupWizardFinger::StaticNew                       _ZN19PowerupWizardFinger9StaticNewEv
// TODO     44 B  PowerupWizardFinger::updateState_Activated           _ZN19PowerupWizardFinger21updateState_ActivatedEv
// TODO     36 B  PowerupWizardFinger::~PowerupWizardFinger            _ZN19PowerupWizardFingerD0Ev
// TODO     36 B  PowerupWizardFinger::onExitState_Activated           _ZN19PowerupWizardFinger21onExitState_ActivatedE12PowerupState
// TODO     20 B  PowerupWizardFinger::unregisterForEvents             _ZN19PowerupWizardFinger19unregisterForEventsEv
// TODO     16 B  PowerupWizardFinger::isTouching                      _ZN19PowerupWizardFinger10isTouchingEv
// TODO      4 B  PowerupWizardFinger::onEnterState_Selected           _ZN19PowerupWizardFinger21onEnterState_SelectedE12PowerupState
