// PvZ2/zombies/Chief/ZombieAnimRig_Chief.cpp
//
// 12 function(s), 1872 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieAnimRig_Chief
//
// TODO    388 B  ZombieAnimRig_Chief::getHeadLayerNames               _ZN19ZombieAnimRig_Chief17getHeadLayerNamesEv
// TODO    388 B  ZombieAnimRig_Chief::getArmLayerNames                _ZN19ZombieAnimRig_Chief16getArmLayerNamesEv
// TODO    320 B  ZombieAnimRig_Chief::getArmReplacementPairNames      _ZN19ZombieAnimRig_Chief26getArmReplacementPairNamesEv
// TODO    224 B  ZombieAnimRig_Chief::PlaySpawnWind                   _ZN19ZombieAnimRig_Chief13PlaySpawnWindE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    180 B  ZombieAnimRig_Chief::StaticClassInit                 _ZN19ZombieAnimRig_Chief15StaticClassInitEv
// TODO    124 B  ZombieAnimRig_Chief::StaticGetClass                  _ZN19ZombieAnimRig_Chief14StaticGetClassEv
// TODO     56 B  ZombieAnimRig_Chief::ZombieAnimRig_Chief             _ZN19ZombieAnimRig_ChiefC2Ev
// TODO     56 B  ZombieAnimRig_Chief::ZombieAnimRig_Chief             _ZN19ZombieAnimRig_ChiefC1Ev
// TODO     44 B  ZombieAnimRig_Chief::StaticNew                       _ZN19ZombieAnimRig_Chief9StaticNewEv
// TODO     36 B  ZombieAnimRig_Chief::~ZombieAnimRig_Chief            _ZN19ZombieAnimRig_ChiefD0Ev
// TODO     28 B  ZombieAnimRig_Chief::~ZombieAnimRig_Chief            _ZN19ZombieAnimRig_ChiefD2Ev
// TODO     28 B  ZombieAnimRig_Chief::~ZombieAnimRig_Chief            _ZN19ZombieAnimRig_ChiefD1Ev
