// PvZ2/zombies/_Chicken_Subsystem/Zombie_Chicken_Subsystem.cpp
//
// 13 function(s), 2380 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieChickenSubsystem
//
// TODO    608 B  ZombieChickenSubsystem::Update                       _ZN22ZombieChickenSubsystem6UpdateEv
// TODO    424 B  ZombieChickenSubsystem::StartChickening              _ZN22ZombieChickenSubsystem15StartChickeningERKSsfi9TeamFlagsffff16ZombieConditionsibbP6Zombie
// TODO    404 B  ZombieChickenSubsystem::spawnChicken                 _ZN22ZombieChickenSubsystem12spawnChickenERKSsfi9TeamFlags16ZombieConditionsi
// TODO    280 B  ZombieChickenSubsystem::StaticClassInit              _ZN22ZombieChickenSubsystem15StaticClassInitEv
// TODO    220 B  ZombieChickenSubsystem::Remove                       _ZN22ZombieChickenSubsystem6RemoveEP6Zombie
// TODO    124 B  ZombieChickenSubsystem::StaticGetClass               _ZN22ZombieChickenSubsystem14StaticGetClassEv
// TODO     64 B  ZombieChickenSubsystem::ZombieChickenSubsystem       _ZN22ZombieChickenSubsystemC2Ev
// TODO     64 B  ZombieChickenSubsystem::ZombieChickenSubsystem       _ZN22ZombieChickenSubsystemC1Ev
// TODO     52 B  ZombieChickenSubsystem::~ZombieChickenSubsystem      _ZN22ZombieChickenSubsystemD2Ev
// TODO     52 B  ZombieChickenSubsystem::~ZombieChickenSubsystem      _ZN22ZombieChickenSubsystemD1Ev
// TODO     44 B  ZombieChickenSubsystem::StaticNew                    _ZN22ZombieChickenSubsystem9StaticNewEv
// TODO     36 B  ZombieChickenSubsystem::~ZombieChickenSubsystem      _ZN22ZombieChickenSubsystemD0Ev
// TODO      8 B  ZombieChickenSubsystem::StopAllChickening            _ZN22ZombieChickenSubsystem17StopAllChickeningEv
