// PvZ2/plants/ElectricPeel/Plant_ElectricPeel.cpp
//
// 35 function(s), 6744 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantElectricPeel, PlantTypeElectricPeel
//
// TODO    760 B  PlantElectricPeel::firePeel                          _ZN17PlantElectricPeel8firePeelERKN4Sexy11SexyVector2ERKNS0_11SexyVector3E
// TODO    752 B  PlantElectricPeel::FindTargetZombieInRow             _ZN17PlantElectricPeel21FindTargetZombieInRowEi11PlantWeaponPiR17PlantTargetParamsN4Sexy5TRectIiEE
// TODO    672 B  PlantElectricPeel::onAnimStoppedCallback             _ZN17PlantElectricPeel21onAnimStoppedCallbackERKSs
// TODO    572 B  PlantElectricPeel::fireGiantEel                      _ZN17PlantElectricPeel12fireGiantEelEv
// TODO    388 B  PlantElectricPeel::PlayAttackAnimation               _ZN17PlantElectricPeel19PlayAttackAnimationEv
// TODO    384 B  PlantElectricPeel::Fire                              _ZN17PlantElectricPeel4FireEN4Sexy9RtWeakPtrI6ZombieEEi11PlantWeapon
// TODO    364 B  PlantElectricPeel::ApplyPlantfood                    _ZN17PlantElectricPeel14ApplyPlantfoodEv
// TODO    336 B  PlantElectricPeel::OnProjectileReturned              _ZN17PlantElectricPeel20OnProjectileReturnedEP14PeelProjectileb
// TODO    244 B  PlantElectricPeel::CancelPlantfood                   _ZN17PlantElectricPeel15CancelPlantfoodEv
// TODO    236 B  PlantElectricPeel::FindTargetDamageableGridItem      _ZN17PlantElectricPeel28FindTargetDamageableGridItemERN4Sexy5TRectIiEE11PlantWeapon
// TODO    232 B  PlantElectricPeel::DoProjectileCombo                 _ZN17PlantElectricPeel17DoProjectileComboEv
// TODO    204 B  PlantElectricPeel::FindTargetAndFire                 _ZN17PlantElectricPeel17FindTargetAndFireE11PlantWeapon
// TODO    180 B  PlantElectricPeel::StaticClassInit                   _ZN17PlantElectricPeel15StaticClassInitEv
// TODO    172 B  PlantElectricPeel::UpdateActions                     _ZN17PlantElectricPeel13UpdateActionsEv
// TODO    144 B  PlantElectricPeel::Initialize                        _ZN17PlantElectricPeel10InitializeEv
// TODO    140 B  PlantElectricPeel::getLaunchDelay                    _ZN17PlantElectricPeel14getLaunchDelayEb
// TODO    124 B  PlantElectricPeel::StaticGetClass                    _ZN17PlantElectricPeel14StaticGetClassEv
// TODO    120 B  PlantElectricPeel::GetPlantAttackRect                _ZN17PlantElectricPeel18GetPlantAttackRectE11PlantWeapon
// TODO    120 B  PlantTypeElectricPeel::StaticGetClass                _ZN21PlantTypeElectricPeel14StaticGetClassEv
// TODO     56 B  PlantElectricPeel::PlantElectricPeel                 _ZN17PlantElectricPeelC2Ev
// TODO     56 B  PlantElectricPeel::PlantElectricPeel                 _ZN17PlantElectricPeelC1Ev
// TODO     52 B  PlantElectricPeel::~PlantElectricPeel                _ZN17PlantElectricPeelD2Ev
// TODO     52 B  PlantElectricPeel::~PlantElectricPeel                _ZN17PlantElectricPeelD1Ev
// TODO     48 B  PlantTypeElectricPeel::PlantTypeElectricPeel         _ZN21PlantTypeElectricPeelC2Ev
// TODO     48 B  PlantTypeElectricPeel::PlantTypeElectricPeel         _ZN21PlantTypeElectricPeelC1Ev
// TODO     44 B  PlantElectricPeel::StaticNew                         _ZN17PlantElectricPeel9StaticNewEv
// TODO     44 B  PlantElectricPeel::shouldGetWaterBuff                _ZN17PlantElectricPeel18shouldGetWaterBuffEv
// TODO     44 B  PlantTypeElectricPeel::StaticNew                     _ZN21PlantTypeElectricPeel9StaticNewEv
// TODO     36 B  PlantElectricPeel::~PlantElectricPeel                _ZN17PlantElectricPeelD0Ev
// TODO     36 B  PlantTypeElectricPeel::~PlantTypeElectricPeel        _ZN21PlantTypeElectricPeelD0Ev
// TODO     20 B  PlantElectricPeel::CanApplyPlantfood                 _ZN17PlantElectricPeel17CanApplyPlantfoodEv
// TODO     20 B  PlantTypeElectricPeel::~PlantTypeElectricPeel        _ZN21PlantTypeElectricPeelD2Ev
// TODO     20 B  PlantTypeElectricPeel::~PlantTypeElectricPeel        _ZN21PlantTypeElectricPeelD1Ev
// TODO     12 B  PlantElectricPeel::PostInitializeFromPropertySheet   _ZN17PlantElectricPeel31PostInitializeFromPropertySheetEv
// TODO     12 B  PlantElectricPeel::CanEndPlantfood                   _ZN17PlantElectricPeel15CanEndPlantfoodEv
