// PvZ2/plants/SnowPea/Plant_SnowPea.cpp
//
// 17 function(s), 3564 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantSnowPea
//
// TODO   1216 B  PlantSnowPea::ApplyPlantfood                         _ZN12PlantSnowPea14ApplyPlantfoodEv
// TODO    724 B  PlantSnowPea::Fire                                   _ZN12PlantSnowPea4FireEN4Sexy9RtWeakPtrI6ZombieEEi11PlantWeapon
// TODO    272 B  PlantSnowPea::CancelPlantfood                        _ZN12PlantSnowPea15CancelPlantfoodEv
// TODO    212 B  PlantSnowPea::UpdatePlantfood                        _ZN12PlantSnowPea15UpdatePlantfoodEv
// TODO    204 B  PlantSnowPea::onPlantfoodEnded                       _ZN12PlantSnowPea16onPlantfoodEndedEv
// TODO    184 B  PlantSnowPea::onPlantfoodStarted                     _ZN12PlantSnowPea18onPlantfoodStartedEv
// TODO    180 B  PlantSnowPea::StaticClassInit                        _ZN12PlantSnowPea15StaticClassInitEv
// TODO    124 B  PlantSnowPea::StaticGetClass                         _ZN12PlantSnowPea14StaticGetClassEv
// TODO     96 B  PlantSnowPea::~PlantSnowPea                          _ZN12PlantSnowPeaD2Ev
// TODO     96 B  PlantSnowPea::~PlantSnowPea                          _ZN12PlantSnowPeaD1Ev
// TODO     64 B  PlantSnowPea::PlantSnowPea                           _ZN12PlantSnowPeaC2Ev
// TODO     64 B  PlantSnowPea::PlantSnowPea                           _ZN12PlantSnowPeaC1Ev
// TODO     44 B  PlantSnowPea::StaticNew                              _ZN12PlantSnowPea9StaticNewEv
// TODO     36 B  PlantSnowPea::~PlantSnowPea                          _ZN12PlantSnowPeaD0Ev
// TODO     36 B  PlantSnowPea::Idle                                   _ZN12PlantSnowPea4IdleEv
// TODO      8 B  PlantSnowPea::CanApplyPlantfood                      _ZN12PlantSnowPea17CanApplyPlantfoodEv
// TODO      4 B  PlantSnowPea::Initialize                             _ZN12PlantSnowPea10InitializeEv
