// PvZ2/BoardTransforms.cpp
//
// 38 function(s), 2744 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: BoardTransforms
//
// TODO    124 B  BoardTransforms::PlantingBoardSpaceToGridY           _ZN15BoardTransforms25PlantingBoardSpaceToGridYEfN4Sexy9RtWeakPtrIK9PlantTypeEE
// TODO    124 B  BoardTransforms::BoardSpaceToGrid                    _ZN15BoardTransforms16BoardSpaceToGridEff
// TODO    124 B  BoardTransforms::BoardSpaceToGrid                    _ZN15BoardTransforms16BoardSpaceToGridEii
// TODO    124 B  BoardTransforms::GridToBoardSpaceRect                _ZN15BoardTransforms20GridToBoardSpaceRectEiiii
// TODO    120 B  BoardTransforms::BoardSpaceToGridXKeepOnBoard        _ZN15BoardTransforms28BoardSpaceToGridXKeepOnBoardEf
// TODO    120 B  BoardTransforms::BoardSpaceToGridYKeepOnBoard        _ZN15BoardTransforms28BoardSpaceToGridYKeepOnBoardEf
// TODO    120 B  BoardTransforms::BoardSpaceToGridXKeepOnBoard        _ZN15BoardTransforms28BoardSpaceToGridXKeepOnBoardEi
// TODO    120 B  BoardTransforms::BoardSpaceToGridYKeepOnBoard        _ZN15BoardTransforms28BoardSpaceToGridYKeepOnBoardEi
// TODO    108 B  BoardTransforms::GridToBoardSpacePos                 _ZN15BoardTransforms19GridToBoardSpacePosEii
// TODO    104 B  BoardTransforms::PlantingBoardSpaceToGridY           _ZN15BoardTransforms25PlantingBoardSpaceToGridYEiN4Sexy9RtWeakPtrIK9PlantTypeEE
// TODO    100 B  BoardTransforms::BoardSpaceToGrid                    _ZN15BoardTransforms16BoardSpaceToGridEffRiS0_
// TODO    100 B  BoardTransforms::BoardSpaceToGrid                    _ZN15BoardTransforms16BoardSpaceToGridEiiRiS0_
// TODO     96 B  BoardTransforms::ClampGridCoords                     _ZN15BoardTransforms15ClampGridCoordsERiS0_
// TODO     92 B  BoardTransforms::OffsetYForPlanting                  _ZN15BoardTransforms18OffsetYForPlantingERiN4Sexy9RtWeakPtrIK9PlantTypeEE
// TODO     80 B  BoardTransforms::IsGridCoordinateOnBoard             _ZN15BoardTransforms23IsGridCoordinateOnBoardEii
// TODO     76 B  BoardTransforms::GridToBoardSpaceUnbounded           _ZN15BoardTransforms25GridToBoardSpaceUnboundedERKN4Sexy5PointE
// TODO     76 B  BoardTransforms::BoardSpaceToGridUnbounded           _ZN15BoardTransforms25BoardSpaceToGridUnboundedERKN4Sexy11SexyVector3E
// TODO     68 B  BoardTransforms::BoardSpaceToGridX                   _ZN15BoardTransforms17BoardSpaceToGridXEf
// TODO     68 B  BoardTransforms::BoardSpaceToGridY                   _ZN15BoardTransforms17BoardSpaceToGridYEf
// TODO     68 B  BoardTransforms::BoardSpaceToGridX                   _ZN15BoardTransforms17BoardSpaceToGridXEi
// TODO     68 B  BoardTransforms::BoardSpaceToGridY                   _ZN15BoardTransforms17BoardSpaceToGridYEi
// TODO     60 B  BoardTransforms::GridToBoardSpaceRect                _ZN15BoardTransforms20GridToBoardSpaceRectERKN4Sexy5PointES3_
// TODO     56 B  BoardTransforms::GridToBoardSpaceYUnbounded          _ZN15BoardTransforms26GridToBoardSpaceYUnboundedEi
// TODO     56 B  BoardTransforms::GridToBoardSpaceRect                _ZN15BoardTransforms20GridToBoardSpaceRectERKN4Sexy5PointE
// TODO     56 B  BoardTransforms::GridRectToBoardSpaceRect            _ZN15BoardTransforms24GridRectToBoardSpaceRectERKN4Sexy5TRectIiEE
// TODO     56 B  BoardTransforms::GridToBoardSpaceXUnbounded_Float    _ZN15BoardTransforms32GridToBoardSpaceXUnbounded_FloatEf
// TODO     52 B  BoardTransforms::BoardSpaceToGridYUnbounded          _ZN15BoardTransforms26BoardSpaceToGridYUnboundedEf
// TODO     52 B  BoardTransforms::BoardSpaceToGridXUnbounded          _ZN15BoardTransforms26BoardSpaceToGridXUnboundedEf
// TODO     48 B  BoardTransforms::GridToBoardSpaceXUnbounded          _ZN15BoardTransforms26GridToBoardSpaceXUnboundedEi
// TODO     48 B  BoardTransforms::BoardSpaceToGridXUnboundedFloat     _ZN15BoardTransforms31BoardSpaceToGridXUnboundedFloatEf
// TODO     48 B  BoardTransforms::BoardSpaceToGridYUnboundedFloat     _ZN15BoardTransforms31BoardSpaceToGridYUnboundedFloatEf
// TODO     40 B  BoardTransforms::BoardSpaceToGridXUnbounded          _ZN15BoardTransforms26BoardSpaceToGridXUnboundedEi
// TODO     40 B  BoardTransforms::BoardSpaceToGridYUnbounded          _ZN15BoardTransforms26BoardSpaceToGridYUnboundedEi
// TODO     36 B  BoardTransforms::GridToBoardSpace                    _ZN15BoardTransforms16GridToBoardSpaceERKN4Sexy5PointE
// TODO      4 B  BoardTransforms::GridToBoardSpaceX                   _ZN15BoardTransforms17GridToBoardSpaceXEi
// TODO      4 B  BoardTransforms::GridToBoardSpaceY                   _ZN15BoardTransforms17GridToBoardSpaceYEi
// TODO      4 B  BoardTransforms::PlantingBoardSpaceToGridX           _ZN15BoardTransforms25PlantingBoardSpaceToGridXEfN4Sexy9RtWeakPtrIK9PlantTypeEE
// TODO      4 B  BoardTransforms::PlantingBoardSpaceToGridX           _ZN15BoardTransforms25PlantingBoardSpaceToGridXEiN4Sexy9RtWeakPtrIK9PlantTypeEE
