// PvZ2/Social/Widgets/LotteryUI.cpp
//
// 24 function(s), 13776 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: LotteryUI
//
// TODO   1452 B  LotteryUI::DrawBottomPrize                           _ZN9LotteryUI15DrawBottomPrizeEPN4Sexy8GraphicsE
// TODO   1420 B  LotteryUI::InitView                                  _ZN9LotteryUI8InitViewEv
// TODO   1120 B  LotteryUI::processLotteryResult                      _ZN9LotteryUI20processLotteryResultEi
// TODO    940 B  LotteryUI::DrawDecoration                            _ZN9LotteryUI14DrawDecorationEPN4Sexy8GraphicsE
// TODO    864 B  LotteryUI::Update                                    _ZN9LotteryUI6UpdateEv
// TODO    812 B  LotteryUI::ButtonDepress                             _ZN9LotteryUI13ButtonDepressEi
// TODO    812 B  LotteryUI::Draw                                      _ZN9LotteryUI4DrawEPN4Sexy8GraphicsE
// TODO    784 B  LotteryUI::LotteryUI                                 _ZN9LotteryUIC1Eb
// TODO    784 B  LotteryUI::LotteryUI                                 _ZN9LotteryUIC2Eb
// TODO    672 B  LotteryUI::EnableToLottery                           _ZN9LotteryUI15EnableToLotteryEv
// TODO    588 B  LotteryUI::doTimesHintDialog                         _ZN9LotteryUI17doTimesHintDialogEv
// TODO    580 B  LotteryUI::DrawCard                                  _ZN9LotteryUI8DrawCardEPN4Sexy8GraphicsE
// TODO    504 B  LotteryUI::getLotteryResult                          _ZN9LotteryUI16getLotteryResultEv
// TODO    504 B  LotteryUI::doHintDialog                              _ZN9LotteryUI12doHintDialogEv
// TODO    308 B  LotteryUI::moveSelector                              _ZN9LotteryUI12moveSelectorEv
// TODO    296 B  LotteryUI::~LotteryUI                                _ZN9LotteryUID2Ev
// TODO    296 B  LotteryUI::~LotteryUI                                _ZN9LotteryUID1Ev
// TODO    276 B  LotteryUI::getLotteryCardPosX                        _ZN9LotteryUI18getLotteryCardPosXEi
// TODO    276 B  LotteryUI::getLotteryCardPosY                        _ZN9LotteryUI18getLotteryCardPosYEi
// TODO    160 B  LotteryUI::GetCols                                   _ZN9LotteryUI7GetColsEv
// TODO    160 B  LotteryUI::GetRows                                   _ZN9LotteryUI7GetRowsEv
// TODO    128 B  LotteryUI::DrawAll                                   _ZN9LotteryUI7DrawAllEPN4Sexy10ModalFlagsEPNS0_8GraphicsE
// TODO     36 B  LotteryUI::~LotteryUI                                _ZN9LotteryUID0Ev
// TODO      4 B  LotteryUI::onLotteryDisabled                         _ZN9LotteryUI17onLotteryDisabledEv
