// PvZ2/plants/Vanilla/PlantAnimRig_Vanilla.cpp
//
// 19 function(s), 2272 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_Vanilla
//
// TODO    404 B  PlantAnimRig_Vanilla::playPlantFoodOn                _ZN20PlantAnimRig_Vanilla15playPlantFoodOnEv
// TODO    232 B  PlantAnimRig_Vanilla::onAnimStopped                  _ZN20PlantAnimRig_Vanilla13onAnimStoppedEv
// TODO    224 B  PlantAnimRig_Vanilla::getCyclingAnimName             _ZN20PlantAnimRig_Vanilla18getCyclingAnimNameEv
// TODO    180 B  PlantAnimRig_Vanilla::StaticClassInit                _ZN20PlantAnimRig_Vanilla15StaticClassInitEv
// TODO    148 B  PlantAnimRig_Vanilla::getPlantFoodMainAnimName       _ZN20PlantAnimRig_Vanilla24getPlantFoodMainAnimNameEv
// TODO    144 B  PlantAnimRig_Vanilla::PlayPreviewAnim                _ZN20PlantAnimRig_Vanilla15PlayPreviewAnimEb
// TODO    136 B  PlantAnimRig_Vanilla::onPopAnimInitialized           _ZN20PlantAnimRig_Vanilla20onPopAnimInitializedEv
// TODO    124 B  PlantAnimRig_Vanilla::StaticGetClass                 _ZN20PlantAnimRig_Vanilla14StaticGetClassEv
// TODO    104 B  PlantAnimRig_Vanilla::getPlantFoodOffAnimName        _ZN20PlantAnimRig_Vanilla23getPlantFoodOffAnimNameEv
// TODO    104 B  PlantAnimRig_Vanilla::getPlantFoodOnAnimName         _ZN20PlantAnimRig_Vanilla22getPlantFoodOnAnimNameEv
// TODO    104 B  PlantAnimRig_Vanilla::getPreviewAnimName             _ZN20PlantAnimRig_Vanilla18getPreviewAnimNameEv
// TODO     72 B  PlantAnimRig_Vanilla::PlantAnimRig_Vanilla           _ZN20PlantAnimRig_VanillaC2Ev
// TODO     72 B  PlantAnimRig_Vanilla::PlantAnimRig_Vanilla           _ZN20PlantAnimRig_VanillaC1Ev
// TODO     64 B  PlantAnimRig_Vanilla::~PlantAnimRig_Vanilla          _ZN20PlantAnimRig_VanillaD2Ev
// TODO     64 B  PlantAnimRig_Vanilla::~PlantAnimRig_Vanilla          _ZN20PlantAnimRig_VanillaD1Ev
// TODO     44 B  PlantAnimRig_Vanilla::StaticNew                      _ZN20PlantAnimRig_Vanilla9StaticNewEv
// TODO     36 B  PlantAnimRig_Vanilla::~PlantAnimRig_Vanilla          _ZN20PlantAnimRig_VanillaD0Ev
// TODO      8 B  PlantAnimRig_Vanilla::SetPlant                       _ZN20PlantAnimRig_Vanilla8SetPlantEN4Sexy9RtWeakPtrI5PlantEE
// TODO      8 B  PlantAnimRig_Vanilla::setPlantFoodPlayCount          _ZN20PlantAnimRig_Vanilla21setPlantFoodPlayCountEi
