// PvZ2/DNode/DNodeWidget.cpp
//
// 39 function(s), 2992 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: DNodeWidget
//
// TODO    272 B  DNodeWidget::setRect                                 _ZN11DNodeWidget7setRectEiiii
// TODO    228 B  DNodeWidget::DNodeWidget                             _ZN11DNodeWidgetC2Ev
// TODO    228 B  DNodeWidget::DNodeWidget                             _ZN11DNodeWidgetC1Ev
// TODO    184 B  DNodeWidget::setRect2                                _ZN11DNodeWidget8setRect2Eiiii
// TODO    180 B  DNodeWidget::StaticClassInit                         _ZN11DNodeWidget15StaticClassInitEv
// TODO    168 B  DNodeWidget::OnGestureLongPress                      _ZN11DNodeWidget18OnGestureLongPressEN4Sexy5PointE
// TODO    160 B  DNodeWidget::addToWidgetManager                      _ZN11DNodeWidget18addToWidgetManagerEbb
// TODO    124 B  DNodeWidget::StaticGetClass                          _ZN11DNodeWidget14StaticGetClassEv
// TODO    108 B  DNodeWidget::TouchesCanceled                         _ZN11DNodeWidget15TouchesCanceledEv
// TODO    108 B  DNodeWidget::removeFromWidgetManager                 _ZN11DNodeWidget23removeFromWidgetManagerEv
// TODO     96 B  DNodeWidget::getWinSize                              _ZN11DNodeWidget10getWinSizeEv
// TODO     92 B  DNodeWidget::reload                                  _ZN11DNodeWidget6reloadERKSs
// TODO     76 B  DNodeWidget::reload                                  _ZN11DNodeWidget6reloadEv
// TODO     60 B  DNodeWidget::~DNodeWidget                            _ZN11DNodeWidgetD2Ev
// TODO     60 B  DNodeWidget::addChild                                _ZN11DNodeWidget8addChildEP14DTransformNodeii
// TODO     60 B  DNodeWidget::removeChild                             _ZN11DNodeWidget11removeChildEP14DTransformNodeb
// TODO     60 B  DNodeWidget::removeChildByTag                        _ZN11DNodeWidget16removeChildByTagEib
// TODO     60 B  DNodeWidget::removeChildByName                       _ZN11DNodeWidget17removeChildByNameERKSsb
// TODO     60 B  DNodeWidget::~DNodeWidget                            _ZN11DNodeWidgetD1Ev
// TODO     52 B  DNodeWidget::addChild                                _ZN11DNodeWidget8addChildEP14DTransformNodei
// TODO     52 B  DNodeWidget::removeAllChildren                       _ZN11DNodeWidget17removeAllChildrenEb
// TODO     48 B  DNodeWidget::load                                    _ZN11DNodeWidget4loadERKSsb
// TODO     44 B  DNodeWidget::addChild                                _ZN11DNodeWidget8addChildEP14DTransformNode
// TODO     44 B  DNodeWidget::getChildByTag                           _ZN11DNodeWidget13getChildByTagEi
// TODO     44 B  DNodeWidget::getChildByName                          _ZN11DNodeWidget14getChildByNameERKSs
// TODO     44 B  DNodeWidget::StaticNew                               _ZN11DNodeWidget9StaticNewEv
// TODO     36 B  DNodeWidget::~DNodeWidget                            _ZN11DNodeWidgetD0Ev
// TODO     32 B  DNodeWidget::Draw                                    _ZN11DNodeWidget4DrawEPN4Sexy8GraphicsE
// TODO     32 B  DNodeWidget::addToWidgetManager                      _ZN11DNodeWidget18addToWidgetManagerEb
// TODO     32 B  DNodeWidget::loadGroup                               _ZN11DNodeWidget9loadGroupERKSs
// TODO     32 B  DNodeWidget::setRootName                             _ZN11DNodeWidget11setRootNameERKSs
// TODO     24 B  DNodeWidget::TouchBegan                              _ZN11DNodeWidget10TouchBeganERKN4Sexy5TouchE
// TODO     24 B  DNodeWidget::TouchMoved                              _ZN11DNodeWidget10TouchMovedERKN4Sexy5TouchE
// TODO     24 B  DNodeWidget::TouchEnded                              _ZN11DNodeWidget10TouchEndedERKN4Sexy5TouchE
// TODO     24 B  DNodeWidget::getLoader                               _ZN11DNodeWidget9getLoaderEv
// TODO      8 B  DNodeWidget::setTouchEnable                          _ZN11DNodeWidget14setTouchEnableEb
// TODO      4 B  DNodeWidget::UserInit                                _ZN11DNodeWidget8UserInitEv
// TODO      4 B  DNodeWidget::Initialize                              _ZN11DNodeWidget10InitializeEv
// TODO      4 B  DNodeWidget::debugBtn                                _ZN11DNodeWidget8debugBtnEv
