// PvZ2/zombies/Hunter/ZombieAnimRig_Hunter.cpp
//
// 11 function(s), 1460 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieAnimRig_Hunter
//
// TODO    348 B  ZombieAnimRig_Hunter::getHeadLayerNames              _ZN20ZombieAnimRig_Hunter17getHeadLayerNamesEv
// TODO    320 B  ZombieAnimRig_Hunter::getArmLayerNames               _ZN20ZombieAnimRig_Hunter16getArmLayerNamesEv
// TODO    320 B  ZombieAnimRig_Hunter::getArmReplacementPairNames     _ZN20ZombieAnimRig_Hunter26getArmReplacementPairNamesEv
// TODO    120 B  ZombieAnimRig_Hunter::StaticGetClass                 _ZN20ZombieAnimRig_Hunter14StaticGetClassEv
// TODO    104 B  ZombieAnimRig_Hunter::getRangedAttackAnimationName   _ZN20ZombieAnimRig_Hunter28getRangedAttackAnimationNameEv
// TODO     56 B  ZombieAnimRig_Hunter::ZombieAnimRig_Hunter           _ZN20ZombieAnimRig_HunterC2Ev
// TODO     56 B  ZombieAnimRig_Hunter::ZombieAnimRig_Hunter           _ZN20ZombieAnimRig_HunterC1Ev
// TODO     44 B  ZombieAnimRig_Hunter::StaticNew                      _ZN20ZombieAnimRig_Hunter9StaticNewEv
// TODO     36 B  ZombieAnimRig_Hunter::~ZombieAnimRig_Hunter          _ZN20ZombieAnimRig_HunterD0Ev
// TODO     28 B  ZombieAnimRig_Hunter::~ZombieAnimRig_Hunter          _ZN20ZombieAnimRig_HunterD2Ev
// TODO     28 B  ZombieAnimRig_Hunter::~ZombieAnimRig_Hunter          _ZN20ZombieAnimRig_HunterD1Ev
