// PvZ2/effects/dino/Effect_DinoShadow.cpp
//
// 10 function(s), 1632 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: Effect_DinoShadow
//
// TODO    636 B  Effect_DinoShadow::onEffectObjectInitialize          _ZN17Effect_DinoShadow24onEffectObjectInitializeEN4Sexy9RtWeakPtrIK16EffectObjectTypeEEii
// TODO    396 B  Effect_DinoShadow::onUpdate                          _ZN17Effect_DinoShadow8onUpdateEv
// TODO    180 B  Effect_DinoShadow::StaticClassInit                   _ZN17Effect_DinoShadow15StaticClassInitEv
// TODO    124 B  Effect_DinoShadow::StaticGetClass                    _ZN17Effect_DinoShadow14StaticGetClassEv
// TODO     56 B  Effect_DinoShadow::~Effect_DinoShadow                _ZN17Effect_DinoShadowD2Ev
// TODO     56 B  Effect_DinoShadow::~Effect_DinoShadow                _ZN17Effect_DinoShadowD1Ev
// TODO     52 B  Effect_DinoShadow::Effect_DinoShadow                 _ZN17Effect_DinoShadowC2Ev
// TODO     52 B  Effect_DinoShadow::Effect_DinoShadow                 _ZN17Effect_DinoShadowC1Ev
// TODO     44 B  Effect_DinoShadow::StaticNew                         _ZN17Effect_DinoShadow9StaticNewEv
// TODO     36 B  Effect_DinoShadow::~Effect_DinoShadow                _ZN17Effect_DinoShadowD0Ev
