// SexyAppFramework/EATech/EAText/1.09.07/include/EAText/internal/EATextSquish.cpp
//
// 14 function(s), 2488 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: EATextSquish
//
// TODO    708 B  EATextSquish::ComputePrincipleComponent              _ZN12EATextSquish25ComputePrincipleComponentERKNS_6Sym3x3E
// TODO    632 B  EATextSquish::ComputeWeightedCovariance              _ZN12EATextSquish25ComputeWeightedCovarianceEiPKNS_4Vec3EPKf
// TODO    228 B  EATextSquish::WriteColourBlock4                      _ZN12EATextSquish17WriteColourBlock4ERKNS_4Vec3ES2_PKhPv
// TODO    168 B  EATextSquish::Compress                               _ZN12EATextSquish8CompressEPKhPvjj
// TODO    168 B  EATextSquish::Min                                    _ZN12EATextSquish3MinERKNS_4Vec3ES2_
// TODO    168 B  EATextSquish::Max                                    _ZN12EATextSquish3MaxERKNS_4Vec3ES2_
// TODO    124 B  EATextSquish::Floor                                  _ZN12EATextSquish5FloorERKNS_4Vec3E
// TODO     52 B  EATextSquish::Vec3                                   _ZN12EATextSquish4Vec3pLERKS0_
// TODO     52 B  EATextSquish::Vec3                                   _ZN12EATextSquish4Vec3mIERKS0_
// TODO     52 B  EATextSquish::Vec3                                   _ZN12EATextSquish4Vec3mLERKS0_
// TODO     48 B  EATextSquish::Vec3                                   _ZN12EATextSquish4Vec3dVEf
// TODO     40 B  EATextSquish::Vec3                                   _ZN12EATextSquish4Vec3mLEf
// TODO     40 B  EATextSquish::Dot                                    _ZN12EATextSquish3DotERKNS_4Vec3ES2_
// TODO      8 B  EATextSquish::Sym3x3                                 _ZN12EATextSquish6Sym3x3ixEi
