// PvZ2/plants/Fishhookgrass/PlantAnimRig_Fishhookgrass.cpp
//
// 36 function(s), 6372 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_Fishhookgrass
//
// TODO    500 B  PlantAnimRig_Fishhookgrass::PlayBeginthrow           _ZN26PlantAnimRig_Fishhookgrass14PlayBeginthrowEb
// TODO    416 B  PlantAnimRig_Fishhookgrass::onPlantfoodChewingContinued _ZN26PlantAnimRig_Fishhookgrass27onPlantfoodChewingContinuedERKSs
// TODO    316 B  PlantAnimRig_Fishhookgrass::onPlantfoodTongueAttackContinued _ZN26PlantAnimRig_Fishhookgrass32onPlantfoodTongueAttackContinuedERKSs
// TODO    316 B  PlantAnimRig_Fishhookgrass::onBitingCompleted        _ZN26PlantAnimRig_Fishhookgrass17onBitingCompletedERKSs
// TODO    316 B  PlantAnimRig_Fishhookgrass::onTongueAttackContinued  _ZN26PlantAnimRig_Fishhookgrass23onTongueAttackContinuedERKSs
// TODO    316 B  PlantAnimRig_Fishhookgrass::PlayBiteContinued        _ZN26PlantAnimRig_Fishhookgrass17PlayBiteContinuedEv
// TODO    296 B  PlantAnimRig_Fishhookgrass::PlayBeginPFthrow         _ZN26PlantAnimRig_Fishhookgrass16PlayBeginPFthrowEv
// TODO    296 B  PlantAnimRig_Fishhookgrass::PlayBeginChewing         _ZN26PlantAnimRig_Fishhookgrass16PlayBeginChewingEv
// TODO    296 B  PlantAnimRig_Fishhookgrass::PlayPlantfoodBeginTongueAttack _ZN26PlantAnimRig_Fishhookgrass30PlayPlantfoodBeginTongueAttackEv
// TODO    296 B  PlantAnimRig_Fishhookgrass::PlayPlantfoodTongueAttackLoop _ZN26PlantAnimRig_Fishhookgrass29PlayPlantfoodTongueAttackLoopEv
// TODO    296 B  PlantAnimRig_Fishhookgrass::PlayPlantfoodBeginChewing _ZN26PlantAnimRig_Fishhookgrass25PlayPlantfoodBeginChewingEv
// TODO    284 B  PlantAnimRig_Fishhookgrass::PlayBeginTongueAttack    _ZN26PlantAnimRig_Fishhookgrass21PlayBeginTongueAttackEb
// TODO    284 B  PlantAnimRig_Fishhookgrass::PlayReceiveHook          _ZN26PlantAnimRig_Fishhookgrass15PlayReceiveHookEb
// TODO    256 B  PlantAnimRig_Fishhookgrass::PlayIdleLooped           _ZN26PlantAnimRig_Fishhookgrass14PlayIdleLoopedEv
// TODO    180 B  PlantAnimRig_Fishhookgrass::StaticClassInit          _ZN26PlantAnimRig_Fishhookgrass15StaticClassInitEv
// TODO    180 B  PlantAnimRig_Fishhookgrass::PlayBeginPFTongueAttack  _ZN26PlantAnimRig_Fishhookgrass23PlayBeginPFTongueAttackEv
// TODO    180 B  PlantAnimRig_Fishhookgrass::PlayPFReceiveHook        _ZN26PlantAnimRig_Fishhookgrass17PlayPFReceiveHookEv
// TODO    180 B  PlantAnimRig_Fishhookgrass::PlayTongueGrab           _ZN26PlantAnimRig_Fishhookgrass14PlayTongueGrabEv
// TODO    180 B  PlantAnimRig_Fishhookgrass::PlayBite                 _ZN26PlantAnimRig_Fishhookgrass8PlayBiteEv
// TODO    180 B  PlantAnimRig_Fishhookgrass::PlayPlantfoodTongueGrab  _ZN26PlantAnimRig_Fishhookgrass23PlayPlantfoodTongueGrabEv
// TODO    180 B  PlantAnimRig_Fishhookgrass::PlayPlantfoodEndSwallowing _ZN26PlantAnimRig_Fishhookgrass26PlayPlantfoodEndSwallowingEv
// TODO    180 B  PlantAnimRig_Fishhookgrass::PlayPlantfoodBurp        _ZN26PlantAnimRig_Fishhookgrass17PlayPlantfoodBurpEv
// TODO    124 B  PlantAnimRig_Fishhookgrass::StaticGetClass           _ZN26PlantAnimRig_Fishhookgrass14StaticGetClassEv
// TODO     68 B  PlantAnimRig_Fishhookgrass::PlantAnimRig_Fishhookgrass _ZN26PlantAnimRig_FishhookgrassC2Ev
// TODO     68 B  PlantAnimRig_Fishhookgrass::PlantAnimRig_Fishhookgrass _ZN26PlantAnimRig_FishhookgrassC1Ev
// TODO     44 B  PlantAnimRig_Fishhookgrass::StaticNew                _ZN26PlantAnimRig_Fishhookgrass9StaticNewEv
// TODO     36 B  PlantAnimRig_Fishhookgrass::~PlantAnimRig_Fishhookgrass _ZN26PlantAnimRig_FishhookgrassD0Ev
// TODO     28 B  PlantAnimRig_Fishhookgrass::~PlantAnimRig_Fishhookgrass _ZN26PlantAnimRig_FishhookgrassD2Ev
// TODO     28 B  PlantAnimRig_Fishhookgrass::~PlantAnimRig_Fishhookgrass _ZN26PlantAnimRig_FishhookgrassD1Ev
// TODO      8 B  PlantAnimRig_Fishhookgrass::PlayAttack               _ZN26PlantAnimRig_Fishhookgrass10PlayAttackE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO      8 B  PlantAnimRig_Fishhookgrass::PlayPlantFoodStart       _ZN26PlantAnimRig_Fishhookgrass18PlayPlantFoodStartEi
// TODO      8 B  PlantAnimRig_Fishhookgrass::PlayPlantFoodStart       _ZN26PlantAnimRig_Fishhookgrass18PlayPlantFoodStartEi20RtReflectionDelegateIN4Sexy9Delegate0EES3_S3_
// TODO      8 B  PlantAnimRig_Fishhookgrass::PlayPlantFoodEnd         _ZN26PlantAnimRig_Fishhookgrass16PlayPlantFoodEndEv
// TODO      8 B  PlantAnimRig_Fishhookgrass::SetFishhookgrassState    _ZN26PlantAnimRig_Fishhookgrass21SetFishhookgrassStateE18FishhookgrassState
// TODO      8 B  PlantAnimRig_Fishhookgrass::CurrentAnimationIsFinished _ZN26PlantAnimRig_Fishhookgrass26CurrentAnimationIsFinishedEv
// TODO      4 B  PlantAnimRig_Fishhookgrass::onChewingContinued       _ZN26PlantAnimRig_Fishhookgrass18onChewingContinuedERKSs
