// PvZ2/zombies/HeianSushi/ZombieAnimRig_HeianSushi.cpp
//
// 14 function(s), 2080 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieAnimRig_HeianSushi
//
// TODO    376 B  ZombieAnimRig_HeianSushi::getArmLayerNames           _ZN24ZombieAnimRig_HeianSushi16getArmLayerNamesEv
// TODO    320 B  ZombieAnimRig_HeianSushi::getHeadLayerNames          _ZN24ZombieAnimRig_HeianSushi17getHeadLayerNamesEv
// TODO    320 B  ZombieAnimRig_HeianSushi::getArmReplacementPairNames _ZN24ZombieAnimRig_HeianSushi26getArmReplacementPairNamesEv
// TODO    244 B  ZombieAnimRig_HeianSushi::PlayTossAnim               _ZN24ZombieAnimRig_HeianSushi12PlayTossAnimE20RtReflectionDelegateIN4Sexy9Delegate0EES3_
// TODO    180 B  ZombieAnimRig_HeianSushi::StaticClassInit            _ZN24ZombieAnimRig_HeianSushi15StaticClassInitEv
// TODO    124 B  ZombieAnimRig_HeianSushi::StaticGetClass             _ZN24ZombieAnimRig_HeianSushi14StaticGetClassEv
// TODO     84 B  ZombieAnimRig_HeianSushi::onAnimStopped              _ZN24ZombieAnimRig_HeianSushi13onAnimStoppedEv
// TODO     72 B  ZombieAnimRig_HeianSushi::~ZombieAnimRig_HeianSushi  _ZN24ZombieAnimRig_HeianSushiD2Ev
// TODO     72 B  ZombieAnimRig_HeianSushi::~ZombieAnimRig_HeianSushi  _ZN24ZombieAnimRig_HeianSushiD1Ev
// TODO     72 B  ZombieAnimRig_HeianSushi::onPopAnimCommand           _ZN24ZombieAnimRig_HeianSushi16onPopAnimCommandEfRKSsS1_
// TODO     68 B  ZombieAnimRig_HeianSushi::ZombieAnimRig_HeianSushi   _ZN24ZombieAnimRig_HeianSushiC2Ev
// TODO     68 B  ZombieAnimRig_HeianSushi::ZombieAnimRig_HeianSushi   _ZN24ZombieAnimRig_HeianSushiC1Ev
// TODO     44 B  ZombieAnimRig_HeianSushi::StaticNew                  _ZN24ZombieAnimRig_HeianSushi9StaticNewEv
// TODO     36 B  ZombieAnimRig_HeianSushi::~ZombieAnimRig_HeianSushi  _ZN24ZombieAnimRig_HeianSushiD0Ev
