// PvZ2/UIEditor/UIEditorMenu.cpp
//
// 16 function(s), 2568 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: UIEditorMenu
//
// TODO    528 B  UIEditorMenu::OnCreate                               _ZN12UIEditorMenu8OnCreateEiRKSbIwSt11char_traitsIwESaIwEEN4Sexy9Delegate1IiEE
// TODO    468 B  UIEditorMenu::ShowMenu                               _ZN12UIEditorMenu8ShowMenuEv
// TODO    388 B  UIEditorMenu::AddSubMenu                             _ZN12UIEditorMenu10AddSubMenuEiRKSbIwSt11char_traitsIwESaIwEE
// TODO    240 B  UIEditorMenu::Resize                                 _ZN12UIEditorMenu6ResizeEiiii
// TODO    196 B  UIEditorMenu::Draw                                   _ZN12UIEditorMenu4DrawEPN4Sexy8GraphicsE
// TODO    192 B  UIEditorMenu::GetSubMenu                             _ZN12UIEditorMenu10GetSubMenuEi
// TODO    132 B  UIEditorMenu::ButtonDepress                          _ZN12UIEditorMenu13ButtonDepressEi
// TODO     88 B  UIEditorMenu::UIEditorMenu                           _ZN12UIEditorMenuC1Ev
// TODO     88 B  UIEditorMenu::UIEditorMenu                           _ZN12UIEditorMenuC2Ev
// TODO     68 B  UIEditorMenu::SetDisabled                            _ZN12UIEditorMenu11SetDisabledEb
// TODO     48 B  UIEditorMenu::~UIEditorMenu                          _ZN12UIEditorMenuD2Ev
// TODO     48 B  UIEditorMenu::~UIEditorMenu                          _ZN12UIEditorMenuD1Ev
// TODO     40 B  UIEditorMenu::HideMenu                               _ZN12UIEditorMenu8HideMenuEv
// TODO     36 B  UIEditorMenu::~UIEditorMenu                          _ZN12UIEditorMenuD0Ev
// TODO      4 B  UIEditorMenu::ScrollTargetReached                    _ZN12UIEditorMenu19ScrollTargetReachedEPN4Sexy12ScrollWidgetE
// TODO      4 B  UIEditorMenu::ScrollTargetInterrupted                _ZN12UIEditorMenu23ScrollTargetInterruptedEPN4Sexy12ScrollWidgetE
