// PvZ2/zombies/RomanHealer/ZombieAnimRig_RomanHealer.cpp
//
// 13 function(s), 1980 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieAnimRig_RomanHealer
//
// TODO    348 B  ZombieAnimRig_RomanHealer::getHeadLayerNames         _ZN25ZombieAnimRig_RomanHealer17getHeadLayerNamesEv
// TODO    320 B  ZombieAnimRig_RomanHealer::getArmLayerNames          _ZN25ZombieAnimRig_RomanHealer16getArmLayerNamesEv
// TODO    320 B  ZombieAnimRig_RomanHealer::getArmReplacementPairNames _ZN25ZombieAnimRig_RomanHealer26getArmReplacementPairNamesEv
// TODO    224 B  ZombieAnimRig_RomanHealer::StartCasting              _ZN25ZombieAnimRig_RomanHealer12StartCastingE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    200 B  ZombieAnimRig_RomanHealer::ContinueCasting           _ZN25ZombieAnimRig_RomanHealer15ContinueCastingE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    200 B  ZombieAnimRig_RomanHealer::StopCasting               _ZN25ZombieAnimRig_RomanHealer11StopCastingE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    120 B  ZombieAnimRig_RomanHealer::StaticGetClass            _ZN25ZombieAnimRig_RomanHealer14StaticGetClassEv
// TODO     56 B  ZombieAnimRig_RomanHealer::ZombieAnimRig_RomanHealer _ZN25ZombieAnimRig_RomanHealerC2Ev
// TODO     56 B  ZombieAnimRig_RomanHealer::ZombieAnimRig_RomanHealer _ZN25ZombieAnimRig_RomanHealerC1Ev
// TODO     44 B  ZombieAnimRig_RomanHealer::StaticNew                 _ZN25ZombieAnimRig_RomanHealer9StaticNewEv
// TODO     36 B  ZombieAnimRig_RomanHealer::~ZombieAnimRig_RomanHealer _ZN25ZombieAnimRig_RomanHealerD0Ev
// TODO     28 B  ZombieAnimRig_RomanHealer::~ZombieAnimRig_RomanHealer _ZN25ZombieAnimRig_RomanHealerD2Ev
// TODO     28 B  ZombieAnimRig_RomanHealer::~ZombieAnimRig_RomanHealer _ZN25ZombieAnimRig_RomanHealerD1Ev
