// PvZ2/zombies/EightiesGargantuar/ZombieEightiesGargantuar.cpp
//
// 24 function(s), 2360 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombieEightiesGargantuar, ZombieEightiesGargantuarProps
//
// TODO    340 B  ZombieEightiesGargantuar::createShockWave            _ZN24ZombieEightiesGargantuar15createShockWaveEv
// TODO    184 B  ZombieEightiesGargantuar::calcShockWaveSpawnPosition _ZN24ZombieEightiesGargantuar26calcShockWaveSpawnPositionEv
// TODO    180 B  ZombieEightiesGargantuar::StaticClassInit            _ZN24ZombieEightiesGargantuar15StaticClassInitEv
// TODO    180 B  ZombieEightiesGargantuarProps::StaticClassInit       _ZN29ZombieEightiesGargantuarProps15StaticClassInitEv
// TODO    164 B  ZombieEightiesGargantuarProps::ZombieEightiesGargantuarProps _ZN29ZombieEightiesGargantuarPropsC2Ev
// TODO    164 B  ZombieEightiesGargantuarProps::ZombieEightiesGargantuarProps _ZN29ZombieEightiesGargantuarPropsC1Ev
// TODO    124 B  ZombieEightiesGargantuar::StaticGetClass             _ZN24ZombieEightiesGargantuar14StaticGetClassEv
// TODO    124 B  ZombieEightiesGargantuarProps::StaticGetClass        _ZN29ZombieEightiesGargantuarProps14StaticGetClassEv
// TODO    120 B  ZombieEightiesGargantuar::onUpdate                   _ZN24ZombieEightiesGargantuar8onUpdateEv
// TODO    120 B  ZombieEightiesGargantuar::onPopAnimCommand           _ZN24ZombieEightiesGargantuar16onPopAnimCommandERKSsfS1_S1_
// TODO     96 B  ZombieEightiesGargantuar::setArbitrarySmashTime      _ZN24ZombieEightiesGargantuar21setArbitrarySmashTimeEv
// TODO     84 B  ZombieEightiesGargantuar::ZombieEightiesGargantuar   _ZN24ZombieEightiesGargantuarC2Ev
// TODO     84 B  ZombieEightiesGargantuar::ZombieEightiesGargantuar   _ZN24ZombieEightiesGargantuarC1Ev
// TODO     56 B  ZombieEightiesGargantuarProps::~ZombieEightiesGargantuarProps _ZN29ZombieEightiesGargantuarPropsD2Ev
// TODO     56 B  ZombieEightiesGargantuarProps::~ZombieEightiesGargantuarProps _ZN29ZombieEightiesGargantuarPropsD1Ev
// TODO     48 B  ZombieEightiesGargantuar::GetJamStyle                _ZN24ZombieEightiesGargantuar11GetJamStyleEv
// TODO     44 B  ZombieEightiesGargantuar::StaticNew                  _ZN24ZombieEightiesGargantuar9StaticNewEv
// TODO     44 B  ZombieEightiesGargantuarProps::StaticNew             _ZN29ZombieEightiesGargantuarProps9StaticNewEv
// TODO     36 B  ZombieEightiesGargantuar::~ZombieEightiesGargantuar  _ZN24ZombieEightiesGargantuarD0Ev
// TODO     36 B  ZombieEightiesGargantuarProps::~ZombieEightiesGargantuarProps _ZN29ZombieEightiesGargantuarPropsD0Ev
// TODO     28 B  ZombieEightiesGargantuar::~ZombieEightiesGargantuar  _ZN24ZombieEightiesGargantuarD2Ev
// TODO     28 B  ZombieEightiesGargantuar::~ZombieEightiesGargantuar  _ZN24ZombieEightiesGargantuarD1Ev
// TODO     12 B  ZombieEightiesGargantuar::StartJamming               _ZN24ZombieEightiesGargantuar12StartJammingEv
// TODO      8 B  ZombieEightiesGargantuar::StopJamming                _ZN24ZombieEightiesGargantuar11StopJammingEv
