// PvZ2/plants/HeadbutterLettuce/PlantAnimRig_HeadbutterLettuce.cpp
//
// 11 function(s), 1092 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: PlantAnimRig_HeadbutterLettuce
//
// TODO    208 B  PlantAnimRig_HeadbutterLettuce::PlayRightHeadbutt    _ZN30PlantAnimRig_HeadbutterLettuce17PlayRightHeadbuttE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    208 B  PlantAnimRig_HeadbutterLettuce::PlayLeftHeadbutt     _ZN30PlantAnimRig_HeadbutterLettuce16PlayLeftHeadbuttE20RtReflectionDelegateIN4Sexy9Delegate1IRKSsEEE
// TODO    180 B  PlantAnimRig_HeadbutterLettuce::StaticClassInit      _ZN30PlantAnimRig_HeadbutterLettuce15StaticClassInitEv
// TODO    124 B  PlantAnimRig_HeadbutterLettuce::getPlantFoodMainAnimName _ZN30PlantAnimRig_HeadbutterLettuce24getPlantFoodMainAnimNameEv
// TODO    124 B  PlantAnimRig_HeadbutterLettuce::StaticGetClass       _ZN30PlantAnimRig_HeadbutterLettuce14StaticGetClassEv
// TODO     56 B  PlantAnimRig_HeadbutterLettuce::PlantAnimRig_HeadbutterLettuce _ZN30PlantAnimRig_HeadbutterLettuceC2Ev
// TODO     56 B  PlantAnimRig_HeadbutterLettuce::PlantAnimRig_HeadbutterLettuce _ZN30PlantAnimRig_HeadbutterLettuceC1Ev
// TODO     44 B  PlantAnimRig_HeadbutterLettuce::StaticNew            _ZN30PlantAnimRig_HeadbutterLettuce9StaticNewEv
// TODO     36 B  PlantAnimRig_HeadbutterLettuce::~PlantAnimRig_HeadbutterLettuce _ZN30PlantAnimRig_HeadbutterLettuceD0Ev
// TODO     28 B  PlantAnimRig_HeadbutterLettuce::~PlantAnimRig_HeadbutterLettuce _ZN30PlantAnimRig_HeadbutterLettuceD2Ev
// TODO     28 B  PlantAnimRig_HeadbutterLettuce::~PlantAnimRig_HeadbutterLettuce _ZN30PlantAnimRig_HeadbutterLettuceD1Ev
