// PvZ2/zombies/PirateSeagull/ZombiePirateSeagull.cpp
//
// 19 function(s), 2216 B to reconstruct. Generated by tools/scaffold.py.
// Replace this banner with real code; drop a TODO line as its function matches.
//
// classes: ZombiePirateSeagull
//
// TODO    492 B  ZombiePirateSeagull::playBirdLossAnimation           _ZN19ZombiePirateSeagull21playBirdLossAnimationEb
// TODO    432 B  ZombiePirateSeagull::onTakeFatalDamage               _ZN19ZombiePirateSeagull17onTakeFatalDamageERK10DamageInfo
// TODO    256 B  ZombiePirateSeagull::onApplyCondition                _ZN19ZombiePirateSeagull16onApplyConditionE16ZombieConditions
// TODO    196 B  ZombiePirateSeagull::onPopAnimCommand                _ZN19ZombiePirateSeagull16onPopAnimCommandERKSsfS1_S1_
// TODO    180 B  ZombiePirateSeagull::StaticClassInit                 _ZN19ZombiePirateSeagull15StaticClassInitEv
// TODO    124 B  ZombiePirateSeagull::StaticGetClass                  _ZN19ZombiePirateSeagull14StaticGetClassEv
// TODO    104 B  ZombiePirateSeagull::onEnterState_Ash                _ZN19ZombiePirateSeagull16onEnterState_AshE11ZombieState
// TODO     56 B  ZombiePirateSeagull::ZombiePirateSeagull             _ZN19ZombiePirateSeagullC2Ev
// TODO     56 B  ZombiePirateSeagull::ZombiePirateSeagull             _ZN19ZombiePirateSeagullC1Ev
// TODO     52 B  ZombiePirateSeagull::onZombieInitialize              _ZN19ZombiePirateSeagull18onZombieInitializeEv
// TODO     52 B  ZombiePirateSeagull::onExitState_Electrocute         _ZN19ZombiePirateSeagull23onExitState_ElectrocuteE11ZombieState
// TODO     44 B  ZombiePirateSeagull::canTargetEntityHeight           _ZN19ZombiePirateSeagull21canTargetEntityHeightE17BoardEntityHeight
// TODO     44 B  ZombiePirateSeagull::StaticNew                       _ZN19ZombiePirateSeagull9StaticNewEv
// TODO     36 B  ZombiePirateSeagull::~ZombiePirateSeagull            _ZN19ZombiePirateSeagullD0Ev
// TODO     28 B  ZombiePirateSeagull::~ZombiePirateSeagull            _ZN19ZombiePirateSeagullD2Ev
// TODO     28 B  ZombiePirateSeagull::~ZombiePirateSeagull            _ZN19ZombiePirateSeagullD1Ev
// TODO     20 B  ZombiePirateSeagull::findTarget                      _ZN19ZombiePirateSeagull10findTargetEv
// TODO     12 B  ZombiePirateSeagull::updateState_Ash                 _ZN19ZombiePirateSeagull15updateState_AshEv
// TODO      4 B  ZombiePirateSeagull::onExitState_Ash                 _ZN19ZombiePirateSeagull15onExitState_AshE11ZombieState
